# Generated by Django 6.0 on 2026-01-28 18:00

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cockpit", "0003_alter_activitylog_entity_type_and_more"),
        ("contacts", "0003_add_parent_entity_fields"),
        ("customers", "0007_customer_custom_data_alter_customer_tenant"),
        ("products", "0006_product_custom_data_alter_product_tenant"),
        ("suppliers", "0009_supplier_custom_data_alter_supplier_tenant"),
        ("tenants", "0006_metadata_lockdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "inquiry_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated inquiry number (INQ-YYYY-NNNNN)",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("quoted", "Quoted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current status of the inquiry",
                        max_length=20,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("scheduled_call", "Scheduled Call"),
                            ("inbound_call", "Inbound Call"),
                            ("email", "Email"),
                            ("website", "Website"),
                            ("trade_show", "Trade Show"),
                            ("referral", "Referral"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="How this inquiry originated",
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("supplier", "Supplier"), ("customer", "Customer")],
                        help_text="Whether this inquiry is from a supplier or customer",
                        max_length=20,
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact name at time of inquiry",
                        max_length=255,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Contact email at time of inquiry",
                        max_length=254,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact phone at time of inquiry",
                        max_length=50,
                    ),
                ),
                (
                    "contact_company",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Company name at time of inquiry",
                        max_length=255,
                    ),
                ),
                (
                    "contact_position",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact position/title at time of inquiry",
                        max_length=100,
                    ),
                ),
                (
                    "inquiry_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the inquiry was created",
                    ),
                ),
                (
                    "quoted_date",
                    models.DateTimeField(blank=True, help_text="When the quote was provided", null=True),
                ),
                (
                    "decision_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the inquiry was accepted or rejected",
                        null=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, help_text="Quote expiration date", null=True),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="General notes about this inquiry",
                    ),
                ),
                (
                    "competitor_names",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Known competitors for this deal",
                    ),
                ),
                (
                    "competitor_pricing_notes",
                    models.TextField(blank=True, default="", help_text="Intel on competitor pricing"),
                ),
                (
                    "win_loss_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reason for win or loss (filled on close)",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary contact person",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="contacts.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this inquiry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer (if entity_type is customer)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="customers.customer",
                    ),
                ),
                (
                    "source_call",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source scheduled call (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="cockpit.scheduledcall",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supplier (if entity_type is supplier)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry",
                "verbose_name_plural": "Inquiries",
                "ordering": ["-inquiry_date"],
            },
        ),
        migrations.CreateModel(
            name="InquiryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Requested quantity",
                        max_digits=12,
                    ),
                ),
                (
                    "desired_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected total amount",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "desired_price_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Expected price per unit",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "desired_uom",
                    models.CharField(
                        choices=[
                            ("LBS", "Pounds"),
                            ("KG", "Kilograms"),
                            ("CS", "Cases"),
                            ("EA", "Each"),
                            ("PLT", "Pallets"),
                            ("BOX", "Boxes"),
                        ],
                        default="LBS",
                        help_text="Expected unit of measure",
                        max_length=10,
                    ),
                ),
                (
                    "desired_uom_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Quantity in UOM",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "desired_processed_date",
                    models.DateField(blank=True, help_text="Expected processing date", null=True),
                ),
                (
                    "desired_expiration_date",
                    models.DateField(blank=True, help_text="Expected expiration date", null=True),
                ),
                (
                    "desired_available_date",
                    models.DateField(blank=True, help_text="When needed/available", null=True),
                ),
                (
                    "desired_shipping_date",
                    models.DateField(blank=True, help_text="Expected ship date", null=True),
                ),
                (
                    "desired_delivery_date",
                    models.DateField(blank=True, help_text="Expected delivery date", null=True),
                ),
                (
                    "actual_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual total amount",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "actual_price_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Actual price per unit",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "actual_uom",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LBS", "Pounds"),
                            ("KG", "Kilograms"),
                            ("CS", "Cases"),
                            ("EA", "Each"),
                            ("PLT", "Pallets"),
                            ("BOX", "Boxes"),
                        ],
                        default="",
                        help_text="Actual unit of measure",
                        max_length=10,
                    ),
                ),
                (
                    "actual_uom_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual quantity in UOM",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "actual_processed_date",
                    models.DateField(blank=True, help_text="Actual processing date", null=True),
                ),
                (
                    "actual_expiration_date",
                    models.DateField(blank=True, help_text="Actual expiration date", null=True),
                ),
                (
                    "actual_available_date",
                    models.DateField(blank=True, help_text="Actual availability date", null=True),
                ),
                (
                    "actual_shipping_date",
                    models.DateField(blank=True, help_text="Actual ship date", null=True),
                ),
                (
                    "actual_delivery_date",
                    models.DateField(blank=True, help_text="Actual delivery date", null=True),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", help_text="Line item notes"),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="inquiries.inquiry",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_lines",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry Product",
                "verbose_name_plural": "Inquiry Products",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["tenant", "inquiry_number"],
                name="inquiries_i_tenant__4a4582_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(fields=["tenant", "status"], name="inquiries_i_tenant__c7fc7c_idx"),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(fields=["tenant", "entity_type"], name="inquiries_i_tenant__e92a12_idx"),
        ),
    ]
