# Generated by Django 6.0 on 2026-01-28 18:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0001_initial"),
        ("products", "0006_product_custom_data_alter_product_tenant"),
        ("tenants", "0006_metadata_lockdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InquiryTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Weekly Beef Order')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of this template's purpose",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("supplier", "Supplier"), ("customer", "Customer")],
                        help_text="Whether this template is for suppliers or customers",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is available for use",
                    ),
                ),
                (
                    "default_valid_days",
                    models.PositiveIntegerField(
                        default=7, help_text="Default number of days quote is valid"
                    ),
                ),
                (
                    "default_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Default notes to include in inquiry",
                    ),
                ),
                (
                    "use_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this template has been used",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_inquiry_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry Template",
                "verbose_name_plural": "Inquiry Templates",
                "ordering": ["-use_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="InquiryTemplateProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Default quantity to request",
                        max_digits=12,
                    ),
                ),
                (
                    "default_uom",
                    models.CharField(
                        choices=[
                            ("LBS", "Pounds"),
                            ("KG", "Kilograms"),
                            ("CS", "Cases"),
                            ("EA", "Each"),
                            ("PLT", "Pallets"),
                            ("BOX", "Boxes"),
                        ],
                        default="LBS",
                        help_text="Default unit of measure",
                        max_length=10,
                    ),
                ),
                (
                    "default_price_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Default price per unit (if known)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notes for this product in this template",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order in template"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_lines",
                        to="products.product",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="inquiries.inquirytemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Product",
                "verbose_name_plural": "Template Products",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="inquirytemplate",
            index=models.Index(
                fields=["tenant", "entity_type", "is_active"],
                name="inquiries_i_tenant__360e28_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inquirytemplateproduct",
            unique_together={("template", "product")},
        ),
    ]
