# Generated by Django 6.0 on 2026-03-18 03:16
# Add RLS policies for Inquiry and InquiryTemplate models

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0003_alter_product_fks_to_system"),
    ]

    operations = [
        RunSQL(
            sql="""
            -- Enable RLS on inquiries_inquiry
            ALTER TABLE inquiries_inquiry ENABLE ROW LEVEL SECURITY;

            -- Drop existing policies (idempotent)
            DROP POLICY IF EXISTS inquiry_tenant_isolation ON inquiries_inquiry;
            DROP POLICY IF EXISTS inquiry_tenant_insert ON inquiries_inquiry;

            -- Create tenant isolation policy for SELECT/UPDATE/DELETE
            CREATE POLICY inquiry_tenant_isolation ON inquiries_inquiry
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- Create tenant isolation policy for INSERT
            CREATE POLICY inquiry_tenant_insert ON inquiries_inquiry
                FOR INSERT
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- Enable RLS on inquiries_inquirytemplate
            ALTER TABLE inquiries_inquirytemplate ENABLE ROW LEVEL SECURITY;

            -- Drop existing policies (idempotent)
            DROP POLICY IF EXISTS inquirytemplate_tenant_isolation ON inquiries_inquirytemplate;
            DROP POLICY IF EXISTS inquirytemplate_tenant_insert ON inquiries_inquirytemplate;

            -- Create tenant isolation policy for SELECT/UPDATE/DELETE
            CREATE POLICY inquirytemplate_tenant_isolation ON inquiries_inquirytemplate
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- Create tenant isolation policy for INSERT
            CREATE POLICY inquirytemplate_tenant_insert ON inquiries_inquirytemplate
                FOR INSERT
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS inquirytemplate_tenant_insert ON inquiries_inquirytemplate;
            DROP POLICY IF EXISTS inquirytemplate_tenant_isolation ON inquiries_inquirytemplate;
            ALTER TABLE inquiries_inquirytemplate DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS inquiry_tenant_insert ON inquiries_inquiry;
            DROP POLICY IF EXISTS inquiry_tenant_isolation ON inquiries_inquiry;
            ALTER TABLE inquiries_inquiry DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
