# Generated by Django 6.0 on 2026-03-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0003_alter_product_fks_to_system"),
    ]

    operations = []
