# Generated by Django 6.0 on 2026-03-29 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0004_add_rls_policies_batch"),
        ("plants", "0011_fix_plants_rls_policies_safe_current_setting"),
        ("suppliers", "0015_shorten_supplieravailableitem_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiryproduct",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: plant selected for this line (customer inquiries)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiry_products",
                to="plants.plant",
            ),
        ),
        migrations.AddField(
            model_name="inquiryproduct",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: supplier selected for this line (customer inquiries)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiry_products",
                to="suppliers.supplier",
            ),
        ),
    ]
