# Generated by Django 6.0 on 2026-03-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0004_add_rls_policies_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="contact_phone_type",
            field=models.CharField(
                blank=True,
                choices=[("mobile", "Mobile"), ("office", "Office")],
                default="office",
                help_text="Contact phone type at time of inquiry (mobile or office)",
                max_length=10,
            ),
        ),
    ]
