# Generated by Django 6.0 on 2026-03-23
# Squashed replacement for inquiries/0003 to ensure FK removal happens before products deletes legacy Product.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("inquiries", "0003_alter_product_fks_to_system"),
    ]

    # Ensure the legacy FK fields are removed while products.Product still exists in migration state.
    run_before = [
        ("products", "0008_masterproduct_delete_product_and_more"),
    ]

    dependencies = [
        ("inquiries", "0002_add_inquiry_templates"),
        ("system", "0002_add_product_model"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE inquiries_inquiryproduct DROP COLUMN IF EXISTS product_id;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE inquiries_inquirytemplateproduct DROP COLUMN IF EXISTS product_id;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(model_name="inquiryproduct", name="product"),
                migrations.RemoveField(model_name="inquirytemplateproduct", name="product"),
            ],
        ),
        migrations.AddField(
            model_name="inquiryproduct",
            name="product",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiry_lines",
                to="system.product",
            ),
        ),
        migrations.AddField(
            model_name="inquirytemplateproduct",
            name="product",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="template_lines",
                to="system.product",
            ),
        ),
    ]
