# Generated by Django 6.0 on 2026-03-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0005_inquiry_contact_phone_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="shipping_type",
            field=models.CharField(
                choices=[
                    ("tenant", "Tenant"),
                    ("customer_pickup", "Customer Pick-Up"),
                    ("supplier_delivering", "Supplier Delivering"),
                ],
                db_index=True,
                default="tenant",
                help_text="Shipping type (cascades into fulfillment/logistics)",
                max_length=32,
            ),
        ),
    ]
