# Generated by Django 6.0 on 2026-03-30 20:18

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0006_inquiry_shipping_type"),
        ("tenants", "0013_alter_activitylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiryproduct",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AddField(
            model_name="inquiryproduct",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiry_products",
                to="tenants.tenant",
            ),
        ),
        RunSQL(
            sql="""
            UPDATE inquiries_inquiryproduct ip
            SET tenant_id = i.tenant_id
            FROM inquiries_inquiry i
            WHERE ip.inquiry_id = i.id
              AND ip.tenant_id IS NULL;
            """,
            reverse_sql=RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="inquiryproduct",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiry_products",
                to="tenants.tenant",
            ),
        ),
        RunSQL(
            sql="""
            -- Enable RLS on inquiries_inquiryproduct
            ALTER TABLE inquiries_inquiryproduct ENABLE ROW LEVEL SECURITY;

            -- Drop existing policies (idempotent)
            DROP POLICY IF EXISTS inquiryproduct_tenant_isolation ON inquiries_inquiryproduct;
            DROP POLICY IF EXISTS inquiryproduct_tenant_insert ON inquiries_inquiryproduct;

            -- Create tenant isolation policy for SELECT/UPDATE/DELETE
            CREATE POLICY inquiryproduct_tenant_isolation ON inquiries_inquiryproduct
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- Create tenant isolation policy for INSERT
            CREATE POLICY inquiryproduct_tenant_insert ON inquiries_inquiryproduct
                FOR INSERT
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS inquiryproduct_tenant_insert ON inquiries_inquiryproduct;
            DROP POLICY IF EXISTS inquiryproduct_tenant_isolation ON inquiries_inquiryproduct;
            ALTER TABLE inquiries_inquiryproduct DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
