# Generated by Django 6.0 on 2026-03-30 20:34

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations import RunSQL
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0006_inquiry_shipping_type"),
        ("tenants", "0013_alter_activitylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirytemplateproduct",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inquirytemplateproduct",
            name="modified_on",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inquirytemplateproduct",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AddField(
            model_name="inquirytemplateproduct",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiry_template_products",
                to="tenants.tenant",
            ),
        ),
        RunSQL(
            sql="""
            UPDATE inquiries_inquirytemplateproduct itp
            SET tenant_id = t.tenant_id
            FROM inquiries_inquirytemplate t
            WHERE itp.template_id = t.id
              AND itp.tenant_id IS NULL;
            """,
            reverse_sql=RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="inquirytemplateproduct",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiry_template_products",
                to="tenants.tenant",
            ),
        ),
        RunSQL(
            sql="""
            -- Enable RLS on inquiries_inquirytemplateproduct
            ALTER TABLE inquiries_inquirytemplateproduct ENABLE ROW LEVEL SECURITY;

            -- Drop existing policies (idempotent)
            DROP POLICY IF EXISTS inquirytemplateproduct_tenant_isolation ON inquiries_inquirytemplateproduct;
            DROP POLICY IF EXISTS inquirytemplateproduct_tenant_insert ON inquiries_inquirytemplateproduct;

            -- Create tenant isolation policy for SELECT/UPDATE/DELETE
            CREATE POLICY inquirytemplateproduct_tenant_isolation ON inquiries_inquirytemplateproduct
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- Create tenant isolation policy for INSERT
            CREATE POLICY inquirytemplateproduct_tenant_insert ON inquiries_inquirytemplateproduct
                FOR INSERT
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS inquirytemplateproduct_tenant_insert ON inquiries_inquirytemplateproduct;
            DROP POLICY IF EXISTS inquirytemplateproduct_tenant_isolation ON inquiries_inquirytemplateproduct;
            ALTER TABLE inquiries_inquirytemplateproduct DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
