# Generated by Django 6.0 on 2026-03-30 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0007_inquiryproduct_custom_data_inquiryproduct_tenant"),
        ("inquiries", "0007_inquirytemplateproduct_tenant_rls"),
    ]

    operations = []
