# Generated by Django 6.0 on 2026-03-31 04:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0005_inquiryproduct_plant_inquiryproduct_supplier"),
        ("inquiries", "0008_merge_20260330_2056"),
    ]

    operations = []
