# Generated by Django 6.0 on 2026-05-06 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0009_merge_20260331_0402"),
        ("integrations", "0006_alter_emaillog_status"),
        ("products", "0009_alter_masterproduct_protein"),
        ("purchase_orders", "0019_operational_readiness"),
        ("sales_orders", "0017_operational_readiness"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="carrier_purchase_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Carrier purchase order created from this inquiry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_inquiries",
                to="purchase_orders.carrierpurchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="requested_master_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant-scoped master product anchor for the requested item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trading_inquiries",
                to="products.masterproduct",
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="requested_protein",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beef", "Beef"),
                    ("Chicken", "Chicken"),
                    ("Duck", "Duck"),
                    ("Pork", "Pork"),
                    ("Lamb", "Lamb"),
                    ("Turkey", "Turkey"),
                    ("Fish", "Fish"),
                    ("Horse", "Horse"),
                    ("Other", "Other"),
                ],
                db_index=True,
                default="",
                help_text="Requested protein anchor used by the hardcoded trading path",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="route_decision",
            field=models.CharField(
                blank=True,
                choices=[("FULFILL", "Fulfill"), ("BROKER", "Broker")],
                db_index=True,
                default="",
                help_text="Trading engine route chosen for this inquiry (FULFILL or BROKER)",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Sales order created from this inquiry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_inquiries",
                to="sales_orders.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="source_email",
            field=models.ForeignKey(
                blank=True,
                help_text="Source email record when this inquiry originated from inbound email",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiries",
                to="integrations.emaillog",
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="source_email_message_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Snapshot of the source email message ID for durable lineage",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="source_email_thread_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Snapshot of the source email thread/conversation ID for durable lineage",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="supplier_purchase_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Supplier purchase order created from this inquiry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_inquiries",
                to="purchase_orders.purchaseorder",
            ),
        ),
    ]
