# Generated by Django 6.0 on 2026-04-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0009_merge_20260331_0402"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
