# Generated by Django 6.0 on 2026-05-06 23:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0010_inquiry_carrier_purchase_order_and_more"),
        ("integrations", "0006_alter_emaillog_status"),
        ("suppliers", "0020_golden_schema_refactor"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InquirySupplierRFQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("correlation_key", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("sender_email", models.EmailField(blank=True, default="", max_length=254)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("recipient_name", models.CharField(blank=True, default="", max_length=255)),
                ("subject", models.CharField(default="", max_length=300)),
                ("body", models.TextField(default="")),
                ("provider", models.CharField(default="microsoft", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("provider_message_id", models.CharField(blank=True, default="", max_length=255)),
                ("provider_thread_id", models.CharField(blank=True, default="", max_length=255)),
                ("provider_internet_message_id", models.CharField(blank=True, default="", max_length=255)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_inquiry_supplier_rfqs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_rfqs",
                        to="inquiries.inquiry",
                    ),
                ),
                (
                    "sender_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_supplier_rfqs",
                        to="integrations.externalauthprovider",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_rfqs",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry Supplier RFQ",
                "verbose_name_plural": "Inquiry Supplier RFQs",
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(fields=["tenant", "inquiry", "status"], name="inq_rfq_tenant_inquiry_idx"),
                    models.Index(fields=["tenant", "supplier", "status"], name="inq_rfq_tenant_supplier_idx"),
                    models.Index(fields=["tenant", "correlation_key"], name="inq_rfq_tenant_corr_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "inquiry", "supplier"), name="unique_inquiry_supplier_rfq_per_tenant"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE inquiries_inquirysupplierrfq ENABLE ROW LEVEL SECURITY;
            ALTER TABLE inquiries_inquirysupplierrfq FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS inquirysupplierrfq_tenant_insert ON inquiries_inquirysupplierrfq;
            DROP POLICY IF EXISTS inquirysupplierrfq_tenant_isolation ON inquiries_inquirysupplierrfq;

            CREATE POLICY inquirysupplierrfq_tenant_isolation ON inquiries_inquirysupplierrfq
              USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

            CREATE POLICY inquirysupplierrfq_tenant_insert ON inquiries_inquirysupplierrfq
              FOR INSERT WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS inquirysupplierrfq_tenant_insert ON inquiries_inquirysupplierrfq;
            DROP POLICY IF EXISTS inquirysupplierrfq_tenant_isolation ON inquiries_inquirysupplierrfq;
            ALTER TABLE inquiries_inquirysupplierrfq NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE inquiries_inquirysupplierrfq DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
