# Generated by Django 6.0 on 2026-05-07 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0011_inquirysupplierrfq"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "trade_id",
                    models.CharField(
                        help_text="Unique trade session identifier (e.g., TRD-2026-00001)", max_length=50, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("sourcing", "Sourcing"),
                            ("quoted", "Quoted"),
                            ("ordered", "Ordered"),
                            ("logistics", "Logistics"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="initiated",
                        help_text="Current lifecycle status of the trade.",
                        max_length=20,
                    ),
                ),
                (
                    "source_email_message_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Internet message-ID of the email that initiated this trade.",
                        max_length=512,
                    ),
                ),
                (
                    "source_email_thread_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provider thread ID of the originating email thread.",
                        max_length=512,
                    ),
                ),
                (
                    "source_email_subject",
                    models.CharField(
                        blank=True, default="", help_text="Subject of the originating email.", max_length=1024
                    ),
                ),
                (
                    "source_email_sender",
                    models.EmailField(
                        blank=True, default="", help_text="Sender of the originating email.", max_length=254
                    ),
                ),
                (
                    "route_decision",
                    models.CharField(
                        blank=True,
                        choices=[("FULFILL", "Fulfill"), ("BROKER", "Broker")],
                        default="",
                        help_text="Route decision (FULFILL or BROKER) cached for queries.",
                        max_length=20,
                    ),
                ),
                (
                    "initiated_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the trade session was initiated."),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the trade session completed (all docs fulfilled).", null=True
                    ),
                ),
                (
                    "inquiry",
                    models.OneToOneField(
                        help_text="Root inquiry that initiated this trade.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_session",
                        to="inquiries.inquiry",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade Session",
                "verbose_name_plural": "Trade Sessions",
                "ordering": ["-initiated_at"],
                "indexes": [
                    models.Index(fields=["tenant", "trade_id"], name="inquiries_t_tenant__e7e01d_idx"),
                    models.Index(fields=["tenant", "status"], name="inquiries_t_tenant__1552aa_idx"),
                ],
            },
        ),
        # RLS policy for tenant isolation (CTE-05.1)
        migrations.RunSQL(
            sql="""
            ALTER TABLE inquiries_tradesession ENABLE ROW LEVEL SECURITY;
            CREATE POLICY tradesession_tenant_isolation ON inquiries_tradesession
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tradesession_tenant_isolation ON inquiries_tradesession;
            ALTER TABLE inquiries_tradesession DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
