# Generated by Django 6.0 on 2026-05-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0012_trade_session_lineage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("sourcing", "Sourcing"),
                    ("quoted", "Quoted"),
                    ("ordered", "Ordered"),
                    ("logistics", "Logistics"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("halted", "Halted"),
                ],
                default="initiated",
                help_text="Current lifecycle status of the trade.",
                max_length=20,
            ),
        ),
    ]
