# Generated by Django 6.0 on 2026-05-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0013_add_halted_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="requested_protein",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beef", "Beef"),
                    ("Chicken", "Chicken"),
                    ("Fowl", "Fowl"),
                    ("Turkey", "Turkey"),
                    ("Lamb", "Lamb"),
                    ("Veal", "Veal"),
                    ("Seafood", "Seafood"),
                    ("Venison", "Venison"),
                    ("Bison", "Bison"),
                    ("Duck", "Duck"),
                    ("Rabbit", "Rabbit"),
                    ("Goat", "Goat"),
                    ("Mutton", "Mutton"),
                    ("Pork", "Pork"),
                    ("Fish", "Fish"),
                    ("Horse", "Horse"),
                    ("Other", "Other"),
                ],
                db_index=True,
                default="",
                help_text="Requested protein anchor used by the hardcoded trading path",
                max_length=50,
            ),
        ),
    ]
