# Generated by Django 6.0 on 2026-05-15 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0011_alter_contact_department"),
        ("inquiries", "0014_alter_inquiry_requested_protein"),
        ("locations", "0012_locationassociatedmasterproduct_and_more"),
        ("plants", "0018_plant_site_code"),
        ("suppliers", "0021_supplier_accounting_payable_contact_email_and_more"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiryproduct",
            name="fulfillment_date_time",
            field=models.DateTimeField(
                blank=True, help_text="When this product needs to be fulfilled/received by", null=True
            ),
        ),
        migrations.AddField(
            model_name="inquiryproduct",
            name="respond_by_date_time",
            field=models.DateTimeField(blank=True, help_text="Deadline for suppliers to respond with bids", null=True),
        ),
        migrations.AddField(
            model_name="inquiryproduct",
            name="ship_to_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer delivery/ship-to location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiry_products_ship_to",
                to="locations.location",
            ),
        ),
        migrations.CreateModel(
            name="InquiryProductSupplierBid",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "bid_price_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Supplier's quoted price per unit",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "bid_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Supplier's total bid amount", max_digits=12, null=True
                    ),
                ),
                (
                    "bid_uom",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LBS", "Pounds"),
                            ("KG", "Kilograms"),
                            ("CS", "Cases"),
                            ("EA", "Each"),
                            ("PLT", "Pallets"),
                            ("BOX", "Boxes"),
                        ],
                        default="",
                        help_text="Unit of measure for bid",
                        max_length=10,
                    ),
                ),
                (
                    "bid_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Quantity the supplier can fulfill",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "bid_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("requested", "Bid Requested"),
                            ("received", "Bid Received"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(blank=True, help_text="When the bid request was sent", null=True),
                ),
                ("responded_at", models.DateTimeField(blank=True, help_text="When the supplier responded", null=True)),
                (
                    "bid_notes",
                    models.TextField(blank=True, default="", help_text="Internal notes about this bid (trader-facing)"),
                ),
                (
                    "supplier_notes",
                    models.TextField(
                        blank=True, default="", help_text="Notes from the supplier (parsed from response)"
                    ),
                ),
                (
                    "bid_response_data",
                    models.JSONField(blank=True, default=dict, help_text="Parsed bid response data (from email/API)"),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sales dept contact at the supplier",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_bid_contacts",
                        to="contacts.contact",
                    ),
                ),
                (
                    "inquiry_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_bids",
                        to="inquiries.inquiryproduct",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: specific plant for this bid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_product_bids",
                        to="plants.plant",
                    ),
                ),
                (
                    "rfq",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to outbound RFQ audit row",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_bids",
                        to="inquiries.inquirysupplierrfq",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_product_bids",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry Product Supplier Bid",
                "verbose_name_plural": "Inquiry Product Supplier Bids",
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "inquiry_product", "bid_status"], name="inqbid_tenant_prod_status_idx"
                    ),
                    models.Index(fields=["tenant", "supplier", "bid_status"], name="inqbid_tenant_supp_status_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "inquiry_product", "supplier", "plant"),
                        name="unique_bid_per_product_supplier_plant",
                    )
                ],
            },
        ),
        # RLS: Enable Row-Level Security for tenant isolation (MANDATORY)
        migrations.RunSQL(
            sql="""
            ALTER TABLE inquiries_inquiryproductsupplierbid ENABLE ROW LEVEL SECURITY;

            CREATE POLICY inquiryproductsupplierbid_tenant_isolation
                ON inquiries_inquiryproductsupplierbid
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS inquiryproductsupplierbid_tenant_isolation
                ON inquiries_inquiryproductsupplierbid;
            ALTER TABLE inquiries_inquiryproductsupplierbid DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
