# Generated by Django 6.0 on 2026-05-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0015_supplier_bid_system"),
        ("integrations", "0010_emaillog_failure_code_emaillog_status_metadata"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(help_text="Type of entity (inquiry, purchase_order, etc)", max_length=30),
                ),
                ("entity_id", models.IntegerField(help_text="ID of the related entity")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("inquiry", "Inquiry"),
                            ("purchase_order", "Purchase Order"),
                            ("sales_order", "Sales Order"),
                            ("carrier_po", "Carrier PO"),
                            ("fulfillment", "Fulfillment"),
                            ("invoice", "Invoice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("direction", models.CharField(choices=[("sent", "Sent"), ("received", "Received")], max_length=10)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("email", "Email"),
                            ("attachment", "Attachment"),
                            ("contract", "Contract"),
                            ("quote", "Quote"),
                            ("bid_request", "Bid Request"),
                            ("bid_response", "Bid Response"),
                            ("confirmation", "Confirmation"),
                            ("invoice_doc", "Invoice Document"),
                            ("bol", "Bill of Lading"),
                            ("pod", "Proof of Delivery"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("file", models.FileField(blank=True, null=True, upload_to="trade_documents/%Y/%m/")),
                ("file_size", models.IntegerField(blank=True, help_text="File size in bytes", null=True)),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                (
                    "generated_by",
                    models.CharField(
                        choices=[("system", "System"), ("user", "User"), ("email_ingest", "Email Ingestion")],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("stage_order", models.IntegerField(default=0, help_text="Execution order within stage")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "email_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trade_documents",
                        to="integrations.emaillog",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "trade_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="inquiries.tradesession",
                    ),
                ),
            ],
            options={
                "ordering": ["stage_order", "created_on"],
                "indexes": [
                    models.Index(fields=["tenant", "trade_session"], name="inquiries_t_tenant__3458c5_idx"),
                    models.Index(fields=["tenant", "entity_type", "entity_id"], name="inquiries_t_tenant__428480_idx"),
                ],
            },
        ),
        # RLS for TradeDocument + backfill RLS for TradeSession (previously missing)
        migrations.RunSQL(
            sql="""
            ALTER TABLE inquiries_tradedocument ENABLE ROW LEVEL SECURITY;
            DO $$ BEGIN
                CREATE POLICY tradedocument_tenant_isolation ON inquiries_tradedocument
                    USING (tenant_id = current_setting('app.current_tenant')::uuid);
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;

            ALTER TABLE inquiries_tradesession ENABLE ROW LEVEL SECURITY;
            DO $$ BEGIN
                CREATE POLICY tradesession_tenant_isolation ON inquiries_tradesession
                    USING (tenant_id = current_setting('app.current_tenant')::uuid);
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tradedocument_tenant_isolation ON inquiries_tradedocument;
            ALTER TABLE inquiries_tradedocument DISABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tradesession_tenant_isolation ON inquiries_tradesession;
            ALTER TABLE inquiries_tradesession DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
