# Generated by Django 6.0 on 2026-05-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0016_trade_document_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiryproduct",
            name="commission_per_unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Commission/markup per unit (trader's profit per unit)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inquiryproductsupplierbid",
            name="commission_per_unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Commission/markup per unit (trader's profit per unit)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
