# Generated by Django 6.0 on 2025-12-06 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "carrier_type",
                    models.CharField(
                        choices=[
                            ("truck", "Truck"),
                            ("rail", "Rail"),
                            ("air", "Air"),
                            ("sea", "Sea"),
                            ("other", "Other"),
                        ],
                        default="truck",
                        max_length=20,
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("zip_code", models.CharField(blank=True, default="", max_length=20)),
                ("country", models.CharField(default="USA", max_length=100)),
                (
                    "mc_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Motor Carrier Number",
                        max_length=50,
                    ),
                ),
                (
                    "dot_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Department of Transportation Number",
                        max_length=50,
                    ),
                ),
                (
                    "insurance_provider",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "my_customer_num_from_carrier",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Our customer number with this carrier",
                        max_length=100,
                    ),
                ),
                (
                    "accounting_payable_contact_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Accounting payable contact name",
                        max_length=255,
                    ),
                ),
                (
                    "accounting_payable_contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Accounting payable contact phone",
                        max_length=20,
                    ),
                ),
                (
                    "accounting_payable_contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Accounting payable contact email",
                        max_length=254,
                    ),
                ),
                (
                    "sales_contact_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sales contact name",
                        max_length=255,
                    ),
                ),
                (
                    "sales_contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sales contact phone",
                        max_length=20,
                    ),
                ),
                (
                    "sales_contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Sales contact email",
                        max_length=254,
                    ),
                ),
                (
                    "accounting_payment_terms",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Wire", "Wire"),
                            ("ACH", "ACH"),
                            ("Check", "Check"),
                            ("Credit Card", "Credit Card"),
                        ],
                        default="",
                        help_text="Payment terms (e.g., Wire, ACH, Check)",
                        max_length=50,
                    ),
                ),
                (
                    "credit_limits",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Wire 1 day prior", "Wire 1 day prior"),
                            ("Net 7", "Net 7"),
                            ("Net 15", "Net 15"),
                            ("Net 30", "Net 30"),
                            ("Net 45", "Net 45"),
                            ("Net 60", "Net 60"),
                        ],
                        default="",
                        help_text="Credit limits/terms (e.g., Net 30, Wire 1 day prior)",
                        max_length=50,
                    ),
                ),
                (
                    "account_line_of_credit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("$0 - $50,000", "$0 - $50,000"),
                            ("$50,000 - $100,000", "$50,000 - $100,000"),
                            ("$100,000 - $250,000", "$100,000 - $250,000"),
                            ("$250,000 - $500,000", "$250,000 - $500,000"),
                            ("$500,000 - $1,000,000", "$500,000 - $1,000,000"),
                            ("$1,000,000+", "$1,000,000+"),
                        ],
                        default="",
                        help_text="Line of credit amount range",
                        max_length=50,
                    ),
                ),
                (
                    "departments",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Departments (comma-separated: BOL, COA, POD, etc.)",
                        max_length=255,
                    ),
                ),
                (
                    "how_carrier_make_appointment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Email", "Email"),
                            ("Phone", "Phone"),
                            ("Website", "Website"),
                            ("Fax", "Fax"),
                            ("FCFS", "FCFS"),
                        ],
                        default="",
                        help_text="How carrier makes appointments (e.g., Email, Phone)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contacts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Multiple contacts associated with this carrier",
                        related_name="carriers",
                        to="contacts.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrier",
                "verbose_name_plural": "Carriers",
                "ordering": ["name"],
            },
        ),
    ]
