# Generated by Django 6.0 on 2025-12-10 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_tenant_field_if_not_exists(apps, schema_editor):
    """Add tenant field only if it doesn't exist"""
    from django.db import connection

    with connection.cursor() as cursor:
        # Check if table and tenant_id column exist
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema='public'
            AND table_name=%s
            AND column_name='tenant_id';
        """,
            ["carriers_carrier"],
        )

        if not cursor.fetchone():
            # Check if any tenants exist
            cursor.execute("SELECT id FROM tenants_tenant LIMIT 1;")
            result = cursor.fetchone()

            if result:
                # Production path: Tenant exists, use it as default
                default_tenant_id = result[0]
                cursor.execute(
                    """
                    ALTER TABLE carriers_carrier
                    ADD COLUMN tenant_id UUID NOT NULL DEFAULT %s
                    REFERENCES tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;
                """,
                    [default_tenant_id],
                )

                # Remove the default after adding the column
                cursor.execute(
                    """
                    ALTER TABLE carriers_carrier
                    ALTER COLUMN tenant_id DROP DEFAULT;
                """
                )
            else:
                # Test/Fresh DB path: No tenants exist yet, add as nullable
                cursor.execute(
                    """
                    ALTER TABLE carriers_carrier
                    ADD COLUMN tenant_id UUID NULL
                    REFERENCES tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;
                """
                )


class Migration(migrations.Migration):
    dependencies = [
        ("carriers", "0001_initial"),
        ("contacts", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # CRITICAL FIX: Separate State (Django) from Database (SQL)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Tell Django the field exists so models validate
                migrations.AddField(
                    model_name="carrier",
                    name="tenant",
                    field=models.ForeignKey(
                        help_text="Tenant this carrier belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carriers",
                        to="tenants.tenant",
                    ),
                    preserve_default=False,
                ),
            ],
            database_operations=[
                # Actually create the column safely using our custom script
                migrations.RunPython(add_tenant_field_if_not_exists, migrations.RunPython.noop),
            ],
        ),
        # Add index (Safe to run after column is ensured)
        migrations.AddIndex(
            model_name="carrier",
            index=models.Index(fields=["tenant", "name"], name="carriers_ca_tenant__8e23de_idx"),
        ),
    ]
