# Generated by Django 6.0 on 2026-01-07 23:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carriers", "0003_add_logistics_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="departments_array",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("BOL", "BOL"), ("COA", "COA"), ("POD", "POD")],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="Departments (multi-select: BOL, COA, POD) - NEW",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="how_carrier_make_appointment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Email", "Email"),
                    ("Phone", "Phone"),
                    ("Website", "Website"),
                    ("Fax", "Fax"),
                    ("First Come First Serve", "First Come First Serve"),
                ],
                default="",
                help_text="How carrier makes appointments (e.g., Email, Phone)",
                max_length=50,
            ),
        ),
    ]
