# Generated by Django 6.0 on 2026-03-18 03:16
# Add RLS policy for Carrier model

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("carriers", "0005_carrier_created_on_carrier_custom_data_and_more"),
    ]

    operations = [
        RunSQL(
            sql="""
            -- Enable RLS on carriers_carrier
            ALTER TABLE carriers_carrier ENABLE ROW LEVEL SECURITY;

            -- Create tenant isolation policy
            CREATE POLICY carriers_carrier_tenant_isolation ON carriers_carrier
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS carriers_carrier_tenant_isolation ON carriers_carrier;
            ALTER TABLE carriers_carrier DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
