# Generated by Django 6.0 on 2026-03-22
# Normalize RLS policy to safe current_setting('app.current_tenant', true)

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("carriers", "0006_add_rls_policies_batch"),
    ]

    # NOTE:
    # Avoid `run_before` here. Some environments already have fulfillments.0001 applied,
    # and adding ordering edges can cause InconsistentMigrationHistory during deploy.

    operations = [
        RunSQL(
            sql="""
            ALTER TABLE carriers_carrier ENABLE ROW LEVEL SECURITY;
            ALTER TABLE carriers_carrier FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS carriers_carrier_tenant_isolation ON carriers_carrier;
            CREATE POLICY carriers_carrier_tenant_isolation ON carriers_carrier
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS carriers_carrier_tenant_isolation ON carriers_carrier;
            CREATE POLICY carriers_carrier_tenant_isolation ON carriers_carrier
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
        ),
    ]
