# Generated by Django 6.0 on 2026-03-22
# Normalize RLS policy to safe current_setting('app.current_tenant', true)

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("carriers", "0006_add_rls_policies_batch"),
    ]

    # Ensure this runs before fulfillments initial migration (which FK-checks carriers_carrier)
    run_before = [
        ("fulfillments", "0001_initial"),
    ]

    operations = [
        RunSQL(
            sql="""
            ALTER TABLE carriers_carrier ENABLE ROW LEVEL SECURITY;
            ALTER TABLE carriers_carrier FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS carriers_carrier_tenant_isolation ON carriers_carrier;
            CREATE POLICY carriers_carrier_tenant_isolation ON carriers_carrier
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS carriers_carrier_tenant_isolation ON carriers_carrier;
            CREATE POLICY carriers_carrier_tenant_isolation ON carriers_carrier
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
        ),
    ]
