# Generated by Django 6.0 on 2026-03-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0007_fix_carrier_rls_policy_safe_current_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="phone_type",
            field=models.CharField(
                blank=True,
                choices=[("mobile", "Mobile"), ("office", "Office")],
                default="office",
                help_text="Carrier phone type (mobile or office)",
                max_length=10,
            ),
        ),
    ]
