# Generated by Django 6.0 on 2026-05-07 12:25

import django.db.models.deletion
import tenant_apps.carriers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0009_golden_schema_refactor"),
        ("integrations", "0006_alter_emaillog_status"),
        ("sales_orders", "0018_salesorderapprovaldispatch"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarrierFreightInquiry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("sender_email", models.EmailField(blank=True, default="", max_length=254)),
                ("recipient_email", models.EmailField(blank=True, default="", max_length=254)),
                ("recipient_name", models.CharField(blank=True, default="", max_length=255)),
                ("subject", models.CharField(default="", max_length=300)),
                ("body", models.TextField(default="")),
                ("origin_city", models.CharField(blank=True, default="", max_length=100)),
                ("origin_state", models.CharField(blank=True, default="", max_length=100)),
                ("destination_city", models.CharField(blank=True, default="", max_length=100)),
                ("destination_state", models.CharField(blank=True, default="", max_length=100)),
                ("commodity", models.CharField(blank=True, default="", max_length=255)),
                ("weight", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("weight_unit", models.CharField(blank=True, default="lbs", max_length=10)),
                ("pickup_date", models.DateField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("special_instructions", models.TextField(blank=True, default="")),
                (
                    "inquiry_pdf",
                    models.FileField(
                        blank=True, default="", upload_to=tenant_apps.carriers.models.carrier_freight_inquiry_upload_to
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("replied", "Replied"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("provider_message_id", models.CharField(blank=True, default="", max_length=255)),
                ("provider_thread_id", models.CharField(blank=True, default="", max_length=255)),
                ("provider_internet_message_id", models.CharField(blank=True, default="", max_length=255)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freight_inquiries",
                        to="carriers.carrier",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carrier_freight_inquiries_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrier_freight_inquiries",
                        to="sales_orders.salesorder",
                    ),
                ),
                (
                    "sender_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carrier_freight_inquiries",
                        to="integrations.externalauthprovider",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrier Freight Inquiry",
                "verbose_name_plural": "Carrier Freight Inquiries",
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="cfi_tenant_status_idx"),
                    models.Index(fields=["tenant", "sales_order"], name="cfi_tenant_so_idx"),
                    models.Index(fields=["tenant", "carrier"], name="cfi_tenant_carrier_idx"),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE carriers_carrierfreightinquiry ENABLE ROW LEVEL SECURITY;
            CREATE POLICY carrierfreightinquiry_tenant_isolation
                ON carriers_carrierfreightinquiry
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS carrierfreightinquiry_tenant_isolation
                ON carriers_carrierfreightinquiry;
            ALTER TABLE carriers_carrierfreightinquiry DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
