# Generated by Django 6.0 on 2026-05-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0010_carrierfreightinquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="carrier_release_number",
            field=models.CharField(
                blank=True, default="", help_text="Default carrier release number reference", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="contact_title",
            field=models.CharField(blank=True, default="", help_text="Primary carrier contact title", max_length=100),
        ),
        migrations.AddField(
            model_name="carrier",
            name="delivery_date",
            field=models.DateField(blank=True, help_text="Default delivery date", null=True),
        ),
        migrations.AddField(
            model_name="carrier",
            name="delivery_po_number",
            field=models.CharField(
                blank=True, default="", help_text="Default delivery PO number reference", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="description_of_product_item",
            field=models.TextField(blank=True, default="", help_text="Default product item description"),
        ),
        migrations.AddField(
            model_name="carrier",
            name="edible_or_inedible",
            field=models.CharField(
                blank=True,
                choices=[("Edible", "Edible"), ("Inedible", "Inedible"), ("Edible & Inedible", "Edible & Inedible")],
                default="",
                help_text="Default edible / inedible classification",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="fresh_or_frozen",
            field=models.CharField(
                blank=True,
                choices=[("Fresh", "Fresh"), ("Frozen", "Frozen")],
                default="",
                help_text="Default fresh or frozen setting",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="net_or_catch_of_package",
            field=models.CharField(
                blank=True,
                choices=[("Net", "Net"), ("Catch", "Catch")],
                default="",
                help_text="Default net or catch of package",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="our_purchase_order_number_to_supplier",
            field=models.CharField(
                blank=True, default="", help_text="Default supplier PO number reference", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="package_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Boxed wax lined", "Boxed wax lined"),
                    ("Boxed Poly", "Boxed Poly"),
                    ("Combos", "Combos"),
                    ("Nude Block", "Nude Block"),
                    ("Boxed COV", "Boxed COV"),
                    ("Boxed CO2", "Boxed CO2"),
                    ("Combo bins", "Combo bins"),
                    ("Totes", "Totes"),
                    ("Bags", "Bags"),
                    ("Bulk", "Bulk"),
                    ("Poly-Multiple", "Poly-Multiple"),
                    ("Nude", "Nude"),
                ],
                default="",
                help_text="Default package type",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="pick_up_date",
            field=models.DateField(blank=True, help_text="Default pick up date", null=True),
        ),
        migrations.AddField(
            model_name="carrier",
            name="pickup_delivery_address",
            field=models.TextField(blank=True, default="", help_text="Address of pick up / delivery location"),
        ),
        migrations.AddField(
            model_name="carrier",
            name="pickup_delivery_building_name",
            field=models.CharField(
                blank=True, default="", help_text="Business building name for pick up / delivery", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="pickup_delivery_city",
            field=models.CharField(
                blank=True, default="", help_text="City for pick up / delivery location", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="pickup_delivery_state_zip",
            field=models.CharField(
                blank=True, default="", help_text="State and ZIP for pick up / delivery location", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="plant_address",
            field=models.TextField(blank=True, default="", help_text="Plant address"),
        ),
        migrations.AddField(
            model_name="carrier",
            name="plant_city",
            field=models.CharField(blank=True, default="", help_text="Plant city", max_length=100),
        ),
        migrations.AddField(
            model_name="carrier",
            name="plant_state_zip",
            field=models.CharField(blank=True, default="", help_text="Plant state and ZIP", max_length=100),
        ),
        migrations.AddField(
            model_name="carrier",
            name="quantity",
            field=models.IntegerField(blank=True, help_text="Default quantity", null=True),
        ),
        migrations.AddField(
            model_name="carrier",
            name="receiving_contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="carrier",
            name="receiving_contact_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="carrier",
            name="receiving_contact_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="carrier",
            name="sales_contact_cell_phone",
            field=models.CharField(blank=True, default="", help_text="Sales contact cell phone number", max_length=20),
        ),
        migrations.AddField(
            model_name="carrier",
            name="sales_contact_direct_phone",
            field=models.CharField(
                blank=True, default="", help_text="Sales contact direct phone number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="sales_contact_main_phone",
            field=models.CharField(blank=True, default="", help_text="Sales contact main phone number", max_length=20),
        ),
        migrations.AddField(
            model_name="carrier",
            name="shipping_contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="carrier",
            name="shipping_contact_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="carrier",
            name="shipping_contact_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="carrier",
            name="supplier_confirmation_order_number",
            field=models.CharField(
                blank=True, default="", help_text="Default supplier confirmation order number reference", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="tested_product",
            field=models.BooleanField(default=False, help_text="Default tested-product flag"),
        ),
        migrations.AddField(
            model_name="carrier",
            name="total_weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="Default total weight", max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="type_of_protein",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beef", "Beef"),
                    ("Chicken", "Chicken"),
                    ("Fowl", "Fowl"),
                    ("Turkey", "Turkey"),
                    ("Lamb", "Lamb"),
                    ("Veal", "Veal"),
                    ("Seafood", "Seafood"),
                    ("Venison", "Venison"),
                    ("Bison", "Bison"),
                    ("Duck", "Duck"),
                    ("Rabbit", "Rabbit"),
                    ("Goat", "Goat"),
                    ("Mutton", "Mutton"),
                    ("Pork", "Pork"),
                    ("Fish", "Fish"),
                    ("Horse", "Horse"),
                    ("Other", "Other"),
                ],
                default="",
                help_text="Default type of protein hauled by this carrier",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="account_line_of_credit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("$50K", "$50K"),
                    ("50K-100K", "50K-100K"),
                    ("100K-150K", "100K-150K"),
                    ("150K-200K", "150K-200K"),
                    ("Etc.", "Etc."),
                    ("Wire", "Wire"),
                    ("$0 - $50,000", "$0 - $50,000"),
                    ("$50,000 - $100,000", "$50,000 - $100,000"),
                    ("$100,000 - $250,000", "$100,000 - $250,000"),
                    ("$250,000 - $500,000", "$250,000 - $500,000"),
                    ("$500,000 - $1,000,000", "$500,000 - $1,000,000"),
                    ("$1,000,000+", "$1,000,000+"),
                ],
                default="",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="credit_limit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Wire 1 day prior", "Wire 1 day prior"),
                    ("Wire 2 day prior", "Wire 2 day prior"),
                    ("Wire 3 day prior", "Wire 3 day prior"),
                    ("Wire 4 day prior", "Wire 4 day prior"),
                    ("Wire 5 day prior", "Wire 5 day prior"),
                    ("ACH 1 day prior", "ACH 1 day prior"),
                    ("ACH 2 day prior", "ACH 2 day prior"),
                    ("ACH 3 day prior", "ACH 3 day prior"),
                    ("ACH 4 day prior", "ACH 4 day prior"),
                    ("Net 5 days", "Net 5 days"),
                    ("Net 7 days", "Net 7 days"),
                    ("Net 10 days", "Net 10 days"),
                    ("Net 14 days", "Net 14 days"),
                    ("Net 30 days", "Net 30 days"),
                    ("Net 7", "Net 7"),
                    ("Net 15", "Net 15"),
                    ("Net 30", "Net 30"),
                    ("Net 45", "Net 45"),
                    ("Net 60", "Net 60"),
                ],
                default="",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="credit_limits",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Wire 1 day prior", "Wire 1 day prior"),
                    ("Wire 2 day prior", "Wire 2 day prior"),
                    ("Wire 3 day prior", "Wire 3 day prior"),
                    ("Wire 4 day prior", "Wire 4 day prior"),
                    ("Wire 5 day prior", "Wire 5 day prior"),
                    ("ACH 1 day prior", "ACH 1 day prior"),
                    ("ACH 2 day prior", "ACH 2 day prior"),
                    ("ACH 3 day prior", "ACH 3 day prior"),
                    ("ACH 4 day prior", "ACH 4 day prior"),
                    ("Net 5 days", "Net 5 days"),
                    ("Net 7 days", "Net 7 days"),
                    ("Net 10 days", "Net 10 days"),
                    ("Net 14 days", "Net 14 days"),
                    ("Net 30 days", "Net 30 days"),
                    ("Net 7", "Net 7"),
                    ("Net 15", "Net 15"),
                    ("Net 30", "Net 30"),
                    ("Net 45", "Net 45"),
                    ("Net 60", "Net 60"),
                ],
                default="",
                help_text="Credit limits/terms (e.g., Net 30, Wire 1 day prior)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="how_carrier_make_appointment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Email", "Email"),
                    ("Phone", "Phone"),
                    ("Website", "Website"),
                    ("FCFS", "FCFS"),
                    ("Fax", "Fax"),
                    ("First Come First Serve", "First Come First Serve"),
                ],
                default="",
                help_text="How carrier makes appointments (e.g., Email, Phone)",
                max_length=50,
            ),
        ),
    ]
