# Generated by Django 6.0 on 2026-04-28 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fulfillments", "0007_fulfillment_document_milestones_and_more"),
        ("purchase_orders", "0017_purchaseorder_deleted_at_purchaseorder_is_deleted"),
        ("sales_orders", "0015_salesorder_deleted_at_salesorder_is_deleted"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("deal_number", models.CharField(editable=False, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "assigned_trader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_deals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fulfillment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deal",
                        to="fulfillments.fulfillment",
                    ),
                ),
                (
                    "purchase_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deal",
                        to="purchase_orders.purchaseorder",
                    ),
                ),
                (
                    "sales_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="deal", to="sales_orders.salesorder"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="DealActionItem",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("milestone_key", models.CharField(default="transit_documents", max_length=64)),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("normal", "Normal"), ("high", "High"), ("urgent", "Urgent")],
                        default="normal",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("completed", "Completed"), ("cancelled", "Cancelled")],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deal_action_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="action_items", to="deals.deal"
                    ),
                ),
                (
                    "fulfillment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_action_items",
                        to="fulfillments.fulfillment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "created_on"],
            },
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["tenant", "deal_number"], name="deals_deal_tenant__d8f29b_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["tenant", "status"], name="deals_deal_tenant__6a3b02_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["assigned_trader"], name="deals_deal_assigne_193405_idx"),
        ),
        migrations.AddConstraint(
            model_name="deal",
            constraint=models.UniqueConstraint(fields=("tenant", "deal_number"), name="unique_tenant_deal_number"),
        ),
        migrations.AddIndex(
            model_name="dealactionitem",
            index=models.Index(fields=["tenant", "status"], name="deals_deala_tenant__a76bab_idx"),
        ),
        migrations.AddIndex(
            model_name="dealactionitem",
            index=models.Index(fields=["tenant", "assigned_user"], name="deals_deala_tenant__515882_idx"),
        ),
        migrations.AddIndex(
            model_name="dealactionitem",
            index=models.Index(fields=["tenant", "due_date"], name="deals_deala_tenant__2257aa_idx"),
        ),
        migrations.AddConstraint(
            model_name="dealactionitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="open"),
                fields=("deal", "fulfillment", "milestone_key"),
                name="unique_open_deal_action_item_per_milestone",
            ),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE deals_deal ENABLE ROW LEVEL SECURITY;
            ALTER TABLE deals_deal FORCE ROW LEVEL SECURITY;
            CREATE POLICY deals_deal_tenant_isolation ON deals_deal
                USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

            ALTER TABLE deals_dealactionitem ENABLE ROW LEVEL SECURITY;
            ALTER TABLE deals_dealactionitem FORCE ROW LEVEL SECURITY;
            CREATE POLICY deals_dealactionitem_tenant_isolation ON deals_dealactionitem
                USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS deals_dealactionitem_tenant_isolation ON deals_dealactionitem;
            ALTER TABLE deals_dealactionitem DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS deals_deal_tenant_isolation ON deals_deal;
            ALTER TABLE deals_deal DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
