# Generated by Django 6.0 on 2026-02-01 00:37

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0006_metadata_lockdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemChoiceList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier (e.g., 'protein_type', 'payment_terms')",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Slug must start with a letter and contain only lowercase letters, numbers, and underscores.",
                                regex="^[a-z][a-z0-9_]*$",
                            )
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Protein Type', 'Payment Terms')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this choice list is used for",
                    ),
                ),
                (
                    "model_field_path",
                    models.CharField(
                        blank=True,
                        help_text="Dot-path to model field (e.g., 'products.Product.protein_type')",
                        max_length=255,
                    ),
                ),
                (
                    "is_extensible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether tenant admins can add custom items",
                    ),
                ),
                (
                    "is_reorderable",
                    models.BooleanField(default=True, help_text="Whether items can be reordered"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_choice_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Choice List",
                "verbose_name_plural": "System Choice Lists",
                "db_table": "system_choice_list",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="SystemFieldSchema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_path",
                    models.CharField(
                        help_text="Dot-path to field (e.g., 'products.product.protein_type')",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Field path must be dot-separated lowercase identifiers (e.g., "products.product.protein_type")',
                                regex="^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)+$",
                            )
                        ],
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("NUMBER", "Number"),
                            ("DECIMAL", "Decimal"),
                            ("DATE", "Date"),
                            ("DATETIME", "DateTime"),
                            ("BOOLEAN", "Boolean"),
                            ("CHOICE", "Choice/Dropdown"),
                            ("MULTI_CHOICE", "Multiple Choice"),
                            ("FOREIGN_KEY", "Foreign Key"),
                            ("JSON", "JSON"),
                            ("FILE", "File Upload"),
                        ],
                        default="TEXT",
                        help_text="Data type of this field",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Override display label (uses model field name if blank)",
                        max_length=255,
                    ),
                ),
                (
                    "help_text",
                    models.TextField(blank=True, help_text="Help text shown below the field"),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True,
                        help_text="Placeholder text for empty fields",
                        max_length=255,
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Validation rules, e.g.:\n        {\n            "required": true,\n            "min_length": 3,\n            "max_length": 100,\n            "pattern": "^[A-Z]+$",\n            "min_value": 0,\n            "max_value": 1000000\n        }',
                    ),
                ),
                (
                    "default_value",
                    models.JSONField(blank=True, help_text="Default value for new records", null=True),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, help_text="Whether this field is required"),
                ),
                (
                    "is_readonly",
                    models.BooleanField(default=False, help_text="Whether this field is read-only"),
                ),
                (
                    "is_hidden",
                    models.BooleanField(default=False, help_text="Whether this field is hidden from UI"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "choice_list",
                    models.ForeignKey(
                        blank=True,
                        help_text="For CHOICE/MULTI_CHOICE fields: the source choice list",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schema_fields",
                        to="system.systemchoicelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Field Schema",
                "verbose_name_plural": "System Field Schemas",
                "db_table": "system_field_schema",
                "ordering": ["field_path"],
            },
        ),
        migrations.CreateModel(
            name="SystemChoiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Value stored in database (e.g., 'BEEF', 'NET30')",
                        max_length=100,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable label (e.g., 'Beef', 'Net 30 Days')",
                        max_length=255,
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (e.g., icon, color, description)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sort order within the list (lower = first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item is available for selection",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="Whether this is the default selection"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning tenant (null for system-defined items)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_choice_items",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "choice_list",
                    models.ForeignKey(
                        help_text="The choice list this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="system.systemchoicelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Choice Item",
                "verbose_name_plural": "System Choice Items",
                "db_table": "system_choice_item",
                "ordering": ["order", "label"],
                "indexes": [
                    models.Index(
                        fields=["choice_list", "is_active", "order"],
                        name="system_choi_choice__d34c93_idx",
                    ),
                    models.Index(
                        fields=["tenant", "choice_list"],
                        name="system_choi_tenant__d147f1_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("tenant__isnull", True)),
                        fields=("choice_list", "value"),
                        name="unique_system_choice_value",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("tenant__isnull", False)),
                        fields=("choice_list", "tenant", "value"),
                        name="unique_tenant_choice_value",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Configuration key (e.g., 'ui.theme.primary_color')",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Config key must be dot-separated lowercase identifiers (e.g., "ui.theme.primary_color")',
                                regex="^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)*$",
                            )
                        ],
                    ),
                ),
                (
                    "value",
                    models.JSONField(help_text="Configuration value (JSON: string, number, boolean, object, array)"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("UI", "User Interface"),
                            ("BUSINESS", "Business Rules"),
                            ("FEATURES", "Feature Flags"),
                            ("INTEGRATIONS", "Integrations"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Category for grouping in admin UI",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of what this config controls"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant this configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_tenant_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Configuration",
                "verbose_name_plural": "Tenant Configurations",
                "db_table": "tenant_config",
                "ordering": ["tenant", "key"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "category"],
                        name="tenant_conf_tenant__b679c1_idx",
                    ),
                    models.Index(fields=["key"], name="tenant_conf_key_f823c5_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("tenant", "key"), name="unique_tenant_config_key")],
            },
        ),
    ]
