# Generated by Django 6.0 on 2026-02-02 07:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "product_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique product code (e.g., 'BEEF-RIBEYE-001')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, help_text="Short product name", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Detailed description of the product")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BEEF", "Beef"),
                            ("PORK", "Pork"),
                            ("POULTRY", "Poultry"),
                            ("SEAFOOD", "Seafood"),
                            ("LAMB", "Lamb"),
                            ("VEAL", "Veal"),
                            ("GAME", "Game"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Primary product category",
                        max_length=50,
                    ),
                ),
                (
                    "protein_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Type of protein (references SystemChoiceList 'protein_type')",
                        max_length=100,
                    ),
                ),
                (
                    "fresh_or_frozen",
                    models.CharField(
                        blank=True, default="", help_text="Product state: FRESH, FROZEN, or blank", max_length=20
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Package type (references SystemChoiceList 'package_type')",
                        max_length=100,
                    ),
                ),
                (
                    "carton_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Type of carton (references SystemChoiceList 'carton_type')",
                        max_length=100,
                    ),
                ),
                (
                    "unit_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Standard unit weight in default UOM",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "uom",
                    models.CharField(
                        blank=True, default="LB", help_text="Unit of measure (LB, KG, etc.)", max_length=10
                    ),
                ),
                (
                    "pcs_per_carton",
                    models.CharField(
                        blank=True, default="", help_text="Pieces per carton (e.g., '4/10')", max_length=50
                    ),
                ),
                (
                    "namp_code",
                    models.CharField(
                        blank=True, default="", help_text="NAMP (North American Meat Processors) code", max_length=50
                    ),
                ),
                ("usda_code", models.CharField(blank=True, default="", help_text="USDA code", max_length=50)),
                ("ub_code", models.CharField(blank=True, default="", help_text="UB code", max_length=50)),
                (
                    "edible_or_inedible",
                    models.CharField(
                        blank=True, default="", help_text="Edible or inedible classification", max_length=50
                    ),
                ),
                (
                    "net_or_catch",
                    models.CharField(blank=True, default="", help_text="Weight type: NET or CATCH", max_length=20),
                ),
                (
                    "tested_product",
                    models.BooleanField(default=False, help_text="Whether this product requires testing"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this product is active and available"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legacy_tenant_product_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Original ID from tenant_apps.products for migration tracking",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "system_product",
                "ordering": ["product_code"],
                "indexes": [
                    models.Index(fields=["category", "is_active"], name="system_prod_categor_0d370e_idx"),
                    models.Index(fields=["protein_type", "is_active"], name="system_prod_protein_7bb60a_idx"),
                ],
            },
        ),
    ]
