# Generated by Django 6.0 on 2026-02-02 07:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0009_supplier_custom_data_alter_supplier_tenant"),
        ("system", "0002_add_product_model"),
        ("tenants", "0006_metadata_lockdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantProductPreference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tenant-specific display name (overrides product.name)",
                        max_length=255,
                    ),
                ),
                (
                    "internal_code",
                    models.CharField(blank=True, default="", help_text="Tenant's internal product code", max_length=50),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", help_text="Tenant-specific notes about this product"),
                ),
                (
                    "default_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tenant's default selling price",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "default_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tenant's default purchase cost",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "supplier_item_number",
                    models.CharField(
                        blank=True, default="", help_text="Supplier's item number for this product", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this product is active for this tenant"),
                ),
                ("is_favorite", models.BooleanField(default=False, help_text="Quick-access favorite product")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="Sort order in product lists (lower = first)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant's preferred supplier for this product",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_products",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The system product this preference is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_preferences",
                        to="system.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant this preference belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_preferences",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Product Preference",
                "verbose_name_plural": "Tenant Product Preferences",
                "db_table": "tenant_product_preference",
                "ordering": ["sort_order", "product__name"],
                "indexes": [
                    models.Index(fields=["tenant", "is_active", "sort_order"], name="tenant_prod_tenant__eb68f4_idx"),
                    models.Index(fields=["tenant", "is_favorite"], name="tenant_prod_tenant__734c3d_idx"),
                    models.Index(fields=["tenant", "preferred_supplier"], name="tenant_prod_tenant__bb8243_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("tenant", "product"), name="unique_tenant_product")],
            },
        ),
    ]
