# Generated by Django 6.0 on 2026-02-03 23:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("system", "0004_migrate_product_data"),
        ("tenants", "0006_metadata_lockdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigAuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("object_id", models.CharField(help_text="ID of the changed entity", max_length=255)),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Human-readable entity type (e.g., 'TenantConfig', 'ChoiceList')", max_length=50
                    ),
                ),
                ("entity_name", models.CharField(help_text="Name/key of the entity for display", max_length=255)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                            ("IMPORT", "Imported"),
                            ("EXPORT", "Exported"),
                        ],
                        help_text="Type of change",
                        max_length=10,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, help_text="Specific field that was changed (for updates)", max_length=100
                    ),
                ),
                ("old_value", models.JSONField(blank=True, help_text="Previous value (JSON)", null=True)),
                ("new_value", models.JSONField(blank=True, help_text="New value (JSON)", null=True)),
                (
                    "snapshot_before",
                    models.JSONField(blank=True, help_text="Complete entity state before change", null=True),
                ),
                (
                    "snapshot_after",
                    models.JSONField(blank=True, help_text="Complete entity state after change", null=True),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True, help_text="Email snapshot for display even if user deleted", max_length=254
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, help_text="IP address of the request", null=True),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User agent string")),
                ("notes", models.TextField(blank=True, help_text="Additional notes about the change")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of entity that was changed",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant context (null for system-level changes)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_audit_logs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Config Audit Log",
                "verbose_name_plural": "Config Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["entity_type", "-created_at"], name="system_conf_entity__d66e70_idx"),
                    models.Index(fields=["user", "-created_at"], name="system_conf_user_id_dfad5a_idx"),
                    models.Index(fields=["tenant", "-created_at"], name="system_conf_tenant__e840bc_idx"),
                    models.Index(fields=["change_type", "-created_at"], name="system_conf_change__abef6c_idx"),
                    models.Index(fields=["-created_at"], name="system_conf_created_d5ae85_idx"),
                ],
            },
        ),
    ]
