# Generated by Django 6.0 on 2026-02-06 15:08

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0005_add_config_audit_log"),
        ("tenants", "0006_metadata_lockdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantForm",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Form name/title", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Optional form description")),
                (
                    "type",
                    models.CharField(
                        choices=[("single_step", "Single Step"), ("multi_step", "Multi-Step")],
                        db_index=True,
                        default="single_step",
                        help_text="Form type: single-step or multi-step",
                        max_length=20,
                    ),
                ),
                (
                    "form_definition",
                    models.JSONField(default=dict, help_text="Form structure: entity type, fields, validation"),
                ),
                (
                    "version",
                    models.IntegerField(default=1, help_text="Form version number (auto-incremented on update)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usage_count",
                    models.IntegerField(default=0, help_text="Number of times this form is referenced by workflows"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this form",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this form",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this form",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenant_forms",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["tenant", "type"], name="tenant_form_tenant__aa1707_idx"),
                    models.Index(fields=["tenant", "name"], name="tenant_form_tenant__f255f7_idx"),
                    models.Index(fields=["created_at"], name="tenant_form_created_e29529_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "name", "version"), name="unique_tenant_form_name_version"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantWorkForm",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Workflow name/title", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Optional workflow description")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("archived", "Archived")],
                        db_index=True,
                        default="draft",
                        help_text="Workflow status: draft, active, or archived",
                        max_length=20,
                    ),
                ),
                (
                    "workflow_definition",
                    models.JSONField(default=dict, help_text="Complete React Flow canvas state (nodes + edges)"),
                ),
                (
                    "form_references",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        help_text="List of TenantForm IDs referenced in this workflow",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, help_text="Workflow version number (auto-incremented on update)"),
                ),
                (
                    "execution_count",
                    models.IntegerField(default=0, help_text="Number of times this workflow has been executed"),
                ),
                (
                    "last_executed_at",
                    models.DateTimeField(blank=True, help_text="When this workflow was last executed", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clone_count",
                    models.IntegerField(default=0, help_text="Number of times this workflow has been cloned"),
                ),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original workflow if this is a clone",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clones",
                        to="system.tenantworkform",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this workflow",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workforms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous version of this workflow (for version history)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_versions",
                        to="system.tenantworkform",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this workflow",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workforms",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this workflow",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_workforms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenant_workforms",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="tenant_work_tenant__38ff02_idx"),
                    models.Index(fields=["tenant", "name"], name="tenant_work_tenant__799037_idx"),
                    models.Index(fields=["created_at"], name="tenant_work_created_d74313_idx"),
                    models.Index(fields=["last_executed_at"], name="tenant_work_last_ex_4f3a8f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "name", "version"), name="unique_tenant_workform_name_version"
                    )
                ],
            },
        ),
    ]
