# Generated by Django 6.0 on 2026-02-12 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0006_add_tenant_form_and_workform_models"),
        ("tenants", "0010_add_tenant_configuration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantform",
            name="definition_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA256 hash of form_definition for deduplication",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenantform",
            name="is_template",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Whether this form is a reusable template"
            ),
        ),
        migrations.AddField(
            model_name="tenantform",
            name="source_node_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Original container node ID from React Flow (for versioning)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="tenantform",
            index=models.Index(fields=["tenant", "source_node_id", "version"], name="tenant_form_tenant__e55fee_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantform",
            index=models.Index(fields=["definition_hash"], name="tenant_form_definit_5ea781_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantform",
            index=models.Index(fields=["is_template"], name="tenant_form_is_temp_e7ded0_idx"),
        ),
    ]
