# Generated by Django 6.0 on 2026-02-14 18:56

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0008_rename_node_types"),
        ("tenants", "0010_add_tenant_configuration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantChoiceOverride",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "disabled_system_items",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        help_text="IDs of system items to hide from this tenant",
                    ),
                ),
                (
                    "display_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom display preferences (e.g., custom ordering, grouping)",
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Internal notes about why customizations were made")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "choice_list",
                    models.ForeignKey(
                        help_text="The choice list being customized",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_overrides",
                        to="system.systemchoicelist",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant applying these overrides",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choice_overrides",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified these overrides",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Choice Override",
                "verbose_name_plural": "Tenant Choice Overrides",
                "db_table": "tenant_choice_override",
                "ordering": ["tenant", "choice_list"],
                "indexes": [models.Index(fields=["tenant", "choice_list"], name="tenant_choi_tenant__b0c714_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "choice_list"), name="unique_tenant_choice_override")
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantFieldDefinition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model identifier (e.g., 'suppliers.Supplier', 'products.Product')", max_length=100
                    ),
                ),
                (
                    "field_key",
                    models.CharField(
                        help_text="Key for storing data in custom_data JSON (e.g., 'halal_certified')",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Field key must start with a letter and contain only lowercase letters, numbers, and underscores.",
                                regex="^[a-z][a-z0-9_]*$",
                            )
                        ],
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Text Area"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("datetime", "Date & Time"),
                            ("select", "Single Select"),
                            ("multiselect", "Multi Select"),
                            ("checkbox", "Checkbox"),
                            ("url", "URL"),
                            ("email", "Email"),
                        ],
                        help_text="Type of field (text, select, date, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="Display label for the field (e.g., 'Halal Certified')", max_length=255),
                ),
                ("help_text", models.TextField(blank=True, help_text="Help text shown to users")),
                ("is_required", models.BooleanField(default=False, help_text="Whether this field is required")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this field is currently active/visible"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, help_text="Order in which custom fields are displayed"),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        Field-specific configuration:\n        - For \'select\'/\'multiselect\': {"options": [{"value": "A", "label": "Option A"}]}\n        - For \'number\': {"min": 0, "max": 100, "step": 1}\n        - For \'text\': {"min_length": 3, "max_length": 50, "pattern": "regex"}\n        - For \'url\': {"allowed_domains": ["example.com"]}\n        ',
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        Custom validation rules:\n        - {"required": true}\n        - {"min_length": 3, "max_length": 100}\n        - {"pattern": "^[A-Z0-9-]+$", "message": "Custom error"}\n        - {"custom_validator": "function_name"}\n        ',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this field",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_field_definitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this field definition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_definitions",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this field",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_field_definitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Field Definition",
                "verbose_name_plural": "Tenant Field Definitions",
                "db_table": "tenant_field_definition",
                "ordering": ["model_name", "display_order", "label"],
                "indexes": [
                    models.Index(fields=["tenant", "model_name"], name="tenant_fiel_tenant__250b78_idx"),
                    models.Index(fields=["tenant", "is_active"], name="tenant_fiel_tenant__162451_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "model_name", "field_key"), name="unique_tenant_field_definition"
                    )
                ],
            },
        ),
    ]
