# Generated by Django 6.0 on 2026-03-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0009_phase3_choice_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_system",
            field=models.BooleanField(
                default=True, help_text="Whether this product is part of the system-wide golden list"
            ),
        ),
        migrations.AddField(
            model_name="tenantproductpreference",
            name="is_custom",
            field=models.BooleanField(
                default=False, help_text="Whether this preference row represents a tenant-owned custom product"
            ),
        ),
    ]
