# Generated by Django 6.0 on 2026-03-19 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0010_product_is_system_tenantproductpreference_is_custom"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantform",
            name="is_workform",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If true, this TenantForm was generated from a TenantWorkForm save",
            ),
        ),
        migrations.AddField(
            model_name="tenantform",
            name="parent_workform",
            field=models.ForeignKey(
                blank=True,
                help_text="The TenantWorkForm that generated this form (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_forms",
                to="system.tenantworkform",
            ),
        ),
    ]
