# Generated by Django 6.0 on 2026-03-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0011_tenantform_is_workform_tenantform_parent_workform"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                ("id", models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                (
                    "active_openai_model_id",
                    models.CharField(
                        default="gpt-4o-mini",
                        help_text="Active OpenAI model ID to use for chat/swarm execution",
                        max_length=128,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configuration",
                "db_table": "system_configuration",
            },
        ),
    ]
