# Generated by Django 6.0 on 2026-01-08 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tenants", "0006_metadata_lockdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "object_id",
                    models.PositiveIntegerField(help_text="ID of the related entity"),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("supplier", "Supplier"),
                            ("customer", "Customer"),
                            ("plant", "Plant"),
                            ("purchase_order", "Purchase Order"),
                            ("sales_order", "Sales Order"),
                            ("carrier", "Carrier"),
                            ("product", "Product"),
                            ("invoice", "Invoice"),
                            ("contact", "Contact"),
                        ],
                        help_text="Entity type (Supplier, Customer, Order, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.PositiveIntegerField(help_text="ID of the entity"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional title/subject of the activity",
                        max_length=255,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Activity note content (supports multiline text)"),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, help_text="Pin important notes to top of feed"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated tags (e.g., 'call, follow-up, urgent')",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of entity this log relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this log entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this activity log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("supplier", "Supplier"),
                            ("customer", "Customer"),
                            ("plant", "Plant"),
                            ("purchase_order", "Purchase Order"),
                            ("sales_order", "Sales Order"),
                            ("carrier", "Carrier"),
                            ("product", "Product"),
                            ("invoice", "Invoice"),
                            ("contact", "Contact"),
                        ],
                        help_text="Entity type for this call",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.PositiveIntegerField(help_text="ID of the related entity"),
                ),
                (
                    "title",
                    models.CharField(help_text="Call subject/title", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="Call notes/agenda"),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(help_text="When is this call scheduled?"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=30, help_text="Expected call duration in minutes"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, help_text="Has this call been completed?"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="When was this call completed?", null=True),
                ),
                (
                    "activity_log",
                    models.ForeignKey(
                        blank=True,
                        help_text="Activity log created from this call (if completed)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_calls",
                        to="cockpit.activitylog",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User responsible for this call",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this scheduled call",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scheduled_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this scheduled call belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_calls",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Call",
                "verbose_name_plural": "Scheduled Calls",
                "ordering": ["scheduled_for"],
            },
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["tenant", "entity_type", "entity_id"],
                name="cockpit_act_tenant__2fc30b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["tenant", "-created_on"], name="cockpit_act_tenant__c2e219_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="cockpit_act_content_b664de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledcall",
            index=models.Index(
                fields=["tenant", "scheduled_for"],
                name="cockpit_sch_tenant__3f2f38_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledcall",
            index=models.Index(fields=["tenant", "is_completed"], name="cockpit_sch_tenant__5a45d6_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduledcall",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="cockpit_sch_entity__09408c_idx",
            ),
        ),
    ]
