# Generated by Django 6.0 on 2026-01-08 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cockpit", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of entity this log relates to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, help_text="ID of the related entity", null=True),
        ),
    ]
