# Generated by Django 6.0 on 2026-01-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cockpit", "0002_alter_activitylog_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("supplier", "Supplier"),
                    ("customer", "Customer"),
                    ("plant", "Plant"),
                    ("purchase_order", "Purchase Order"),
                    ("sales_order", "Sales Order"),
                    ("carrier", "Carrier"),
                    ("product", "Product"),
                    ("invoice", "Invoice"),
                    ("contact", "Contact"),
                    ("inquiry", "Inquiry"),
                    ("fulfillment", "Fulfillment"),
                ],
                help_text="Entity type (Supplier, Customer, Order, etc.)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledcall",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("supplier", "Supplier"),
                    ("customer", "Customer"),
                    ("plant", "Plant"),
                    ("purchase_order", "Purchase Order"),
                    ("sales_order", "Sales Order"),
                    ("carrier", "Carrier"),
                    ("product", "Product"),
                    ("invoice", "Invoice"),
                    ("contact", "Contact"),
                    ("inquiry", "Inquiry"),
                    ("fulfillment", "Fulfillment"),
                ],
                help_text="Entity type for this call",
                max_length=50,
            ),
        ),
    ]
