# Generated by Django 6.0 on 2026-02-02 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cockpit", "0003_alter_activitylog_entity_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWorkspaceLayout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "layout",
                    models.JSONField(default=list, help_text="Widget layout positions (react-grid-layout format)"),
                ),
                ("widgets", models.JSONField(default=list, help_text="Widget configurations (id, type, title)")),
                (
                    "version",
                    models.PositiveIntegerField(default=1, help_text="Layout schema version for future migrations"),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User this layout belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_layout",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Workspace Layout",
                "verbose_name_plural": "User Workspace Layouts",
            },
        ),
    ]
