# Generated by Django 6.0 on 2026-02-27 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cockpit", "0004_add_user_workspace_layout"),
        ("tenants", "0010_add_tenant_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AddField(
            model_name="scheduledcall",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledcall",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
    ]
