# Generated by Django 6.0 on 2026-03-22
# Normalize RLS policies to safe current_setting('app.current_tenant', true)

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("cockpit", "0006_add_rls_policies_batch"),
    ]

    operations = [
        RunSQL(
            sql="""
            ALTER TABLE cockpit_activitylog ENABLE ROW LEVEL SECURITY;
            ALTER TABLE cockpit_activitylog FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS cockpit_activitylog_tenant_isolation ON cockpit_activitylog;
            CREATE POLICY cockpit_activitylog_tenant_isolation ON cockpit_activitylog
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

            ALTER TABLE cockpit_scheduledcall ENABLE ROW LEVEL SECURITY;
            ALTER TABLE cockpit_scheduledcall FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS cockpit_scheduledcall_tenant_isolation ON cockpit_scheduledcall;
            CREATE POLICY cockpit_scheduledcall_tenant_isolation ON cockpit_scheduledcall
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS cockpit_activitylog_tenant_isolation ON cockpit_activitylog;
            CREATE POLICY cockpit_activitylog_tenant_isolation ON cockpit_activitylog
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant')::uuid);

            DROP POLICY IF EXISTS cockpit_scheduledcall_tenant_isolation ON cockpit_scheduledcall;
            CREATE POLICY cockpit_scheduledcall_tenant_isolation ON cockpit_scheduledcall
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
        ),
    ]
