# Generated by Django 6.0 on 2025-12-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("core", "0001_initial"),
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Customer company name", max_length=255),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact person name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary contact email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Customer address", null=True),
                ),
                (
                    "street_address",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Street address (alternative to address field)",
                        max_length=255,
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, help_text="City", max_length=100, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="State or province",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True,
                        help_text="ZIP or postal code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, help_text="Country", max_length=100, null=True),
                ),
                (
                    "edible_inedible",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Edible", "Edible"),
                            ("Inedible", "Inedible"),
                            ("Edible & Inedible", "Edible & Inedible"),
                        ],
                        default="",
                        help_text="Type of products handled",
                        max_length=50,
                    ),
                ),
                (
                    "type_of_plant",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Customer type of plant (e.g., Vertical, Processor)",
                        max_length=100,
                    ),
                ),
                (
                    "purchasing_preference_origin",
                    models.CharField(
                        blank=True,
                        choices=[("Domestic", "Domestic"), ("Imported", "Imported")],
                        default="",
                        help_text="Purchasing preference origin (e.g., Domestic, Imported)",
                        max_length=100,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pet Sector", "Pet Sector"),
                            ("Processor", "Processor"),
                            ("Retail", "Retail"),
                            ("Food Service", "Food Service"),
                            ("Export", "Export"),
                        ],
                        default="",
                        help_text="Industry sector (e.g., Pet Sector, Retail)",
                        max_length=100,
                    ),
                ),
                (
                    "will_pickup_load",
                    models.BooleanField(default=False, help_text="Will customer pickup load?"),
                ),
                (
                    "accounting_payment_terms",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Wire", "Wire"),
                            ("ACH", "ACH"),
                            ("Check", "Check"),
                            ("Credit Card", "Credit Card"),
                        ],
                        default="",
                        help_text="Payment terms (e.g., Wire, ACH, Check)",
                        max_length=50,
                    ),
                ),
                (
                    "credit_limits",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Wire 1 day prior", "Wire 1 day prior"),
                            ("Net 7", "Net 7"),
                            ("Net 15", "Net 15"),
                            ("Net 30", "Net 30"),
                            ("Net 45", "Net 45"),
                            ("Net 60", "Net 60"),
                        ],
                        default="",
                        help_text="Credit limits/terms (e.g., Net 30, Wire 1 day prior)",
                        max_length=50,
                    ),
                ),
                (
                    "account_line_of_credit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("$0 - $50,000", "$0 - $50,000"),
                            ("$50,000 - $100,000", "$50,000 - $100,000"),
                            ("$100,000 - $250,000", "$100,000 - $250,000"),
                            ("$250,000 - $500,000", "$250,000 - $500,000"),
                            ("$500,000 - $1,000,000", "$500,000 - $1,000,000"),
                            ("$1,000,000+", "$1,000,000+"),
                        ],
                        default="",
                        help_text="Line of credit amount range",
                        max_length=50,
                    ),
                ),
                (
                    "buyer_contact_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Buyer contact name",
                        max_length=255,
                    ),
                ),
                (
                    "buyer_contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Buyer contact phone",
                        max_length=20,
                    ),
                ),
                (
                    "buyer_contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Buyer contact email",
                        max_length=254,
                    ),
                ),
                (
                    "type_of_certificate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("3rd Party", "3rd Party"),
                            ("BRC", "BRC"),
                            ("SQF", "SQF"),
                            ("Halal", "Halal"),
                            ("Kosher", "Kosher"),
                            ("Organic", "Organic"),
                        ],
                        default="",
                        help_text="Certificate type required (e.g., 3rd Party, BRC)",
                        max_length=100,
                    ),
                ),
                (
                    "product_exportable",
                    models.BooleanField(
                        default=False,
                        help_text="Does customer require exportable products?",
                    ),
                ),
                (
                    "accounting_terms",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Accounting terms (deprecated, use accounting_payment_terms)",
                        max_length=100,
                    ),
                ),
                (
                    "accounting_line_of_credit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Line of credit amount (deprecated, use account_line_of_credit)",
                        max_length=100,
                    ),
                ),
                (
                    "contacts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Multiple contacts associated with this customer",
                        related_name="customers",
                        to="contacts.contact",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated plant establishment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plants.plant",
                    ),
                ),
                (
                    "proteins",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Protein types handled by this customer",
                        to="core.protein",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["name"],
            },
        ),
    ]
