# Generated by Django 6.0 on 2026-01-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_customer_contact_title_alter_customer_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="type_of_certificate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3rd Party", "3rd Party"),
                    ("BRC", "BRC"),
                    ("FSSAI", "FSSAI"),
                    ("SQF", "SQF"),
                    ("IFS", "IFS"),
                    ("ISO", "ISO"),
                    ("HACCP", "HACCP"),
                    ("Halal", "Halal"),
                    ("Kosher", "Kosher"),
                    ("Organic", "Organic"),
                ],
                default="",
                help_text="Certificate type required (e.g., 3rd Party, BRC)",
                max_length=100,
            ),
        ),
    ]
