# Generated by Django 6.0 on 2026-01-07 23:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_alter_customer_type_of_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="industry_array",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Pet Sector", "Pet Sector"),
                        ("Processor", "Processor"),
                        ("Retail", "Retail"),
                        ("Wholesaler", "Wholesaler"),
                        ("Food Service", "Food Service"),
                        ("Export", "Export"),
                    ],
                    max_length=100,
                ),
                blank=True,
                default=list,
                help_text="Industry sectors (multi-select: Pet Sector, Retail, etc.) - NEW",
                verbose_name="Industry Sectors",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="preferred_protein_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Beef", "Beef"),
                        ("Chicken", "Chicken"),
                        ("Pork", "Pork"),
                        ("Lamb", "Lamb"),
                        ("Turkey", "Turkey"),
                        ("Fish", "Fish"),
                        ("Horse", "Horse"),
                        ("Other", "Other"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="Preferred protein types (multi-select: Beef, Chicken, Pork, etc.)",
            ),
        ),
    ]
