# Generated by Django 6.0 on 2026-01-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_customer_industry_array_and_more"),
        ("products", "0004_state_sync_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products associated with this customer",
                related_name="customers",
                to="products.product",
            ),
        ),
    ]
