# Generated by Django 6.0 on 2026-02-02 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_alter_customer_products_to_system"),
        ("locations", "0006_update_order_plant_references"),
    ]

    operations = [
        # 1) Clean up orphaned plant_id values that don't exist in locations_location
        # This prevents FK violation when altering the constraint
        migrations.RunSQL(
            sql="""
                UPDATE customers_customer c
                SET plant_id = NULL
                WHERE plant_id IS NOT NULL
                  AND NOT EXISTS (
                      SELECT 1 FROM locations_location l
                      WHERE l.id = c.plant_id
                  );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 2) Now safe to alter the FK constraint
        migrations.AlterField(
            model_name="customer",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated plant/location establishment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_plants",
                to="locations.location",
            ),
        ),
    ]
