# Generated by Django 6.0 on 2026-03-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0009_alter_customer_plant"),
    ]

    operations = []
