# Generated by Django 6.0 on 2026-03-18 03:16
# Upgrade RLS policy for Customer model to modern standard (app.current_tenant)

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0009_alter_customer_plant"),
    ]

    operations = [
        RunSQL(
            sql="""
            -- Enable RLS on customers_customer (idempotent)
            ALTER TABLE customers_customer ENABLE ROW LEVEL SECURITY;

            -- Drop any existing policies (upgrade from legacy app.current_tenant_id pattern)
            DROP POLICY IF EXISTS customer_tenant_isolation ON customers_customer;
            DROP POLICY IF EXISTS customer_tenant_insert ON customers_customer;

            -- Create tenant isolation policy for SELECT/UPDATE/DELETE
            CREATE POLICY customer_tenant_isolation ON customers_customer
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- Create tenant isolation policy for INSERT
            CREATE POLICY customer_tenant_insert ON customers_customer
                FOR INSERT
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS customer_tenant_insert ON customers_customer;
            DROP POLICY IF EXISTS customer_tenant_isolation ON customers_customer;
            ALTER TABLE customers_customer DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
