# Generated by Django 6.0 on 2026-03-29 19:28

from django.db import migrations, models


def backfill_customer_phone_slots(apps, schema_editor):
    Customer = apps.get_model("customers", "Customer")

    for c in Customer.objects.all().iterator():
        legacy_phone = (c.phone or "").strip()
        if not legacy_phone:
            continue

        # Only backfill when the new slots are empty.
        if (c.phone_mobile or "").strip() or (c.phone_office or "").strip():
            continue

        if (c.phone_type or "").strip() == "mobile":
            c.phone_mobile = legacy_phone
        else:
            c.phone_office = legacy_phone

        c.save(update_fields=["phone_mobile", "phone_office"])


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0011_customer_phone_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_mobile",
            field=models.CharField(blank=True, default="", help_text="Mobile phone number", max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_office",
            field=models.CharField(blank=True, default="", help_text="Office phone number", max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_office_extension",
            field=models.CharField(blank=True, default="", help_text="Office phone extension", max_length=10),
        ),
        migrations.RunPython(backfill_customer_phone_slots, migrations.RunPython.noop),
    ]
