# Generated by Django 6.0 on 2026-03-29 19:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0012_customer_phone_mobile_customer_phone_office_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pet Sector", "Pet Sector"),
                    ("Pet Foods", "Pet Foods"),
                    ("Processor", "Processor"),
                    ("Retail", "Retail"),
                    ("Wholesaler", "Wholesaler"),
                    ("Food Service", "Food Service"),
                    ("Export", "Export"),
                ],
                default="",
                help_text="Industry sector (e.g., Pet Sector, Retail)",
                max_length=100,
                verbose_name="Industry Sector",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="industry_array",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Pet Sector", "Pet Sector"),
                        ("Pet Foods", "Pet Foods"),
                        ("Processor", "Processor"),
                        ("Retail", "Retail"),
                        ("Wholesaler", "Wholesaler"),
                        ("Food Service", "Food Service"),
                        ("Export", "Export"),
                    ],
                    max_length=100,
                ),
                blank=True,
                default=list,
                help_text="Industry sectors (multi-select: Pet Sector, Retail, etc.) - NEW",
                verbose_name="Industry Sectors",
            ),
        ),
    ]
