# Generated by Django 6.0 on 2026-03-29 20:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0013_alter_customer_industry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="preferred_protein_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Beef", "Beef"),
                        ("Chicken", "Chicken"),
                        ("Duck", "Duck"),
                        ("Pork", "Pork"),
                        ("Lamb", "Lamb"),
                        ("Turkey", "Turkey"),
                        ("Fish", "Fish"),
                        ("Horse", "Horse"),
                        ("Other", "Other"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="Preferred protein types (multi-select: Beef, Chicken, Pork, etc.)",
            ),
        ),
    ]
