# Generated by Django 6.0 on 2026-04-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0015_alter_customer_account_line_of_credit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Wire 1 day prior", "Wire 1 day prior"),
                    ("Net 7", "Net 7"),
                    ("Net 15", "Net 15"),
                    ("Net 30", "Net 30"),
                    ("Net 45", "Net 45"),
                    ("Net 60", "Net 60"),
                ],
                default="",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_terms",
            field=models.CharField(
                blank=True,
                choices=[("Wire", "Wire"), ("ACH", "ACH"), ("Check", "Check"), ("Credit Card", "Credit Card")],
                default="",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="account_line_of_credit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("$0 - $50,000", "$0 - $50,000"),
                    ("$50,000 - $100,000", "$50,000 - $100,000"),
                    ("$100,000 - $250,000", "$100,000 - $250,000"),
                    ("$250,000 - $500,000", "$250,000 - $500,000"),
                    ("$500,000 - $1,000,000", "$500,000 - $1,000,000"),
                    ("$1,000,000+", "$1,000,000+"),
                ],
                default="",
                max_length=50,
                null=True,
            ),
        ),
    ]
