# Generated by Django 6.0 on 2026-02-23 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpreferences",
            options={"verbose_name": "User Preferences", "verbose_name_plural": "User Preferences"},
        ),
        migrations.CreateModel(
            name="UserFavorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True, help_text="Type of entity (customer, supplier, product, etc.)", max_length=50
                    ),
                ),
                ("entity_id", models.IntegerField(help_text="ID of the favorited entity")),
                ("entity_title", models.CharField(blank=True, help_text="Cached title for display", max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, help_text="When this was favorited"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who favorited this entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Favorite",
                "verbose_name_plural": "User Favorites",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="core_userfa_user_created_idx"),
                    models.Index(fields=["user", "entity_type"], name="core_userfa_user_entity_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "entity_type", "entity_id"), name="unique_user_favorite")
                ],
            },
        ),
    ]
