# Generated by Django 6.0 on 2026-03-27 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_userpreferences_options_userfavorite"),
        ("tenants", "0011_bootstrap_rls_session_vars"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userfavorite",
            name="unique_user_favorite",
        ),
        migrations.RemoveIndex(
            model_name="userfavorite",
            name="core_userfa_user_entity_idx",
        ),
        migrations.AddField(
            model_name="userfavorite",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant context for this favorite",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_favorites",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="userfavorite",
            index=models.Index(fields=["user", "tenant", "entity_type"], name="core_userfa_user_entity_idx"),
        ),
        migrations.AddConstraint(
            model_name="userfavorite",
            constraint=models.UniqueConstraint(
                fields=("user", "tenant", "entity_type", "entity_id"), name="unique_user_tenant_favorite"
            ),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE core_userfavorite ENABLE ROW LEVEL SECURITY;

            DO $$
            BEGIN
              IF NOT EXISTS (
                SELECT 1 FROM pg_policies
                WHERE schemaname = 'public'
                  AND tablename = 'core_userfavorite'
                  AND policyname = 'core_userfavorite_tenant_isolation'
              ) THEN
                CREATE POLICY core_userfavorite_tenant_isolation ON core_userfavorite
                  USING (tenant_id = nullif(current_setting('app.current_tenant', true), '')::uuid);
              END IF;
            END $$;
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS core_userfavorite_tenant_isolation ON core_userfavorite;
            ALTER TABLE core_userfavorite DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
