# Generated by Django 6.0 on 2026-03-31 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0003_remove_userfavorite_unique_user_favorite_and_more"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantAuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.CharField(db_index=True, max_length=255)),
                ("entity_type", models.CharField(db_index=True, max_length=100)),
                ("entity_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[("CREATE", "Created"), ("UPDATE", "Updated"), ("DELETE", "Deleted")], max_length=10
                    ),
                ),
                ("changed_fields", models.JSONField(blank=True, null=True)),
                ("snapshot_before", models.JSONField(blank=True, null=True)),
                ("snapshot_after", models.JSONField(blank=True, null=True)),
                ("actor_email", models.EmailField(blank=True, default="", max_length=254)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="audit_events", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "-created_at"], name="core_audit_tenant_created_idx"),
                    models.Index(fields=["entity_type", "object_id"], name="core_audit_entity_obj_idx"),
                    models.Index(fields=["action", "-created_at"], name="core_audit_action_created_idx"),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE core_tenantauditevent ENABLE ROW LEVEL SECURITY;
            CREATE POLICY tenantauditevent_tenant_isolation ON core_tenantauditevent
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tenantauditevent_tenant_isolation ON core_tenantauditevent;
            ALTER TABLE core_tenantauditevent DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
