# Generated by Django 6.0 on 2026-04-27 23:32
#
# Reconciles migration state with actual model.
# Migration 0005_comment created indexes with explicit names (core_comment_tenant_entity_idx,
# etc.) but the model uses auto-generated names. This state-only migration tells Django
# the indexes now have auto-generated names, without touching the database.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_comment"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="comment",
                    new_name="core_commen_tenant__efa08d_idx",
                    old_name="core_comment_tenant_entity_idx",
                ),
                migrations.RenameIndex(
                    model_name="comment",
                    new_name="core_commen_tenant__cca0ec_idx",
                    old_name="core_comment_tenant_created_idx",
                ),
                migrations.RenameIndex(
                    model_name="comment",
                    new_name="core_commen_content_37d5bd_idx",
                    old_name="core_comment_content_object_idx",
                ),
            ],
            database_operations=[],
        ),
    ]
