# Generated by Django 6.0 on 2026-04-27 23:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_comment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="comment",
            new_name="core_commen_tenant__efa08d_idx",
            old_name="core_comment_tenant_entity_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="core_commen_tenant__cca0ec_idx",
            old_name="core_comment_tenant_created_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="core_commen_content_37d5bd_idx",
            old_name="core_comment_content_object_idx",
        ),
    ]
