# Generated by Django 6.0 on 2026-04-27 23:32
#
# NOTE: Original migration tried to RenameIndex from explicitly-named indexes
# (core_comment_tenant_entity_idx, etc.) but 0005_comment created them with
# Django's auto-generated hash-based names (core_commen_tenant__2622f4_idx, etc.).
# Attempting to rename from non-existent old names caused ProgrammingError,
# blocking ALL subsequent migrations (including TradeSession).
# Fix: replaced with no-op since indexes already exist and work correctly.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_comment"),
    ]

    operations = [
        # Intentionally empty — indexes exist with auto-generated names and work fine.
        # Original RenameIndex ops referenced old_names that never existed in the DB.
    ]
