# Generated by Django 6.0 on 2026-04-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_comment_index_names"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                ALTER TABLE core_comment ENABLE ROW LEVEL SECURITY;
                ALTER TABLE core_comment FORCE ROW LEVEL SECURITY;

                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_policies
                    WHERE schemaname = 'public'
                      AND tablename = 'core_comment'
                      AND policyname = 'core_comment_tenant_isolation'
                ) THEN
                    CREATE POLICY core_comment_tenant_isolation ON core_comment
                        FOR ALL
                        USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                        WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS core_comment_tenant_isolation ON core_comment;
            ALTER TABLE core_comment NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE core_comment DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
