# Generated by Django 6.0 on 2026-04-29 00:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        ("core", "0007_enable_rls_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "idempotency_key",
                    models.CharField(help_text="Caller-supplied Idempotency-Key header value", max_length=255),
                ),
                (
                    "request_method",
                    models.CharField(help_text="HTTP method for the original mutation request", max_length=10),
                ),
                (
                    "request_path",
                    models.CharField(help_text="Canonical request path used for idempotency scoping", max_length=255),
                ),
                (
                    "request_fingerprint",
                    models.CharField(help_text="SHA-256 fingerprint of the request payload", max_length=64),
                ),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Cached HTTP status for completed idempotent responses", null=True
                    ),
                ),
                (
                    "response_body",
                    models.JSONField(
                        blank=True, help_text="Cached JSON response payload for completed requests", null=True
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True, help_text="Lease expiration for in-flight requests using this key", null=True
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(fields=["tenant", "idempotency_key"], name="core_idempo_tenant__833410_idx"),
                    models.Index(fields=["tenant", "locked_until"], name="core_idempo_tenant__db8539_idx"),
                    models.Index(fields=["tenant", "-created_on"], name="core_idempo_tenant__58b7e7_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "idempotency_key"), name="core_idempotencykey_tenant_key_uniq"
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                ALTER TABLE core_idempotencykey ENABLE ROW LEVEL SECURITY;
                ALTER TABLE core_idempotencykey FORCE ROW LEVEL SECURITY;

                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_policies
                    WHERE schemaname = 'public'
                      AND tablename = 'core_idempotencykey'
                      AND policyname = 'core_idempotencykey_tenant_isolation'
                ) THEN
                    CREATE POLICY core_idempotencykey_tenant_isolation ON core_idempotencykey
                        FOR ALL
                        USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                        WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS core_idempotencykey_tenant_isolation ON core_idempotencykey;
            ALTER TABLE core_idempotencykey NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE core_idempotencykey DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
