# Generated by Django 6.0 on 2026-04-30 20:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_idempotencykey"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ETLImportBatch",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "run_key",
                    models.CharField(
                        db_index=True,
                        help_text="Deterministic batch key derived from tenant + manifest checksum + dry-run options.",
                        max_length=64,
                    ),
                ),
                ("mode", models.CharField(choices=[("dry_run", "Dry Run")], default="dry_run", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("source_manifest", models.JSONField(blank=True, default=dict)),
                ("manifest_checksum", models.CharField(blank=True, default="", max_length=64)),
                ("command_options", models.JSONField(blank=True, default=dict)),
                ("resume_cursor", models.JSONField(blank=True, default=dict)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("failure_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_checkpoint_at", models.DateTimeField(blank=True, null=True)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("processed_rows", models.PositiveIntegerField(default=0)),
                ("would_create_count", models.PositiveIntegerField(default=0)),
                ("would_update_count", models.PositiveIntegerField(default=0)),
                ("would_skip_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="ETLImportRowJournal",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("entity", models.CharField(db_index=True, max_length=100)),
                ("source_path", models.CharField(max_length=500)),
                ("source_sheet", models.CharField(blank=True, default="", max_length=255)),
                ("source_row_number", models.PositiveIntegerField()),
                ("source_identifier", models.CharField(blank=True, default="", max_length=255)),
                ("normalized_lookup_key", models.CharField(blank=True, default="", max_length=255)),
                ("row_fingerprint", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                (
                    "planned_action",
                    models.CharField(
                        choices=[
                            ("would_create", "Would Create"),
                            ("would_update", "Would Update"),
                            ("would_skip", "Would Skip"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("target_model", models.CharField(blank=True, default="", max_length=255)),
                ("target_identifier", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("planned", "Planned"), ("error", "Error")], default="planned", max_length=20
                    ),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=100)),
                ("error_message", models.TextField(blank=True, default="")),
                ("side_effects_suppressed", models.JSONField(blank=True, default=list)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("normalized_payload", models.JSONField(blank=True, default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("processed_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Owning ETL dry-run batch.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="row_journals",
                        to="core.etlimportbatch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["batch_id", "entity", "source_row_number"],
            },
        ),
        migrations.AddIndex(
            model_name="etlimportbatch",
            index=models.Index(fields=["tenant", "status", "-created_on"], name="core_etlb_tenant_status_idx"),
        ),
        migrations.AddIndex(
            model_name="etlimportbatch",
            index=models.Index(fields=["tenant", "manifest_checksum"], name="core_etlb_manifest_idx"),
        ),
        migrations.AddConstraint(
            model_name="etlimportbatch",
            constraint=models.UniqueConstraint(fields=("tenant", "run_key"), name="core_etlb_tenant_run_uniq"),
        ),
        migrations.AddIndex(
            model_name="etlimportrowjournal",
            index=models.Index(fields=["tenant", "batch", "planned_action"], name="core_etlr_batch_action_idx"),
        ),
        migrations.AddIndex(
            model_name="etlimportrowjournal",
            index=models.Index(fields=["tenant", "entity", "row_fingerprint"], name="core_etlr_entity_fp_idx"),
        ),
        migrations.AddConstraint(
            model_name="etlimportrowjournal",
            constraint=models.UniqueConstraint(
                fields=("batch", "entity", "source_path", "source_sheet", "source_row_number"),
                name="core_etlr_batch_source_uniq",
            ),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE core_etlimportbatch ENABLE ROW LEVEL SECURITY;
            ALTER TABLE core_etlimportbatch FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS etlimportbatch_tenant_isolation ON core_etlimportbatch;
            CREATE POLICY etlimportbatch_tenant_isolation ON core_etlimportbatch
                USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

            ALTER TABLE core_etlimportrowjournal ENABLE ROW LEVEL SECURITY;
            ALTER TABLE core_etlimportrowjournal FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS etlimportrowjournal_tenant_isolation ON core_etlimportrowjournal;
            CREATE POLICY etlimportrowjournal_tenant_isolation ON core_etlimportrowjournal
                USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS etlimportrowjournal_tenant_isolation ON core_etlimportrowjournal;
            ALTER TABLE core_etlimportrowjournal NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE core_etlimportrowjournal DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS etlimportbatch_tenant_isolation ON core_etlimportbatch;
            ALTER TABLE core_etlimportbatch NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE core_etlimportbatch DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
