# Generated by Django 6.0 on 2026-04-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_etl_dry_run_journal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etlimportbatch",
            name="mode",
            field=models.CharField(
                choices=[
                    ("dry_run", "Dry Run"),
                    ("apply_master_data", "Apply Master Data"),
                    ("apply_transactions", "Apply Transactions"),
                ],
                default="dry_run",
                max_length=20,
            ),
        ),
    ]
