# Generated by Django 6.0 on 2026-05-01 02:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_etl_apply_modes"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveBatch",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("run_key", models.CharField(db_index=True, max_length=64)),
                (
                    "mode",
                    models.CharField(
                        choices=[("dry_run", "Dry Run"), ("execute", "Execute")], default="dry_run", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("cutoff_date", models.DateField(db_index=True)),
                ("command_options", models.JSONField(blank=True, default=dict)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("failure_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("requested_by_email", models.EmailField(blank=True, default="", max_length=254)),
                ("approved_by_email", models.EmailField(blank=True, default="", max_length=254)),
                ("dry_run_record_count", models.PositiveIntegerField(default=0)),
                ("archived_record_count", models.PositiveIntegerField(default=0)),
                ("legal_hold_skip_count", models.PositiveIntegerField(default=0)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archive_batches_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archive_batches_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="ArchiveLegalHold",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("scope_model", models.CharField(db_index=True, max_length=255)),
                ("scope_selector", models.JSONField(blank=True, default=dict)),
                ("reason_code", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True, default="")),
                ("placed_by_email", models.EmailField(blank=True, default="", max_length=254)),
                ("placed_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("released_by_email", models.EmailField(blank=True, default="", max_length=254)),
                ("released_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "placed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archive_legal_holds_placed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archive_legal_holds_released",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-placed_at", "-created_on"],
            },
        ),
        migrations.CreateModel(
            name="ArchiveRecordSnapshot",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("model_label", models.CharField(db_index=True, max_length=255)),
                ("archive_class", models.CharField(db_index=True, max_length=100)),
                ("object_pk", models.CharField(db_index=True, max_length=255)),
                ("parent_model_label", models.CharField(blank=True, default="", max_length=255)),
                ("parent_object_pk", models.CharField(blank=True, default="", max_length=255)),
                ("retention_basis_date", models.DateField(blank=True, null=True)),
                ("snapshot_payload", models.JSONField(blank=True, default=dict)),
                ("payload_checksum", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Owning archive batch.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="core.archivebatch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["batch_id", "model_label", "object_pk"],
            },
        ),
        migrations.AddIndex(
            model_name="archivebatch",
            index=models.Index(fields=["tenant", "status", "-created_on"], name="core_archbatch_status_idx"),
        ),
        migrations.AddIndex(
            model_name="archivebatch",
            index=models.Index(fields=["tenant", "cutoff_date"], name="core_archbatch_cutoff_idx"),
        ),
        migrations.AddConstraint(
            model_name="archivebatch",
            constraint=models.UniqueConstraint(fields=("tenant", "run_key"), name="core_archbatch_tenant_run_uniq"),
        ),
        migrations.AddIndex(
            model_name="archivelegalhold",
            index=models.Index(fields=["tenant", "scope_model", "released_at"], name="core_archhold_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="archivelegalhold",
            index=models.Index(fields=["tenant", "-placed_at"], name="core_archhold_tenant_idx"),
        ),
        migrations.AddIndex(
            model_name="archiverecordsnapshot",
            index=models.Index(fields=["tenant", "batch", "model_label"], name="core_archsnap_batch_model_idx"),
        ),
        migrations.AddIndex(
            model_name="archiverecordsnapshot",
            index=models.Index(fields=["tenant", "retention_basis_date"], name="core_archsnap_retention_idx"),
        ),
        migrations.AddConstraint(
            model_name="archiverecordsnapshot",
            constraint=models.UniqueConstraint(
                fields=("batch", "model_label", "object_pk"), name="core_archsnap_batch_model_obj_uniq"
            ),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE core_archivebatch ENABLE ROW LEVEL SECURITY;
            ALTER TABLE core_archivebatch FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS core_archivebatch_tenant_isolation ON core_archivebatch;
            CREATE POLICY core_archivebatch_tenant_isolation ON core_archivebatch
                USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

            ALTER TABLE core_archivelegalhold ENABLE ROW LEVEL SECURITY;
            ALTER TABLE core_archivelegalhold FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS core_archivelegalhold_tenant_isolation ON core_archivelegalhold;
            CREATE POLICY core_archivelegalhold_tenant_isolation ON core_archivelegalhold
                USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

            ALTER TABLE core_archiverecordsnapshot ENABLE ROW LEVEL SECURITY;
            ALTER TABLE core_archiverecordsnapshot FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS core_archiverecordsnapshot_tenant_isolation ON core_archiverecordsnapshot;
            CREATE POLICY core_archiverecordsnapshot_tenant_isolation ON core_archiverecordsnapshot
                USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS core_archiverecordsnapshot_tenant_isolation ON core_archiverecordsnapshot;
            ALTER TABLE core_archiverecordsnapshot NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE core_archiverecordsnapshot DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS core_archivelegalhold_tenant_isolation ON core_archivelegalhold;
            ALTER TABLE core_archivelegalhold NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE core_archivelegalhold DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS core_archivebatch_tenant_isolation ON core_archivebatch;
            ALTER TABLE core_archivebatch NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE core_archivebatch DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
