# Generated by Django 6.0 on 2026-05-06 05:37

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_archive_historical_records"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalDocumentReference",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("invoice_summary", "Invoice Summary"),
                            ("invoice_pdf", "Invoice PDF"),
                            ("sales_order_status", "Sales Order Status"),
                            ("purchase_order_status", "Purchase Order Status"),
                            ("fulfillment_tracking", "Fulfillment Tracking"),
                            ("fulfillment_bol", "Fulfillment BOL"),
                            ("fulfillment_pod", "Fulfillment POD"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("source_record_type", models.CharField(db_index=True, max_length=100)),
                ("source_record_id", models.CharField(db_index=True, max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("byte_size", models.PositiveBigIntegerField(default=0)),
                ("checksum", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                (
                    "storage_backend",
                    models.CharField(
                        blank=True,
                        default="default",
                        help_text="Internal storage backend identifier. Do not expose in portal serializers.",
                        max_length=100,
                    ),
                ),
                (
                    "storage_key",
                    models.CharField(
                        help_text="Internal-only storage locator. Never expose to portal clients.", max_length=500
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("published_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_document_references_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_on"],
            },
        ),
        migrations.CreateModel(
            name="PortalGrant",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("subject_email", models.EmailField(db_index=True, max_length=254)),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA-256 digest of the opaque grant secret. Raw tokens are never stored.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("consumed", "Consumed"), ("revoked", "Revoked")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "resource_scope",
                    models.JSONField(
                        blank=True, default=dict, help_text="Tenant-explicit record scope keyed by entity type."
                    ),
                ),
                (
                    "document_sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Allowed guest-safe document source categories for this grant.",
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("revoked_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("revoked_reason", models.CharField(blank=True, default="", max_length=255)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("max_uses", models.PositiveIntegerField(default=1)),
                ("use_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_grants_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_grants_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="PortalGrantDocumentAccess",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("linked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "document_reference",
                    models.ForeignKey(
                        help_text="Curated portal-safe document registry entry.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grant_links",
                        to="core.portaldocumentreference",
                    ),
                ),
                (
                    "grant",
                    models.ForeignKey(
                        help_text="Portal grant that may expose this curated document.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_links",
                        to="core.portalgrant",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_grant_document_links_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["grant_id", "sort_order", "created_on"],
            },
        ),
        migrations.AddIndex(
            model_name="portaldocumentreference",
            index=models.Index(fields=["tenant", "source_kind", "published_at"], name="core_pdocref_source_idx"),
        ),
        migrations.AddIndex(
            model_name="portaldocumentreference",
            index=models.Index(
                fields=["tenant", "source_record_type", "source_record_id"], name="core_pdocref_record_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portaldocumentreference",
            index=models.Index(fields=["tenant", "is_active", "published_at"], name="core_pdocref_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="portaldocumentreference",
            constraint=models.UniqueConstraint(
                fields=("tenant", "storage_backend", "storage_key"), name="core_pdocref_tenant_key_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="portalgrant",
            index=models.Index(fields=["tenant", "status", "expires_at"], name="core_pgrant_status_idx"),
        ),
        migrations.AddIndex(
            model_name="portalgrant",
            index=models.Index(fields=["tenant", "subject_email"], name="core_pgrant_subject_idx"),
        ),
        migrations.AddIndex(
            model_name="portalgrant",
            index=models.Index(fields=["tenant", "revoked_at"], name="core_pgrant_revoke_idx"),
        ),
        migrations.AddConstraint(
            model_name="portalgrant",
            constraint=models.CheckConstraint(condition=models.Q(max_uses__gte=1), name="core_pgrant_max_uses_gte_1"),
        ),
        migrations.AddConstraint(
            model_name="portalgrant",
            constraint=models.UniqueConstraint(fields=("tenant", "token_hash"), name="core_pgrant_tenant_hash_uniq"),
        ),
        migrations.AddIndex(
            model_name="portalgrantdocumentaccess",
            index=models.Index(fields=["tenant", "grant", "sort_order"], name="core_pgrantdoc_grant_idx"),
        ),
        migrations.AddIndex(
            model_name="portalgrantdocumentaccess",
            index=models.Index(fields=["tenant", "document_reference"], name="core_pgrantdoc_doc_idx"),
        ),
        migrations.AddConstraint(
            model_name="portalgrantdocumentaccess",
            constraint=models.UniqueConstraint(
                fields=("tenant", "grant", "document_reference"), name="core_pgrantdoc_tenant_link_uniq"
            ),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE core_portaldocumentreference ENABLE ROW LEVEL SECURITY;
            ALTER TABLE core_portaldocumentreference FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS core_portaldocumentreference_tenant_isolation ON core_portaldocumentreference;
            CREATE POLICY core_portaldocumentreference_tenant_isolation ON core_portaldocumentreference
                USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

            ALTER TABLE core_portalgrant ENABLE ROW LEVEL SECURITY;
            ALTER TABLE core_portalgrant FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS core_portalgrant_tenant_isolation ON core_portalgrant;
            CREATE POLICY core_portalgrant_tenant_isolation ON core_portalgrant
                USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

            ALTER TABLE core_portalgrantdocumentaccess ENABLE ROW LEVEL SECURITY;
            ALTER TABLE core_portalgrantdocumentaccess FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS core_portalgrantdocumentaccess_tenant_isolation ON core_portalgrantdocumentaccess;
            CREATE POLICY core_portalgrantdocumentaccess_tenant_isolation ON core_portalgrantdocumentaccess
                USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS core_portalgrantdocumentaccess_tenant_isolation ON core_portalgrantdocumentaccess;
            ALTER TABLE core_portalgrantdocumentaccess NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE core_portalgrantdocumentaccess DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS core_portalgrant_tenant_isolation ON core_portalgrant;
            ALTER TABLE core_portalgrant NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE core_portalgrant DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS core_portaldocumentreference_tenant_isolation ON core_portaldocumentreference;
            ALTER TABLE core_portaldocumentreference NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE core_portaldocumentreference DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
