# Generated by Django 6.0 on 2026-05-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_portaldocumentreference_portalgrant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantauditevent",
            name="action",
            field=models.CharField(
                choices=[("CREATE", "Created"), ("UPDATE", "Updated"), ("DELETE", "Deleted"), ("ACCESS", "Accessed")],
                max_length=10,
            ),
        ),
    ]
