# Generated by Django 6.0 on 2026-05-07 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_tenantauditevent_action"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeEventLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(help_text="Unique UUID for this event instance.", max_length=36, unique=True),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True, help_text="Canonical event type (e.g., 'supplier_po.approved').", max_length=50
                    ),
                ),
                (
                    "trade_session_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="FK to TradeSession (stored as int for flexibility).",
                        null=True,
                    ),
                ),
                (
                    "trade_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Human-readable trade ID (TRD-YYYY-NNNNN).",
                        max_length=50,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(blank=True, default="", help_text="Source entity class name.", max_length=100),
                ),
                ("entity_id", models.CharField(blank=True, default="", help_text="Source entity PK.", max_length=36)),
                (
                    "actor_user_id",
                    models.CharField(blank=True, default="", help_text="User who triggered the event.", max_length=36),
                ),
                ("payload", models.JSONField(blank=True, default=dict, help_text="Full serialized event payload.")),
                (
                    "route_decision",
                    models.CharField(blank=True, default="", help_text="FULFILL or BROKER route.", max_length=20),
                ),
                (
                    "processed",
                    models.BooleanField(
                        default=False, help_text="Whether this event has been consumed by saga handlers."
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, help_text="When this event was processed.", null=True),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade Event Log",
                "verbose_name_plural": "Trade Event Logs",
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(fields=["tenant", "event_type"], name="core_tradee_tenant__c39c69_idx"),
                    models.Index(fields=["tenant", "trade_session_id"], name="core_tradee_tenant__cf4d45_idx"),
                    models.Index(fields=["tenant", "trade_id"], name="core_tradee_tenant__30d0af_idx"),
                    models.Index(fields=["tenant", "processed", "-created_on"], name="core_tradee_tenant__b16134_idx"),
                ],
            },
        ),
        # RLS policy for tenant isolation
        migrations.RunSQL(
            sql="""
            ALTER TABLE core_tradeeventlog ENABLE ROW LEVEL SECURITY;
            CREATE POLICY tradeeventlog_tenant_isolation ON core_tradeeventlog
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tradeeventlog_tenant_isolation ON core_tradeeventlog;
            ALTER TABLE core_tradeeventlog DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
