# Generated by Django 6.0 on 2026-05-07 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_trade_event_log"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeExceptionQueue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "trade_session_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="FK to TradeSession (stored as int for flexibility).",
                        null=True,
                    ),
                ),
                (
                    "trade_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Human-readable trade ID (TRD-YYYY-NNNNN).",
                        max_length=50,
                    ),
                ),
                (
                    "failed_step",
                    models.CharField(
                        db_index=True,
                        help_text="Step identifier that failed (e.g., 'sales_order.pdf_generation').",
                        max_length=100,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        db_index=True,
                        default="UNKNOWN",
                        help_text="Classification code for the failure type.",
                        max_length=50,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", help_text="Human-readable error description."),
                ),
                (
                    "stack_trace",
                    models.TextField(blank=True, default="", help_text="Python stack trace (truncated to 2000 chars)."),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Entity being operated on when failure occurred.",
                        max_length=100,
                    ),
                ),
                ("entity_id", models.CharField(blank=True, default="", help_text="Entity PK.", max_length=36)),
                (
                    "source_event_id",
                    models.CharField(
                        blank=True, default="", help_text="Domain event that triggered the failed step.", max_length=36
                    ),
                ),
                (
                    "context_payload",
                    models.JSONField(blank=True, default=dict, help_text="Full context for debugging and retry."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("retrying", "Retrying"),
                            ("resolved", "Resolved"),
                            ("exhausted", "Max Retries Exhausted"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.PositiveSmallIntegerField(default=0, help_text="Number of retry attempts.")),
                ("last_retry_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.CharField(
                        blank=True, default="", help_text="User ID who resolved this exception.", max_length=36
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_notes",
                    models.TextField(blank=True, default="", help_text="Operator notes on how the issue was resolved."),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade Exception Queue",
                "verbose_name_plural": "Trade Exception Queue",
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(fields=["tenant", "status", "-created_on"], name="core_tradee_tenant__e13ae9_idx"),
                    models.Index(fields=["tenant", "trade_session_id"], name="core_tradee_tenant__30c600_idx"),
                    models.Index(fields=["tenant", "reason_code"], name="core_tradee_tenant__49eaae_idx"),
                ],
            },
        ),
        # RLS policy for tenant isolation
        migrations.RunSQL(
            sql="""
            ALTER TABLE core_tradeexceptionqueue ENABLE ROW LEVEL SECURITY;
            CREATE POLICY tradeexceptionqueue_tenant_isolation ON core_tradeexceptionqueue
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tradeexceptionqueue_tenant_isolation ON core_tradeexceptionqueue;
            ALTER TABLE core_tradeexceptionqueue DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
