# Generated by Django 6.0 on 2026-05-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_trade_exception_queue"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeErrorLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[("error", "Error"), ("warn", "Warning"), ("fatal", "Fatal")],
                        db_index=True,
                        default="error",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("frontend", "Frontend"), ("backend", "Backend"), ("api", "API")],
                        db_index=True,
                        default="frontend",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(help_text="Error message (truncated to 2000 chars).")),
                ("stack_trace", models.TextField(blank=True, default="", help_text="Stack trace if available.")),
                (
                    "component",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Component/module where error occurred.",
                        max_length=255,
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, default="", help_text="Page URL when error occurred.", max_length=2048),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", help_text="Browser user agent string.", max_length=512),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant context (if available when error occurred).",
                        null=True,
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True, help_text="User ID (if authenticated when error occurred).", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional context (API status, request method, etc.)."
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="SHA-256 hash for deduplication.",
                        max_length=64,
                    ),
                ),
                (
                    "occurrence_count",
                    models.PositiveIntegerField(default=1, help_text="Number of times this exact error has been seen."),
                ),
            ],
            options={
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(fields=["-created_on"], name="core_runtim_created_15d0ea_idx"),
                    models.Index(fields=["source", "level", "-created_on"], name="core_runtim_source_c9123d_idx"),
                    models.Index(fields=["fingerprint"], name="core_runtim_fingerp_b920c4_idx"),
                ],
            },
        ),
    ]
