# Generated by Django 6.0 on 2025-12-06 20:20

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("products", "0001_initial"),
        ("sales_orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "invoice_number",
                    models.CharField(help_text="Unique invoice number", max_length=100, unique=True),
                ),
                (
                    "date_time_stamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when invoice was created",
                    ),
                ),
                (
                    "pick_up_date",
                    models.DateField(blank=True, help_text="Pick up date", null=True),
                ),
                (
                    "delivery_date",
                    models.DateField(blank=True, help_text="Delivery date", null=True),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, help_text="Payment due date", null=True),
                ),
                (
                    "our_sales_order_num",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Our sales order number",
                        max_length=100,
                    ),
                ),
                (
                    "delivery_po_num",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Delivery PO number",
                        max_length=100,
                    ),
                ),
                (
                    "accounting_payable_contact_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Accounting payable contact name",
                        max_length=255,
                    ),
                ),
                (
                    "accounting_payable_contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Accounting payable contact phone",
                        max_length=20,
                    ),
                ),
                (
                    "accounting_payable_contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Accounting payable contact email",
                        max_length=254,
                    ),
                ),
                (
                    "type_of_protein",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Type of protein",
                        max_length=100,
                    ),
                ),
                (
                    "description_of_product_item",
                    models.TextField(blank=True, default="", help_text="Description of product item"),
                ),
                (
                    "quantity",
                    models.IntegerField(blank=True, help_text="Quantity of items", null=True),
                ),
                (
                    "total_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total weight",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("LBS", "LBS"), ("KG", "KG")],
                        default="LBS",
                        help_text="Unit of weight (LBS or KG)",
                        max_length=10,
                    ),
                ),
                (
                    "edible_or_inedible",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Edible", "Edible"),
                            ("Inedible", "Inedible"),
                            ("Edible & Inedible", "Edible & Inedible"),
                        ],
                        default="",
                        help_text="Edible or inedible product",
                        max_length=50,
                    ),
                ),
                (
                    "tested_product",
                    models.BooleanField(default=False, help_text="Is this a tested product?"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price per unit",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total invoice amount",
                        max_digits=10,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tax amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        help_text="Current status of the invoice",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", help_text="Additional notes"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer for this invoice",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product being invoiced",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related sales order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales_orders.salesorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-date_time_stamp", "-created_on"],
            },
        ),
    ]
