# Generated by Django 6.0 on 2026-01-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_state_sync_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Wire", "Wire"),
                    ("ACH", "ACH"),
                    ("Check", "Check"),
                    ("Credit Card", "Credit Card"),
                ],
                default="",
                help_text="Payment terms (e.g., Wire, ACH, Check)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="type_of_protein",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beef", "Beef"),
                    ("Chicken", "Chicken"),
                    ("Pork", "Pork"),
                    ("Lamb", "Lamb"),
                    ("Turkey", "Turkey"),
                    ("Fish", "Fish"),
                    ("Horse", "Horse"),
                    ("Other", "Other"),
                ],
                default="",
                help_text="Type of protein",
                max_length=100,
            ),
        ),
    ]
