# Generated by Django 6.0 on 2026-01-08 13:14

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_customer_industry_array_and_more"),
        ("invoices", "0004_invoice_payment_terms_alter_invoice_type_of_protein"),
        ("products", "0004_state_sync_tenant"),
        (
            "purchase_orders",
            "0007_carrierpurchaseorder_carrier_release_format_and_more",
        ),
        ("sales_orders", "0006_salesorder_carrier_release_format_and_more"),
        ("suppliers", "0005_supplier_departments_array"),
        ("tenants", "0006_metadata_lockdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "claim_number",
                    models.CharField(
                        help_text="Unique claim number/reference",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "claim_type",
                    models.CharField(
                        choices=[
                            ("payable", "Payable (Supplier Claim)"),
                            ("receivable", "Receivable (Customer Claim)"),
                        ],
                        help_text="Is this a payable (supplier) or receivable (customer) claim?",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("settled", "Settled/Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the claim",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Reason for the claim (e.g., damaged goods, incorrect quantity, quality issue)"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of the claim",
                    ),
                ),
                (
                    "claimed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount being claimed",
                        max_digits=10,
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Approved amount (may differ from claimed)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "settled_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual amount paid/settled",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("claim_date", models.DateField(help_text="Date claim was filed")),
                (
                    "resolution_date",
                    models.DateField(
                        blank=True,
                        help_text="Date claim was resolved/settled",
                        null=True,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notes on how claim was resolved",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim",
                "verbose_name_plural": "Claims",
                "ordering": ["-claim_date", "-created_on"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["tenant", "invoice_number"],
                name="invoices_in_tenant__625d18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["tenant", "status"], name="invoices_in_tenant__0fd538_idx"),
        ),
        migrations.AddField(
            model_name="claim",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="User assigned to handle this claim",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who filed this claim",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Related customer (for receivable claims)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claims",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="Related invoice",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claims",
                to="invoices.invoice",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Related purchase order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claims",
                to="purchase_orders.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Related sales order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claims",
                to="sales_orders.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Related supplier (for payable claims)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claims",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this claim belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["tenant", "claim_type", "status"],
                name="invoices_cl_tenant__4df233_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["tenant", "claim_number"], name="invoices_cl_tenant__860277_idx"),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["tenant", "-claim_date"], name="invoices_cl_tenant__412862_idx"),
        ),
    ]
