# Generated by Django 6.0 on 2026-01-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0005_claim_invoice_invoices_in_tenant__625d18_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="outstanding_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Outstanding amount (calculated: total - paid)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("partial", "Partial"),
                    ("paid", "Paid"),
                ],
                default="unpaid",
                help_text="Payment status of the invoice",
                max_length=20,
            ),
        ),
    ]
