# Generated by Django 6.0 on 2026-01-08 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0006_invoice_outstanding_amount_invoice_payment_status"),
        ("purchase_orders", "0008_purchaseorder_outstanding_amount_and_more"),
        ("sales_orders", "0007_salesorder_outstanding_amount_and_more"),
        ("tenants", "0006_metadata_lockdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, help_text="Payment amount", max_digits=10),
                ),
                (
                    "payment_date",
                    models.DateField(help_text="Date payment was made/received"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wire", "Wire Transfer"),
                            ("ach", "ACH"),
                            ("check", "Check"),
                            ("credit_card", "Credit Card"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        default="check",
                        help_text="Method of payment",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Check number, wire confirmation, or transaction ID",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes about this payment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who recorded this payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Invoice this payment is for (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Purchase order this payment is for (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="purchase_orders.purchaseorder",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sales order this payment is for (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="sales_orders.salesorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this payment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "ordering": ["-payment_date", "-created_on"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "payment_date"],
                        name="invoices_pa_tenant__318b98_idx",
                    ),
                    models.Index(
                        fields=["tenant", "purchase_order"],
                        name="invoices_pa_tenant__dc90c5_idx",
                    ),
                    models.Index(
                        fields=["tenant", "sales_order"],
                        name="invoices_pa_tenant__83d300_idx",
                    ),
                    models.Index(
                        fields=["tenant", "invoice"],
                        name="invoices_pa_tenant__4a2d71_idx",
                    ),
                ],
            },
        ),
    ]
