# Generated by Django 6.0 on 2026-01-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_customer_industry_array_and_more"),
        ("invoices", "0007_paymenttransaction"),
        ("products", "0004_state_sync_tenant"),
        ("sales_orders", "0007_salesorder_outstanding_amount_and_more"),
        ("tenants", "0006_metadata_lockdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(help_text="Invoice number (unique per tenant)", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("tenant", "invoice_number"), name="unique_tenant_invoice_number"
            ),
        ),
    ]
