# Generated by Django 6.0 on 2026-02-13 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0009_alter_product_fk_to_system"),
        ("system", "0007_add_container_versioning_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Product being invoiced",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system.product",
            ),
        ),
    ]
