# Generated by Django 6.0 on 2026-03-23
# Squashed replacement for invoices/0009 to ensure FK removal happens before products deletes legacy Product.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("invoices", "0009_alter_product_fk_to_system"),
    ]

    # Ensure the legacy FK field is removed while products.Product still exists in migration state.
    run_before = [
        ("products", "0008_masterproduct_delete_product_and_more"),
    ]

    dependencies = [
        ("invoices", "0008_alter_invoice_invoice_number_and_more"),
        ("system", "0002_add_product_model"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE invoices_invoice DROP COLUMN IF EXISTS product_id;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(model_name="invoice", name="product"),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="system.product",
            ),
        ),
    ]
