# Generated by Django 6.0 on 2026-03-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0011_refactor_invoices_to_tenantaware"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="type_of_protein",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beef", "Beef"),
                    ("Chicken", "Chicken"),
                    ("Duck", "Duck"),
                    ("Pork", "Pork"),
                    ("Lamb", "Lamb"),
                    ("Turkey", "Turkey"),
                    ("Fish", "Fish"),
                    ("Horse", "Horse"),
                    ("Other", "Other"),
                ],
                default="",
                help_text="Type of protein",
                max_length=100,
            ),
        ),
    ]
