# Generated by Django 6.0 on 2026-03-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0012_alter_invoice_type_of_protein"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_subscription",
            field=models.BooleanField(
                default=False,
                help_text="True for platform subscription billing invoices; false for business/customer invoices.",
            ),
        ),
    ]
