# Generated by Django 6.0 on 2026-04-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0015_golden_schema_refactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("sent", "Sent"),
                    ("partial_paid", "Partially Paid"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                help_text="Current status of the invoice",
                max_length=20,
            ),
        ),
    ]
