# Generated by Django 6.0 on 2026-05-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0016_operational_readiness"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="fresh_or_frozen",
            field=models.CharField(
                blank=True, choices=[("Fresh", "Fresh"), ("Frozen", "Frozen")], default="", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="net_or_catch",
            field=models.CharField(blank=True, choices=[("Net", "Net"), ("Catch", "Catch")], default="", max_length=20),
        ),
        migrations.AddField(
            model_name="invoice",
            name="package_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Boxed wax lined", "Boxed wax lined"),
                    ("Boxed Poly", "Boxed Poly"),
                    ("Combos", "Combos"),
                    ("Nude Block", "Nude Block"),
                    ("Boxed COV", "Boxed COV"),
                    ("Boxed CO2", "Boxed CO2"),
                    ("Combo bins", "Combo bins"),
                    ("Totes", "Totes"),
                    ("Bags", "Bags"),
                    ("Bulk", "Bulk"),
                    ("Poly-Multiple", "Poly-Multiple"),
                    ("Nude", "Nude"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_net_weight",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="how_to_make_appointment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Email", "Email"),
                    ("Phone", "Phone"),
                    ("Website", "Website"),
                    ("FCFS", "FCFS"),
                    ("Fax", "Fax"),
                    ("First Come First Serve", "First Come First Serve"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="type_of_protein",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beef", "Beef"),
                    ("Chicken", "Chicken"),
                    ("Fowl", "Fowl"),
                    ("Turkey", "Turkey"),
                    ("Lamb", "Lamb"),
                    ("Veal", "Veal"),
                    ("Seafood", "Seafood"),
                    ("Venison", "Venison"),
                    ("Bison", "Bison"),
                    ("Duck", "Duck"),
                    ("Rabbit", "Rabbit"),
                    ("Goat", "Goat"),
                    ("Mutton", "Mutton"),
                    ("Pork", "Pork"),
                    ("Fish", "Fish"),
                    ("Horse", "Horse"),
                    ("Other", "Other"),
                ],
                default="",
                help_text="Type of protein",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="package_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Boxed wax lined", "Boxed wax lined"),
                    ("Boxed Poly", "Boxed Poly"),
                    ("Combos", "Combos"),
                    ("Nude Block", "Nude Block"),
                    ("Boxed COV", "Boxed COV"),
                    ("Boxed CO2", "Boxed CO2"),
                    ("Combo bins", "Combo bins"),
                    ("Totes", "Totes"),
                    ("Bags", "Bags"),
                    ("Bulk", "Bulk"),
                    ("Poly-Multiple", "Poly-Multiple"),
                    ("Nude", "Nude"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="protein_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beef", "Beef"),
                    ("Chicken", "Chicken"),
                    ("Fowl", "Fowl"),
                    ("Turkey", "Turkey"),
                    ("Lamb", "Lamb"),
                    ("Veal", "Veal"),
                    ("Seafood", "Seafood"),
                    ("Venison", "Venison"),
                    ("Bison", "Bison"),
                    ("Duck", "Duck"),
                    ("Rabbit", "Rabbit"),
                    ("Goat", "Goat"),
                    ("Mutton", "Mutton"),
                    ("Pork", "Pork"),
                    ("Fish", "Fish"),
                    ("Horse", "Horse"),
                    ("Other", "Other"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
