# Generated by Django 6.0 on 2026-01-23 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0006_metadata_lockdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlueprintVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the version",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        help_text="Version number (1, 2, 3, etc.)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        help_text="Version status",
                        max_length=20,
                    ),
                ),
                (
                    "schema_config",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of field definitions for dynamic schema",
                    ),
                ),
                (
                    "workflow_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="React Flow UI state (nodes, edges, positions)",
                    ),
                ),
                (
                    "logic_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Execution logic and mappings for workflow steps",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Blueprint Version",
                "verbose_name_plural": "Blueprint Versions",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="EntityBlueprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the blueprint",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier (e.g., 'customer', 'sales-order')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Customer Blueprint')",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "published_version",
                    models.OneToOneField(
                        blank=True,
                        help_text="Currently active version for this blueprint",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_for_blueprint",
                        to="system_config.blueprintversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Blueprint",
                "verbose_name_plural": "Entity Blueprints",
                "ordering": ["slug"],
            },
        ),
        migrations.AddField(
            model_name="blueprintversion",
            name="blueprint",
            field=models.ForeignKey(
                help_text="The blueprint this version belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="system_config.entityblueprint",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blueprintversion",
            unique_together={("blueprint", "version")},
        ),
        migrations.CreateModel(
            name="WorkflowRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "workflow_slug",
                    models.CharField(
                        help_text="Reference to EntityBlueprint.slug", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="IN_PROGRESS",
                        help_text="Current workflow execution status",
                        max_length=20,
                    ),
                ),
                (
                    "current_step_index",
                    models.IntegerField(
                        default=0, help_text="Index of current step in workflow"
                    ),
                ),
                (
                    "data_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Secure clipboard for workflow data (step inputs/outputs)",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Run",
                "verbose_name_plural": "Workflow Runs",
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "workflow_slug"],
                        name="system_conf_tenant__b2e826_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status"],
                        name="system_conf_tenant__ef5168_idx",
                    ),
                ],
            },
        ),
    ]
