# Generated by Django 6.0 on 2026-01-23 10:59

from django.db import migrations
import uuid


def bootstrap_system_tenant(apps, schema_editor):
    """
    Bootstrap the System Root tenant with zero-UUID.
    
    This tenant is used for global system administration and serves as
    the anchor for Global System Admins who can manage all tenants.
    """
    # Get models
    Tenant = apps.get_model('tenants', 'Tenant')
    Group = apps.get_model('auth', 'Group')
    
    # Create System Root tenant with zero-UUID
    system_tenant_id = uuid.UUID('00000000-0000-0000-0000-000000000000')
    system_tenant, created = Tenant.objects.get_or_create(
        id=system_tenant_id,
        defaults={
            'name': 'System Root',
            'slug': 'system',
            'is_active': True,
        }
    )
    
    if created:
        print(f"✅ Created System Root tenant: {system_tenant.id}")
    else:
        print(f"ℹ️  System Root tenant already exists: {system_tenant.id}")
    
    # Create Global System Admins group
    admin_group, created = Group.objects.get_or_create(
        name='Global System Admins'
    )
    
    if created:
        print(f"✅ Created Global System Admins group")
    else:
        print(f"ℹ️  Global System Admins group already exists")


def reverse_bootstrap(apps, schema_editor):
    """
    Reverse the bootstrap operation.
    
    Note: This will NOT delete the System Root tenant or group,
    as they may have associated data. Manual cleanup required if needed.
    """
    print("⚠️  Reverse migration: System Root tenant and Global System Admins group remain.")
    print("   Manual cleanup required if removal is needed.")


class Migration(migrations.Migration):

    dependencies = [
        ("system_config", "0001_initial"),
        ("tenants", "0006_metadata_lockdown"),  # Ensure tenants app is migrated
        ("auth", "__latest__"),  # Ensure auth app is available
    ]

    operations = [
        migrations.RunPython(
            bootstrap_system_tenant,
            reverse_code=reverse_bootstrap,
        ),
    ]
