# Generated by Django 6.0 on 2026-01-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Idempotent index creation for tenant-related fields.

    Uses SeparateDatabaseAndState with IF NOT EXISTS to safely handle
    environments where indexes may already exist from earlier migrations.
    """

    dependencies = [
        ("carriers", "0003_add_logistics_indexes"),
        ("contacts", "0002_contact_tenant_and_more"),
        ("plants", "0004_metadata_lockdown"),
        ("products", "0004_state_sync_tenant"),
        ("purchase_orders", "0004_state_sync_tenant"),
        ("sales_orders", "0004_state_sync_tenant"),
        (
            "suppliers",
            "0003_rename_suppliers_s_tenant__idx_suppliers_s_tenant__566edc_idx",
        ),
        ("tenants", "0006_metadata_lockdown"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="carrierpurchaseorder",
                    index=models.Index(
                        fields=["tenant", "our_carrier_po_num"],
                        name="purchase_or_tenant__6ab6fd_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="coldstorageentry",
                    index=models.Index(
                        fields=["tenant", "date_time_stamp_created"],
                        name="purchase_or_tenant__d5379c_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="purchaseorder",
                    index=models.Index(
                        fields=["tenant", "order_number"],
                        name="purchase_or_tenant__e12583_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="purchaseorder",
                    index=models.Index(
                        fields=["tenant", "order_date"],
                        name="purchase_or_tenant__e60062_idx",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE INDEX IF NOT EXISTS purchase_or_tenant__6ab6fd_idx
                        ON purchase_orders_carrierpurchaseorder (tenant_id, our_carrier_po_num);
                    """,
                    reverse_sql="DROP INDEX IF EXISTS purchase_or_tenant__6ab6fd_idx;",
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE INDEX IF NOT EXISTS purchase_or_tenant__d5379c_idx
                        ON purchase_orders_coldstorageentry (tenant_id, date_time_stamp_created);
                    """,
                    reverse_sql="DROP INDEX IF EXISTS purchase_or_tenant__d5379c_idx;",
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE INDEX IF NOT EXISTS purchase_or_tenant__e12583_idx
                        ON purchase_orders_purchaseorder (tenant_id, order_number);
                    """,
                    reverse_sql="DROP INDEX IF EXISTS purchase_or_tenant__e12583_idx;",
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE INDEX IF NOT EXISTS purchase_or_tenant__e60062_idx
                        ON purchase_orders_purchaseorder (tenant_id, order_date);
                    """,
                    reverse_sql="DROP INDEX IF EXISTS purchase_or_tenant__e60062_idx;",
                ),
            ],
        ),
    ]
