# Generated by Django 6.0 on 2026-01-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_orders", "0005_metadata_lockdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="credit_limit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Wire 1 day prior", "Wire 1 day prior"),
                    ("Net 7", "Net 7"),
                    ("Net 15", "Net 15"),
                    ("Net 30", "Net 30"),
                    ("Net 45", "Net 45"),
                    ("Net 60", "Net 60"),
                ],
                default="",
                help_text="Credit limit/terms",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="edible_or_inedible",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Edible", "Edible"),
                    ("Inedible", "Inedible"),
                    ("Edible & Inedible", "Edible & Inedible"),
                ],
                default="",
                help_text="Edible or inedible product",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="fresh_or_frozen",
            field=models.CharField(
                blank=True,
                choices=[("Fresh", "Fresh"), ("Frozen", "Frozen")],
                default="",
                help_text="Product state (Fresh or Frozen)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="item_description",
            field=models.TextField(blank=True, default="", help_text="Detailed item description"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="logistics_scenario",
            field=models.CharField(
                choices=[
                    ("customer_pickup", "Customer Pickup"),
                    ("supplier_delivery", "Supplier Delivery"),
                    ("we_pickup", "We Pickup (Our Logistics)"),
                ],
                default="supplier_delivery",
                help_text="Logistics scenario: Customer Pickup, Supplier Delivery, or We Pickup",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="net_or_catch",
            field=models.CharField(
                blank=True,
                choices=[("Net", "Net"), ("Catch", "Catch")],
                default="",
                help_text="Weight type (Net or Catch)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="package_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Boxed wax lined", "Boxed wax lined"),
                    ("Boxed CO2", "Boxed CO2"),
                    ("Combo bins", "Combo bins"),
                    ("Totes", "Totes"),
                    ("Bags", "Bags"),
                    ("Bulk", "Bulk"),
                    ("Poly-Multiple", "Poly-Multiple"),
                    ("Nude", "Nude"),
                ],
                default="",
                help_text="Package type (Combo, Box, Bag, etc.)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="payment_terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Wire", "Wire"),
                    ("ACH", "ACH"),
                    ("Check", "Check"),
                    ("Credit Card", "Credit Card"),
                ],
                default="",
                help_text="Payment terms (Wire, ACH, Check, etc.)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="price_per_unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price per unit/pound",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="special_instructions",
            field=models.TextField(blank=True, default="", help_text="Special instructions or notes"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier_contact_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Auto-populated from Supplier - Contact email",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier_contact_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-populated from Supplier - Contact person name",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier_contact_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-populated from Supplier - Contact phone",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier_corporate_address",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Auto-populated from Supplier - Corporate address",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="type_of_protein",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beef", "Beef"),
                    ("Chicken", "Chicken"),
                    ("Pork", "Pork"),
                    ("Lamb", "Lamb"),
                    ("Turkey", "Turkey"),
                    ("Fish", "Fish"),
                    ("Horse", "Horse"),
                    ("Other", "Other"),
                ],
                default="",
                help_text="Type of protein (Beef, Pork, Chicken, etc.)",
                max_length=50,
            ),
        ),
    ]
