# Generated by Django 6.0 on 2026-01-07 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_enable_rls_locations"),
        ("purchase_orders", "0006_add_logistics_scenario_and_41_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrierpurchaseorder",
            name="carrier_release_format",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Supplier Confirmation Order Number",
                        "Supplier Confirmation Order Number",
                    ),
                    ("Carrier Release Number", "Carrier Release Number"),
                    ("Both", "Both"),
                ],
                default="",
                help_text="Carrier release format",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="carrierpurchaseorder",
            name="delivery_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Delivery location for this carrier order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_carrier_purchase_orders",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="carrierpurchaseorder",
            name="pick_up_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Pick up location for this carrier order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickup_carrier_purchase_orders",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="delivery_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Delivery location for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_purchase_orders",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="pick_up_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Pick up location for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickup_purchase_orders",
                to="locations.location",
            ),
        ),
        migrations.AlterField(
            model_name="carrierpurchaseorder",
            name="how_carrier_make_appointment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Email", "Email"),
                    ("Phone", "Phone"),
                    ("Website", "Website"),
                    ("Fax", "Fax"),
                    ("First Come First Serve", "First Come First Serve"),
                ],
                default="",
                help_text="How carrier makes appointments",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="how_carrier_make_appointment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Email", "Email"),
                    ("Phone", "Phone"),
                    ("Website", "Website"),
                    ("Fax", "Fax"),
                    ("First Come First Serve", "First Come First Serve"),
                ],
                default="",
                help_text="How carrier makes appointments",
                max_length=50,
            ),
        ),
    ]
