# Generated by Django 6.0 on 2026-01-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carriers", "0004_carrier_departments_array_and_more"),
        ("contacts", "0002_contact_tenant_and_more"),
        ("locations", "0002_enable_rls_locations"),
        ("plants", "0004_metadata_lockdown"),
        ("products", "0004_state_sync_tenant"),
        ("purchase_orders", "0008_purchaseorder_outstanding_amount_and_more"),
        ("suppliers", "0005_supplier_departments_array"),
        ("tenants", "0006_metadata_lockdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_number",
            field=models.CharField(help_text="Order number (unique per tenant)", max_length=50),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.UniqueConstraint(
                fields=("tenant", "order_number"),
                name="unique_tenant_purchase_order_number",
            ),
        ),
    ]
