# Generated by Django 6.0 on 2026-02-02 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0004_add_plant_fields"),
        ("purchase_orders", "0009_alter_purchaseorder_order_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrierpurchaseorder",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="Plant/facility for this order (location with plant_* type)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plant_carrier_purchase_orders",
                to="locations.location",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="Plant/facility for this order (location with plant_* type)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plant_purchase_orders",
                to="locations.location",
            ),
        ),
    ]
