# Generated by Django 6.0 on 2026-02-13 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_orders", "0011_alter_product_fks_to_system"),
        ("system", "0007_add_container_versioning_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrierpurchaseorder",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Product being ordered",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system.product",
            ),
        ),
        migrations.AlterField(
            model_name="coldstorageentry",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Product being stored",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system.product",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Product being purchased",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="system.product",
            ),
        ),
    ]
