# Generated by Django 6.0 on 2026-02-27 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0012_alter_carrierpurchaseorder_product_and_more"),
        ("tenants", "0010_add_tenant_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrierpurchaseorder",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AddField(
            model_name="coldstorageentry",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="carrierpurchaseorder",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="coldstorageentry",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        # Enable Row-Level Security (RLS) for tenant isolation
        migrations.RunSQL(
            sql="""
            -- Enable RLS on purchase_orders_purchaseorder
            ALTER TABLE purchase_orders_purchaseorder ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS purchaseorder_tenant_isolation ON purchase_orders_purchaseorder;
            CREATE POLICY purchaseorder_tenant_isolation ON purchase_orders_purchaseorder
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            
            DROP POLICY IF EXISTS purchaseorder_tenant_insert ON purchase_orders_purchaseorder;
            CREATE POLICY purchaseorder_tenant_insert ON purchase_orders_purchaseorder
            FOR INSERT WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            
            -- Enable RLS on purchase_orders_carrierpurchaseorder
            ALTER TABLE purchase_orders_carrierpurchaseorder ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS carrierpurchaseorder_tenant_isolation ON purchase_orders_carrierpurchaseorder;
            CREATE POLICY carrierpurchaseorder_tenant_isolation ON purchase_orders_carrierpurchaseorder
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            
            DROP POLICY IF EXISTS carrierpurchaseorder_tenant_insert ON purchase_orders_carrierpurchaseorder;
            CREATE POLICY carrierpurchaseorder_tenant_insert ON purchase_orders_carrierpurchaseorder
            FOR INSERT WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            
            -- Enable RLS on purchase_orders_coldstorageentry
            ALTER TABLE purchase_orders_coldstorageentry ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS coldstorageentry_tenant_isolation ON purchase_orders_coldstorageentry;
            CREATE POLICY coldstorageentry_tenant_isolation ON purchase_orders_coldstorageentry
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            
            DROP POLICY IF EXISTS coldstorageentry_tenant_insert ON purchase_orders_coldstorageentry;
            CREATE POLICY coldstorageentry_tenant_insert ON purchase_orders_coldstorageentry
            FOR INSERT WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            -- Disable RLS policies for purchase_orders_purchaseorder
            DROP POLICY IF EXISTS purchaseorder_tenant_isolation ON purchase_orders_purchaseorder;
            DROP POLICY IF EXISTS purchaseorder_tenant_insert ON purchase_orders_purchaseorder;
            ALTER TABLE purchase_orders_purchaseorder DISABLE ROW LEVEL SECURITY;
            
            -- Disable RLS policies for purchase_orders_carrierpurchaseorder
            DROP POLICY IF EXISTS carrierpurchaseorder_tenant_isolation ON purchase_orders_carrierpurchaseorder;
            DROP POLICY IF EXISTS carrierpurchaseorder_tenant_insert ON purchase_orders_carrierpurchaseorder;
            ALTER TABLE purchase_orders_carrierpurchaseorder DISABLE ROW LEVEL SECURITY;
            
            -- Disable RLS policies for purchase_orders_coldstorageentry
            DROP POLICY IF EXISTS coldstorageentry_tenant_isolation ON purchase_orders_coldstorageentry;
            DROP POLICY IF EXISTS coldstorageentry_tenant_insert ON purchase_orders_coldstorageentry;
            ALTER TABLE purchase_orders_coldstorageentry DISABLE ROW LEVEL SECURITY;
            """
        ),
    ]
