# Generated by Django 6.0 on 2026-03-22
# Ensure purchase_orders FK migration chain runs before products deletes legacy Product.
#
# Without this ordering guard, fresh installs can attempt to apply products/0008
# (which removes products.Product) before purchase_orders/0011 (which removes FKs
# pointing at products.Product), causing a model resolution error.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_orders", "0013_refactor_to_tenantaware"),
    ]

    run_before = [
        ("products", "0008_masterproduct_delete_product_and_more"),
    ]

    operations = []
