# Generated by Django 6.0 on 2026-03-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0014_ordering_guard_run_before_products_0008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrierpurchaseorder",
            name="type_of_protein",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beef", "Beef"),
                    ("Chicken", "Chicken"),
                    ("Duck", "Duck"),
                    ("Pork", "Pork"),
                    ("Lamb", "Lamb"),
                    ("Turkey", "Turkey"),
                    ("Fish", "Fish"),
                    ("Horse", "Horse"),
                    ("Other", "Other"),
                ],
                default="",
                help_text="Type of protein",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="type_of_protein",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beef", "Beef"),
                    ("Chicken", "Chicken"),
                    ("Duck", "Duck"),
                    ("Pork", "Pork"),
                    ("Lamb", "Lamb"),
                    ("Turkey", "Turkey"),
                    ("Fish", "Fish"),
                    ("Horse", "Horse"),
                    ("Other", "Other"),
                ],
                default="",
                help_text="Type of protein (Beef, Pork, Chicken, etc.)",
                max_length=50,
            ),
        ),
    ]
