# Generated by Django 6.0 on 2026-03-23
# Squashed replacement for purchase_orders/0011 to avoid hard dependency on legacy products.Product.
#
# Problem:
# - products/0008 deletes products.Product
# - purchase_orders/0011 removes FKs that point to products.Product
# On fresh installs, Django may apply products/0008 before purchase_orders/0011, causing
# model resolution errors during RemoveField database operations.
#
# Solution:
# - Replace 0011 with a migration that drops the legacy columns using SQL (no model resolution)
#   and updates migration state via SeparateDatabaseAndState.
# - This remains safe in long-lived environments: if 0011 is already applied, this squashed
#   migration is considered applied because it "replaces" 0011.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("purchase_orders", "0011_alter_product_fks_to_system"),
    ]

    # Ensure the legacy FK fields are removed while products.Product still exists in migration state.
    run_before = [
        ("products", "0008_masterproduct_delete_product_and_more"),
    ]

    dependencies = [
        ("purchase_orders", "0010_update_plant_fk_to_location"),
        ("system", "0002_add_product_model"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE purchase_orders_purchaseorder DROP COLUMN IF EXISTS product_id;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE purchase_orders_carrierpurchaseorder DROP COLUMN IF EXISTS product_id;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE purchase_orders_coldstorageentry DROP COLUMN IF EXISTS product_id;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(model_name="purchaseorder", name="product"),
                migrations.RemoveField(model_name="carrierpurchaseorder", name="product"),
                migrations.RemoveField(model_name="coldstorageentry", name="product"),
            ],
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="system.product",
            ),
        ),
        migrations.AddField(
            model_name="carrierpurchaseorder",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Product being ordered",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carrier_purchase_orders",
                to="system.product",
            ),
        ),
        migrations.AddField(
            model_name="coldstorageentry",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Product being stored",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cold_storage_entries",
                to="system.product",
            ),
        ),
    ]
