# Generated by Django 6.0 on 2026-03-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_orders", "0015_alter_carrierpurchaseorder_type_of_protein_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="logistics_scenario",
            field=models.CharField(
                choices=[
                    ("customer_pickup", "Customer - Picking Up"),
                    ("supplier_delivery", "Supplier - Delivering"),
                    ("we_pickup", "Tenant - Pickup (We Handle Logistics)"),
                ],
                default="supplier_delivery",
                help_text="Logistics scenario: Customer Pickup, Supplier Delivery, or We Pickup",
                max_length=50,
            ),
        ),
    ]
