# Generated by Django 6.0 on 2026-03-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_orders", "0016_alter_purchaseorder_logistics_scenario"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
