# Generated by Django 6.0 on 2026-04-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_orders", "0018_golden_schema_refactor"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrierpurchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("dispatched", "Dispatched"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                help_text="Current freight order workflow status.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("sent", "Sent"),
                    ("carrier_assigned", "Carrier Assigned"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("invoiced", "Invoiced"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Current status of the purchase order",
                max_length=20,
            ),
        ),
    ]
