# Generated by Django 6.0 on 2026-05-07 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import tenant_apps.purchase_orders.models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0006_alter_emaillog_status"),
        ("purchase_orders", "0019_operational_readiness"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrderApprovalDispatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "approved_pdf",
                    models.FileField(
                        blank=True,
                        default="",
                        upload_to=tenant_apps.purchase_orders.models.purchase_order_approval_dispatch_upload_to,
                    ),
                ),
                ("approved_pdf_checksum", models.CharField(blank=True, default="", max_length=64)),
                ("approved_pdf_byte_size", models.PositiveBigIntegerField(default=0)),
                ("pdf_generated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("sender_email", models.EmailField(blank=True, default="", max_length=254)),
                ("recipient_email", models.EmailField(blank=True, default="", max_length=254)),
                ("recipient_name", models.CharField(blank=True, default="", max_length=255)),
                ("subject", models.CharField(default="", max_length=300)),
                ("body", models.TextField(default="")),
                ("provider", models.CharField(default="microsoft", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("provider_message_id", models.CharField(blank=True, default="", max_length=255)),
                ("provider_thread_id", models.CharField(blank=True, default="", max_length=255)),
                ("provider_internet_message_id", models.CharField(blank=True, default="", max_length=255)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_order_approval_dispatches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_dispatch",
                        to="purchase_orders.purchaseorder",
                    ),
                ),
                (
                    "sender_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_order_approval_dispatches",
                        to="integrations.externalauthprovider",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order Approval Dispatch",
                "verbose_name_plural": "Purchase Order Approval Dispatches",
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="po_dispatch_tenant_status_idx"),
                    models.Index(fields=["tenant", "sent_at"], name="po_dispatch_tenant_sent_idx"),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE purchase_orders_purchaseorderapprovaldispatch ENABLE ROW LEVEL SECURITY;
            ALTER TABLE purchase_orders_purchaseorderapprovaldispatch FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS purchaseorderapprovaldispatch_tenant_insert ON purchase_orders_purchaseorderapprovaldispatch;
            DROP POLICY IF EXISTS purchaseorderapprovaldispatch_tenant_isolation ON purchase_orders_purchaseorderapprovaldispatch;

            CREATE POLICY purchaseorderapprovaldispatch_tenant_isolation ON purchase_orders_purchaseorderapprovaldispatch
              USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

            CREATE POLICY purchaseorderapprovaldispatch_tenant_insert ON purchase_orders_purchaseorderapprovaldispatch
              FOR INSERT WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS purchaseorderapprovaldispatch_tenant_insert ON purchase_orders_purchaseorderapprovaldispatch;
            DROP POLICY IF EXISTS purchaseorderapprovaldispatch_tenant_isolation ON purchase_orders_purchaseorderapprovaldispatch;
            ALTER TABLE purchase_orders_purchaseorderapprovaldispatch NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE purchase_orders_purchaseorderapprovaldispatch DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
