# Generated by Django 6.0 on 2026-05-07 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0012_trade_session_lineage"),
        ("purchase_orders", "0020_purchaseorderapprovaldispatch"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carrierpurchaseorder",
            options={},
        ),
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={},
        ),
        migrations.AddField(
            model_name="carrierpurchaseorder",
            name="trade_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Trade session lineage key (CTE-05.1).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carrier_purchase_orders",
                to="inquiries.tradesession",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="trade_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Trade session lineage key (CTE-05.1).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="inquiries.tradesession",
            ),
        ),
    ]
