# Generated by Django 6.0 on 2025-12-15 18:35

import django.db.models.deletion
from django.db import migrations, models


def create_table_with_tenant_if_not_exists(apps, schema_editor):
    """Create AIConfiguration table with tenant field if it doesn't exist"""
    from django.db import connection

    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute(
            """
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = 'ai_assistant_configurations'
            );
        """
        )
        table_exists = cursor.fetchone()[0]

        if not table_exists:
            # Table doesn't exist - create it with tenant field from the start
            cursor.execute(
                """
                CREATE TABLE ai_assistant_configurations (
                    id BIGSERIAL PRIMARY KEY,
                    tenant_id UUID NOT NULL REFERENCES tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED,
                    name VARCHAR(100) NOT NULL UNIQUE,
                    provider VARCHAR(50) NOT NULL DEFAULT 'openai',
                    model_name VARCHAR(100) NOT NULL DEFAULT 'gpt-4o-mini',
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    is_default BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
                );
            """
            )

            # Add index for tenant lookups
            cursor.execute(
                """
                CREATE INDEX ai_assistant_configurations_tenant_id_idx
                ON ai_assistant_configurations(tenant_id);
            """
            )
        else:
            # Table exists - check if tenant_id column exists
            cursor.execute(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema='public'
                AND table_name='ai_assistant_configurations'
                AND column_name='tenant_id';
            """
            )

            if not cursor.fetchone():
                # Add tenant_id column to existing table
                cursor.execute("SELECT id FROM tenants_tenant LIMIT 1;")
                result = cursor.fetchone()

                if result:
                    # Production path: Tenant exists, use it as default
                    default_tenant_id = result[0]
                    cursor.execute(
                        """
                        ALTER TABLE ai_assistant_configurations
                        ADD COLUMN tenant_id UUID NOT NULL DEFAULT %s
                        REFERENCES tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;
                    """,
                        [default_tenant_id],
                    )

                    # Remove the default after adding the column
                    cursor.execute(
                        """
                        ALTER TABLE ai_assistant_configurations
                        ALTER COLUMN tenant_id DROP DEFAULT;
                    """
                    )
                else:
                    # Test/Fresh DB path: No tenants exist yet, add as nullable
                    cursor.execute(
                        """
                        ALTER TABLE ai_assistant_configurations
                        ADD COLUMN tenant_id UUID NULL
                        REFERENCES tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;
                    """
                    )

                # Add index
                cursor.execute(
                    """
                    CREATE INDEX IF NOT EXISTS ai_assistant_configurations_tenant_id_idx
                    ON ai_assistant_configurations(tenant_id);
                """
                )


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_table_with_tenant_if_not_exists, migrations.RunPython.noop),
    ]
