# Generated by Django 6.0 on 2026-01-04 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Golden State Synchronization: Inform Django that tenant field exists.

    The 0002 migration used RunPython with raw SQL to add the tenant column,
    but Django's autodetector can't see inside RunPython operations. This
    migration uses SeparateDatabaseAndState to update Django's internal state
    WITHOUT running any SQL (since the column already exists in the database).
    """

    dependencies = [
        ("ai_assistant", "0002_aiconfiguration_tenant"),
        ("tenants", "0004_add_golden_ticket_features"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Tell Django's state system that tenant field exists
                migrations.AddField(
                    model_name="aiconfiguration",
                    name="tenant",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_configurations",
                        to="tenants.tenant",
                        help_text="Tenant this aiconfiguration belongs to",
                    ),
                ),
            ],
            database_operations=[
                # NO-OP: Column already exists from RunPython in 0002
            ],
        ),
    ]
