# Generated by Django 6.0 on 2026-03-18 03:16
# Add RLS policy for AIConfiguration model

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0004_aiconfiguration_created_on_and_more"),
    ]

    operations = [
        RunSQL(
            sql="""
            -- Enable RLS on ai_assistant_configurations
            ALTER TABLE ai_assistant_configurations ENABLE ROW LEVEL SECURITY;

            -- Create tenant isolation policy
            CREATE POLICY ai_assistant_configurations_tenant_isolation ON ai_assistant_configurations
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS ai_assistant_configurations_tenant_isolation ON ai_assistant_configurations;
            ALTER TABLE ai_assistant_configurations DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
