# Generated by Django 6.0 on 2026-03-20 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0005_add_rls_policies_batch"),
        ("tenants", "0010_add_tenant_configuration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFeedbackLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("document_id", models.UUIDField(help_text="Upstream document identifier")),
                ("document_type", models.CharField(help_text="Classified document type", max_length=64)),
                ("original_extracted_data", models.JSONField(blank=True, default=dict)),
                ("user_corrected_data", models.JSONField(blank=True, default=dict)),
                ("confidence_score", models.FloatField(default=0.0, help_text="Model confidence from 0.0 to 1.0")),
                (
                    "precision_delta",
                    models.FloatField(default=0.0, help_text="Derived change ratio between original and corrected"),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_feedback_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Feedback Log",
                "verbose_name_plural": "AI Feedback Logs",
                "db_table": "ai_assistant_feedback_logs",
                "indexes": [
                    models.Index(fields=["tenant", "document_id"], name="ai_fb_tenant_doc_idx"),
                    models.Index(fields=["tenant", "document_type"], name="ai_fb_tenant_type_idx"),
                ],
            },
        ),
        RunSQL(
            sql="""
            -- Enable RLS on ai_assistant_feedback_logs
            ALTER TABLE ai_assistant_feedback_logs ENABLE ROW LEVEL SECURITY;

            -- Create tenant isolation policy
            CREATE POLICY ai_assistant_feedback_logs_tenant_isolation ON ai_assistant_feedback_logs
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS ai_assistant_feedback_logs_tenant_isolation ON ai_assistant_feedback_logs;
            ALTER TABLE ai_assistant_feedback_logs DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
