# Generated by Django 6.0 on 2026-03-20 00:33

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0006_aifeedbacklog"),
        ("tenants", "0010_add_tenant_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorMemory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(default="context", help_text="context|purchase_order|other", max_length=64),
                ),
                ("document_id", models.UUIDField(blank=True, null=True)),
                ("content", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "embedding",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Embedding vector as JSON array (pgvector optional).",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vector Memory",
                "verbose_name_plural": "Vector Memory",
                "db_table": "ai_assistant_vector_memory",
                "indexes": [models.Index(fields=["tenant", "source_type"], name="ai_vec_tenant_src_idx")],
            },
        ),
        RunSQL(
            sql="""
            -- Enable RLS on ai_assistant_vector_memory
            ALTER TABLE ai_assistant_vector_memory ENABLE ROW LEVEL SECURITY;

            -- Create tenant isolation policy
            CREATE POLICY ai_assistant_vector_memory_tenant_isolation ON ai_assistant_vector_memory
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS ai_assistant_vector_memory_tenant_isolation ON ai_assistant_vector_memory;
            ALTER TABLE ai_assistant_vector_memory DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
