# Generated by Django 6.0 on 2026-03-22
# Normalize RLS policies to safe current_setting('app.current_tenant', true)

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0007_vectormemory"),
    ]

    operations = [
        RunSQL(
            sql="""
            -- AIConfiguration
            ALTER TABLE ai_assistant_configurations ENABLE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_configurations FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS ai_assistant_configurations_tenant_isolation ON ai_assistant_configurations;
            CREATE POLICY ai_assistant_configurations_tenant_isolation ON ai_assistant_configurations
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- AIFeedbackLog
            ALTER TABLE ai_assistant_feedback_logs ENABLE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_feedback_logs FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS ai_assistant_feedback_logs_tenant_isolation ON ai_assistant_feedback_logs;
            CREATE POLICY ai_assistant_feedback_logs_tenant_isolation ON ai_assistant_feedback_logs
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- VectorMemory
            ALTER TABLE ai_assistant_vector_memory ENABLE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_vector_memory FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS ai_assistant_vector_memory_tenant_isolation ON ai_assistant_vector_memory;
            CREATE POLICY ai_assistant_vector_memory_tenant_isolation ON ai_assistant_vector_memory
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS ai_assistant_configurations_tenant_isolation ON ai_assistant_configurations;
            CREATE POLICY ai_assistant_configurations_tenant_isolation ON ai_assistant_configurations
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant')::uuid);

            DROP POLICY IF EXISTS ai_assistant_feedback_logs_tenant_isolation ON ai_assistant_feedback_logs;
            CREATE POLICY ai_assistant_feedback_logs_tenant_isolation ON ai_assistant_feedback_logs
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant')::uuid);

            DROP POLICY IF EXISTS ai_assistant_vector_memory_tenant_isolation ON ai_assistant_vector_memory;
            CREATE POLICY ai_assistant_vector_memory_tenant_isolation ON ai_assistant_vector_memory
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
        ),
    ]
