# Generated by Django 6.0 on 2026-03-23 14:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0008_fix_ai_assistant_rls_policies_safe_current_setting"),
        ("tenants", "0011_bootstrap_rls_session_vars"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="ai_assistant/documents/%Y/%m/%d",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "txt",
                                    "csv",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                ]
                            )
                        ],
                    ),
                ),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                ("content_type", models.CharField(blank=True, default="", max_length=128)),
                ("file_size", models.BigIntegerField(default=0)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who uploaded this document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional chat session this document was uploaded into",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="ai_assistant.chatsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Document",
                "verbose_name_plural": "AI Documents",
                "db_table": "ai_assistant_documents",
                "indexes": [
                    models.Index(fields=["tenant", "owner", "created_on"], name="aidoc_tnt_owner_created_idx")
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE ai_assistant_documents ENABLE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_documents FORCE ROW LEVEL SECURITY;

            CREATE POLICY ai_assistant_documents_tenant_isolation ON ai_assistant_documents
              USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS ai_assistant_documents_tenant_isolation ON ai_assistant_documents;
            ALTER TABLE ai_assistant_documents DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
