# Generated by Django 6.0 on 2026-03-23 21:05

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0009_aidocument"),
        ("tenants", "0011_bootstrap_rls_session_vars"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantKnowledgeFact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "domain_category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional domain label (e.g. ordering, invoicing, cold_storage)",
                        max_length=64,
                    ),
                ),
                ("fact_text", models.TextField(help_text="Canonical tenant fact text")),
                (
                    "embedding",
                    models.JSONField(
                        blank=True,
                        null=True,
                        default=list,
                        help_text="Embedding vector as JSON array (pgvector optional).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Knowledge Fact",
                "verbose_name_plural": "Tenant Knowledge Facts",
                "db_table": "ai_assistant_tenant_knowledge_facts",
                "indexes": [models.Index(fields=["tenant", "domain_category"], name="ai_kf_tenant_domain_idx")],
            },
        ),
        RunSQL(
            sql="""
            ALTER TABLE ai_assistant_tenant_knowledge_facts ENABLE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_tenant_knowledge_facts FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS ai_assistant_tenant_knowledge_facts_tenant_isolation ON ai_assistant_tenant_knowledge_facts;
            CREATE POLICY ai_assistant_tenant_knowledge_facts_tenant_isolation ON ai_assistant_tenant_knowledge_facts
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS ai_assistant_tenant_knowledge_facts_tenant_isolation ON ai_assistant_tenant_knowledge_facts;
            ALTER TABLE ai_assistant_tenant_knowledge_facts DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
