# Generated by Django 6.0 on 2026-03-24 00:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0010_tenantknowledgefact"),
        ("tenants", "0011_bootstrap_rls_session_vars"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="aifeedbacklog",
            index=models.Index(
                fields=["tenant", "resolved_by", "confidence_score", "created_on"], name="ai_fb_queue_idx"
            ),
        ),
    ]
