# Generated by Django 6.0 on 2026-03-27 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0011_aifeedbacklog_ai_fb_queue_idx"),
        ("tenants", "0011_bootstrap_rls_session_vars"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("user_message", models.TextField(blank=True, default="")),
                ("assistant_message", models.TextField(blank=True, default="")),
                ("user_correction", models.TextField(help_text="User-provided correction")),
                ("lesson_text", models.TextField(help_text="Normalized lesson learned to apply in future responses")),
                ("entity_type", models.CharField(blank=True, default="", max_length=64)),
                ("entity_id", models.CharField(blank=True, default="", max_length=64)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_feedback_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Feedback",
                "verbose_name_plural": "AI Feedback",
                "db_table": "ai_assistant_feedback",
                "indexes": [
                    models.Index(fields=["tenant", "is_active", "created_on"], name="ai_fb_item_queue_idx"),
                    models.Index(fields=["tenant", "entity_type", "created_on"], name="ai_fb_item_entity_idx"),
                ],
            },
        ),
        RunSQL(
            sql="""
            ALTER TABLE ai_assistant_feedback ENABLE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_feedback FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS ai_assistant_feedback_tenant_isolation ON ai_assistant_feedback;
            CREATE POLICY ai_assistant_feedback_tenant_isolation ON ai_assistant_feedback
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS ai_assistant_feedback_tenant_isolation ON ai_assistant_feedback;
            ALTER TABLE ai_assistant_feedback DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
