# Generated by Django 6.0 on 2026-03-27 09:04

import django.core.validators
import tenant_apps.ai_assistant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0012_aifeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aidocument",
            name="file",
            field=models.FileField(
                upload_to=tenant_apps.ai_assistant.models.aidocument_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "txt", "csv", "jpg", "jpeg", "png", "doc", "docx", "xls", "xlsx"]
                    )
                ],
            ),
        ),
    ]
