# Generated by Django 6.0 on 2026-03-31 18:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0013_alter_aidocument_file"),
        ("tenants", "0013_alter_activitylog_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationLog",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("entity_type", models.CharField(default="supplier", max_length=32)),
                ("entity_id", models.CharField(blank=True, default="", max_length=64)),
                ("to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(default="", max_length=300)),
                ("body", models.TextField(default="")),
                (
                    "provider",
                    models.CharField(
                        default="manual", help_text="manual|outlook (send is always human-approved)", max_length=32
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communication_logs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication Log",
                "verbose_name_plural": "Communication Logs",
                "db_table": "ai_assistant_communication_logs",
                "indexes": [
                    models.Index(fields=["tenant", "status", "created_on"], name="ai_comms_tenant_status_idx"),
                    models.Index(fields=["tenant", "entity_type", "created_on"], name="ai_comms_tenant_entity_idx"),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE ai_assistant_communication_logs ENABLE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_communication_logs FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS communicationlog_tenant_insert ON ai_assistant_communication_logs;
            DROP POLICY IF EXISTS communicationlog_tenant_isolation ON ai_assistant_communication_logs;

            CREATE POLICY communicationlog_tenant_isolation ON ai_assistant_communication_logs
              USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

            CREATE POLICY communicationlog_tenant_insert ON ai_assistant_communication_logs
              FOR INSERT WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS communicationlog_tenant_insert ON ai_assistant_communication_logs;
            DROP POLICY IF EXISTS communicationlog_tenant_isolation ON ai_assistant_communication_logs;
            ALTER TABLE ai_assistant_communication_logs NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_communication_logs DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
