# Generated by Django 6.0 on 2026-03-31 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0014_communicationlog"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantAIMemory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Stable key for upserts (e.g. vendor:acme:routing_rule)", max_length=128
                    ),
                ),
                ("memory_text", models.TextField(blank=True, default="", help_text="Human-readable memory text")),
                (
                    "memory_json",
                    models.JSONField(blank=True, default=dict, help_text="Optional structured memory payload"),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "embedding",
                    models.JSONField(
                        blank=True, default=list, help_text="Embedding vector as JSON array (pgvector optional)."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant AI Memory",
                "verbose_name_plural": "Tenant AI Memories",
                "db_table": "ai_assistant_tenant_memory",
                "indexes": [models.Index(fields=["tenant", "key"], name="ai_mem_tenant_key_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "key"), name="unique_ai_memory_key_per_tenant")
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE ai_assistant_tenant_memory ENABLE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_tenant_memory FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS tenantaimemory_tenant_insert ON ai_assistant_tenant_memory;
            DROP POLICY IF EXISTS tenantaimemory_tenant_isolation ON ai_assistant_tenant_memory;

            CREATE POLICY tenantaimemory_tenant_isolation ON ai_assistant_tenant_memory
              USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

            CREATE POLICY tenantaimemory_tenant_insert ON ai_assistant_tenant_memory
              FOR INSERT WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tenantaimemory_tenant_insert ON ai_assistant_tenant_memory;
            DROP POLICY IF EXISTS tenantaimemory_tenant_isolation ON ai_assistant_tenant_memory;
            ALTER TABLE ai_assistant_tenant_memory NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_tenant_memory DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
