# Generated by Django 6.0 on 2026-04-29 17:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _normalize_uuid(raw_value):
    try:
        return str(uuid.UUID(str(raw_value or '').strip()))
    except (TypeError, ValueError, AttributeError):
        return ''


def backfill_chat_tenant_fields(apps, schema_editor):
    ChatSession = apps.get_model('ai_assistant', 'ChatSession')
    ChatMessage = apps.get_model('ai_assistant', 'ChatMessage')
    Tenant = apps.get_model('tenants', 'Tenant')

    valid_tenant_ids = {
        str(tenant_id)
        for tenant_id in Tenant.objects.values_list('id', flat=True)
    }

    for session in ChatSession.objects.filter(tenant__isnull=True).iterator():
        context_data = session.context_data if isinstance(session.context_data, dict) else {}
        tenant_id = _normalize_uuid(context_data.get('tenant_id'))
        if tenant_id and tenant_id in valid_tenant_ids:
            session.tenant_id = tenant_id
            session.save(update_fields=['tenant'])

    for message in ChatMessage.objects.filter(tenant__isnull=True).select_related('session').iterator():
        session_tenant_id = str(getattr(message.session, 'tenant_id', '') or '').strip()
        if session_tenant_id:
            message.tenant_id = session_tenant_id
            message.save(update_fields=['tenant'])


def clear_chat_tenant_fields(apps, schema_editor):
    ChatSession = apps.get_model('ai_assistant', 'ChatSession')
    ChatMessage = apps.get_model('ai_assistant', 'ChatMessage')

    ChatMessage.objects.update(tenant=None)
    ChatSession.objects.update(tenant=None)


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0015_tenantaimemory"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this chat message belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_chat_messages",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this chat session belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_chat_sessions",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["tenant", "session", "created_on"], name="ai_assistan_tenant__f45a01_idx"),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["tenant", "owner", "-last_activity"], name="ai_assistan_tenant__7b7f70_idx"),
        ),
        migrations.RunPython(backfill_chat_tenant_fields, reverse_code=clear_chat_tenant_fields),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                ALTER TABLE ai_assistant_chat_sessions ENABLE ROW LEVEL SECURITY;
                ALTER TABLE ai_assistant_chat_sessions FORCE ROW LEVEL SECURITY;

                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_policies
                    WHERE schemaname = 'public'
                      AND tablename = 'ai_assistant_chat_sessions'
                      AND policyname = 'ai_assistant_chat_sessions_tenant_isolation'
                ) THEN
                    CREATE POLICY ai_assistant_chat_sessions_tenant_isolation ON ai_assistant_chat_sessions
                        FOR ALL
                        USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                        WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
                END IF;

                ALTER TABLE ai_assistant_chat_messages ENABLE ROW LEVEL SECURITY;
                ALTER TABLE ai_assistant_chat_messages FORCE ROW LEVEL SECURITY;

                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_policies
                    WHERE schemaname = 'public'
                      AND tablename = 'ai_assistant_chat_messages'
                      AND policyname = 'ai_assistant_chat_messages_tenant_isolation'
                ) THEN
                    CREATE POLICY ai_assistant_chat_messages_tenant_isolation ON ai_assistant_chat_messages
                        FOR ALL
                        USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                        WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS ai_assistant_chat_messages_tenant_isolation ON ai_assistant_chat_messages;
            ALTER TABLE ai_assistant_chat_messages NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_chat_messages DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS ai_assistant_chat_sessions_tenant_isolation ON ai_assistant_chat_sessions;
            ALTER TABLE ai_assistant_chat_sessions NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_chat_sessions DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
