# Generated by Django 6.0 on 2026-04-28 20:11

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from django.db.migrations import RunSQL
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0015_tenantaimemory"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name="tenantaimemory",
            name="embedding_vector",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, help_text="Native pgvector embedding for semantic retrieval.", null=True
            ),
        ),
        migrations.AddField(
            model_name="tenantknowledgefact",
            name="embedding_vector",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, help_text="Native pgvector embedding for semantic retrieval.", null=True
            ),
        ),
        migrations.AddField(
            model_name="vectormemory",
            name="embedding_vector",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, help_text="Native pgvector embedding for semantic retrieval.", null=True
            ),
        ),
        migrations.CreateModel(
            name="AIDocumentChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField(default=0)),
                ("content", models.TextField(default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "embedding",
                    models.JSONField(
                        blank=True, default=list, help_text="Embedding vector as JSON array for back-compat."
                    ),
                ),
                (
                    "embedding_vector",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1536,
                        help_text="Native pgvector embedding for semantic retrieval.",
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="ai_assistant.aidocument"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Document Chunk",
                "verbose_name_plural": "AI Document Chunks",
                "db_table": "ai_assistant_document_chunks",
                "indexes": [models.Index(fields=["tenant", "document"], name="aidoc_chunk_tenant_doc_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "document", "chunk_index"), name="unique_ai_document_chunk_per_tenant"
                    )
                ],
            },
        ),
        RunSQL(
            sql="""
            ALTER TABLE ai_assistant_document_chunks ENABLE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_document_chunks FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS ai_assistant_document_chunks_tenant_isolation ON ai_assistant_document_chunks;
            CREATE POLICY ai_assistant_document_chunks_tenant_isolation ON ai_assistant_document_chunks
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS ai_assistant_document_chunks_tenant_isolation ON ai_assistant_document_chunks;
            ALTER TABLE ai_assistant_document_chunks DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
