# Generated by Django 6.0 on 2026-04-29 21:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0016_chatmessage_tenant_chatsession_tenant_and_more"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRun",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source", models.CharField(default="chat", max_length=32)),
                ("event_type", models.CharField(default="user_chat", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("approval_required", "Approval Required"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("correlation_id", models.CharField(blank=True, default="", max_length=128)),
                ("intent", models.CharField(blank=True, default="", max_length=128)),
                ("user_message", models.TextField(blank=True, default="")),
                ("response_text", models.TextField(blank=True, default="")),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("approval_required_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_runs_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_runs",
                        to="ai_assistant.chatsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Run",
                "verbose_name_plural": "AI Runs",
                "db_table": "ai_assistant_runs",
            },
        ),
        migrations.CreateModel(
            name="AITask",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tool_name", models.CharField(max_length=128)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("approval_required", "Approval Required"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("requires_approval", models.BooleanField(default=False)),
                ("approval_requested_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("input_payload", models.JSONField(blank=True, default=dict)),
                ("output_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("target_entity_type", models.CharField(blank=True, default="", max_length=64)),
                ("target_entity_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_tasks_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="ai_assistant.airun"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Task",
                "verbose_name_plural": "AI Tasks",
                "db_table": "ai_assistant_tasks",
            },
        ),
        migrations.CreateModel(
            name="AIApproval",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tool_name", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("resolution_note", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_approvals_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_approvals_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="approvals", to="ai_assistant.airun"
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="approval", to="ai_assistant.aitask"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Approval",
                "verbose_name_plural": "AI Approvals",
                "db_table": "ai_assistant_approvals",
            },
        ),
        migrations.AddIndex(
            model_name="airun",
            index=models.Index(fields=["tenant", "status", "created_on"], name="ai_run_tenant_status_idx"),
        ),
        migrations.AddIndex(
            model_name="airun",
            index=models.Index(fields=["tenant", "requested_by", "created_on"], name="ai_run_tenant_user_idx"),
        ),
        migrations.AddIndex(
            model_name="airun",
            index=models.Index(fields=["tenant", "session", "created_on"], name="ai_run_tenant_session_idx"),
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(fields=["tenant", "status", "created_on"], name="ai_task_tenant_status_idx"),
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(fields=["tenant", "run", "sequence"], name="ai_task_tenant_run_idx"),
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(fields=["tenant", "tool_name", "created_on"], name="ai_task_tenant_tool_idx"),
        ),
        migrations.AddConstraint(
            model_name="aitask",
            constraint=models.UniqueConstraint(fields=("run", "sequence"), name="unique_ai_task_sequence_per_run"),
        ),
        migrations.AddIndex(
            model_name="aiapproval",
            index=models.Index(fields=["tenant", "status", "created_on"], name="ai_appr_tenant_status_idx"),
        ),
        migrations.AddIndex(
            model_name="aiapproval",
            index=models.Index(fields=["tenant", "requested_by", "created_on"], name="ai_appr_tenant_user_idx"),
        ),
        migrations.AddIndex(
            model_name="aiapproval",
            index=models.Index(fields=["tenant", "tool_name", "created_on"], name="ai_appr_tenant_tool_idx"),
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                ALTER TABLE ai_assistant_runs ENABLE ROW LEVEL SECURITY;
                ALTER TABLE ai_assistant_runs FORCE ROW LEVEL SECURITY;

                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_policies
                    WHERE schemaname = 'public'
                      AND tablename = 'ai_assistant_runs'
                      AND policyname = 'ai_assistant_runs_tenant_isolation'
                ) THEN
                    CREATE POLICY ai_assistant_runs_tenant_isolation ON ai_assistant_runs
                        FOR ALL
                        USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                        WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
                END IF;

                ALTER TABLE ai_assistant_tasks ENABLE ROW LEVEL SECURITY;
                ALTER TABLE ai_assistant_tasks FORCE ROW LEVEL SECURITY;

                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_policies
                    WHERE schemaname = 'public'
                      AND tablename = 'ai_assistant_tasks'
                      AND policyname = 'ai_assistant_tasks_tenant_isolation'
                ) THEN
                    CREATE POLICY ai_assistant_tasks_tenant_isolation ON ai_assistant_tasks
                        FOR ALL
                        USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                        WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
                END IF;

                ALTER TABLE ai_assistant_approvals ENABLE ROW LEVEL SECURITY;
                ALTER TABLE ai_assistant_approvals FORCE ROW LEVEL SECURITY;

                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_policies
                    WHERE schemaname = 'public'
                      AND tablename = 'ai_assistant_approvals'
                      AND policyname = 'ai_assistant_approvals_tenant_isolation'
                ) THEN
                    CREATE POLICY ai_assistant_approvals_tenant_isolation ON ai_assistant_approvals
                        FOR ALL
                        USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                        WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS ai_assistant_approvals_tenant_isolation ON ai_assistant_approvals;
            ALTER TABLE ai_assistant_approvals NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_approvals DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS ai_assistant_tasks_tenant_isolation ON ai_assistant_tasks;
            ALTER TABLE ai_assistant_tasks NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_tasks DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS ai_assistant_runs_tenant_isolation ON ai_assistant_runs;
            ALTER TABLE ai_assistant_runs NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_runs DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
