# Generated by Django 6.0 on 2026-04-29 22:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0017_airun_aitask_aiapproval_and_more"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIDocumentSemanticChunk",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("chunk_index", models.PositiveIntegerField(default=0)),
                ("content", models.TextField(default="")),
                ("content_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "embedding",
                    models.JSONField(
                        blank=True, default=list, help_text="Embedding vector as JSON array (pgvector optional)."
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semantic_chunks",
                        to="ai_assistant.aidocument",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Document Semantic Chunk",
                "verbose_name_plural": "AI Document Semantic Chunks",
                "db_table": "ai_assistant_document_semantic_chunks",
                "indexes": [
                    models.Index(fields=["tenant", "document", "chunk_index"], name="ai_doc_chunk_doc_idx"),
                    models.Index(fields=["tenant", "created_on"], name="ai_doc_chunk_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("document", "chunk_index"), name="unique_ai_document_chunk_index")
                ],
            },
        ),
        migrations.CreateModel(
            name="AILineageEvent",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=64)),
                ("source_type", models.CharField(blank=True, default="", max_length=64)),
                ("source_id", models.CharField(blank=True, default="", max_length=128)),
                ("target_type", models.CharField(blank=True, default="", max_length=64)),
                ("target_id", models.CharField(blank=True, default="", max_length=128)),
                ("summary", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lineage_events",
                        to="ai_assistant.aiapproval",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lineage_events",
                        to="ai_assistant.aidocument",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lineage_events",
                        to="ai_assistant.airun",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lineage_events",
                        to="ai_assistant.aitask",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Lineage Event",
                "verbose_name_plural": "AI Lineage Events",
                "db_table": "ai_assistant_lineage_events",
                "indexes": [
                    models.Index(fields=["tenant", "event_type", "created_on"], name="ai_lineage_event_type_idx"),
                    models.Index(fields=["tenant", "document", "created_on"], name="ai_lineage_document_idx"),
                    models.Index(fields=["tenant", "run", "created_on"], name="ai_lineage_run_idx"),
                    models.Index(fields=["tenant", "task", "created_on"], name="ai_lineage_task_idx"),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                ALTER TABLE ai_assistant_document_semantic_chunks ENABLE ROW LEVEL SECURITY;
                ALTER TABLE ai_assistant_document_semantic_chunks FORCE ROW LEVEL SECURITY;

                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_policies
                    WHERE schemaname = 'public'
                      AND tablename = 'ai_assistant_document_semantic_chunks'
                      AND policyname = 'ai_assistant_document_semantic_chunks_tenant_isolation'
                ) THEN
                    CREATE POLICY ai_assistant_document_semantic_chunks_tenant_isolation ON ai_assistant_document_semantic_chunks
                        FOR ALL
                        USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                        WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
                END IF;

                ALTER TABLE ai_assistant_lineage_events ENABLE ROW LEVEL SECURITY;
                ALTER TABLE ai_assistant_lineage_events FORCE ROW LEVEL SECURITY;

                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_policies
                    WHERE schemaname = 'public'
                      AND tablename = 'ai_assistant_lineage_events'
                      AND policyname = 'ai_assistant_lineage_events_tenant_isolation'
                ) THEN
                    CREATE POLICY ai_assistant_lineage_events_tenant_isolation ON ai_assistant_lineage_events
                        FOR ALL
                        USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                        WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS ai_assistant_lineage_events_tenant_isolation ON ai_assistant_lineage_events;
            ALTER TABLE ai_assistant_lineage_events NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_lineage_events DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS ai_assistant_document_semantic_chunks_tenant_isolation ON ai_assistant_document_semantic_chunks;
            ALTER TABLE ai_assistant_document_semantic_chunks NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE ai_assistant_document_semantic_chunks DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
