# Generated by Django 6.0 on 2026-05-07 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0018_aidocumentsemanticchunk_ailineageevent"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aifeedbacklog",
            name="feedback_comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Operator comment captured with inbox feedback; required for negative feedback.",
            ),
        ),
        migrations.AddField(
            model_name="aifeedbacklog",
            name="feedback_signal",
            field=models.CharField(
                blank=True,
                choices=[("thumbs_up", "Thumbs Up"), ("thumbs_down", "Thumbs Down")],
                help_text="Optional inbox reaction signal captured from the operator.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aifeedbacklog",
            name="feedback_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Surface where the operator submitted feedback (for example: ai_inbox).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="aifeedbacklog",
            name="retraining_queued_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this feedback was queued for retraining.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aifeedbacklog",
            name="retraining_status",
            field=models.CharField(
                choices=[("not_queued", "Not queued"), ("queued", "Queued"), ("exported", "Exported")],
                default="not_queued",
                help_text="Tracks whether the feedback has been queued/exported for retraining workflows.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="aifeedbacklog",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_feedback_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="aifeedbacklog",
            index=models.Index(fields=["tenant", "retraining_status", "created_on"], name="ai_fb_retrain_idx"),
        ),
    ]
