# Generated by Django 6.0 on 2026-05-07 16:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0019_aifeedbacklog_feedback_comment_and_more"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CockpitDraftForm",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source_feedback_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, help_text="FK to AIFeedbackLog that triggered this draft.", null=True
                    ),
                ),
                (
                    "source_document_id",
                    models.UUIDField(blank=True, help_text="Source document/email UUID.", null=True),
                ),
                (
                    "form_type",
                    models.CharField(
                        db_index=True,
                        help_text="Target form type: purchase_order, inquiry, sales_order, bid, etc.",
                        max_length=64,
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Pre-populated form fields from parsed email/document."
                    ),
                ),
                (
                    "parsed_payload",
                    models.JSONField(
                        blank=True, default=dict, help_text="Full parsed payload (provenance) from email parser."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("discarded", "Discarded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "submitted_entity_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Entity type created on submission (e.g., PurchaseOrder).",
                        max_length=64,
                    ),
                ),
                (
                    "submitted_entity_id",
                    models.CharField(blank=True, default="", help_text="PK of created entity.", max_length=64),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to review this draft.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cockpit_draft_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cockpit_draft_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cockpit Draft Form",
                "verbose_name_plural": "Cockpit Draft Forms",
                "db_table": "ai_assistant_cockpit_drafts",
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(fields=["tenant", "status", "-created_on"], name="ai_draft_tenant_status_idx"),
                    models.Index(fields=["tenant", "form_type", "-created_on"], name="ai_draft_tenant_type_idx"),
                    models.Index(fields=["tenant", "assigned_to", "status"], name="ai_draft_assigned_idx"),
                ],
            },
        ),
        # RLS Policy — tenant isolation at database level
        migrations.RunSQL(
            sql="""
            ALTER TABLE ai_assistant_cockpit_drafts ENABLE ROW LEVEL SECURITY;
            CREATE POLICY cockpit_drafts_tenant_isolation ON ai_assistant_cockpit_drafts
                USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS cockpit_drafts_tenant_isolation ON ai_assistant_cockpit_drafts;
            ALTER TABLE ai_assistant_cockpit_drafts DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
