# Generated by Django 6.0 on 2026-05-13 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0020_cockpit_draft_form"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AILearningSnapshot",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Entity type for this snapshot (e.g., purchase_order, supplier).", max_length=64
                    ),
                ),
                ("total_events", models.IntegerField(default=0)),
                ("positive_signals", models.IntegerField(default=0)),
                ("negative_signals", models.IntegerField(default=0)),
                (
                    "correction_rate",
                    models.FloatField(default=0.0, help_text="Percentage of events where user corrected AI output."),
                ),
                (
                    "avg_resolution_time_ms",
                    models.IntegerField(default=0, help_text="Average time users took to review/act on AI output."),
                ),
                (
                    "top_corrected_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {field, count, common_corrections} for most-corrected fields.",
                    ),
                ),
                (
                    "accuracy_trend",
                    models.FloatField(
                        default=0.0, help_text="Accuracy change compared to previous period (positive = improving)."
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Learning Snapshot",
                "verbose_name_plural": "AI Learning Snapshots",
                "db_table": "ai_assistant_learning_snapshots",
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="ExternalApprovalRequest",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("purchase_order", "Purchase Order"),
                            ("sales_order", "Sales Order"),
                            ("invoice", "Invoice"),
                            ("carrier_release", "Carrier Release"),
                            ("rfq", "RFQ"),
                            ("general", "General Communication"),
                        ],
                        help_text="Type of outbound communication.",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("edited_and_approved", "Edited & Approved"),
                            ("expired", "Expired"),
                            ("delegated", "Delegated"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("normal", "Normal"), ("high", "High"), ("urgent", "Urgent")],
                        default="normal",
                        max_length=16,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Human-readable summary of the outbound communication.", max_length=500),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("supplier", "Supplier"),
                            ("customer", "Customer"),
                            ("carrier", "Carrier"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "recipient_entity_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID of the recipient entity (supplier/customer/carrier).",
                        max_length=255,
                    ),
                ),
                ("recipient_name", models.CharField(blank=True, default="", max_length=255)),
                ("recipient_email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "content_preview",
                    models.TextField(blank=True, default="", help_text="Rendered preview of what will be sent."),
                ),
                (
                    "content_payload",
                    models.JSONField(blank=True, default=dict, help_text="Full payload for actual send."),
                ),
                (
                    "edited_content",
                    models.JSONField(
                        blank=True, help_text="Content after user edits (if edited before approval).", null=True
                    ),
                ),
                (
                    "source_entity_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Entity type that triggered this (po, so, invoice, etc.).",
                        max_length=64,
                    ),
                ),
                ("source_entity_id", models.CharField(blank=True, default="", max_length=255)),
                ("ai_generated", models.BooleanField(default=False, help_text="Whether this was drafted by AI.")),
                (
                    "ai_confidence",
                    models.FloatField(
                        blank=True, help_text="AI confidence score for the generated content.", null=True
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_notes", models.TextField(blank=True, default="")),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, help_text="Auto-expire stale requests (default 72h).", null=True),
                ),
            ],
            options={
                "verbose_name": "External Approval Request",
                "verbose_name_plural": "External Approval Requests",
                "db_table": "ai_assistant_external_approval_requests",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="UserAIPreferences",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "require_external_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Require manual approval before sending to external parties. DEFAULT ON.",
                    ),
                ),
                (
                    "approval_auto_approve_threshold",
                    models.FloatField(
                        default=0.99, help_text="AI confidence threshold for auto-approval (0.99 = nearly never auto)."
                    ),
                ),
                (
                    "show_ai_confidence_badges",
                    models.BooleanField(default=True, help_text="Show confidence badges on AI-filled fields."),
                ),
                (
                    "show_ai_suggestions",
                    models.BooleanField(default=True, help_text="Show AI suggestion chips on entity pages."),
                ),
                (
                    "feedback_detail_level",
                    models.CharField(
                        choices=[("minimal", "Minimal"), ("standard", "Standard"), ("detailed", "Detailed")],
                        default="standard",
                        max_length=16,
                    ),
                ),
                (
                    "notification_frequency",
                    models.CharField(
                        choices=[
                            ("realtime", "Real-time"),
                            ("hourly_digest", "Hourly Digest"),
                            ("daily_digest", "Daily Digest"),
                        ],
                        default="realtime",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "User AI Preferences",
                "verbose_name_plural": "User AI Preferences",
                "db_table": "ai_assistant_user_ai_preferences",
            },
        ),
        migrations.AddField(
            model_name="aifeedbacklog",
            name="action_taken_at",
            field=models.DateTimeField(blank=True, help_text="When the user took action on this item.", null=True),
        ),
        migrations.AddField(
            model_name="aifeedbacklog",
            name="fields_modified_by_user",
            field=models.JSONField(
                blank=True, default=list, help_text="List of field names the user modified after AI auto-fill."
            ),
        ),
        migrations.AddField(
            model_name="aifeedbacklog",
            name="implicit_signal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accepted_as_is", "Accepted As-Is"),
                    ("accepted_with_edits", "Accepted With Edits"),
                    ("dismissed_unopened", "Dismissed Unopened"),
                    ("dismissed_after_view", "Dismissed After View"),
                    ("field_correction", "Field Correction"),
                    ("suggestion_clicked", "Suggestion Clicked"),
                    ("suggestion_dismissed", "Suggestion Dismissed"),
                    ("search_navigate", "Search Navigate"),
                    ("undo_revert", "Undo/Revert"),
                ],
                default="",
                help_text="Type of implicit signal captured from user behavior.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="aifeedbacklog",
            name="review_duration_ms",
            field=models.IntegerField(
                blank=True, help_text="Milliseconds the user spent reviewing this item before acting.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aifeedbacklog",
            name="source_entity_id",
            field=models.CharField(
                blank=True, default="", help_text="ID of the entity related to this feedback.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="aifeedbacklog",
            name="source_entity_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Entity type related to this feedback (e.g., purchase_order, supplier).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="aifeedbacklog",
            name="source_surface",
            field=models.CharField(
                blank=True,
                choices=[
                    ("form", "Form"),
                    ("inbox", "Inbox"),
                    ("approval_queue", "Approval Queue"),
                    ("chat", "Chat"),
                    ("suggestion_chip", "Suggestion Chip"),
                    ("search", "Search"),
                    ("entity_page", "Entity Page"),
                    ("workflow", "Workflow"),
                    ("notification", "Notification"),
                ],
                default="",
                help_text="UI surface where this feedback originated.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="aifeedbacklog",
            name="suggestion_viewed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the user first viewed this AI suggestion.", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="aifeedbacklog",
            index=models.Index(fields=["tenant", "implicit_signal", "created_on"], name="ai_fb_implicit_idx"),
        ),
        migrations.AddIndex(
            model_name="aifeedbacklog",
            index=models.Index(fields=["tenant", "source_surface", "created_on"], name="ai_fb_surface_idx"),
        ),
        migrations.AddField(
            model_name="ailearningsnapshot",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="externalapprovalrequest",
            name="delegated_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delegated_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="externalapprovalrequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_approval_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="externalapprovalrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_approval_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="externalapprovalrequest",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="useraipreferences",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="useraipreferences",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="ai_preferences", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="ailearningsnapshot",
            index=models.Index(fields=["tenant", "entity_type", "period_end"], name="ai_snap_tenant_entity_idx"),
        ),
        migrations.AddIndex(
            model_name="ailearningsnapshot",
            index=models.Index(fields=["tenant", "period_end"], name="ai_snap_tenant_period_idx"),
        ),
        migrations.AddIndex(
            model_name="externalapprovalrequest",
            index=models.Index(fields=["tenant", "status", "created_on"], name="ext_appr_tenant_status_idx"),
        ),
        migrations.AddIndex(
            model_name="externalapprovalrequest",
            index=models.Index(fields=["tenant", "request_type", "status"], name="ext_appr_tenant_type_idx"),
        ),
        migrations.AddIndex(
            model_name="externalapprovalrequest",
            index=models.Index(fields=["tenant", "requested_by", "status"], name="ext_appr_tenant_user_idx"),
        ),
        migrations.AddIndex(
            model_name="externalapprovalrequest",
            index=models.Index(fields=["tenant", "expires_at"], name="ext_appr_tenant_expiry_idx"),
        ),
        migrations.AddIndex(
            model_name="useraipreferences",
            index=models.Index(fields=["tenant", "user"], name="ai_prefs_tenant_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="useraipreferences",
            constraint=models.UniqueConstraint(fields=("tenant", "user"), name="unique_user_ai_prefs_per_tenant"),
        ),
        # ── RLS policies for new tenant-aware tables ──────────────────
        migrations.RunSQL(
            sql="""
            -- RLS for ExternalApprovalRequest
            ALTER TABLE ai_assistant_external_approval_requests ENABLE ROW LEVEL SECURITY;
            CREATE POLICY ext_approval_tenant_isolation ON ai_assistant_external_approval_requests
                USING (tenant_id = current_setting('app.current_tenant')::uuid);

            -- RLS for UserAIPreferences
            ALTER TABLE ai_assistant_user_ai_preferences ENABLE ROW LEVEL SECURITY;
            CREATE POLICY user_ai_prefs_tenant_isolation ON ai_assistant_user_ai_preferences
                USING (tenant_id = current_setting('app.current_tenant')::uuid);

            -- RLS for AILearningSnapshot
            ALTER TABLE ai_assistant_learning_snapshots ENABLE ROW LEVEL SECURITY;
            CREATE POLICY learning_snapshot_tenant_isolation ON ai_assistant_learning_snapshots
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS ext_approval_tenant_isolation ON ai_assistant_external_approval_requests;
            ALTER TABLE ai_assistant_external_approval_requests DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS user_ai_prefs_tenant_isolation ON ai_assistant_user_ai_preferences;
            ALTER TABLE ai_assistant_user_ai_preferences DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS learning_snapshot_tenant_isolation ON ai_assistant_learning_snapshots;
            ALTER TABLE ai_assistant_learning_snapshots DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
