/**
 * WorkForm Execution API Service
 *
 * Tracks executions of apps.system.models.TenantWorkForm via
 * tenant_apps.workflows.models.TenantWorkFormExecution.
 */

import { businessApi } from './businessApi';

export type WorkFormExecutionStatus = 'pending' | 'in_progress' | 'completed' | 'failed' | 'cancelled';

export type WorkFormExecutionAuditEvent = {
  event?: string;
  node_id?: string;
  node_type?: string;
  routed_to?: string;
  ts?: string;
  [key: string]: unknown;
};

export interface WorkFormExecution {
  id: string;
  tenant: string;
  workform: string;
  workform_name: string;
  status: WorkFormExecutionStatus;
  initial_data: Record<string, unknown>;
  context_data: Record<string, unknown>;
  audit_trail: WorkFormExecutionAuditEvent[];
  /**
   * Derived per-node status map generated by the backend from the audit trail.
   * Keys are node IDs, values are statuses like "completed" / "failed" / "in_progress".
   */
  node_statuses?: Record<string, string>;
  /** Node label map derived from the WorkForm definition (node_id -> label). */
  node_labels?: Record<string, string>;
  /** Backend-derived "where am I" pointer for UI surfaces. */
  current_node_id?: string | null;
  current_node_type?: string | null;
  current_node_label?: string | null;
  last_event?: string | null;
  /** Compact list of errors recorded during execution (if any). */
  errors?: Array<{
    node_id?: string;
    node_type?: string;
    node_label?: string | null;
    error: string;
    routed_to?: string;
    ts?: string;
  }>;
  started_by?: string | null;
  started_by_name?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  error_message?: string;
  created_on: string;
  modified_on: string;
}

export interface WorkFormExecutionListResponse {
  count: number;
  next: string | null;
  previous: string | null;
  results: WorkFormExecution[];
}

export interface WorkFormExecutionAnalyticsSummary {
  total_runs: number;
  active_runs: number;
  completed_runs: number;
  failed_runs: number;
  suspended_runs: number;
  success_rate: number;
  avg_duration_ms: number | null;
}

export interface WorkFormExecutionAnalyticsNodeRow {
  workform_id: string;
  workform_name: string;
  node_id: string;
  node_type: string;
  node_label?: string | null;
  failure_count?: number;
  last_failed_at?: string | null;
  avg_duration_ms?: number | null;
  max_duration_ms?: number | null;
  sample_count?: number;
}

export interface WorkFormExecutionAnalyticsWorkformRow {
  workform_id: string;
  workform_name: string;
  total_runs: number;
  completed_runs: number;
  failed_runs: number;
  success_rate: number;
}

export interface WorkFormExecutionAnalyticsResponse {
  window_days: number;
  generated_at: string;
  summary: WorkFormExecutionAnalyticsSummary;
  status_counts: Record<string, number>;
  top_workforms: WorkFormExecutionAnalyticsWorkformRow[];
  top_failed_nodes: WorkFormExecutionAnalyticsNodeRow[];
  slowest_actions: WorkFormExecutionAnalyticsNodeRow[];
}

export type NodeActionType = 'approve' | 'reject';

export interface NodeActionPayload {
  node_id: string;
  action: NodeActionType;
  comment?: string;
}

export interface NodeActionResponse {
  success: boolean;
  execution_id: string;
  node_id: string;
  action: NodeActionType;
  new_status?: string;
  message?: string;
}

export class WorkFormExecutionService {
  private baseUrl = '/workflows/workform-executions/';

  async getExecutions(params?: {
    status?: string;
    search?: string;
    start_date?: string;
    end_date?: string;
    page?: number;
    page_size?: number;
    workform?: string;
    started_by?: string;
    entity_type?: string;
    entity_id?: string;
  }): Promise<WorkFormExecutionListResponse> {
    const response = await businessApi.get(this.baseUrl, { params });

    const results = Array.isArray(response.data?.results)
      ? response.data.results
      : Array.isArray(response.data)
        ? response.data
        : [];

    return {
      count: response.data?.count ?? results.length,
      next: response.data?.next ?? null,
      previous: response.data?.previous ?? null,
      results,
    };
  }

  async getExecution(id: string): Promise<WorkFormExecution> {
    const response = await businessApi.get(`${this.baseUrl}${id}/`);
    return response.data;
  }

  async getAnalytics(params?: { days?: number; limit?: number }): Promise<WorkFormExecutionAnalyticsResponse> {
    const response = await businessApi.get(`${this.baseUrl}analytics/`, { params });
    return response.data;
  }

  /** Submit approve/reject decision for a node within an execution. */
  async nodeAction(executionId: string, payload: NodeActionPayload): Promise<NodeActionResponse> {
    const response = await businessApi.post<NodeActionResponse>(
      `${this.baseUrl}${executionId}/node-action/`,
      payload,
    );
    return response.data;
  }
}

export const workformExecutionService = new WorkFormExecutionService();
