"""Deterministic normalized field mappings for Golden Schema ETL."""

from __future__ import annotations

from dataclasses import dataclass, field

from .contracts import CANONICAL_ALIAS_TARGETS, SourceShape


@dataclass(frozen=True)
class FieldMapping:
    """Map a normalized source field onto a destination model field."""

    source_field: str
    target_field: str
    required: bool = False
    notes: str = ""


@dataclass(frozen=True)
class EntityContract:
    """Normalized ETL contract for one entity surface."""

    entity: str
    model_label: str
    source_shape: str
    target_kind: str
    match_key_priority: tuple[tuple[str, ...], ...]
    field_mappings: tuple[FieldMapping, ...]
    canonical_targets: tuple[str, ...] = ()
    dependencies: tuple[str, ...] = ()
    relationship_fields: tuple[str, ...] = ()
    notes: tuple[str, ...] = field(default_factory=tuple)


ENTITY_CONTRACTS = {
    "products": EntityContract(
        entity="products",
        model_label="apps.system.models.product.Product",
        source_shape=SourceShape.MASTER_ROWS.value,
        target_kind="master_data",
        match_key_priority=(("product_code",),),
        field_mappings=(
            FieldMapping("product_code", "product_code", required=True),
            FieldMapping("name", "name", required=True),
            FieldMapping("description", "description"),
            FieldMapping("category", "category"),
            FieldMapping("protein_type", "protein_type"),
            FieldMapping("fresh_or_frozen", "fresh_or_frozen"),
            FieldMapping("package_type", "package_type"),
            FieldMapping("carton_type", "carton_type"),
            FieldMapping("unit_weight", "unit_weight"),
            FieldMapping("uom", "uom"),
            FieldMapping("pcs_per_carton", "pcs_per_carton"),
            FieldMapping("namp_code", "namp_code"),
            FieldMapping("usda_code", "usda_code"),
            FieldMapping("ub_code", "ub_code"),
            FieldMapping("edible_or_inedible", "edible_or_inedible"),
            FieldMapping("net_or_catch", "net_or_catch"),
            FieldMapping("tested_product", "tested_product"),
            FieldMapping("is_active", "is_active"),
        ),
        notes=(
            "Products are global system records, not tenant-scoped rows.",
            "GA-01.* importers must match existing products by product_code before any create path.",
        ),
    ),
    "plants": EntityContract(
        entity="plants",
        model_label="tenant_apps.plants.models.Plant",
        source_shape=SourceShape.MASTER_ROWS.value,
        target_kind="master_data",
        match_key_priority=(("plant_est_num",), ("supplier_source_key", "name")),
        field_mappings=(
            FieldMapping("supplier_source_key", "supplier", required=True, notes="Resolve within tenant."),
            FieldMapping("name", "name", required=True),
            FieldMapping("plant_est_num", "plant_est_num"),
            FieldMapping("plant_type", "plant_type"),
            FieldMapping("address", "address"),
            FieldMapping("city", "city"),
            FieldMapping("state", "state"),
            FieldMapping("zip_code", "zip_code"),
            FieldMapping("country", "country"),
            FieldMapping("booking_contact_email", "booking_contact_email"),
            FieldMapping("booking_contact_phone", "booking_contact_phone"),
            FieldMapping("capacity", "capacity"),
            FieldMapping("is_active", "is_active"),
        ),
        dependencies=("suppliers",),
        relationship_fields=("supplier_source_key",),
        notes=(
            "Plants remain a tenant-aware model even though transactional headers usually FK locations.",
        ),
    ),
    "locations": EntityContract(
        entity="locations",
        model_label="tenant_apps.locations.models.Location",
        source_shape=SourceShape.MASTER_ROWS.value,
        target_kind="master_data",
        match_key_priority=(("code",), ("plant_est_num",), ("name", "city", "state")),
        field_mappings=(
            FieldMapping("code", "code"),
            FieldMapping("name", "name", required=True),
            FieldMapping("location_type", "location_type"),
            FieldMapping("address", "address"),
            FieldMapping("city", "city"),
            FieldMapping("state", "state"),
            FieldMapping("zip_code", "zip_code"),
            FieldMapping("country", "country"),
            FieldMapping("phone", "phone"),
            FieldMapping("email", "email"),
            FieldMapping("contact_name", "contact_name"),
            FieldMapping("supplier_source_key", "supplier", notes="Resolve within tenant."),
            FieldMapping("customer_source_key", "customer", notes="Resolve within tenant."),
            FieldMapping("plant_est_num", "plant_est_num"),
            FieldMapping("is_active", "is_active"),
        ),
        relationship_fields=("supplier_source_key", "customer_source_key"),
        notes=(
            "Transactional headers use locations for plant, pickup, and delivery anchors.",
        ),
    ),
    "suppliers": EntityContract(
        entity="suppliers",
        model_label="tenant_apps.suppliers.models.Supplier",
        source_shape=SourceShape.MASTER_ROWS.value,
        target_kind="master_data",
        match_key_priority=(("name",), ("email",), ("phone",)),
        field_mappings=(
            FieldMapping("name", "name", required=True),
            FieldMapping("contact_person", "contact_person"),
            FieldMapping("email", "email"),
            FieldMapping("phone", "phone"),
            FieldMapping("street_address", "street_address"),
            FieldMapping("city", "city"),
            FieldMapping("state", "state"),
            FieldMapping("zip_code", "zip_code"),
            FieldMapping("country", "country"),
            FieldMapping("payment_terms", "payment_terms"),
            FieldMapping("credit_limit", "credit_limit"),
            FieldMapping("account_line_of_credit", "account_line_of_credit"),
            FieldMapping("shipping_offered", "shipping_offered"),
            FieldMapping("how_to_book_pickup", "how_to_book_pickup"),
            FieldMapping("offer_contracts", "offer_contracts"),
            FieldMapping("offers_export_documents", "offers_export_documents"),
            FieldMapping("plant_location_source_key", "plant", notes="Resolve locations.Location within tenant."),
        ),
        canonical_targets=CANONICAL_ALIAS_TARGETS["suppliers"],
        relationship_fields=("plant_location_source_key",),
    ),
    "customers": EntityContract(
        entity="customers",
        model_label="tenant_apps.customers.models.Customer",
        source_shape=SourceShape.MASTER_ROWS.value,
        target_kind="master_data",
        match_key_priority=(("name",), ("email",), ("phone",)),
        field_mappings=(
            FieldMapping("name", "name", required=True),
            FieldMapping("contact_person", "contact_person"),
            FieldMapping("email", "email"),
            FieldMapping("phone", "phone"),
            FieldMapping("street_address", "street_address"),
            FieldMapping("city", "city"),
            FieldMapping("state", "state"),
            FieldMapping("zip_code", "zip_code"),
            FieldMapping("country", "country"),
            FieldMapping("payment_terms", "payment_terms"),
            FieldMapping("credit_limit", "credit_limit"),
            FieldMapping("account_line_of_credit", "account_line_of_credit"),
            FieldMapping("industry", "industry"),
            FieldMapping("type_of_certificate", "type_of_certificate"),
            FieldMapping("will_pickup_load", "will_pickup_load"),
            FieldMapping("plant_location_source_key", "plant", notes="Resolve locations.Location within tenant."),
        ),
        canonical_targets=CANONICAL_ALIAS_TARGETS["customers"],
        relationship_fields=("plant_location_source_key",),
    ),
    "carriers": EntityContract(
        entity="carriers",
        model_label="tenant_apps.carriers.models.Carrier",
        source_shape=SourceShape.MASTER_ROWS.value,
        target_kind="master_data",
        match_key_priority=(("code",), ("mc_number",), ("dot_number",), ("name",)),
        field_mappings=(
            FieldMapping("code", "code", required=True),
            FieldMapping("name", "name", required=True),
            FieldMapping("carrier_type", "carrier_type"),
            FieldMapping("contact_person", "contact_person"),
            FieldMapping("phone", "phone"),
            FieldMapping("email", "email"),
            FieldMapping("address", "address"),
            FieldMapping("city", "city"),
            FieldMapping("state", "state"),
            FieldMapping("zip_code", "zip_code"),
            FieldMapping("country", "country"),
            FieldMapping("mc_number", "mc_number"),
            FieldMapping("dot_number", "dot_number"),
            FieldMapping("payment_terms", "payment_terms"),
            FieldMapping("credit_limit", "credit_limit"),
            FieldMapping("how_to_make_appointment", "how_to_make_appointment"),
            FieldMapping("my_customer_num_from_carrier", "my_customer_num_from_carrier"),
        ),
        canonical_targets=CANONICAL_ALIAS_TARGETS["carriers"],
    ),
    "contacts": EntityContract(
        entity="contacts",
        model_label="tenant_apps.contacts.models.Contact",
        source_shape=SourceShape.MASTER_ROWS.value,
        target_kind="master_data",
        match_key_priority=(
            ("email",),
            ("first_name", "last_name", "company"),
            ("first_name", "last_name", "phone"),
        ),
        field_mappings=(
            FieldMapping("first_name", "first_name", required=True),
            FieldMapping("last_name", "last_name", required=True),
            FieldMapping("email", "email"),
            FieldMapping("phone", "phone"),
            FieldMapping("phone_type", "phone_type"),
            FieldMapping("company", "company"),
            FieldMapping("title", "title"),
            FieldMapping("department", "department"),
            FieldMapping("notes", "notes"),
            FieldMapping("supplier_source_key", "supplier", notes="Resolve within tenant."),
            FieldMapping("customer_source_key", "customer", notes="Resolve within tenant."),
            FieldMapping("plant_source_key", "plant", notes="Resolve within tenant."),
            FieldMapping("location_source_key", "location", notes="Resolve within tenant."),
        ),
        relationship_fields=(
            "supplier_source_key",
            "customer_source_key",
            "plant_source_key",
            "location_source_key",
        ),
        notes=("Use department as the canonical operational role field; contact_type remains legacy.",),
    ),
    "purchase_orders": EntityContract(
        entity="purchase_orders",
        model_label="tenant_apps.purchase_orders.models.PurchaseOrder",
        source_shape=SourceShape.TRANSACTION_HEADERS.value,
        target_kind="transaction_header",
        match_key_priority=(("order_number",), ("our_purchase_order_number_to_supplier",)),
        field_mappings=(
            FieldMapping("order_number", "order_number", required=True),
            FieldMapping("supplier_source_key", "supplier", required=True, notes="Resolve within tenant."),
            FieldMapping("product_code", "product", notes="Resolve global system.Product by product_code."),
            FieldMapping("status", "status"),
            FieldMapping("payment_status", "payment_status"),
            FieldMapping("order_date", "order_date", required=True),
            FieldMapping("delivery_date", "delivery_date"),
            FieldMapping("total_amount", "total_amount"),
            FieldMapping("outstanding_amount", "outstanding_amount"),
            FieldMapping("our_purchase_order_number_to_supplier", "our_purchase_order_number_to_supplier"),
            FieldMapping("my_customer_number_from_supplier", "my_customer_number_from_supplier"),
            FieldMapping("supplier_confirmation_order_number", "supplier_confirmation_order_number"),
            FieldMapping("carrier_source_key", "carrier", notes="Resolve within tenant."),
            FieldMapping("carrier_release_number", "carrier_release_number"),
            FieldMapping("how_to_make_appointment", "how_to_make_appointment"),
            FieldMapping("billing_contact_name", "billing_contact_name"),
            FieldMapping("billing_contact_phone", "billing_contact_phone"),
            FieldMapping("billing_contact_email", "billing_contact_email"),
            FieldMapping("billing_address_street", "billing_address_street"),
            FieldMapping("billing_address_city", "billing_address_city"),
            FieldMapping("billing_address_state_zip", "billing_address_state_zip"),
            FieldMapping("shipping_contact_name", "shipping_contact_name"),
            FieldMapping("shipping_contact_phone", "shipping_contact_phone"),
            FieldMapping("shipping_contact_email", "shipping_contact_email"),
            FieldMapping("shipping_address_street", "shipping_address_street"),
            FieldMapping("shipping_address_city", "shipping_address_city"),
            FieldMapping("shipping_address_state_zip", "shipping_address_state_zip"),
            FieldMapping("notes", "notes"),
        ),
        canonical_targets=CANONICAL_ALIAS_TARGETS["purchase_orders"],
        dependencies=("suppliers", "carriers", "products"),
        relationship_fields=("supplier_source_key", "carrier_source_key", "product_code"),
        notes=("Do not rely on auto-generated order_number or save-time alias syncing during ETL.",),
    ),
    "sales_orders": EntityContract(
        entity="sales_orders",
        model_label="tenant_apps.sales_orders.models.SalesOrder",
        source_shape=SourceShape.TRANSACTION_HEADERS.value,
        target_kind="transaction_header",
        match_key_priority=(("our_sales_order_num",), ("our_sales_order_number_for_customer",)),
        field_mappings=(
            FieldMapping("our_sales_order_num", "our_sales_order_num", required=True),
            FieldMapping("our_sales_order_number_for_customer", "our_sales_order_number_for_customer"),
            FieldMapping("supplier_source_key", "supplier", required=True, notes="Resolve within tenant."),
            FieldMapping("customer_source_key", "customer", required=True, notes="Resolve within tenant."),
            FieldMapping("carrier_source_key", "carrier", notes="Resolve within tenant."),
            FieldMapping("product_code", "product", notes="Resolve global system.Product by product_code."),
            FieldMapping("plant_location_source_key", "plant", notes="Resolve locations.Location within tenant."),
            FieldMapping("pickup_location_source_key", "pick_up_location", notes="Resolve locations.Location within tenant."),
            FieldMapping("delivery_location_source_key", "delivery_location", notes="Resolve locations.Location within tenant."),
            FieldMapping("contact_source_key", "contact", notes="Resolve within tenant."),
            FieldMapping("delivery_po_number", "delivery_po_number"),
            FieldMapping("carrier_release_number", "carrier_release_number"),
            FieldMapping("how_to_make_appointment", "how_to_make_appointment"),
            FieldMapping("quantity", "quantity"),
            FieldMapping("total_weight", "total_weight"),
            FieldMapping("weight_unit", "weight_unit"),
            FieldMapping("status", "status"),
            FieldMapping("payment_status", "payment_status"),
            FieldMapping("outstanding_amount", "outstanding_amount"),
            FieldMapping("total_amount", "total_amount"),
            FieldMapping("notes", "notes"),
            FieldMapping("billing_contact_name", "billing_contact_name"),
            FieldMapping("billing_contact_phone", "billing_contact_phone"),
            FieldMapping("billing_contact_email", "billing_contact_email"),
            FieldMapping("shipping_contact_name", "shipping_contact_name"),
            FieldMapping("shipping_contact_phone", "shipping_contact_phone"),
            FieldMapping("shipping_contact_email", "shipping_contact_email"),
        ),
        canonical_targets=CANONICAL_ALIAS_TARGETS["sales_orders"],
        dependencies=("suppliers", "customers", "carriers", "contacts", "locations", "products"),
        relationship_fields=(
            "supplier_source_key",
            "customer_source_key",
            "carrier_source_key",
            "contact_source_key",
            "plant_location_source_key",
            "pickup_location_source_key",
            "delivery_location_source_key",
            "product_code",
        ),
    ),
    "invoices": EntityContract(
        entity="invoices",
        model_label="tenant_apps.invoices.models.Invoice",
        source_shape=SourceShape.TRANSACTION_HEADERS.value,
        target_kind="transaction_header",
        match_key_priority=(("invoice_number",),),
        field_mappings=(
            FieldMapping("invoice_number", "invoice_number", required=True),
            FieldMapping("customer_source_key", "customer", required=True, notes="Resolve within tenant."),
            FieldMapping("sales_order_source_key", "sales_order", notes="Resolve within tenant."),
            FieldMapping("product_code", "product", notes="Resolve global system.Product by product_code."),
            FieldMapping("due_date", "due_date"),
            FieldMapping("our_sales_order_number_for_customer", "our_sales_order_number_for_customer"),
            FieldMapping("delivery_po_number", "delivery_po_number"),
            FieldMapping("payment_terms", "payment_terms"),
            FieldMapping("carrier_release_number", "carrier_release_number"),
            FieldMapping("how_to_make_appointment", "how_to_make_appointment"),
            FieldMapping("type_of_protein", "type_of_protein"),
            FieldMapping("description_of_product_item", "description_of_product_item"),
            FieldMapping("quantity", "quantity"),
            FieldMapping("total_weight", "total_weight"),
            FieldMapping("weight_unit", "weight_unit"),
            FieldMapping("edible_or_inedible", "edible_or_inedible"),
            FieldMapping("tested_product", "tested_product"),
            FieldMapping("unit_price", "unit_price"),
            FieldMapping("total_amount", "total_amount"),
            FieldMapping("tax_amount", "tax_amount"),
            FieldMapping("status", "status"),
            FieldMapping("payment_status", "payment_status"),
            FieldMapping("outstanding_amount", "outstanding_amount"),
            FieldMapping("accounting_payable_contact_name", "accounting_payable_contact_name"),
            FieldMapping("accounting_payable_contact_phone", "accounting_payable_contact_phone"),
            FieldMapping("accounting_payable_contact_email", "accounting_payable_contact_email"),
            FieldMapping("billing_contact_name", "billing_contact_name"),
            FieldMapping("billing_contact_phone", "billing_contact_phone"),
            FieldMapping("billing_contact_email", "billing_contact_email"),
            FieldMapping("shipping_contact_name", "shipping_contact_name"),
            FieldMapping("shipping_contact_phone", "shipping_contact_phone"),
            FieldMapping("shipping_contact_email", "shipping_contact_email"),
        ),
        canonical_targets=CANONICAL_ALIAS_TARGETS["invoices"],
        dependencies=("customers", "sales_orders", "products"),
        relationship_fields=("customer_source_key", "sales_order_source_key", "product_code"),
    ),
    "carrier_pos": EntityContract(
        entity="carrier_pos",
        model_label="tenant_apps.purchase_orders.models.CarrierPurchaseOrder",
        source_shape=SourceShape.TRANSACTION_HEADERS.value,
        target_kind="transaction_header",
        match_key_priority=(("our_carrier_po_num",),),
        field_mappings=(
            FieldMapping("our_carrier_po_num", "our_carrier_po_num", required=True),
            FieldMapping("carrier_source_key", "carrier", required=True, notes="Resolve within tenant."),
            FieldMapping("supplier_source_key", "supplier", required=True, notes="Resolve within tenant."),
            FieldMapping("plant_location_source_key", "plant", notes="Resolve locations.Location within tenant."),
            FieldMapping("pickup_location_source_key", "pick_up_location", notes="Resolve locations.Location within tenant."),
            FieldMapping("delivery_location_source_key", "delivery_location", notes="Resolve locations.Location within tenant."),
            FieldMapping("product_code", "product", notes="Resolve global system.Product by product_code."),
            FieldMapping("purchase_order_source_key", "linked_order", notes="Resolve purchase order within tenant."),
            FieldMapping("sales_order_source_key", "sales_order", notes="Resolve sales order within tenant."),
            FieldMapping("carrier_name", "carrier_name"),
            FieldMapping("payment_terms", "payment_terms"),
            FieldMapping("credit_limits", "credit_limits"),
            FieldMapping("carrier_release_number", "carrier_release_number"),
            FieldMapping("how_to_make_appointment", "how_to_make_appointment"),
            FieldMapping("type_of_protein", "type_of_protein"),
            FieldMapping("fresh_or_frozen", "fresh_or_frozen"),
            FieldMapping("package_type", "package_type"),
            FieldMapping("net_or_catch", "net_or_catch"),
            FieldMapping("edible_or_inedible", "edible_or_inedible"),
            FieldMapping("total_weight", "total_weight"),
            FieldMapping("weight_unit", "weight_unit"),
            FieldMapping("quantity", "quantity"),
            FieldMapping("departments_of_carrier", "departments_of_carrier"),
        ),
        canonical_targets=CANONICAL_ALIAS_TARGETS["carrier_pos"],
        dependencies=("carriers", "suppliers", "locations", "purchase_orders", "sales_orders", "products"),
        relationship_fields=(
            "carrier_source_key",
            "supplier_source_key",
            "plant_location_source_key",
            "pickup_location_source_key",
            "delivery_location_source_key",
            "purchase_order_source_key",
            "sales_order_source_key",
            "product_code",
        ),
        notes=("Use the existing CarrierPurchaseOrder freight header; do not introduce a new freight model.",),
    ),
    "purchase_order_items": EntityContract(
        entity="purchase_order_items",
        model_label="tenant_apps.purchase_orders.models.PurchaseOrderItem",
        source_shape=SourceShape.TRANSACTION_LINE_ITEMS.value,
        target_kind="transaction_line_item",
        match_key_priority=(("document_number", "line_number"),),
        field_mappings=(
            FieldMapping("document_number", "purchase_order", required=True, notes="Resolve purchase_orders.order_number within tenant."),
            FieldMapping("line_number", "line_number", required=True),
            FieldMapping("product_code", "product_description", required=True, notes="Resolve global system.Product by product_code."),
            FieldMapping("protein_type", "protein_type"),
            FieldMapping("fresh_or_frozen", "fresh_or_frozen"),
            FieldMapping("package_type", "package_type"),
            FieldMapping("quantity", "quantity"),
            FieldMapping("uom", "uom"),
            FieldMapping("net_or_catch", "net_or_catch"),
            FieldMapping("edible_or_inedible", "edible_or_inedible"),
            FieldMapping("tested_product", "tested_product"),
            FieldMapping("total_net_weight", "total_net_weight"),
            FieldMapping("notes", "notes"),
        ),
        dependencies=("purchase_orders", "products"),
        relationship_fields=("document_number", "product_code"),
    ),
    "sales_order_items": EntityContract(
        entity="sales_order_items",
        model_label="tenant_apps.sales_orders.models.SalesOrderItem",
        source_shape=SourceShape.TRANSACTION_LINE_ITEMS.value,
        target_kind="transaction_line_item",
        match_key_priority=(("document_number", "line_number"),),
        field_mappings=(
            FieldMapping("document_number", "sales_order", required=True, notes="Resolve sales_orders.our_sales_order_num within tenant."),
            FieldMapping("line_number", "line_number", required=True),
            FieldMapping("product_code", "product_description", required=True, notes="Resolve global system.Product by product_code."),
            FieldMapping("protein_type", "protein_type"),
            FieldMapping("fresh_or_frozen", "fresh_or_frozen"),
            FieldMapping("package_type", "package_type"),
            FieldMapping("quantity", "quantity"),
            FieldMapping("uom", "uom"),
            FieldMapping("net_or_catch", "net_or_catch"),
            FieldMapping("edible_or_inedible", "edible_or_inedible"),
            FieldMapping("tested_product", "tested_product"),
            FieldMapping("total_net_weight", "total_net_weight"),
            FieldMapping("notes", "notes"),
        ),
        dependencies=("sales_orders", "products"),
        relationship_fields=("document_number", "product_code"),
    ),
    "invoice_items": EntityContract(
        entity="invoice_items",
        model_label="tenant_apps.invoices.models.InvoiceItem",
        source_shape=SourceShape.TRANSACTION_LINE_ITEMS.value,
        target_kind="transaction_line_item",
        match_key_priority=(("document_number", "line_number"),),
        field_mappings=(
            FieldMapping("document_number", "invoice", required=True, notes="Resolve invoices.invoice_number within tenant."),
            FieldMapping("line_number", "line_number", required=True),
            FieldMapping("product_code", "product_description", required=True, notes="Resolve global system.Product by product_code."),
            FieldMapping("protein_type", "protein_type"),
            FieldMapping("fresh_or_frozen", "fresh_or_frozen"),
            FieldMapping("package_type", "package_type"),
            FieldMapping("quantity", "quantity"),
            FieldMapping("uom", "uom"),
            FieldMapping("net_or_catch", "net_or_catch"),
            FieldMapping("edible_or_inedible", "edible_or_inedible"),
            FieldMapping("tested_product", "tested_product"),
            FieldMapping("total_net_weight", "total_net_weight"),
            FieldMapping("unit_price", "unit_price"),
            FieldMapping("line_total", "line_total"),
        ),
        dependencies=("invoices", "products"),
        relationship_fields=("document_number", "product_code"),
    ),
    "carrier_po_items": EntityContract(
        entity="carrier_po_items",
        model_label="tenant_apps.purchase_orders.models.CarrierPOItem",
        source_shape=SourceShape.TRANSACTION_LINE_ITEMS.value,
        target_kind="transaction_line_item",
        match_key_priority=(("document_number", "line_number"),),
        field_mappings=(
            FieldMapping("document_number", "carrier_purchase_order", required=True, notes="Resolve carrier_pos.our_carrier_po_num within tenant."),
            FieldMapping("line_number", "line_number", required=True),
            FieldMapping("product_code", "product_description", required=True, notes="Resolve global system.Product by product_code."),
            FieldMapping("protein_type", "protein_type"),
            FieldMapping("fresh_or_frozen", "fresh_or_frozen"),
            FieldMapping("package_type", "package_type"),
            FieldMapping("quantity", "quantity"),
            FieldMapping("uom", "uom"),
            FieldMapping("net_or_catch", "net_or_catch"),
            FieldMapping("edible_or_inedible", "edible_or_inedible"),
            FieldMapping("tested_product", "tested_product"),
            FieldMapping("total_net_weight", "total_net_weight"),
            FieldMapping("notes", "notes"),
        ),
        dependencies=("carrier_pos", "products"),
        relationship_fields=("document_number", "product_code"),
    ),
}
