# Generated by Django 6.0 on 2025-12-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("carriers", "0001_initial"),
        ("contacts", "0001_initial"),
        ("customers", "0001_initial"),
        ("plants", "0001_initial"),
        ("products", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "our_sales_order_num",
                    models.CharField(help_text="Our sales order number", max_length=100, unique=True),
                ),
                (
                    "date_time_stamp",
                    models.DateTimeField(auto_now_add=True, help_text="Date and time when SO was created"),
                ),
                (
                    "pick_up_date",
                    models.DateField(blank=True, help_text="Scheduled pick up date", null=True),
                ),
                (
                    "delivery_date",
                    models.DateField(blank=True, help_text="Scheduled delivery date", null=True),
                ),
                (
                    "delivery_po_num",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Delivery PO number",
                        max_length=100,
                    ),
                ),
                (
                    "carrier_release_num",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Carrier release number",
                        max_length=100,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(blank=True, help_text="Quantity of items", null=True),
                ),
                (
                    "total_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total weight",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("LBS", "LBS"), ("KG", "KG")],
                        default="LBS",
                        help_text="Unit of weight (LBS or KG)",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the sales order",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total order amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", help_text="Additional notes"),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Carrier for this sales order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carriers.carrier",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary contact for this order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.contact",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer for this sales order",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Plant/facility for this order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plants.plant",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product being sold",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Supplier for this sales order",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Order",
                "verbose_name_plural": "Sales Orders",
                "ordering": ["-date_time_stamp", "-created_on"],
            },
        ),
    ]
