# Generated by Django 6.0 on 2026-01-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Idempotent index creation for tenant-related fields.

    Uses SeparateDatabaseAndState with IF NOT EXISTS to safely handle
    environments where indexes may already exist from earlier migrations.
    """

    dependencies = [
        ("carriers", "0003_add_logistics_indexes"),
        ("contacts", "0002_contact_tenant_and_more"),
        ("customers", "0003_customer_contact_title_alter_customer_industry"),
        ("plants", "0004_metadata_lockdown"),
        ("products", "0004_state_sync_tenant"),
        ("sales_orders", "0004_state_sync_tenant"),
        (
            "suppliers",
            "0003_rename_suppliers_s_tenant__idx_suppliers_s_tenant__566edc_idx",
        ),
        ("tenants", "0006_metadata_lockdown"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="salesorder",
                    index=models.Index(
                        fields=["tenant", "our_sales_order_num"],
                        name="sales_order_tenant__027d51_idx",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE INDEX IF NOT EXISTS sales_order_tenant__027d51_idx
                        ON sales_orders_salesorder (tenant_id, our_sales_order_num);
                    """,
                    reverse_sql="DROP INDEX IF EXISTS sales_order_tenant__027d51_idx;",
                ),
            ],
        ),
    ]
