# Generated by Django 6.0 on 2026-01-07 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_enable_rls_locations"),
        ("sales_orders", "0005_metadata_lockdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="carrier_release_format",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Supplier Confirmation Order Number",
                        "Supplier Confirmation Order Number",
                    ),
                    ("Carrier Release Number", "Carrier Release Number"),
                    ("Both", "Both"),
                ],
                default="",
                help_text="Carrier release format",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="delivery_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Delivery location for this sales order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_sales_orders",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="pick_up_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Pick up location for this sales order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickup_sales_orders",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="plant_est_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Plant establishment number",
                max_length=50,
            ),
        ),
    ]
