# Generated by Django 6.0 on 2026-01-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carriers", "0004_carrier_departments_array_and_more"),
        ("contacts", "0002_contact_tenant_and_more"),
        ("customers", "0005_customer_industry_array_and_more"),
        ("locations", "0002_enable_rls_locations"),
        ("plants", "0004_metadata_lockdown"),
        ("products", "0004_state_sync_tenant"),
        ("sales_orders", "0007_salesorder_outstanding_amount_and_more"),
        ("suppliers", "0005_supplier_departments_array"),
        ("tenants", "0006_metadata_lockdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="our_sales_order_num",
            field=models.CharField(help_text="Our sales order number (unique per tenant)", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="salesorder",
            constraint=models.UniqueConstraint(
                fields=("tenant", "our_sales_order_num"),
                name="unique_tenant_sales_order_num",
            ),
        ),
    ]
