# Generated by Django 6.0 on 2026-02-02 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0004_add_plant_fields"),
        ("sales_orders", "0009_salesorder_custom_data_alter_salesorder_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="Plant/facility for this order (location with plant_* type)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plant_sales_orders",
                to="locations.location",
            ),
        ),
    ]
