# Generated by Django 6.0 on 2026-03-18
# Upgrade RLS policy for SalesOrder model to modern standard (app.current_tenant)

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("sales_orders", "0012_alter_salesorder_product"),
    ]

    operations = [
        RunSQL(
            sql="""
            -- Enable RLS on sales_orders_salesorder (idempotent)
            ALTER TABLE sales_orders_salesorder ENABLE ROW LEVEL SECURITY;

            -- Drop any existing policies:
            -- 'sales_order_tenant_isolation' is the original name from tenants/0002_enable_rls_policies.py
            -- 'salesorder_tenant_isolation' and 'salesorder_tenant_insert' are the target standardised names.
            -- Dropping all variants ensures idempotent upgrade across environments.
            DROP POLICY IF EXISTS sales_order_tenant_isolation ON sales_orders_salesorder;
            DROP POLICY IF EXISTS salesorder_tenant_isolation ON sales_orders_salesorder;
            DROP POLICY IF EXISTS salesorder_tenant_insert ON sales_orders_salesorder;

            -- Create tenant isolation policy for SELECT/UPDATE/DELETE
            CREATE POLICY salesorder_tenant_isolation ON sales_orders_salesorder
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- Create tenant isolation policy for INSERT
            CREATE POLICY salesorder_tenant_insert ON sales_orders_salesorder
                FOR INSERT
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS salesorder_tenant_insert ON sales_orders_salesorder;
            DROP POLICY IF EXISTS salesorder_tenant_isolation ON sales_orders_salesorder;
            ALTER TABLE sales_orders_salesorder DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
