# Generated by Django 6.0 on 2026-03-22
# Ensure sales_orders product-FK migration chain runs before products deletes legacy Product.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales_orders", "0013_add_rls_policies_batch"),
    ]

    # NOTE:
    # Avoid `run_before` here. `products.0008` may already be applied in long-lived environments,
    # and adding ordering edges can cause InconsistentMigrationHistory during deploy.

    operations = []
