# Generated by Django 6.0 on 2026-03-22
# Ensure sales_orders product-FK migration chain runs before products deletes legacy Product.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales_orders", "0013_add_rls_policies_batch"),
    ]

    run_before = [
        ("products", "0008_masterproduct_delete_product_and_more"),
    ]

    operations = []
