# Generated by Django 6.0 on 2026-03-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_orders", "0014_ordering_guard_run_before_products_0008"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
