# Generated by Django 6.0 on 2026-04-30 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_orders", "0015_salesorder_deleted_at_salesorder_is_deleted"),
        ("system", "0015_enable_rls_tenant_forms_workforms"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="billing_address_city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="billing_address_state_zip",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="billing_address_street",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="billing_building_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="billing_contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="billing_contact_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="billing_contact_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="billing_contact_title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="carrier_release_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="delivery_po_number",
            field=models.CharField(blank=True, default="", help_text="Canonical delivery PO number.", max_length=100),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="how_to_make_appointment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Email", "Email"),
                    ("Phone", "Phone"),
                    ("Website", "Website"),
                    ("Fax", "Fax"),
                    ("First Come First Serve", "First Come First Serve"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="our_sales_order_number_for_customer",
            field=models.CharField(
                blank=True, default="", help_text="Canonical sales order number shown to the customer.", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_address_city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_address_state_zip",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_address_street",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_building_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_contact_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_contact_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_contact_title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="carrier_release_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Supplier Confirmation Order Number", "Supplier Confirmation Order Number"),
                    ("Carrier Release Number", "Carrier Release Number"),
                    ("Both", "Both"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="pick_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SalesOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "protein_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Beef", "Beef"),
                            ("Chicken", "Chicken"),
                            ("Duck", "Duck"),
                            ("Pork", "Pork"),
                            ("Lamb", "Lamb"),
                            ("Turkey", "Turkey"),
                            ("Fish", "Fish"),
                            ("Horse", "Horse"),
                            ("Other", "Other"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                (
                    "fresh_or_frozen",
                    models.CharField(
                        blank=True, choices=[("Fresh", "Fresh"), ("Frozen", "Frozen")], default="", max_length=20
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Boxed wax lined", "Boxed wax lined"),
                            ("Boxed CO2", "Boxed CO2"),
                            ("Combo bins", "Combo bins"),
                            ("Totes", "Totes"),
                            ("Bags", "Bags"),
                            ("Bulk", "Bulk"),
                            ("Poly-Multiple", "Poly-Multiple"),
                            ("Nude", "Nude"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("uom", models.CharField(choices=[("LBS", "LBS"), ("KG", "KG")], default="LBS", max_length=10)),
                (
                    "net_or_catch",
                    models.CharField(
                        blank=True, choices=[("Net", "Net"), ("Catch", "Catch")], default="", max_length=20
                    ),
                ),
                (
                    "edible_or_inedible",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Edible", "Edible"),
                            ("Inedible", "Inedible"),
                            ("Edible & Inedible", "Edible & Inedible"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("tested_product", models.BooleanField(default=False)),
                ("total_net_weight", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("line_number", models.PositiveIntegerField(default=1)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "product_description",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_product_descriptions",
                        to="system.product",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="sales_orders.salesorder"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["sales_order_id", "line_number", "created_on"],
                "indexes": [models.Index(fields=["tenant", "sales_order"], name="sales_order_tenant__6621df_idx")],
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE sales_orders_salesorderitem ENABLE ROW LEVEL SECURITY;
            ALTER TABLE sales_orders_salesorderitem FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS salesorderitem_tenant_isolation ON sales_orders_salesorderitem;
            DROP POLICY IF EXISTS salesorderitem_tenant_insert ON sales_orders_salesorderitem;
            CREATE POLICY salesorderitem_tenant_isolation ON sales_orders_salesorderitem
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            CREATE POLICY salesorderitem_tenant_insert ON sales_orders_salesorderitem
                FOR INSERT
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS salesorderitem_tenant_insert ON sales_orders_salesorderitem;
            DROP POLICY IF EXISTS salesorderitem_tenant_isolation ON sales_orders_salesorderitem;
            ALTER TABLE sales_orders_salesorderitem DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
