# Generated by Django 6.0 on 2026-04-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_orders", "0016_golden_schema_refactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("confirmed", "Confirmed"),
                    ("sent", "Sent"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("invoiced", "Invoiced"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Current status of the sales order",
                max_length=20,
            ),
        ),
    ]
