# Generated by Django 6.0 on 2026-05-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_orders", "0019_trade_session_lineage"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="description_of_product_item",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="edible_or_inedible",
            field=models.CharField(
                blank=True,
                choices=[("Edible", "Edible"), ("Inedible", "Inedible"), ("Edible & Inedible", "Edible & Inedible")],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="fresh_or_frozen",
            field=models.CharField(
                blank=True, choices=[("Fresh", "Fresh"), ("Frozen", "Frozen")], default="", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="logistics_scenario",
            field=models.CharField(
                choices=[
                    ("customer_pickup", "Customer - Picking Up"),
                    ("supplier_delivery", "Supplier - Delivering"),
                    ("we_pickup", "Tenant - Pickup (We Handle Logistics)"),
                ],
                default="supplier_delivery",
                help_text="Logistics scenario for this sales order",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="net_or_catch",
            field=models.CharField(blank=True, choices=[("Net", "Net"), ("Catch", "Catch")], default="", max_length=20),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="package_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Boxed wax lined", "Boxed wax lined"),
                    ("Boxed Poly", "Boxed Poly"),
                    ("Combos", "Combos"),
                    ("Nude Block", "Nude Block"),
                    ("Boxed COV", "Boxed COV"),
                    ("Boxed CO2", "Boxed CO2"),
                    ("Combo bins", "Combo bins"),
                    ("Totes", "Totes"),
                    ("Bags", "Bags"),
                    ("Bulk", "Bulk"),
                    ("Poly-Multiple", "Poly-Multiple"),
                    ("Nude", "Nude"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="receiving_contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="receiving_contact_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="receiving_contact_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="receiving_contact_title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="tested_product",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="total_net_weight",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="type_of_protein",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beef", "Beef"),
                    ("Chicken", "Chicken"),
                    ("Fowl", "Fowl"),
                    ("Turkey", "Turkey"),
                    ("Lamb", "Lamb"),
                    ("Veal", "Veal"),
                    ("Seafood", "Seafood"),
                    ("Venison", "Venison"),
                    ("Bison", "Bison"),
                    ("Duck", "Duck"),
                    ("Rabbit", "Rabbit"),
                    ("Goat", "Goat"),
                    ("Mutton", "Mutton"),
                    ("Pork", "Pork"),
                    ("Fish", "Fish"),
                    ("Horse", "Horse"),
                    ("Other", "Other"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="uom",
            field=models.CharField(choices=[("LBS", "LBS"), ("KG", "KG")], default="LBS", max_length=10),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="how_to_make_appointment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Email", "Email"),
                    ("Phone", "Phone"),
                    ("Website", "Website"),
                    ("FCFS", "FCFS"),
                    ("Fax", "Fax"),
                    ("First Come First Serve", "First Come First Serve"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="package_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Boxed wax lined", "Boxed wax lined"),
                    ("Boxed Poly", "Boxed Poly"),
                    ("Combos", "Combos"),
                    ("Nude Block", "Nude Block"),
                    ("Boxed COV", "Boxed COV"),
                    ("Boxed CO2", "Boxed CO2"),
                    ("Combo bins", "Combo bins"),
                    ("Totes", "Totes"),
                    ("Bags", "Bags"),
                    ("Bulk", "Bulk"),
                    ("Poly-Multiple", "Poly-Multiple"),
                    ("Nude", "Nude"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="protein_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beef", "Beef"),
                    ("Chicken", "Chicken"),
                    ("Fowl", "Fowl"),
                    ("Turkey", "Turkey"),
                    ("Lamb", "Lamb"),
                    ("Veal", "Veal"),
                    ("Seafood", "Seafood"),
                    ("Venison", "Venison"),
                    ("Bison", "Bison"),
                    ("Duck", "Duck"),
                    ("Rabbit", "Rabbit"),
                    ("Goat", "Goat"),
                    ("Mutton", "Mutton"),
                    ("Pork", "Pork"),
                    ("Fish", "Fish"),
                    ("Horse", "Horse"),
                    ("Other", "Other"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
