# Generated by Django 6.0 on 2025-12-06 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "plant_est_num",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Plant establishment number",
                        max_length=50,
                    ),
                ),
                (
                    "plant_type",
                    models.CharField(
                        choices=[
                            ("processing", "Processing Plant"),
                            ("distribution", "Distribution Center"),
                            ("warehouse", "Warehouse"),
                            ("retail", "Retail Location"),
                            ("other", "Other"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(default="")),
                ("city", models.CharField(default="", max_length=100)),
                ("state", models.CharField(default="", max_length=100)),
                ("zip_code", models.CharField(default="", max_length=20)),
                ("country", models.CharField(default="USA", max_length=100)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("manager", models.CharField(blank=True, default="", max_length=100)),
                (
                    "capacity",
                    models.PositiveIntegerField(blank=True, help_text="Capacity in units", null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant",
                "verbose_name_plural": "Plants",
                "ordering": ["name"],
            },
        ),
    ]
