# Generated by Django 6.0 on 2026-01-04 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Idempotent index creation for tenant-related fields.

    Uses SeparateDatabaseAndState with IF NOT EXISTS to safely handle
    environments where indexes may already exist from earlier migrations.
    """

    dependencies = [
        ("plants", "0003_state_sync_tenant"),
        ("tenants", "0006_metadata_lockdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="plant",
                    index=models.Index(fields=["tenant", "code"], name="plants_plan_tenant__9efb37_idx"),
                ),
                migrations.AddIndex(
                    model_name="plant",
                    index=models.Index(fields=["tenant", "name"], name="plants_plan_tenant__00c5a7_idx"),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE INDEX IF NOT EXISTS plants_plan_tenant__9efb37_idx
                        ON plants_plant (tenant_id, code);
                    """,
                    reverse_sql="DROP INDEX IF EXISTS plants_plan_tenant__9efb37_idx;",
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE INDEX IF NOT EXISTS plants_plan_tenant__00c5a7_idx
                        ON plants_plant (tenant_id, name);
                    """,
                    reverse_sql="DROP INDEX IF EXISTS plants_plan_tenant__00c5a7_idx;",
                ),
            ],
        ),
    ]
