# Generated by Django 6.0 on 2026-03-15 18:21

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.special import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0007_plant_created_on_plant_custom_data_plant_modified_on_and_more"),
        ("system", "0010_product_is_system_tenantproductpreference_is_custom"),
        ("tenants", "0010_add_tenant_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantAssociatedProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associated_product_links",
                        to="plants.plant",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant_affinity_links",
                        to="system.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant Known Product",
                "verbose_name_plural": "Plant Known Products",
            },
        ),
        migrations.AddField(
            model_name="plant",
            name="associated_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products commonly sold/produced by this plant",
                related_name="sold_by_plants",
                through="plants.PlantAssociatedProduct",
                to="system.product",
                verbose_name="Known Products Sold",
            ),
        ),
        migrations.AddIndex(
            model_name="plantassociatedproduct",
            index=models.Index(fields=["tenant", "plant"], name="plants_plan_tenant__c28da7_idx"),
        ),
        migrations.AddIndex(
            model_name="plantassociatedproduct",
            index=models.Index(fields=["tenant", "product"], name="plants_plan_tenant__41b9e8_idx"),
        ),
        migrations.AddConstraint(
            model_name="plantassociatedproduct",
            constraint=models.UniqueConstraint(
                fields=("tenant", "plant", "product"), name="unique_plant_product_affinity_per_tenant"
            ),
        ),
        RunSQL(
            sql="""
            ALTER TABLE plants_plantassociatedproduct ENABLE ROW LEVEL SECURITY;
            ALTER TABLE plants_plantassociatedproduct FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS plantassociatedproduct_tenant_isolation ON plants_plantassociatedproduct;
            CREATE POLICY plantassociatedproduct_tenant_isolation ON plants_plantassociatedproduct
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS plantassociatedproduct_tenant_isolation ON plants_plantassociatedproduct;
            ALTER TABLE plants_plantassociatedproduct NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE plants_plantassociatedproduct DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
