# Generated by Django 6.0 on 2026-03-18
# Upgrade RLS policy for Plant model to modern standard (app.current_tenant)

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0008_plantassociatedproduct_plant_associated_products_and_more"),
    ]

    operations = [
        RunSQL(
            sql="""
            -- Enable RLS on plants_plant (idempotent)
            ALTER TABLE plants_plant ENABLE ROW LEVEL SECURITY;

            -- Drop any existing policies (upgrade from legacy app.current_tenant_id pattern)
            DROP POLICY IF EXISTS plant_tenant_isolation ON plants_plant;
            DROP POLICY IF EXISTS plants_plant_tenant_isolation ON plants_plant;
            DROP POLICY IF EXISTS plant_tenant_insert ON plants_plant;

            -- Create tenant isolation policy for SELECT/UPDATE/DELETE
            CREATE POLICY plant_tenant_isolation ON plants_plant
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- Create tenant isolation policy for INSERT
            CREATE POLICY plant_tenant_insert ON plants_plant
                FOR INSERT
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS plant_tenant_insert ON plants_plant;
            DROP POLICY IF EXISTS plant_tenant_isolation ON plants_plant;
            ALTER TABLE plants_plant DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
