# Generated by Django 6.0 on 2026-03-20 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0009_add_rls_policies_batch"),
        ("products", "0008_masterproduct_delete_product_and_more"),
        ("system", "0011_tenantform_is_workform_tenantform_parent_workform"),
        ("tenants", "0010_add_tenant_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="associated_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Legacy system.Product associations (deprecated).",
                related_name="sold_by_plants",
                through="plants.PlantAssociatedProduct",
                to="system.product",
                verbose_name="Known Products Sold",
            ),
        ),
        migrations.CreateModel(
            name="PlantAssociatedMasterProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "master_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant_affinity_links",
                        to="products.masterproduct",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associated_master_product_links",
                        to="plants.plant",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant Known Master Product",
                "verbose_name_plural": "Plant Known Master Products",
            },
        ),
        migrations.AddField(
            model_name="plant",
            name="associated_master_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Master products commonly sold/produced by this plant.",
                related_name="known_by_plants",
                through="plants.PlantAssociatedMasterProduct",
                to="products.masterproduct",
                verbose_name="Known Master Products",
            ),
        ),
        migrations.AddIndex(
            model_name="plantassociatedmasterproduct",
            index=models.Index(fields=["tenant", "plant"], name="plants_plan_tenant__bc6892_idx"),
        ),
        migrations.AddIndex(
            model_name="plantassociatedmasterproduct",
            index=models.Index(fields=["tenant", "master_product"], name="plants_plan_tenant__0cb56c_idx"),
        ),
        migrations.AddConstraint(
            model_name="plantassociatedmasterproduct",
            constraint=models.UniqueConstraint(
                fields=("tenant", "plant", "master_product"), name="unique_plant_master_product_affinity_per_tenant"
            ),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE plants_plantassociatedmasterproduct ENABLE ROW LEVEL SECURITY;
            ALTER TABLE plants_plantassociatedmasterproduct FORCE ROW LEVEL SECURITY;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies
                    WHERE tablename = 'plants_plantassociatedmasterproduct'
                    AND policyname = 'plantassociatedmasterproduct_tenant_isolation'
                ) THEN
                    CREATE POLICY plantassociatedmasterproduct_tenant_isolation ON plants_plantassociatedmasterproduct
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS plantassociatedmasterproduct_tenant_isolation ON plants_plantassociatedmasterproduct;
            ALTER TABLE plants_plantassociatedmasterproduct NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE plants_plantassociatedmasterproduct DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
