# Generated by Django 6.0 on 2026-03-22
# Normalize RLS policies to safe current_setting('app.current_tenant', true)

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0010_alter_plant_associated_products_and_more"),
    ]

    operations = [
        RunSQL(
            sql="""
            ALTER TABLE plants_plantassociatedproduct ENABLE ROW LEVEL SECURITY;
            ALTER TABLE plants_plantassociatedproduct FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS plantassociatedproduct_tenant_isolation ON plants_plantassociatedproduct;
            CREATE POLICY plantassociatedproduct_tenant_isolation ON plants_plantassociatedproduct
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS plantassociatedproduct_tenant_isolation ON plants_plantassociatedproduct;
            CREATE POLICY plantassociatedproduct_tenant_isolation ON plants_plantassociatedproduct
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
        ),
    ]
