# Generated by Django 6.0 on 2026-03-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0011_fix_plants_rls_policies_safe_current_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="phone_type",
            field=models.CharField(
                blank=True,
                choices=[("mobile", "Mobile"), ("office", "Office")],
                default="office",
                help_text="Plant phone type (mobile or office)",
                max_length=10,
            ),
        ),
    ]
