# Generated by Django 6.0 on 2026-03-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0012_plant_phone_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="booking_contact_email",
            field=models.EmailField(
                blank=True, default="", help_text="Booking contact email (optional)", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="booking_contact_phone",
            field=models.CharField(blank=True, default="", help_text="Booking contact phone (optional)", max_length=20),
        ),
        migrations.AddField(
            model_name="plant",
            name="booking_contact_phone_type",
            field=models.CharField(
                blank=True,
                choices=[("mobile", "Mobile"), ("office", "Office")],
                default="office",
                help_text="Booking contact phone type (mobile or office)",
                max_length=10,
            ),
        ),
    ]
