# Generated by Django 6.0 on 2026-03-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0013_plant_booking_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="fcfs",
            field=models.BooleanField(
                default=False, help_text="FCFS (First Come First Serve) plant scheduling/availability flag"
            ),
        ),
    ]
