# Generated by Django 6.0 on 2026-03-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0014_plant_fcfs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="plant_type",
            field=models.CharField(
                choices=[
                    ("vertical", "Vertical (Kill to Capture)"),
                    ("processing", "Processing Plant"),
                    ("distribution", "Distribution Center"),
                    ("warehouse", "Warehouse"),
                    ("retail", "Retail Location"),
                    ("other", "Other"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
