# Generated by Django 6.0 on 2026-04-01 00:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0015_alter_plant_plant_type"),
        ("products", "0009_alter_masterproduct_protein"),
        ("suppliers", "0019_alter_supplier_account_line_of_credit_and_more"),
        ("system", "0014_enable_rls_tenant_product_preference"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="plant",
            name="plants_plan_tenant__9efb37_idx",
        ),
        migrations.AlterField(
            model_name="plant",
            name="plant_type",
            field=models.CharField(
                choices=[
                    ("vertical", "Vertical (Kill to Fabrication)"),
                    ("processing", "Processing Plant"),
                    ("distribution", "Distribution Center"),
                    ("warehouse", "Warehouse"),
                    ("retail", "Retail Location"),
                    ("other", "Other"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="plant",
            index=models.Index(fields=["tenant", "plant_est_num"], name="plants_plan_tenant__65ae85_idx"),
        ),
        migrations.RemoveField(
            model_name="plant",
            name="code",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="email",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="manager",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="phone_type",
        ),
    ]
