# Generated by Django 6.0 on 2026-04-27 06:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_tenantauditevent"),
        ("plants", "0016_remove_plant_plants_plan_tenant__9efb37_idx_and_more"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="export_approved",
            field=models.BooleanField(default=False, help_text="Whether this plant is export approved."),
        ),
        migrations.AddField(
            model_name="plant",
            name="export_documents_handled",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Export documents handled when export approved.",
            ),
        ),
        migrations.CreateModel(
            name="PlantProteinOffered",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protein_offered_links",
                        to="plants.plant",
                    ),
                ),
                (
                    "protein",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant_offered_links",
                        to="core.protein",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant Protein Offered",
                "verbose_name_plural": "Plant Proteins Offered",
            },
        ),
        migrations.AddField(
            model_name="plant",
            name="proteins_offered",
            field=models.ManyToManyField(
                blank=True,
                help_text="Proteins offered by this plant (tenant-scoped link table).",
                related_name="plants_offering",
                through="plants.PlantProteinOffered",
                to="core.protein",
            ),
        ),
        migrations.CreateModel(
            name="PlantProteinTested",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protein_tested_links",
                        to="plants.plant",
                    ),
                ),
                (
                    "protein",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant_tested_links",
                        to="core.protein",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant Protein Tested",
                "verbose_name_plural": "Plant Proteins Tested",
            },
        ),
        migrations.AddField(
            model_name="plant",
            name="proteins_tested",
            field=models.ManyToManyField(
                blank=True,
                help_text="Proteins tested (COA) by this plant (tenant-scoped link table).",
                related_name="plants_testing",
                through="plants.PlantProteinTested",
                to="core.protein",
            ),
        ),
        migrations.AddIndex(
            model_name="plantproteinoffered",
            index=models.Index(fields=["tenant", "plant"], name="plants_plan_tenant__11b39d_idx"),
        ),
        migrations.AddIndex(
            model_name="plantproteinoffered",
            index=models.Index(fields=["tenant", "protein"], name="plants_plan_tenant__bf4c33_idx"),
        ),
        migrations.AddConstraint(
            model_name="plantproteinoffered",
            constraint=models.UniqueConstraint(
                fields=("tenant", "plant", "protein"), name="unique_plant_protein_offered_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="plantproteintested",
            index=models.Index(fields=["tenant", "plant"], name="plants_plan_tenant__edc7dc_idx"),
        ),
        migrations.AddIndex(
            model_name="plantproteintested",
            index=models.Index(fields=["tenant", "protein"], name="plants_plan_tenant__db7fa3_idx"),
        ),
        migrations.AddConstraint(
            model_name="plantproteintested",
            constraint=models.UniqueConstraint(
                fields=("tenant", "plant", "protein"), name="unique_plant_protein_tested_per_tenant"
            ),
        ),
        migrations.RunSQL(
            sql="""
            -- RLS policies for tenant-aware through tables introduced in this migration.

            -- plants_plantproteinoffered
            ALTER TABLE IF EXISTS plants_plantproteinoffered ENABLE ROW LEVEL SECURITY;
            ALTER TABLE IF EXISTS plants_plantproteinoffered FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS plantproteinoffered_tenant_isolation ON plants_plantproteinoffered;
            CREATE POLICY plantproteinoffered_tenant_isolation ON plants_plantproteinoffered
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS plantproteinoffered_tenant_isolation ON plants_plantproteinoffered;
            ALTER TABLE IF EXISTS plants_plantproteinoffered NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE IF EXISTS plants_plantproteinoffered DISABLE ROW LEVEL SECURITY;
            """,
        ),
        migrations.RunSQL(
            sql="""
            -- plants_plantproteintested
            ALTER TABLE IF EXISTS plants_plantproteintested ENABLE ROW LEVEL SECURITY;
            ALTER TABLE IF EXISTS plants_plantproteintested FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS plantproteintested_tenant_isolation ON plants_plantproteintested;
            CREATE POLICY plantproteintested_tenant_isolation ON plants_plantproteintested
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS plantproteintested_tenant_isolation ON plants_plantproteintested;
            ALTER TABLE IF EXISTS plants_plantproteintested NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE IF EXISTS plants_plantproteintested DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
