# Generated by Django 6.0 on 2026-05-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0017_plant_export_approved_plant_export_documents_handled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="site_code",
            field=models.CharField(
                blank=True, default="", help_text="Internal site code for the plant/facility", max_length=50
            ),
        ),
    ]
