# Generated by Django 6.0 on 2026-04-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0017_plant_export_approved_plant_export_documents_handled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
