# Generated by Django 6.0 on 2025-12-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "product_code",
                    models.CharField(help_text="Unique product code", max_length=50, unique=True),
                ),
                (
                    "description_of_product_item",
                    models.TextField(help_text="Detailed description of the product item"),
                ),
                (
                    "type_of_protein",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Beef", "Beef"),
                            ("Chicken", "Chicken"),
                            ("Pork", "Pork"),
                            ("Lamb", "Lamb"),
                            ("Turkey", "Turkey"),
                            ("Fish", "Fish"),
                            ("Horse", "Horse"),
                            ("Other", "Other"),
                        ],
                        default="",
                        help_text="Type of protein (e.g., Beef, Chicken, Pork)",
                        max_length=50,
                    ),
                ),
                (
                    "fresh_or_frozen",
                    models.CharField(
                        blank=True,
                        choices=[("Fresh", "Fresh"), ("Frozen", "Frozen")],
                        default="",
                        help_text="Product state (Fresh or Frozen)",
                        max_length=20,
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Boxed wax lined", "Boxed wax lined"),
                            ("Boxed CO2", "Boxed CO2"),
                            ("Combo bins", "Combo bins"),
                            ("Totes", "Totes"),
                            ("Bags", "Bags"),
                            ("Bulk", "Bulk"),
                            ("Poly-Multiple", "Poly-Multiple"),
                            ("Nude", "Nude"),
                        ],
                        default="",
                        help_text="Package type (e.g., Boxed wax lined, Combo bins)",
                        max_length=50,
                    ),
                ),
                (
                    "net_or_catch",
                    models.CharField(
                        blank=True,
                        choices=[("Net", "Net"), ("Catch", "Catch")],
                        default="",
                        help_text="Weight type (Net or Catch)",
                        max_length=20,
                    ),
                ),
                (
                    "edible_or_inedible",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Edible", "Edible"),
                            ("Inedible", "Inedible"),
                            ("Edible & Inedible", "Edible & Inedible"),
                        ],
                        default="",
                        help_text="Edible or inedible product",
                        max_length=50,
                    ),
                ),
                (
                    "tested_product",
                    models.BooleanField(default=False, help_text="Is this a tested product?"),
                ),
                (
                    "supplier_item_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Supplier's item number",
                        max_length=100,
                    ),
                ),
                (
                    "plants_available",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Plants where product is available (e.g., TX, WI, MI)",
                        max_length=200,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        choices=[("Domestic", "Domestic"), ("Imported", "Imported")],
                        default="",
                        help_text="Product origin (Packer, Boxed Cold Storage)",
                        max_length=100,
                    ),
                ),
                (
                    "carton_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Poly-Multiple", "Poly-Multiple"),
                            ("Waxed Lined", "Waxed Lined"),
                            ("Cardboard", "Cardboard"),
                            ("Plastic", "Plastic"),
                        ],
                        default="",
                        help_text="Type of carton (e.g., Poly-Multiple, Waxed Lined)",
                        max_length=50,
                    ),
                ),
                (
                    "pcs_per_carton",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Pieces per carton (e.g., 4/10)",
                        max_length=50,
                    ),
                ),
                (
                    "uom",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Unit of measure (LB, KG)",
                        max_length=10,
                    ),
                ),
                (
                    "namp",
                    models.CharField(blank=True, default="", help_text="NAMP code", max_length=50),
                ),
                (
                    "usda",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="USDA code (auto-generated/pulled)",
                        max_length=50,
                    ),
                ),
                (
                    "ub",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="UB code (auto-generated/pulled)",
                        max_length=50,
                    ),
                ),
                (
                    "unit_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Standard unit weight",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is this product active?"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supplier for this product",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["product_code"],
            },
        ),
    ]
