# Generated by Django 5.1.4 on 2026-01-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description_of_product_item",
            field=models.TextField(db_index=True, help_text="Detailed description of the product item"),
        ),
    ]
