# Generated by Django 6.0 on 2026-01-10 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_state_sync_tenant"),
        ("suppliers", "0006_alter_supplier_plant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary supplier for this product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplied_products",
                to="suppliers.supplier",
            ),
        ),
    ]
