# Generated by Django 6.0 on 2026-01-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_add_products_m2m"),
        ("tenants", "0006_metadata_lockdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="custom_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extensible schema data for dynamic fields defined in Blueprints.",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
    ]
