# Generated by Django 6.0 on 2026-03-18
# Upgrade RLS policy for Product model to modern standard (app.current_tenant)

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_product_custom_data_alter_product_tenant"),
    ]

    operations = [
        RunSQL(
            sql="""
            -- Enable RLS on products_product (idempotent)
            ALTER TABLE products_product ENABLE ROW LEVEL SECURITY;

            -- Drop any existing policies (upgrade from legacy app.current_tenant_id pattern)
            DROP POLICY IF EXISTS product_tenant_isolation ON products_product;
            DROP POLICY IF EXISTS products_product_tenant_isolation ON products_product;
            DROP POLICY IF EXISTS product_tenant_insert ON products_product;

            -- Create tenant isolation policy for SELECT/UPDATE/DELETE
            CREATE POLICY product_tenant_isolation ON products_product
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- Create tenant isolation policy for INSERT
            CREATE POLICY product_tenant_insert ON products_product
                FOR INSERT
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS product_tenant_insert ON products_product;
            DROP POLICY IF EXISTS product_tenant_isolation ON products_product;
            ALTER TABLE products_product DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
