# Generated by Django 6.0 on 2026-03-20 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_add_rls_policies_batch"),
        ("tenants", "0010_add_tenant_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "protein",
                    models.CharField(
                        choices=[
                            ("Beef", "Beef"),
                            ("Chicken", "Chicken"),
                            ("Pork", "Pork"),
                            ("Lamb", "Lamb"),
                            ("Turkey", "Turkey"),
                            ("Fish", "Fish"),
                            ("Horse", "Horse"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(choices=[("whole", "Whole"), ("flat", "Flat"), ("point", "Point")], max_length=20),
                ),
                (
                    "trim",
                    models.CharField(
                        choices=[
                            ("trimmed", "Trimmed"),
                            ("not_trimmed", "Not Trimmed (commodity trimmed)"),
                            ("super_trimmed", "Super Trimmed (x+)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("display_name", models.CharField(editable=False, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Master Product",
                "verbose_name_plural": "Master Products",
                "ordering": ["display_name"],
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE products_masterproduct ENABLE ROW LEVEL SECURITY;
            ALTER TABLE products_masterproduct FORCE ROW LEVEL SECURITY;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies
                    WHERE tablename = 'products_masterproduct'
                    AND policyname = 'masterproduct_tenant_isolation'
                ) THEN
                    CREATE POLICY masterproduct_tenant_isolation ON products_masterproduct
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS masterproduct_tenant_isolation ON products_masterproduct;
            ALTER TABLE products_masterproduct NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE products_masterproduct DISABLE ROW LEVEL SECURITY;
            """,
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.AddConstraint(
            model_name="masterproduct",
            constraint=models.UniqueConstraint(
                fields=("tenant", "protein", "item_name", "type", "trim"), name="unique_master_product_per_tenant"
            ),
        ),
    ]
