# Generated by Django 6.0 on 2026-03-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_masterproduct_delete_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterproduct",
            name="protein",
            field=models.CharField(
                choices=[
                    ("Beef", "Beef"),
                    ("Chicken", "Chicken"),
                    ("Duck", "Duck"),
                    ("Pork", "Pork"),
                    ("Lamb", "Lamb"),
                    ("Turkey", "Turkey"),
                    ("Fish", "Fish"),
                    ("Horse", "Horse"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
