# Generated by Django 6.0 on 2026-05-06 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_masterproduct_protein"),
        ("system", "0015_enable_rls_tenant_forms_workforms"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterproduct",
            name="system_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Explicit bridge to the shared system product used for availability routing.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="master_products",
                to="system.product",
            ),
        ),
    ]
