# Generated by Django 6.0 on 2026-05-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_masterproduct_system_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterproduct",
            name="protein",
            field=models.CharField(
                choices=[
                    ("Beef", "Beef"),
                    ("Chicken", "Chicken"),
                    ("Fowl", "Fowl"),
                    ("Turkey", "Turkey"),
                    ("Lamb", "Lamb"),
                    ("Veal", "Veal"),
                    ("Seafood", "Seafood"),
                    ("Venison", "Venison"),
                    ("Bison", "Bison"),
                    ("Duck", "Duck"),
                    ("Rabbit", "Rabbit"),
                    ("Goat", "Goat"),
                    ("Mutton", "Mutton"),
                    ("Pork", "Pork"),
                    ("Fish", "Fish"),
                    ("Horse", "Horse"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
