# Generated by Django 6.0 on 2026-01-25 19:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0006_metadata_lockdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the form", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the form's purpose",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                        ],
                        default="draft",
                        help_text="Current status of the form",
                        max_length=20,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use as default form for entity creation (single-entity forms only)",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="file-text",
                        help_text="Icon identifier for UI",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this form",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_forms_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this form belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_forms",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Form",
                "verbose_name_plural": "Tenant Forms",
                "ordering": ["tenant", "name"],
            },
        ),
        migrations.CreateModel(
            name="TenantFormEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Type of entity (model name in snake_case)",
                        max_length=100,
                    ),
                ),
                (
                    "step_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom name for this step (defaults to entity name)",
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of this entity in the form (step number)",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        help_text="Form this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="workflows.tenantform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Entity",
                "verbose_name_plural": "Form Entities",
                "ordering": ["form", "order"],
                "unique_together": {("form", "entity_type")},
            },
        ),
        migrations.CreateModel(
            name="TenantFormRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional name for this rule",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this rule is active"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Order in which rules are evaluated"),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=list,
                        help_text="Conditions to evaluate (AND logic between conditions)",
                    ),
                ),
                (
                    "condition_logic",
                    models.CharField(
                        choices=[
                            ("and", "AND - All must match"),
                            ("or", "OR - Any must match"),
                        ],
                        default="and",
                        help_text="Logic for combining multiple conditions",
                        max_length=10,
                    ),
                ),
                (
                    "actions",
                    models.JSONField(
                        default=list,
                        help_text="Actions to perform when conditions are met",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        help_text="Form this rule belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="workflows.tenantform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Rule",
                "verbose_name_plural": "Form Rules",
                "ordering": ["form", "order"],
            },
        ),
        migrations.CreateModel(
            name="TenantWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the workflow", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of what this workflow does",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("inactive", "Inactive"),
                        ],
                        default="draft",
                        help_text="Current status of the workflow",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled Task"),
                            ("record_created", "New Record Created"),
                            ("record_updated", "Record Field Updated"),
                            ("manual", "Manual Run"),
                        ],
                        help_text="What triggers this workflow",
                        max_length=30,
                    ),
                ),
                (
                    "trigger_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuration specific to the trigger type",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Entity type this workflow operates on",
                        max_length=100,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="zap",
                        help_text="Icon identifier for UI",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_run_at",
                    models.DateTimeField(blank=True, help_text="When this workflow last ran", null=True),
                ),
                (
                    "run_count",
                    models.PositiveIntegerField(default=0, help_text="Number of times this workflow has run"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this workflow",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflows_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this workflow belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
                "ordering": ["tenant", "name"],
            },
        ),
        migrations.CreateModel(
            name="TenantWorkflowAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("display_fields", "Display Field(s)"),
                            ("hide_fields", "Hide Field(s)"),
                            ("filter_options", "Filter Field Options"),
                            ("set_value", "Set Field Value"),
                            ("run_workflow", "Run Custom Workflow"),
                            ("display_entities", "Display Entities"),
                            ("send_email", "Send Email"),
                            ("send_notification", "Send In-App Notification"),
                            ("send_teams_slack", "Send to Teams/Slack"),
                            ("send_sms", "Send Text Message"),
                            ("create_record", "Create Record"),
                            ("update_record", "Update Record"),
                        ],
                        help_text="Type of action to perform",
                        max_length=30,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration specific to the action type",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Order in which actions are executed"),
                ),
                (
                    "continue_on_error",
                    models.BooleanField(
                        default=False,
                        help_text="Continue executing subsequent actions if this one fails",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Workflow this action belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="workflows.tenantworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Action",
                "verbose_name_plural": "Workflow Actions",
                "ordering": ["workflow", "order"],
            },
        ),
        migrations.CreateModel(
            name="TenantWorkflowCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_path",
                    models.CharField(
                        help_text="Path to field (e.g., 'status', 'customer.name')",
                        max_length=255,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("eq", "Equals (=)"),
                            ("neq", "Not Equal To (≠)"),
                            ("gt", "Greater Than (>)"),
                            ("lt", "Less Than (<)"),
                            ("gte", "Greater Than or Equal (≥)"),
                            ("lte", "Less Than or Equal (≤)"),
                            ("contains", "Contains"),
                            ("not_contains", "Does Not Contain"),
                            ("is_empty", "Is Empty"),
                            ("is_not_empty", "Is Not Empty"),
                        ],
                        help_text="Comparison operator",
                        max_length=20,
                    ),
                ),
                (
                    "compare_value",
                    models.JSONField(blank=True, help_text="Value to compare against", null=True),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Order of condition evaluation"),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Workflow this condition belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="workflows.tenantworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Condition",
                "verbose_name_plural": "Workflow Conditions",
                "ordering": ["workflow", "order"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecutionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(help_text="What triggered this execution", max_length=30),
                ),
                (
                    "trigger_data",
                    models.JSONField(default=dict, help_text="Data that triggered the workflow"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="started",
                        help_text="Execution status",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actions_executed",
                    models.PositiveIntegerField(default=0, help_text="Number of actions executed"),
                ),
                (
                    "actions_failed",
                    models.PositiveIntegerField(default=0, help_text="Number of actions that failed"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if execution failed",
                    ),
                ),
                (
                    "execution_log",
                    models.JSONField(
                        default=list,
                        help_text="Detailed log of each action's execution",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the workflow (if manual)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Workflow that was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="workflows.tenantworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execution Log",
                "verbose_name_plural": "Execution Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantFormField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_key",
                    models.CharField(help_text="Field key/name from the entity model", max_length=100),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this field is visible in the form",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, help_text="Override: make this field required"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order of the field"),
                ),
                (
                    "custom_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom label (overrides default field label)",
                        max_length=255,
                    ),
                ),
                (
                    "custom_help_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom help text",
                        max_length=500,
                    ),
                ),
                (
                    "default_value",
                    models.JSONField(
                        blank=True,
                        help_text="Default value for this field in this form",
                        null=True,
                    ),
                ),
                (
                    "form_entity",
                    models.ForeignKey(
                        help_text="Form entity this field belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="workflows.tenantformentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Field",
                "verbose_name_plural": "Form Fields",
                "ordering": ["form_entity", "order"],
                "unique_together": {("form_entity", "field_key")},
            },
        ),
        migrations.CreateModel(
            name="TenantList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the option list", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="Description of the list"),
                ),
                (
                    "options",
                    models.JSONField(
                        default=list,
                        help_text="List of options [{value: 'v1', label: 'Label 1'}, ...]",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this list is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this list",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_lists_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this list belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_lists",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant List",
                "verbose_name_plural": "Tenant Lists",
                "ordering": ["tenant", "name"],
                "unique_together": {("tenant", "name")},
            },
        ),
    ]
