# Generated by Django 6.0 on 2026-01-27 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantformfield",
            name="auto_populate_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("copy", "Copy Value"),
                    ("lookup", "Lookup Reference"),
                ],
                default="",
                help_text="How to populate: copy=direct value, lookup=fetch related record",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenantformfield",
            name="auto_populate_source_field",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Field key from source step to use for auto-population",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="tenantformfield",
            name="auto_populate_source_step",
            field=models.ForeignKey(
                blank=True,
                help_text="Step to pull auto-populate value from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fields_that_use_as_source",
                to="workflows.tenantformentity",
            ),
        ),
    ]
