# Generated by Django 6.0 on 2026-01-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_add_auto_populate_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tenantformentity",
            unique_together=set(),
        ),
    ]
