# Generated by Django 6.0 on 2026-01-27 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_metadata_lockdown"),
        ("workflows", "0003_remove_unique_constraint_form_entity_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantform",
            name="is_quick_action_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Allow this form to be added to user Quick Actions menu",
            ),
        ),
        migrations.AddField(
            model_name="tenantformfield",
            name="validation_rules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Validation rules: min_length, max_length, pattern, min, max, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="tenantworkflowaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("display_fields", "Display Field(s)"),
                    ("hide_fields", "Hide Field(s)"),
                    ("filter_options", "Filter Field Options"),
                    ("set_value", "Set Field Value"),
                    ("display_steps", "Display Step(s)"),
                    ("hide_steps", "Hide Step(s)"),
                    ("display_entities", "Display Entities"),
                    ("run_workflow", "Run Custom Workflow"),
                    ("send_email", "Send Email"),
                    ("send_notification", "Send In-App Notification"),
                    ("send_teams_slack", "Send to Teams/Slack"),
                    ("send_sms", "Send Text Message"),
                    ("create_record", "Create Record"),
                    ("update_record", "Update Record"),
                ],
                help_text="Type of action to perform",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        help_text="Current status of the submission",
                        max_length=20,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="All field values: { step_id: { field_key: value } }",
                    ),
                ),
                (
                    "form_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of form structure at submission creation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when submission was completed",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this submission",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        help_text="The step the user is currently on",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_submissions",
                        to="workflows.tenantformentity",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        help_text="The form being submitted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="workflows.tenantform",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this submission belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_submissions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Submission",
                "verbose_name_plural": "Form Submissions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FormStepSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("action_needed", "Action Needed"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        help_text="Current status of this step",
                        max_length=20,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Field values for this step: { field_key: value }",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when step was marked complete",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who completed this step",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_step_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        help_text="The form step/entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_submissions",
                        to="workflows.tenantformentity",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="Parent form submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_submissions",
                        to="workflows.formsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Step Submission",
                "verbose_name_plural": "Step Submissions",
                "ordering": ["submission", "step__order"],
            },
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["tenant", "status"], name="workflows_f_tenant__8314a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["created_by", "status"], name="workflows_f_created_8eb614_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["form", "status"], name="workflows_f_form_id_aa9358_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="formstepsubmission",
            unique_together={("submission", "step")},
        ),
    ]
