# Generated by Django 6.0 on 2026-01-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0004_add_form_submission_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantformfield",
            name="field_type",
            field=models.CharField(
                default="text",
                help_text="Form field type: text, email, select, textarea, number, date, etc.",
                max_length=30,
            ),
        ),
    ]
