# Generated by Django 6.0 on 2026-01-29 03:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import tenant_apps.workflows.models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0005_add_field_type_to_tenantformfield"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSubmissionFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_key",
                    models.CharField(
                        help_text="The field key this file is associated with",
                        max_length=100,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded file",
                        upload_to=tenant_apps.workflows.models.form_submission_upload_path,
                    ),
                ),
                (
                    "original_name",
                    models.CharField(help_text="Original filename as uploaded", max_length=255),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, help_text="MIME type of the file", max_length=100),
                ),
                (
                    "size",
                    models.PositiveIntegerField(default=0, help_text="File size in bytes"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="The form submission this file belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="workflows.formsubmission",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded this file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_submission_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Submission File",
                "verbose_name_plural": "Form Submission Files",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["submission", "field_key"],
                        name="workflows_f_submiss_fe23dd_idx",
                    )
                ],
            },
        ),
    ]
