# Generated by Django 6.0 on 2026-01-29 04:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0006_add_form_submission_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSubmissionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("form_started", "Form Started"),
                            ("step_entered", "Step Entered"),
                            ("step_completed", "Step Completed"),
                            ("field_focused", "Field Focused"),
                            ("field_changed", "Field Changed"),
                            ("field_error", "Field Error"),
                            ("validation_error", "Validation Error"),
                            ("auto_saved", "Auto Saved"),
                            ("form_submitted", "Form Submitted"),
                            ("form_abandoned", "Form Abandoned"),
                        ],
                        help_text="Type of event",
                        max_length=30,
                    ),
                ),
                (
                    "step_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Step ID if event is step-related",
                        null=True,
                    ),
                ),
                (
                    "field_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Field key if event is field-related",
                        max_length=100,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional event data (error messages, field values, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration in milliseconds (for step/form completion)",
                        null=True,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="The form submission this event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="workflows.formsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Submission Event",
                "verbose_name_plural": "Form Submission Events",
                "ordering": ["submission", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["submission", "event_type"],
                        name="workflows_f_submiss_440e24_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="workflows_f_event_t_a4b864_idx",
                    ),
                    models.Index(
                        fields=["step_id", "event_type"],
                        name="workflows_f_step_id_8701fb_idx",
                    ),
                ],
            },
        ),
    ]
