# Generated by Django 6.0 on 2026-02-02 03:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0006_metadata_lockdown"),
        ("workflows", "0007_form_submission_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotificationPreferences",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "notifications_enabled",
                    models.BooleanField(default=True, help_text="Master switch to enable/disable all notifications"),
                ),
                ("email_enabled", models.BooleanField(default=True, help_text="Whether to send email notifications")),
                ("sms_enabled", models.BooleanField(default=False, help_text="Whether to send SMS notifications")),
                ("push_enabled", models.BooleanField(default=True, help_text="Whether to send push notifications")),
                (
                    "type_preferences",
                    models.JSONField(blank=True, default=dict, help_text="Per-type delivery preferences"),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable quiet hours (no notifications during specified times)"
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(blank=True, help_text="Start of quiet hours (e.g., 22:00)", null=True),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(blank=True, help_text="End of quiet hours (e.g., 08:00)", null=True),
                ),
                (
                    "daily_digest_enabled",
                    models.BooleanField(
                        default=False, help_text="Receive a daily digest email instead of individual notifications"
                    ),
                ),
                (
                    "weekly_digest_enabled",
                    models.BooleanField(default=False, help_text="Receive a weekly digest email"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User for these preferences",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Notification Preferences",
                "verbose_name_plural": "User Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="FormStatusHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="",
                        help_text="Previous status (empty if initial creation)",
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        help_text="New status after this change",
                        max_length=20,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", help_text="Optional reason or comment for the status change"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made this status change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="The form submission this history entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="workflows.formsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Status History",
                "verbose_name_plural": "Form Status Histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["submission", "-created_at"], name="workflows_f_submiss_f95cb4_idx"),
                    models.Index(fields=["to_status", "created_at"], name="workflows_f_to_stat_0f96d3_idx"),
                    models.Index(fields=["changed_by", "created_at"], name="workflows_f_changed_c6062b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StepAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("user", "Specific User"),
                            ("role", "Role-Based"),
                            ("team", "Team-Based"),
                            ("pool", "Shared Pool"),
                        ],
                        default="user",
                        help_text="Type of assignment",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Role name for role-based assignment (e.g., 'manager', 'approver')",
                        max_length=100,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, help_text="Whether this step must be completed (vs. skippable)"),
                ),
                (
                    "due_days",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of days allowed to complete this step (SLA)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific user assigned (for USER type)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="step_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_step_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalation_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User to notify if step exceeds due date",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalation_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        help_text="The form this assignment applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_assignments",
                        to="workflows.tenantform",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        help_text="The step being assigned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="workflows.tenantformentity",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this assignment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_assignments",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Step Assignment",
                "verbose_name_plural": "Step Assignments",
                "ordering": ["form", "step__order"],
                "indexes": [
                    models.Index(fields=["tenant", "form"], name="workflows_s_tenant__3c0364_idx"),
                    models.Index(fields=["assigned_user", "assignment_type"], name="workflows_s_assigne_61bc7f_idx"),
                    models.Index(fields=["assigned_role"], name="workflows_s_assigne_a91501_idx"),
                ],
                "unique_together": {("form", "step", "assigned_role"), ("form", "step", "assigned_user")},
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "Task Assigned"),
                            ("task_due_soon", "Task Due Soon"),
                            ("task_overdue", "Task Overdue"),
                            ("task_completed", "Task Completed"),
                            ("form_submitted", "Form Submitted"),
                            ("form_approved", "Form Approved"),
                            ("form_rejected", "Form Rejected"),
                            ("mention", "Mentioned You"),
                            ("comment", "New Comment"),
                            ("status_change", "Status Changed"),
                            ("workflow_trigger", "Workflow Triggered"),
                            ("system", "System Notification"),
                        ],
                        help_text="Type of notification",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title (short, e.g., 'New Task Assigned')", max_length=200),
                ),
                ("message", models.TextField(help_text="Full notification message")),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("normal", "Normal"), ("high", "High"), ("urgent", "Urgent")],
                        default="normal",
                        help_text="Notification priority level",
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Entity type for linking (e.g., 'form_submission', 'purchase_order')",
                        max_length=50,
                    ),
                ),
                ("entity_id", models.UUIDField(blank=True, help_text="UUID of the related entity", null=True)),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL to navigate to when notification is clicked",
                        max_length=500,
                    ),
                ),
                ("is_read", models.BooleanField(default=False, help_text="Whether the notification has been read")),
                ("read_at", models.DateTimeField(blank=True, help_text="When the notification was read", null=True)),
                (
                    "is_dismissed",
                    models.BooleanField(default=False, help_text="Whether the user dismissed this notification"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, help_text="Additional notification data")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When this notification should auto-expire (for cleanup)", null=True
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this notification belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User to receive this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Notification",
                "verbose_name_plural": "User Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_read", "-created_at"], name="workflows_u_user_id_0d55ab_idx"),
                    models.Index(
                        fields=["user", "notification_type", "-created_at"], name="workflows_u_user_id_5eab5b_idx"
                    ),
                    models.Index(fields=["tenant", "-created_at"], name="workflows_u_tenant__b2d0bd_idx"),
                    models.Index(fields=["entity_type", "entity_id"], name="workflows_u_entity__5edd64_idx"),
                    models.Index(fields=["expires_at"], name="workflows_u_expires_aef021_idx"),
                ],
            },
        ),
    ]
