# Generated by Django 6.0 on 2026-02-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0008_wave3_forms_flows_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantform",
            name="flow_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Visual editor flow definition (nodes and edges)"
            ),
        ),
    ]
