# Generated by Django 6.0 on 2026-02-14 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0010_add_tenant_configuration"),
        ("workflows", "0009_add_flow_data_to_tenantform"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current execution status",
                        max_length=20,
                    ),
                ),
                (
                    "current_node_id",
                    models.CharField(
                        blank=True, default="", help_text="ID of the current node/step in the workflow", max_length=255
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Workflow execution context: variables, routing, decisions"
                    ),
                ),
                (
                    "audit_trail",
                    models.JSONField(
                        blank=True, default=list, help_text="Chronological log of node transitions and actions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When execution actually began (vs created_at)", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When execution finished (completed/failed/cancelled)", null=True
                    ),
                ),
                (
                    "total_nodes",
                    models.PositiveIntegerField(default=0, help_text="Total number of nodes in the workflow"),
                ),
                (
                    "completed_nodes",
                    models.PositiveIntegerField(default=0, help_text="Number of nodes completed so far"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", help_text="Error message if execution failed"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User currently assigned to this execution",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who started this execution",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this execution belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_executions",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="The WorkForm being executed",
                        limit_choices_to={"is_workflow": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="workflows.tenantform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Execution",
                "verbose_name_plural": "Workflow Executions",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="workflows_w_tenant__43465b_idx"),
                    models.Index(fields=["workflow", "status"], name="workflows_w_workflo_f6053d_idx"),
                    models.Index(fields=["assigned_to", "status"], name="workflows_w_assigne_99264a_idx"),
                    models.Index(fields=["started_by", "created_at"], name="workflows_w_started_c9d3ce_idx"),
                    models.Index(fields=["status", "-updated_at"], name="workflows_w_status_aa66ca_idx"),
                ],
            },
        ),
    ]
