# Generated by Django 6.0 on 2026-02-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0010_workflowexecution"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="workflowexecution",
            name="workflows_w_tenant__43465b_idx",
        ),
        migrations.RemoveIndex(
            model_name="workflowexecution",
            name="workflows_w_workflo_f6053d_idx",
        ),
        migrations.RemoveIndex(
            model_name="workflowexecution",
            name="workflows_w_assigne_99264a_idx",
        ),
        migrations.RemoveIndex(
            model_name="workflowexecution",
            name="workflows_w_started_c9d3ce_idx",
        ),
        migrations.RemoveIndex(
            model_name="workflowexecution",
            name="workflows_w_status_aa66ca_idx",
        ),
        migrations.AlterField(
            model_name="tenantworkflow",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Run"),
                    ("scheduled", "Scheduled Task"),
                    ("webhook", "Webhook (External API)"),
                    ("event", "Database Event"),
                    ("form_submit", "Form Submission"),
                    ("record_created", "New Record Created"),
                    ("record_updated", "Record Field Updated"),
                ],
                help_text="What triggers this workflow",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="WorkflowExecution",
        ),
    ]
