# Generated by Django 6.0 on 2026-02-27 13:15
# Fix tenant_id population for workflow models from PR #3315

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0012_refactor_to_tenantaware"),
    ]

    operations = [
        # Fix TenantFormEntity: Populate tenant_id from form.tenant_id
        migrations.RunSQL(
            sql="UPDATE workflows_tenantformentity SET tenant_id = (SELECT tenant_id FROM workflows_tenantform WHERE workflows_tenantform.id = workflows_tenantformentity.form_id) WHERE tenant_id IS NULL OR tenant_id = '00000000-0000-0000-0000-000000000001'::uuid;",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Fix TenantFormField: Populate tenant_id from form.tenant_id
        migrations.RunSQL(
            sql="UPDATE workflows_tenantformfield SET tenant_id = (SELECT tenant_id FROM workflows_tenantform WHERE workflows_tenantform.id = workflows_tenantformfield.form_id) WHERE tenant_id IS NULL OR tenant_id = '00000000-0000-0000-0000-000000000001'::uuid;",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Fix TenantFormRule: Populate tenant_id from form.tenant_id
        migrations.RunSQL(
            sql="UPDATE workflows_tenantformrule SET tenant_id = (SELECT tenant_id FROM workflows_tenantform WHERE workflows_tenantform.id = workflows_tenantformrule.form_id) WHERE tenant_id IS NULL OR tenant_id = '00000000-0000-0000-0000-000000000001'::uuid;",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Fix TenantWorkflowCondition: Populate tenant_id from workflow.tenant_id
        migrations.RunSQL(
            sql="UPDATE workflows_tenantworkflowcondition SET tenant_id = (SELECT tenant_id FROM workflows_tenantworkflow WHERE workflows_tenantworkflow.id = workflows_tenantworkflowcondition.workflow_id) WHERE tenant_id IS NULL OR tenant_id = '00000000-0000-0000-0000-000000000001'::uuid;",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Fix TenantWorkflowAction: Populate tenant_id from workflow.tenant_id
        migrations.RunSQL(
            sql="UPDATE workflows_tenantworkflowaction SET tenant_id = (SELECT tenant_id FROM workflows_tenantworkflow WHERE workflows_tenantworkflow.id = workflows_tenantworkflowaction.workflow_id) WHERE tenant_id IS NULL OR tenant_id = '00000000-0000-0000-0000-000000000001'::uuid;",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Fix WorkflowExecutionLog: Populate tenant_id from workflow.tenant_id
        migrations.RunSQL(
            sql="UPDATE workflows_workflowexecutionlog SET tenant_id = (SELECT tenant_id FROM workflows_tenantworkflow WHERE workflows_tenantworkflow.id = workflows_workflowexecutionlog.workflow_id) WHERE tenant_id IS NULL OR tenant_id = '00000000-0000-0000-0000-000000000001'::uuid;",
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
