# Generated by Django 6.0 on 2026-02-27 13:15
# Refactor workflow models to inherit from TenantAwareModel
# CORRECTED VERSION: Uses null + populate + alter pattern

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0011_remove_workflowexecution_workflows_w_tenant__43465b_idx_and_more"),
        ("tenants", "0010_add_tenant_configuration"),
    ]

    operations = [
        # TenantList - already has tenant field
        migrations.AddField(
            model_name="tenantlist",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenantlist",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tenantlist",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        # TenantForm - already has tenant field
        migrations.AddField(
            model_name="tenantform",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenantform",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tenantform",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        # TenantFormEntity - needs tenant field (null + populate + alter pattern)
        migrations.AddField(
            model_name="tenantformentity",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenantformentity",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tenantformentity",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tenantformentity",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
                null=True,
            ),
        ),
        migrations.RunSQL(
            sql="UPDATE workflows_tenantformentity SET tenant_id = (SELECT tenant_id FROM workflows_tenantform WHERE workflows_tenantform.id = workflows_tenantformentity.form_id) WHERE tenant_id IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="tenantformentity",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        # TenantFormField - needs tenant field
        migrations.AddField(
            model_name="tenantformfield",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenantformfield",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tenantformfield",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tenantformfield",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
                null=True,
            ),
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE workflows_tenantformfield tff "
                "SET tenant_id = tf.tenant_id "
                "FROM workflows_tenantformentity tfe "
                "JOIN workflows_tenantform tf ON tf.id = tfe.form_id "
                "WHERE tff.form_entity_id = tfe.id AND tff.tenant_id IS NULL;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="tenantformfield",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        # TenantFormRule - needs tenant field
        migrations.AddField(
            model_name="tenantformrule",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenantformrule",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tenantformrule",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tenantformrule",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
                null=True,
            ),
        ),
        migrations.RunSQL(
            sql="UPDATE workflows_tenantformrule SET tenant_id = (SELECT tenant_id FROM workflows_tenantform WHERE workflows_tenantform.id = workflows_tenantformrule.form_id) WHERE tenant_id IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="tenantformrule",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        # TenantWorkflow - already has tenant field
        migrations.AddField(
            model_name="tenantworkflow",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenantworkflow",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tenantworkflow",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        # TenantWorkflowCondition - needs tenant field
        migrations.AddField(
            model_name="tenantworkflowcondition",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenantworkflowcondition",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tenantworkflowcondition",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tenantworkflowcondition",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
                null=True,
            ),
        ),
        migrations.RunSQL(
            sql="UPDATE workflows_tenantworkflowcondition SET tenant_id = (SELECT tenant_id FROM workflows_tenantworkflow WHERE workflows_tenantworkflow.id = workflows_tenantworkflowcondition.workflow_id) WHERE tenant_id IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="tenantworkflowcondition",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        # TenantWorkflowAction - needs tenant field
        migrations.AddField(
            model_name="tenantworkflowaction",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenantworkflowaction",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tenantworkflowaction",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tenantworkflowaction",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
                null=True,
            ),
        ),
        migrations.RunSQL(
            sql="UPDATE workflows_tenantworkflowaction SET tenant_id = (SELECT tenant_id FROM workflows_tenantworkflow WHERE workflows_tenantworkflow.id = workflows_tenantworkflowaction.workflow_id) WHERE tenant_id IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="tenantworkflowaction",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        # WorkflowExecutionLog - needs tenant field
        migrations.AddField(
            model_name="workflowexecutionlog",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workflowexecutionlog",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="workflowexecutionlog",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workflowexecutionlog",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
                null=True,
            ),
        ),
        migrations.RunSQL(
            sql="UPDATE workflows_workflowexecutionlog SET tenant_id = (SELECT tenant_id FROM workflows_tenantworkflow WHERE workflows_tenantworkflow.id = workflows_workflowexecutionlog.workflow_id) WHERE tenant_id IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="workflowexecutionlog",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        # Row-Level Security (RLS) for all workflow models
        migrations.RunSQL(
            sql="""
            -- TenantList RLS
            ALTER TABLE workflows_tenantlist ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantlist_tenant_isolation ON workflows_tenantlist;
            CREATE POLICY tenantlist_tenant_isolation ON workflows_tenantlist
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            CREATE POLICY tenantlist_tenant_insert ON workflows_tenantlist
            FOR INSERT WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- TenantForm RLS
            ALTER TABLE workflows_tenantform ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantform_tenant_isolation ON workflows_tenantform;
            CREATE POLICY tenantform_tenant_isolation ON workflows_tenantform
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            CREATE POLICY tenantform_tenant_insert ON workflows_tenantform
            FOR INSERT WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- TenantFormEntity RLS
            ALTER TABLE workflows_tenantformentity ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantformentity_tenant_isolation ON workflows_tenantformentity;
            CREATE POLICY tenantformentity_tenant_isolation ON workflows_tenantformentity
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            CREATE POLICY tenantformentity_tenant_insert ON workflows_tenantformentity
            FOR INSERT WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- TenantFormField RLS
            ALTER TABLE workflows_tenantformfield ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantformfield_tenant_isolation ON workflows_tenantformfield;
            CREATE POLICY tenantformfield_tenant_isolation ON workflows_tenantformfield
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            CREATE POLICY tenantformfield_tenant_insert ON workflows_tenantformfield
            FOR INSERT WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- TenantFormRule RLS
            ALTER TABLE workflows_tenantformrule ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantformrule_tenant_isolation ON workflows_tenantformrule;
            CREATE POLICY tenantformrule_tenant_isolation ON workflows_tenantformrule
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            CREATE POLICY tenantformrule_tenant_insert ON workflows_tenantformrule
            FOR INSERT WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- TenantWorkflow RLS
            ALTER TABLE workflows_tenantworkflow ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantworkflow_tenant_isolation ON workflows_tenantworkflow;
            CREATE POLICY tenantworkflow_tenant_isolation ON workflows_tenantworkflow
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            CREATE POLICY tenantworkflow_tenant_insert ON workflows_tenantworkflow
            FOR INSERT WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- TenantWorkflowCondition RLS
            ALTER TABLE workflows_tenantworkflowcondition ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantworkflowcondition_tenant_isolation ON workflows_tenantworkflowcondition;
            CREATE POLICY tenantworkflowcondition_tenant_isolation ON workflows_tenantworkflowcondition
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            CREATE POLICY tenantworkflowcondition_tenant_insert ON workflows_tenantworkflowcondition
            FOR INSERT WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- TenantWorkflowAction RLS
            ALTER TABLE workflows_tenantworkflowaction ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantworkflowaction_tenant_isolation ON workflows_tenantworkflowaction;
            CREATE POLICY tenantworkflowaction_tenant_isolation ON workflows_tenantworkflowaction
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            CREATE POLICY tenantworkflowaction_tenant_insert ON workflows_tenantworkflowaction
            FOR INSERT WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- WorkflowExecutionLog RLS
            ALTER TABLE workflows_workflowexecutionlog ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS workflowexecutionlog_tenant_isolation ON workflows_workflowexecutionlog;
            CREATE POLICY workflowexecutionlog_tenant_isolation ON workflows_workflowexecutionlog
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            CREATE POLICY workflowexecutionlog_tenant_insert ON workflows_workflowexecutionlog
            FOR INSERT WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            -- Rollback: Disable RLS and drop policies
            DROP POLICY IF EXISTS tenantlist_tenant_insert ON workflows_tenantlist;
            DROP POLICY IF EXISTS tenantlist_tenant_isolation ON workflows_tenantlist;
            ALTER TABLE workflows_tenantlist DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS tenantform_tenant_insert ON workflows_tenantform;
            DROP POLICY IF EXISTS tenantform_tenant_isolation ON workflows_tenantform;
            ALTER TABLE workflows_tenantform DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS tenantformentity_tenant_insert ON workflows_tenantformentity;
            DROP POLICY IF EXISTS tenantformentity_tenant_isolation ON workflows_tenantformentity;
            ALTER TABLE workflows_tenantformentity DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS tenantformfield_tenant_insert ON workflows_tenantformfield;
            DROP POLICY IF EXISTS tenantformfield_tenant_isolation ON workflows_tenantformfield;
            ALTER TABLE workflows_tenantformfield DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS tenantformrule_tenant_insert ON workflows_tenantformrule;
            DROP POLICY IF EXISTS tenantformrule_tenant_isolation ON workflows_tenantformrule;
            ALTER TABLE workflows_tenantformrule DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS tenantworkflow_tenant_insert ON workflows_tenantworkflow;
            DROP POLICY IF EXISTS tenantworkflow_tenant_isolation ON workflows_tenantworkflow;
            ALTER TABLE workflows_tenantworkflow DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS tenantworkflowcondition_tenant_insert ON workflows_tenantworkflowcondition;
            DROP POLICY IF EXISTS tenantworkflowcondition_tenant_isolation ON workflows_tenantworkflowcondition;
            ALTER TABLE workflows_tenantworkflowcondition DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS tenantworkflowaction_tenant_insert ON workflows_tenantworkflowaction;
            DROP POLICY IF EXISTS tenantworkflowaction_tenant_isolation ON workflows_tenantworkflowaction;
            ALTER TABLE workflows_tenantworkflowaction DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS workflowexecutionlog_tenant_insert ON workflows_workflowexecutionlog;
            DROP POLICY IF EXISTS workflowexecutionlog_tenant_isolation ON workflows_workflowexecutionlog;
            ALTER TABLE workflows_workflowexecutionlog DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
