# Generated by Django 6.0 on 2026-02-27 15:30
# Sync RLS policies for workflow tables to match manually patched server state
# Uses IF NOT EXISTS logic to be idempotent

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0014_refactor_to_tenantaware_corrected"),
    ]

    operations = [
        # Enable RLS and create policies for all 17 workflow tables
        # Using DO blocks to make operations idempotent
        
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- TenantList
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = 'workflows_tenantlist' 
                    AND policyname = 'tenantlist_tenant_isolation'
                ) THEN
                    ALTER TABLE workflows_tenantlist ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE workflows_tenantlist FORCE ROW LEVEL SECURITY;
                    CREATE POLICY tenantlist_tenant_isolation ON workflows_tenantlist
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;

                -- TenantForm
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = 'workflows_tenantform' 
                    AND policyname = 'tenantform_tenant_isolation'
                ) THEN
                    ALTER TABLE workflows_tenantform ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE workflows_tenantform FORCE ROW LEVEL SECURITY;
                    CREATE POLICY tenantform_tenant_isolation ON workflows_tenantform
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;

                -- TenantFormEntity
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = 'workflows_tenantformentity' 
                    AND policyname = 'tenantformentity_tenant_isolation'
                ) THEN
                    ALTER TABLE workflows_tenantformentity ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE workflows_tenantformentity FORCE ROW LEVEL SECURITY;
                    CREATE POLICY tenantformentity_tenant_isolation ON workflows_tenantformentity
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;

                -- TenantFormField
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = 'workflows_tenantformfield' 
                    AND policyname = 'tenantformfield_tenant_isolation'
                ) THEN
                    ALTER TABLE workflows_tenantformfield ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE workflows_tenantformfield FORCE ROW LEVEL SECURITY;
                    CREATE POLICY tenantformfield_tenant_isolation ON workflows_tenantformfield
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;

                -- TenantFormRule
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = 'workflows_tenantformrule' 
                    AND policyname = 'tenantformrule_tenant_isolation'
                ) THEN
                    ALTER TABLE workflows_tenantformrule ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE workflows_tenantformrule FORCE ROW LEVEL SECURITY;
                    CREATE POLICY tenantformrule_tenant_isolation ON workflows_tenantformrule
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;

                -- TenantWorkflow
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = 'workflows_tenantworkflow' 
                    AND policyname = 'tenantworkflow_tenant_isolation'
                ) THEN
                    ALTER TABLE workflows_tenantworkflow ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE workflows_tenantworkflow FORCE ROW LEVEL SECURITY;
                    CREATE POLICY tenantworkflow_tenant_isolation ON workflows_tenantworkflow
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;

                -- TenantWorkflowCondition
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = 'workflows_tenantworkflowcondition' 
                    AND policyname = 'tenantworkflowcondition_tenant_isolation'
                ) THEN
                    ALTER TABLE workflows_tenantworkflowcondition ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE workflows_tenantworkflowcondition FORCE ROW LEVEL SECURITY;
                    CREATE POLICY tenantworkflowcondition_tenant_isolation ON workflows_tenantworkflowcondition
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;

                -- TenantWorkflowAction
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = 'workflows_tenantworkflowaction' 
                    AND policyname = 'tenantworkflowaction_tenant_isolation'
                ) THEN
                    ALTER TABLE workflows_tenantworkflowaction ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE workflows_tenantworkflowaction FORCE ROW LEVEL SECURITY;
                    CREATE POLICY tenantworkflowaction_tenant_isolation ON workflows_tenantworkflowaction
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;

                -- WorkflowExecutionLog
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = 'workflows_workflowexecutionlog' 
                    AND policyname = 'workflowexecutionlog_tenant_isolation'
                ) THEN
                    ALTER TABLE workflows_workflowexecutionlog ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE workflows_workflowexecutionlog FORCE ROW LEVEL SECURITY;
                    CREATE POLICY workflowexecutionlog_tenant_isolation ON workflows_workflowexecutionlog
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;

                -- FormSubmission
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = 'workflows_formsubmission' 
                    AND policyname = 'formsubmission_tenant_isolation'
                ) THEN
                    ALTER TABLE workflows_formsubmission ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE workflows_formsubmission FORCE ROW LEVEL SECURITY;
                    CREATE POLICY formsubmission_tenant_isolation ON workflows_formsubmission
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;

                -- FormSubmissionValue (REMOVED - table does not exist in current schema)

                -- FormSubmissionFile
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = 'workflows_formsubmissionfile' 
                    AND policyname = 'formsubmissionfile_tenant_isolation'
                ) THEN
                    ALTER TABLE workflows_formsubmissionfile ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE workflows_formsubmissionfile FORCE ROW LEVEL SECURITY;
                    CREATE POLICY formsubmissionfile_tenant_isolation ON workflows_formsubmissionfile
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;

                -- FormSubmissionEvent
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = 'workflows_formsubmissionevent' 
                    AND policyname = 'formsubmissionevent_tenant_isolation'
                ) THEN
                    ALTER TABLE workflows_formsubmissionevent ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE workflows_formsubmissionevent FORCE ROW LEVEL SECURITY;
                    CREATE POLICY formsubmissionevent_tenant_isolation ON workflows_formsubmissionevent
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;

                -- StepAssignment
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = 'workflows_stepassignment' 
                    AND policyname = 'stepassignment_tenant_isolation'
                ) THEN
                    ALTER TABLE workflows_stepassignment ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE workflows_stepassignment FORCE ROW LEVEL SECURITY;
                    CREATE POLICY stepassignment_tenant_isolation ON workflows_stepassignment
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;

                -- UserNotification
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = 'workflows_usernotification' 
                    AND policyname = 'usernotification_tenant_isolation'
                ) THEN
                    ALTER TABLE workflows_usernotification ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE workflows_usernotification FORCE ROW LEVEL SECURITY;
                    CREATE POLICY usernotification_tenant_isolation ON workflows_usernotification
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;

                -- WorkflowExecution (REMOVED - table does not exist; only workflowexecutionlog exists)

            END $$;
            """,
            reverse_sql="""
            -- Reverse: Drop policies and disable RLS
            DO $$
            BEGIN
                -- Drop all policies
                DROP POLICY IF EXISTS tenantlist_tenant_isolation ON workflows_tenantlist;
                DROP POLICY IF EXISTS tenantform_tenant_isolation ON workflows_tenantform;
                DROP POLICY IF EXISTS tenantformentity_tenant_isolation ON workflows_tenantformentity;
                DROP POLICY IF EXISTS tenantformfield_tenant_isolation ON workflows_tenantformfield;
                DROP POLICY IF EXISTS tenantformrule_tenant_isolation ON workflows_tenantformrule;
                DROP POLICY IF EXISTS tenantworkflow_tenant_isolation ON workflows_tenantworkflow;
                DROP POLICY IF EXISTS tenantworkflowcondition_tenant_isolation ON workflows_tenantworkflowcondition;
                DROP POLICY IF EXISTS tenantworkflowaction_tenant_isolation ON workflows_tenantworkflowaction;
                DROP POLICY IF EXISTS workflowexecutionlog_tenant_isolation ON workflows_workflowexecutionlog;
                DROP POLICY IF EXISTS formsubmission_tenant_isolation ON workflows_formsubmission;
                -- formsubmissionvalue table does not exist (skipped)
                DROP POLICY IF EXISTS formsubmissionfile_tenant_isolation ON workflows_formsubmissionfile;
                DROP POLICY IF EXISTS formsubmissionevent_tenant_isolation ON workflows_formsubmissionevent;
                DROP POLICY IF EXISTS stepassignment_tenant_isolation ON workflows_stepassignment;
                DROP POLICY IF EXISTS usernotification_tenant_isolation ON workflows_usernotification;
                -- workflowexecution table does not exist (skipped)

                -- Disable RLS
                ALTER TABLE workflows_tenantlist DISABLE ROW LEVEL SECURITY;
                ALTER TABLE workflows_tenantform DISABLE ROW LEVEL SECURITY;
                ALTER TABLE workflows_tenantformentity DISABLE ROW LEVEL SECURITY;
                ALTER TABLE workflows_tenantformfield DISABLE ROW LEVEL SECURITY;
                ALTER TABLE workflows_tenantformrule DISABLE ROW LEVEL SECURITY;
                ALTER TABLE workflows_tenantworkflow DISABLE ROW LEVEL SECURITY;
                ALTER TABLE workflows_tenantworkflowcondition DISABLE ROW LEVEL SECURITY;
                ALTER TABLE workflows_tenantworkflowaction DISABLE ROW LEVEL SECURITY;
                ALTER TABLE workflows_workflowexecutionlog DISABLE ROW LEVEL SECURITY;
                ALTER TABLE workflows_formsubmission DISABLE ROW LEVEL SECURITY;
                -- formsubmissionvalue table does not exist (skipped)
                ALTER TABLE workflows_formsubmissionfile DISABLE ROW LEVEL SECURITY;
                ALTER TABLE workflows_formsubmissionevent DISABLE ROW LEVEL SECURITY;
                ALTER TABLE workflows_stepassignment DISABLE ROW LEVEL SECURITY;
                ALTER TABLE workflows_usernotification DISABLE ROW LEVEL SECURITY;
                -- workflowexecution table does not exist (skipped)
            END $$;
            """
        ),
    ]
