# Generated by Django 6.0 on 2026-02-27 20:32

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.special import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0010_add_tenant_configuration"),
        ("workflows", "0015_sync_workflow_rls_state"),
    ]

    operations = [
        # NOTE: This migration originally attempted to drop RLS policies and remove tenant fields.
        # That breaks fresh installs and violates our tenant isolation guarantees.
        # We keep only the non-destructive metadata/field alterations below.
        migrations.AlterField(
            model_name="tenantform",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="tenantform",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="tenantformentity",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="tenantformfield",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="tenantformrule",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="tenantlist",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="tenantlist",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="tenantworkflow",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="tenantworkflow",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="tenantworkflowaction",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="tenantworkflowcondition",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="workflowexecutionlog",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
    ]
