# Generated by Django 6.0 on 2026-02-27 20:32

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.special import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0010_add_tenant_configuration"),
        ("workflows", "0015_sync_workflow_rls_state"),
    ]

    operations = [
        # ======================================
        # CRITICAL: Drop RLS policies FIRST before removing tenant fields
        # The tenant_id column is referenced by RLS policies, so we must
        # drop the policies before dropping the column.
        # ======================================
        RunSQL(
            sql="""
            -- Drop RLS policies for formsubmission
            DROP POLICY IF EXISTS workflows_formsubmission_tenant_isolation ON workflows_formsubmission;
            DROP POLICY IF EXISTS formsubmission_tenant_isolation ON workflows_formsubmission;
            
            -- Drop RLS policies for stepassignment  
            DROP POLICY IF EXISTS workflows_stepassignment_tenant_isolation ON workflows_stepassignment;
            DROP POLICY IF EXISTS stepassignment_tenant_isolation ON workflows_stepassignment;
            
            -- Drop RLS policies for usernotification
            DROP POLICY IF EXISTS workflows_usernotification_tenant_isolation ON workflows_usernotification;
            DROP POLICY IF EXISTS usernotification_tenant_isolation ON workflows_usernotification;
            """,
            reverse_sql="""
            -- Recreate RLS policies if rolling back
            CREATE POLICY workflows_formsubmission_tenant_isolation ON workflows_formsubmission
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
                
            CREATE POLICY workflows_stepassignment_tenant_isolation ON workflows_stepassignment
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
                
            CREATE POLICY workflows_usernotification_tenant_isolation ON workflows_usernotification
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """
        ),
        # Now safe to remove indexes and fields
        migrations.RemoveIndex(
            model_name="formsubmission",
            name="workflows_f_tenant__8314a5_idx",
        ),
        migrations.RemoveIndex(
            model_name="stepassignment",
            name="workflows_s_tenant__3c0364_idx",
        ),
        migrations.RemoveIndex(
            model_name="usernotification",
            name="workflows_u_tenant__b2d0bd_idx",
        ),
        migrations.AlterField(
            model_name="tenantform",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="tenantform",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="tenantformentity",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="tenantformfield",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="tenantformrule",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="tenantlist",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="tenantlist",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="tenantworkflow",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="tenantworkflow",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="tenantworkflowaction",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="tenantworkflowcondition",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="workflowexecutionlog",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.RemoveField(
            model_name="formsubmission",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="stepassignment",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="usernotification",
            name="tenant",
        ),
    ]
