# Generated by Django 4.2 on 2026-03-04 (Manual Creation)

from django.db import migrations, models
import django.db.models.deletion



def backfill_tenant_for_formstepsubmission(apps, schema_editor):
    """Backfill tenant for FormStepSubmission from submission.tenant"""
    FormStepSubmission = apps.get_model('workflows', 'FormStepSubmission')
    
    # Use raw SQL for efficiency with large datasets
    schema_editor.execute("""
        UPDATE workflows_formstepsubmission fss
        SET tenant_id = fs.tenant_id
        FROM workflows_formsubmission fs
        WHERE fss.submission_id = fs.id
        AND fss.tenant_id IS NULL;
    """)
    
    print(f"✓ Backfilled tenant for {FormStepSubmission.objects.filter(tenant__isnull=False).count()} FormStepSubmission records")


def backfill_tenant_for_stepassignment(apps, schema_editor):
    """Backfill tenant for StepAssignment from form.tenant"""
    StepAssignment = apps.get_model('workflows', 'StepAssignment')
    
    # Use raw SQL for efficiency
    schema_editor.execute("""
        UPDATE workflows_stepassignment sa
        SET tenant_id = f.tenant_id
        FROM workflows_tenantform f
        WHERE sa.form_id = f.id
        AND sa.tenant_id IS NULL;
    """)
    
    print(f"✓ Backfilled tenant for {StepAssignment.objects.filter(tenant__isnull=False).count()} StepAssignment records")


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0021_remove_tenantformfield_computed_validation_and_more'),
        ('tenants', '0001_initial'),  # Dependency on Tenant model
    ]

    operations = [
        # Step 1: Add tenant field to FormStepSubmission (nullable for backfill)
        migrations.AddField(
            model_name='formstepsubmission',
            name='tenant',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=models.CASCADE,
                related_name='form_step_submissions',
                to='tenants.tenant',
                help_text='Tenant owning this step submission'
            ),
        ),
        
        # Step 2: Backfill tenant values from parent relationships
        migrations.RunPython(
            backfill_tenant_for_formstepsubmission,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 3: Make tenant required (after backfill)
        migrations.AlterField(
            model_name='formstepsubmission',
            name='tenant',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='form_step_submissions',
                to='tenants.tenant',
                help_text='Tenant owning this step submission'
            ),
        ),
        # Step 4: Add database indexes for performance
        migrations.AddIndex(
            model_name='formstepsubmission',
            index=models.Index(fields=['tenant', 'status'], name='fss_tenant_status_idx'),
        ),
        # Step 5: Enable Row-Level Security (RLS) for tenant isolation
        migrations.RunSQL(
            sql="""
            -- Enable RLS on FormStepSubmission
            ALTER TABLE workflows_formstepsubmission ENABLE ROW LEVEL SECURITY;
            
            CREATE POLICY formstepsubmission_tenant_isolation ON workflows_formstepsubmission
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS formstepsubmission_tenant_isolation ON workflows_formstepsubmission;
            ALTER TABLE workflows_formstepsubmission DISABLE ROW LEVEL SECURITY;
            
            """
        ),
    ]
