# Generated by Django 6.0 on 2026-03-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0022_add_tenant_to_step_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantworkflow",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Run"),
                    ("scheduled", "Scheduled Task"),
                    ("webhook", "Webhook (External API)"),
                    ("event", "Database Event"),
                    ("form_submit", "Form Submission"),
                    ("email_received", "Email Received"),
                    ("record_created", "New Record Created"),
                    ("record_updated", "Record Field Updated"),
                ],
                help_text="What triggers this workflow",
                max_length=30,
            ),
        ),
    ]
