# Generated by Django 6.0 on 2026-03-22
# Normalize RLS policy to safe current_setting('app.current_tenant', true)

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0023_alter_tenantworkflow_trigger_type"),
    ]

    operations = [
        RunSQL(
            sql="""
            ALTER TABLE workflows_formstepsubmission ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_formstepsubmission FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS formstepsubmission_tenant_isolation ON workflows_formstepsubmission;
            CREATE POLICY formstepsubmission_tenant_isolation ON workflows_formstepsubmission
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS formstepsubmission_tenant_isolation ON workflows_formstepsubmission;
            CREATE POLICY formstepsubmission_tenant_isolation ON workflows_formstepsubmission
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
        ),
    ]
