# Generated by Django 6.0 on 2026-03-22
# Add RLS policy for TenantFormVersion

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0024_fix_formstepsubmission_rls_policy_safe_current_setting"),
    ]

    operations = [
        RunSQL(
            sql="""
            ALTER TABLE workflows_tenantformversion ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantformversion FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS workflows_tenantformversion_tenant_isolation ON workflows_tenantformversion;
            CREATE POLICY workflows_tenantformversion_tenant_isolation ON workflows_tenantformversion
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS workflows_tenantformversion_tenant_isolation ON workflows_tenantformversion;
            ALTER TABLE workflows_tenantformversion NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantformversion DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
