# Generated by Django 6.0 on 2026-03-30 (Manual Creation)
# Fix: Add missing tenant_id column to workflows_usernotification
#
# Root Cause: Migration 0008 was retroactively modified to include the tenant
# ForeignKey after it had already been applied to production, leaving the
# database table without the tenant_id column.  Django's migration state
# (re-read from the updated 0008) already "knows" about the field and index,
# so this migration performs DATABASE-ONLY operations (no state changes).
#
# Pattern mirrors 0022_add_tenant_to_step_models.py.

from django.db import migrations


def backfill_tenant_for_usernotification(apps, schema_editor):
    """
    Backfill tenant for UserNotification from the user's first tenant membership.

    Notifications are user-scoped; we assign the earliest tenant the user
    belongs to via the tenants_tenant_user join table.  Any notification whose
    user has no tenant membership is deleted — it cannot be assigned to any
    tenant and would otherwise block the NOT NULL constraint.
    """
    schema_editor.execute(
        """
        UPDATE workflows_usernotification un
        SET tenant_id = (
            SELECT tu.tenant_id
            FROM tenants_tenant_user tu
            WHERE tu.user_id = un.user_id
            ORDER BY tu.id
            LIMIT 1
        )
        WHERE un.tenant_id IS NULL;
    """
    )

    schema_editor.execute(
        """
        DELETE FROM workflows_usernotification
        WHERE tenant_id IS NULL;
    """
    )


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0025_add_rls_tenantformversion"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        # Step 1: Add tenant_id column (NULL, idempotent, DB-only)
        # State already reflects this field from retroactively-updated 0008.
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'workflows_usernotification'
                      AND column_name = 'tenant_id'
                ) THEN
                    ALTER TABLE workflows_usernotification ADD COLUMN tenant_id uuid NULL;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 2: Add FK constraint (idempotent, DB-only)
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint c
                    JOIN pg_class t ON t.oid = c.conrelid
                    WHERE t.relname = 'workflows_usernotification'
                      AND c.conname = 'workflows_usernotification_tenant_id_fkey'
                ) THEN
                    ALTER TABLE workflows_usernotification
                        ADD CONSTRAINT workflows_usernotification_tenant_id_fkey
                        FOREIGN KEY (tenant_id)
                        REFERENCES tenants_tenant(id)
                        ON DELETE CASCADE;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE workflows_usernotification
                DROP CONSTRAINT IF EXISTS workflows_usernotification_tenant_id_fkey;
            """,
        ),
        # Step 3: Backfill tenant from user's tenant membership; delete orphans
        migrations.RunPython(
            backfill_tenant_for_usernotification,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 4: Make tenant_id NOT NULL after backfill (DB-only)
        migrations.RunSQL(
            sql="""
            ALTER TABLE workflows_usernotification
                ALTER COLUMN tenant_id SET NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE workflows_usernotification
                ALTER COLUMN tenant_id DROP NOT NULL;
            """,
        ),
        # Step 5: Add index on (tenant_id, created_at DESC) — idempotent, DB-only
        # State already reflects this index from retroactively-updated 0008.
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS workflows_u_tenant__b2d0bd_idx
                ON workflows_usernotification (tenant_id, created_at DESC);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS workflows_u_tenant__b2d0bd_idx;
            """,
        ),
        # Step 6: Enable RLS and (re)create tenant isolation policy
        migrations.RunSQL(
            sql="""
            ALTER TABLE workflows_usernotification ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_usernotification FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS usernotification_tenant_isolation ON workflows_usernotification;
            CREATE POLICY usernotification_tenant_isolation ON workflows_usernotification
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS usernotification_tenant_isolation ON workflows_usernotification;
            ALTER TABLE workflows_usernotification NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE workflows_usernotification DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
