# Generated by Django 6.0 on 2026-03-30 (Manual Creation)
# Fix: Add missing tenant_id column to workflows_stepassignment
# The tenant field exists in the Django ORM state (migration 0008 CreateModel included it),
# but the column is missing from the actual database table because migration 0008 was
# retroactively modified after it was applied to production.
# This migration only performs database operations - state is already correct.

from django.db import migrations


def backfill_tenant_for_stepassignment(apps, schema_editor):
    """Backfill tenant for StepAssignment from form.tenant."""
    schema_editor.execute("""
        UPDATE workflows_stepassignment sa
        SET tenant_id = f.tenant_id
        FROM workflows_tenantform f
        WHERE sa.form_id = f.id
        AND sa.tenant_id IS NULL;
    """)

    # Raise if any rows could not be resolved (would cause NOT NULL to fail in the next step).
    # This protects against orphaned StepAssignment rows (form deleted or form's tenant NULL).
    schema_editor.execute("""
        DO $$
        DECLARE
            orphan_count INTEGER;
        BEGIN
            SELECT COUNT(*) INTO orphan_count
            FROM workflows_stepassignment
            WHERE tenant_id IS NULL;

            IF orphan_count > 0 THEN
                RAISE EXCEPTION
                    'Cannot backfill tenant_id: % StepAssignment row(s) have no resolvable '
                    'tenant (form deleted or form.tenant_id is NULL). Resolve these rows before '
                    're-running the migration.',
                    orphan_count;
            END IF;
        END $$;
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0025_add_rls_tenantformversion'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        # Step 1: Add tenant_id column to the database (idempotent).
        # State already has the field from migration 0008, so only database_operations needed.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'workflows_stepassignment'
                              AND column_name = 'tenant_id'
                        ) THEN
                            ALTER TABLE workflows_stepassignment ADD COLUMN tenant_id uuid NULL;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint c
                            JOIN pg_class t ON t.oid = c.conrelid
                            WHERE t.relname = 'workflows_stepassignment'
                              AND c.conname = 'workflows_stepassignment_tenant_id_fkey'
                        ) THEN
                            ALTER TABLE workflows_stepassignment
                                ADD CONSTRAINT workflows_stepassignment_tenant_id_fkey
                                FOREIGN KEY (tenant_id)
                                REFERENCES tenants_tenant(id)
                                ON DELETE CASCADE;
                        END IF;
                    END $$;
                    """,
                    reverse_sql="""
                    ALTER TABLE workflows_stepassignment
                        DROP CONSTRAINT IF EXISTS workflows_stepassignment_tenant_id_fkey;
                    """,
                ),
            ],
            state_operations=[],
        ),

        # Step 2: Backfill tenant values from form.tenant
        migrations.RunPython(
            backfill_tenant_for_stepassignment,
            reverse_code=migrations.RunPython.noop,
        ),

        # Step 3: Make tenant_id NOT NULL (after backfill)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE workflows_stepassignment
                        ALTER COLUMN tenant_id SET NOT NULL;
                    """,
                    reverse_sql="""
                    ALTER TABLE workflows_stepassignment
                        ALTER COLUMN tenant_id DROP NOT NULL;
                    """,
                ),
            ],
            state_operations=[],
        ),

        # Step 4: Add performance index (idempotent).
        # Index workflows_s_tenant__3c0364_idx is defined in migration 0008's model options
        # but may not exist in the database. Use CREATE INDEX IF NOT EXISTS to be safe.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE INDEX IF NOT EXISTS workflows_s_tenant__3c0364_idx
                        ON workflows_stepassignment (tenant_id, form_id);
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS workflows_s_tenant__3c0364_idx;
                    """,
                ),
            ],
            state_operations=[],
        ),

        # Step 5: Fix the RLS policy for tenant isolation.
        # Migration 0015 attempted to create this policy but it would have failed
        # (silently or not) because tenant_id didn't exist. Drop and recreate idempotently.
        migrations.RunSQL(
            sql="""
            ALTER TABLE workflows_stepassignment ENABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS stepassignment_tenant_isolation ON workflows_stepassignment;
            CREATE POLICY stepassignment_tenant_isolation ON workflows_stepassignment
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS stepassignment_tenant_isolation ON workflows_stepassignment;
            ALTER TABLE workflows_stepassignment DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
