# Generated by Django 6.0 on 2026-03-30 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0026_add_tenant_to_stepassignment"),
        ("workflows", "0026_add_tenant_to_usernotification"),
    ]

    operations = []
