# Generated by Django 6.0 on 2026-03-30 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0012_tenant_contact_phone_type"),
        ("workflows", "0027_merge_20260330_0146"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotificationpreferences",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant context for these preferences",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_notification_preferences",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="usernotificationpreferences",
            name="user",
            field=models.ForeignKey(
                help_text="User for these preferences",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="usernotificationpreferences",
            constraint=models.UniqueConstraint(fields=("user", "tenant"), name="uniq_user_tenant_notification_prefs"),
        ),
    ]
