# Generated by Django 6.0 on 2026-03-31 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0014_enable_rls_tenant_product_preference"),
        ("tenants", "0013_alter_activitylog_action"),
        ("workflows", "0029_ensure_tenantlist_insert_policy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantWorkFormExecution",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current execution status",
                        max_length=20,
                    ),
                ),
                (
                    "initial_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Trigger/initial payload used to start execution"
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Execution context snapshot (variables, errors, outputs)"
                    ),
                ),
                (
                    "audit_trail",
                    models.JSONField(
                        blank=True, default=list, help_text="Chronological log of node transitions and actions"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who started this execution (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_workform_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "workform",
                    models.ForeignKey(
                        help_text="TenantWorkForm that was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="system.tenantworkform",
                    ),
                ),
            ],
            options={
                "verbose_name": "WorkForm Execution",
                "verbose_name_plural": "WorkForm Executions",
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="workflows_t_tenant__c4ec0b_idx"),
                    models.Index(fields=["tenant", "workform"], name="workflows_t_tenant__d1aaa2_idx"),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE workflows_tenantworkformexecution ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantworkformexecution FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS tenantworkformexecution_tenant_insert ON workflows_tenantworkformexecution;
            DROP POLICY IF EXISTS tenantworkformexecution_tenant_isolation ON workflows_tenantworkformexecution;

            CREATE POLICY tenantworkformexecution_tenant_isolation ON workflows_tenantworkformexecution
              USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

            CREATE POLICY tenantworkformexecution_tenant_insert ON workflows_tenantworkformexecution
              FOR INSERT WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tenantworkformexecution_tenant_insert ON workflows_tenantworkformexecution;
            DROP POLICY IF EXISTS tenantworkformexecution_tenant_isolation ON workflows_tenantworkformexecution;
            ALTER TABLE workflows_tenantworkformexecution NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantworkformexecution DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
