# Generated by Django 6.0 on 2026-04-21
# Fix: make Workflow RLS policies safe when app.current_tenant is set to ''
#
# Some historical migrations used:
#   current_setting('app.current_tenant', true)::uuid
# which will raise "invalid input syntax for type uuid" when the session var is
# present but empty string. This migration updates policies to:
#   NULLIF(current_setting('app.current_tenant', true), '')::uuid

from django.db import migrations


SAFE_TENANT_UUID = "NULLIF(current_setting('app.current_tenant', true), '')::uuid"
UNSAFE_TENANT_UUID = "current_setting('app.current_tenant', true)::uuid"


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0031_fix_missing_created_on_modified_on"),
    ]

    operations = [
        migrations.RunSQL(
            sql=f"""
            -- Ensure RLS session var casts are safe even when app.current_tenant = ''

            -- Core workflow tables (+ insert policies where used)
            ALTER TABLE workflows_tenantlist ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantlist FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantlist_tenant_isolation ON workflows_tenantlist;
            CREATE POLICY tenantlist_tenant_isolation ON workflows_tenantlist
                USING (tenant_id = {SAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantlist_tenant_insert ON workflows_tenantlist;
            CREATE POLICY tenantlist_tenant_insert ON workflows_tenantlist
                FOR INSERT WITH CHECK (tenant_id = {SAFE_TENANT_UUID});

            ALTER TABLE workflows_tenantform ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantform FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantform_tenant_isolation ON workflows_tenantform;
            CREATE POLICY tenantform_tenant_isolation ON workflows_tenantform
                USING (tenant_id = {SAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantform_tenant_insert ON workflows_tenantform;
            CREATE POLICY tenantform_tenant_insert ON workflows_tenantform
                FOR INSERT WITH CHECK (tenant_id = {SAFE_TENANT_UUID});

            ALTER TABLE workflows_tenantformentity ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantformentity FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantformentity_tenant_isolation ON workflows_tenantformentity;
            CREATE POLICY tenantformentity_tenant_isolation ON workflows_tenantformentity
                USING (tenant_id = {SAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantformentity_tenant_insert ON workflows_tenantformentity;
            CREATE POLICY tenantformentity_tenant_insert ON workflows_tenantformentity
                FOR INSERT WITH CHECK (tenant_id = {SAFE_TENANT_UUID});

            ALTER TABLE workflows_tenantformfield ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantformfield FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantformfield_tenant_isolation ON workflows_tenantformfield;
            CREATE POLICY tenantformfield_tenant_isolation ON workflows_tenantformfield
                USING (tenant_id = {SAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantformfield_tenant_insert ON workflows_tenantformfield;
            CREATE POLICY tenantformfield_tenant_insert ON workflows_tenantformfield
                FOR INSERT WITH CHECK (tenant_id = {SAFE_TENANT_UUID});

            ALTER TABLE workflows_tenantformrule ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantformrule FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantformrule_tenant_isolation ON workflows_tenantformrule;
            CREATE POLICY tenantformrule_tenant_isolation ON workflows_tenantformrule
                USING (tenant_id = {SAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantformrule_tenant_insert ON workflows_tenantformrule;
            CREATE POLICY tenantformrule_tenant_insert ON workflows_tenantformrule
                FOR INSERT WITH CHECK (tenant_id = {SAFE_TENANT_UUID});

            ALTER TABLE workflows_tenantworkflow ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantworkflow FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantworkflow_tenant_isolation ON workflows_tenantworkflow;
            CREATE POLICY tenantworkflow_tenant_isolation ON workflows_tenantworkflow
                USING (tenant_id = {SAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantworkflow_tenant_insert ON workflows_tenantworkflow;
            CREATE POLICY tenantworkflow_tenant_insert ON workflows_tenantworkflow
                FOR INSERT WITH CHECK (tenant_id = {SAFE_TENANT_UUID});

            ALTER TABLE workflows_tenantworkflowcondition ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantworkflowcondition FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantworkflowcondition_tenant_isolation ON workflows_tenantworkflowcondition;
            CREATE POLICY tenantworkflowcondition_tenant_isolation ON workflows_tenantworkflowcondition
                USING (tenant_id = {SAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantworkflowcondition_tenant_insert ON workflows_tenantworkflowcondition;
            CREATE POLICY tenantworkflowcondition_tenant_insert ON workflows_tenantworkflowcondition
                FOR INSERT WITH CHECK (tenant_id = {SAFE_TENANT_UUID});

            ALTER TABLE workflows_tenantworkflowaction ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantworkflowaction FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantworkflowaction_tenant_isolation ON workflows_tenantworkflowaction;
            CREATE POLICY tenantworkflowaction_tenant_isolation ON workflows_tenantworkflowaction
                USING (tenant_id = {SAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantworkflowaction_tenant_insert ON workflows_tenantworkflowaction;
            CREATE POLICY tenantworkflowaction_tenant_insert ON workflows_tenantworkflowaction
                FOR INSERT WITH CHECK (tenant_id = {SAFE_TENANT_UUID});

            ALTER TABLE workflows_workflowexecutionlog ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_workflowexecutionlog FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS workflowexecutionlog_tenant_isolation ON workflows_workflowexecutionlog;
            CREATE POLICY workflowexecutionlog_tenant_isolation ON workflows_workflowexecutionlog
                USING (tenant_id = {SAFE_TENANT_UUID});
            DROP POLICY IF EXISTS workflowexecutionlog_tenant_insert ON workflows_workflowexecutionlog;
            CREATE POLICY workflowexecutionlog_tenant_insert ON workflows_workflowexecutionlog
                FOR INSERT WITH CHECK (tenant_id = {SAFE_TENANT_UUID});

            -- Form submissions
            ALTER TABLE workflows_formsubmission ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_formsubmission FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS formsubmission_tenant_isolation ON workflows_formsubmission;
            CREATE POLICY formsubmission_tenant_isolation ON workflows_formsubmission
                USING (tenant_id = {SAFE_TENANT_UUID});

            ALTER TABLE workflows_formsubmissionfile ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_formsubmissionfile FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS formsubmissionfile_tenant_isolation ON workflows_formsubmissionfile;
            CREATE POLICY formsubmissionfile_tenant_isolation ON workflows_formsubmissionfile
                USING (
                    submission_id IN (
                        SELECT id FROM workflows_formsubmission
                        WHERE tenant_id = {SAFE_TENANT_UUID}
                    )
                );

            ALTER TABLE workflows_formsubmissionevent ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_formsubmissionevent FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS formsubmissionevent_tenant_isolation ON workflows_formsubmissionevent;
            CREATE POLICY formsubmissionevent_tenant_isolation ON workflows_formsubmissionevent
                USING (
                    submission_id IN (
                        SELECT id FROM workflows_formsubmission
                        WHERE tenant_id = {SAFE_TENANT_UUID}
                    )
                );

            -- Assignments, notifications, and step submissions
            ALTER TABLE workflows_stepassignment ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_stepassignment FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS stepassignment_tenant_isolation ON workflows_stepassignment;
            CREATE POLICY stepassignment_tenant_isolation ON workflows_stepassignment
                USING (tenant_id = {SAFE_TENANT_UUID});

            ALTER TABLE workflows_usernotification ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_usernotification FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS usernotification_tenant_isolation ON workflows_usernotification;
            CREATE POLICY usernotification_tenant_isolation ON workflows_usernotification
                USING (tenant_id = {SAFE_TENANT_UUID});

            ALTER TABLE workflows_formstepsubmission ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_formstepsubmission FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS formstepsubmission_tenant_isolation ON workflows_formstepsubmission;
            CREATE POLICY formstepsubmission_tenant_isolation ON workflows_formstepsubmission
                FOR ALL
                USING (tenant_id = {SAFE_TENANT_UUID});

            -- TenantFormVersion
            ALTER TABLE workflows_tenantformversion ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantformversion FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS workflows_tenantformversion_tenant_isolation ON workflows_tenantformversion;
            CREATE POLICY workflows_tenantformversion_tenant_isolation ON workflows_tenantformversion
                FOR ALL
                USING (tenant_id = {SAFE_TENANT_UUID});

            -- TenantWorkFormExecution
            ALTER TABLE workflows_tenantworkformexecution ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantworkformexecution FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantworkformexecution_tenant_isolation ON workflows_tenantworkformexecution;
            CREATE POLICY tenantworkformexecution_tenant_isolation ON workflows_tenantworkformexecution
                USING (tenant_id = {SAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantworkformexecution_tenant_insert ON workflows_tenantworkformexecution;
            CREATE POLICY tenantworkformexecution_tenant_insert ON workflows_tenantworkformexecution
                FOR INSERT WITH CHECK (tenant_id = {SAFE_TENANT_UUID});
            """,
            reverse_sql=f"""
            -- Reverse: restore historical (unsafe) casts

            ALTER TABLE workflows_tenantlist ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantlist FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantlist_tenant_isolation ON workflows_tenantlist;
            CREATE POLICY tenantlist_tenant_isolation ON workflows_tenantlist
                USING (tenant_id = {UNSAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantlist_tenant_insert ON workflows_tenantlist;
            CREATE POLICY tenantlist_tenant_insert ON workflows_tenantlist
                FOR INSERT WITH CHECK (tenant_id = {UNSAFE_TENANT_UUID});

            ALTER TABLE workflows_tenantform ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantform FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantform_tenant_isolation ON workflows_tenantform;
            CREATE POLICY tenantform_tenant_isolation ON workflows_tenantform
                USING (tenant_id = {UNSAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantform_tenant_insert ON workflows_tenantform;
            CREATE POLICY tenantform_tenant_insert ON workflows_tenantform
                FOR INSERT WITH CHECK (tenant_id = {UNSAFE_TENANT_UUID});

            ALTER TABLE workflows_tenantformentity ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantformentity FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantformentity_tenant_isolation ON workflows_tenantformentity;
            CREATE POLICY tenantformentity_tenant_isolation ON workflows_tenantformentity
                USING (tenant_id = {UNSAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantformentity_tenant_insert ON workflows_tenantformentity;
            CREATE POLICY tenantformentity_tenant_insert ON workflows_tenantformentity
                FOR INSERT WITH CHECK (tenant_id = {UNSAFE_TENANT_UUID});

            ALTER TABLE workflows_tenantformfield ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantformfield FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantformfield_tenant_isolation ON workflows_tenantformfield;
            CREATE POLICY tenantformfield_tenant_isolation ON workflows_tenantformfield
                USING (tenant_id = {UNSAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantformfield_tenant_insert ON workflows_tenantformfield;
            CREATE POLICY tenantformfield_tenant_insert ON workflows_tenantformfield
                FOR INSERT WITH CHECK (tenant_id = {UNSAFE_TENANT_UUID});

            ALTER TABLE workflows_tenantformrule ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantformrule FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantformrule_tenant_isolation ON workflows_tenantformrule;
            CREATE POLICY tenantformrule_tenant_isolation ON workflows_tenantformrule
                USING (tenant_id = {UNSAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantformrule_tenant_insert ON workflows_tenantformrule;
            CREATE POLICY tenantformrule_tenant_insert ON workflows_tenantformrule
                FOR INSERT WITH CHECK (tenant_id = {UNSAFE_TENANT_UUID});

            ALTER TABLE workflows_tenantworkflow ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantworkflow FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantworkflow_tenant_isolation ON workflows_tenantworkflow;
            CREATE POLICY tenantworkflow_tenant_isolation ON workflows_tenantworkflow
                USING (tenant_id = {UNSAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantworkflow_tenant_insert ON workflows_tenantworkflow;
            CREATE POLICY tenantworkflow_tenant_insert ON workflows_tenantworkflow
                FOR INSERT WITH CHECK (tenant_id = {UNSAFE_TENANT_UUID});

            ALTER TABLE workflows_tenantworkflowcondition ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantworkflowcondition FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantworkflowcondition_tenant_isolation ON workflows_tenantworkflowcondition;
            CREATE POLICY tenantworkflowcondition_tenant_isolation ON workflows_tenantworkflowcondition
                USING (tenant_id = {UNSAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantworkflowcondition_tenant_insert ON workflows_tenantworkflowcondition;
            CREATE POLICY tenantworkflowcondition_tenant_insert ON workflows_tenantworkflowcondition
                FOR INSERT WITH CHECK (tenant_id = {UNSAFE_TENANT_UUID});

            ALTER TABLE workflows_tenantworkflowaction ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantworkflowaction FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantworkflowaction_tenant_isolation ON workflows_tenantworkflowaction;
            CREATE POLICY tenantworkflowaction_tenant_isolation ON workflows_tenantworkflowaction
                USING (tenant_id = {UNSAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantworkflowaction_tenant_insert ON workflows_tenantworkflowaction;
            CREATE POLICY tenantworkflowaction_tenant_insert ON workflows_tenantworkflowaction
                FOR INSERT WITH CHECK (tenant_id = {UNSAFE_TENANT_UUID});

            ALTER TABLE workflows_workflowexecutionlog ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_workflowexecutionlog FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS workflowexecutionlog_tenant_isolation ON workflows_workflowexecutionlog;
            CREATE POLICY workflowexecutionlog_tenant_isolation ON workflows_workflowexecutionlog
                USING (tenant_id = {UNSAFE_TENANT_UUID});
            DROP POLICY IF EXISTS workflowexecutionlog_tenant_insert ON workflows_workflowexecutionlog;
            CREATE POLICY workflowexecutionlog_tenant_insert ON workflows_workflowexecutionlog
                FOR INSERT WITH CHECK (tenant_id = {UNSAFE_TENANT_UUID});

            ALTER TABLE workflows_formsubmission ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_formsubmission FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS formsubmission_tenant_isolation ON workflows_formsubmission;
            CREATE POLICY formsubmission_tenant_isolation ON workflows_formsubmission
                USING (tenant_id = {UNSAFE_TENANT_UUID});

            ALTER TABLE workflows_formsubmissionfile ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_formsubmissionfile FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS formsubmissionfile_tenant_isolation ON workflows_formsubmissionfile;
            CREATE POLICY formsubmissionfile_tenant_isolation ON workflows_formsubmissionfile
                USING (
                    submission_id IN (
                        SELECT id FROM workflows_formsubmission
                        WHERE tenant_id = {UNSAFE_TENANT_UUID}
                    )
                );

            ALTER TABLE workflows_formsubmissionevent ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_formsubmissionevent FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS formsubmissionevent_tenant_isolation ON workflows_formsubmissionevent;
            CREATE POLICY formsubmissionevent_tenant_isolation ON workflows_formsubmissionevent
                USING (
                    submission_id IN (
                        SELECT id FROM workflows_formsubmission
                        WHERE tenant_id = {UNSAFE_TENANT_UUID}
                    )
                );

            ALTER TABLE workflows_stepassignment ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_stepassignment FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS stepassignment_tenant_isolation ON workflows_stepassignment;
            CREATE POLICY stepassignment_tenant_isolation ON workflows_stepassignment
                USING (tenant_id = {UNSAFE_TENANT_UUID});

            ALTER TABLE workflows_usernotification ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_usernotification FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS usernotification_tenant_isolation ON workflows_usernotification;
            CREATE POLICY usernotification_tenant_isolation ON workflows_usernotification
                USING (tenant_id = {UNSAFE_TENANT_UUID});

            ALTER TABLE workflows_formstepsubmission ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_formstepsubmission FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS formstepsubmission_tenant_isolation ON workflows_formstepsubmission;
            CREATE POLICY formstepsubmission_tenant_isolation ON workflows_formstepsubmission
                FOR ALL
                USING (tenant_id = {UNSAFE_TENANT_UUID});

            ALTER TABLE workflows_tenantformversion ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantformversion FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS workflows_tenantformversion_tenant_isolation ON workflows_tenantformversion;
            CREATE POLICY workflows_tenantformversion_tenant_isolation ON workflows_tenantformversion
                FOR ALL
                USING (tenant_id = {UNSAFE_TENANT_UUID});

            ALTER TABLE workflows_tenantworkformexecution ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_tenantworkformexecution FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenantworkformexecution_tenant_isolation ON workflows_tenantworkformexecution;
            CREATE POLICY tenantworkformexecution_tenant_isolation ON workflows_tenantworkformexecution
                USING (tenant_id = {UNSAFE_TENANT_UUID});
            DROP POLICY IF EXISTS tenantworkformexecution_tenant_insert ON workflows_tenantworkformexecution;
            CREATE POLICY tenantworkformexecution_tenant_insert ON workflows_tenantworkformexecution
                FOR INSERT WITH CHECK (tenant_id = {UNSAFE_TENANT_UUID});
            """,
        ),
    ]
