# Generated by Django 6.0 on 2026-04-27 23:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0015_enable_rls_tenant_forms_workforms"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        ("workflows", "0032_fix_workflows_rls_uuid_cast_safety"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantworkformexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("suspended", "Suspended"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                help_text="Current execution status",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WorkflowDeadLetter",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("node_id", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("node_type", models.CharField(blank=True, default="", max_length=128)),
                ("task_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("resolved", "Resolved"), ("discarded", "Discarded")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("trigger_data", models.JSONField(blank=True, default=dict)),
                ("execution_context", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("last_failed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "workform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dead_letters",
                        to="system.tenantworkform",
                    ),
                ),
                (
                    "workform_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dead_letters",
                        to="workflows.tenantworkformexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_failed_at"],
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="wf_dlq_tenant_status"),
                    models.Index(fields=["tenant", "workform_execution"], name="wf_dlq_t_wfexec"),
                    models.Index(fields=["tenant", "node_id"], name="wf_dlq_t_node"),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE workflows_workflowdeadletter ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_workflowdeadletter FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS workflowdeadletter_tenant_insert ON workflows_workflowdeadletter;
            DROP POLICY IF EXISTS workflowdeadletter_tenant_isolation ON workflows_workflowdeadletter;

            CREATE POLICY workflowdeadletter_tenant_isolation ON workflows_workflowdeadletter
              USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

            CREATE POLICY workflowdeadletter_tenant_insert ON workflows_workflowdeadletter
              FOR INSERT WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS workflowdeadletter_tenant_insert ON workflows_workflowdeadletter;
            DROP POLICY IF EXISTS workflowdeadletter_tenant_isolation ON workflows_workflowdeadletter;
            ALTER TABLE workflows_workflowdeadletter NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE workflows_workflowdeadletter DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
