# Generated by Django 6.0 on 2026-04-28 08:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0015_enable_rls_tenant_forms_workforms"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        ("workflows", "0033_workform_deadletter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionEventLog",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "sequence",
                    models.PositiveIntegerField(default=0, help_text="Monotonic order within a single execution"),
                ),
                ("event_type", models.CharField(db_index=True, help_text="Canonical event name", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("info", "Info"),
                        ],
                        db_index=True,
                        default="info",
                        help_text="Normalized event status",
                        max_length=20,
                    ),
                ),
                ("node_id", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("node_type", models.CharField(blank=True, default="", max_length=128)),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="When the event or node span started"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="When the event or node span completed", null=True),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(blank=True, help_text="Observed duration in milliseconds", null=True),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, help_text="Minimal event payload for analytics/debugging"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "workform",
                    models.ForeignKey(
                        help_text="TenantWorkForm associated with this telemetry event",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_event_logs",
                        to="system.tenantworkform",
                    ),
                ),
                (
                    "workform_execution",
                    models.ForeignKey(
                        help_text="Execution that produced this telemetry event",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_logs",
                        to="workflows.tenantworkformexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["workform_execution", "sequence", "created_on"],
                "indexes": [
                    models.Index(fields=["tenant", "workform_execution", "sequence"], name="wf_evt_t_exec_seq"),
                    models.Index(fields=["tenant", "workform", "status"], name="wf_evt_t_wf_status"),
                    models.Index(fields=["tenant", "node_id"], name="wf_evt_t_node"),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE workflows_executioneventlog ENABLE ROW LEVEL SECURITY;
            ALTER TABLE workflows_executioneventlog FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS executioneventlog_tenant_insert ON workflows_executioneventlog;
            DROP POLICY IF EXISTS executioneventlog_tenant_isolation ON workflows_executioneventlog;

            CREATE POLICY executioneventlog_tenant_isolation ON workflows_executioneventlog
              USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

            CREATE POLICY executioneventlog_tenant_insert ON workflows_executioneventlog
              FOR INSERT WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS executioneventlog_tenant_insert ON workflows_executioneventlog;
            DROP POLICY IF EXISTS executioneventlog_tenant_isolation ON workflows_executioneventlog;
            ALTER TABLE workflows_executioneventlog NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE workflows_executioneventlog DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
