# Generated by Django 6.0 on 2026-04-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0034_executioneventlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantworkformexecution",
            name="runtime_state",
            field=models.JSONField(
                blank=True, default=dict, help_text="Hydrated runtime projection derived from execution telemetry"
            ),
        ),
    ]
