# Generated by Django 6.0 on 2025-12-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        help_text="Current status of the contact",
                        max_length=20,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Contact's first name", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Contact's last name", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        help_text="Company or organization",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Job position or title",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Sales", "Sales"),
                            ("Accounting", "Accounting"),
                            ("Shipping", "Shipping"),
                            ("Receiving", "Receiving"),
                            ("Operations", "Operations"),
                            ("Quality", "Quality"),
                            ("Executive", "Executive"),
                            ("Doc's BOL", "Doc's BOL"),
                            ("COA", "COA"),
                            ("POD", "POD"),
                        ],
                        default="",
                        help_text="Type of contact (e.g., Sales, Accounting, Shipping)",
                        max_length=50,
                    ),
                ),
                (
                    "contact_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact title/designation",
                        max_length=100,
                    ),
                ),
                (
                    "main_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Main phone number",
                        max_length=20,
                    ),
                ),
                (
                    "direct_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Direct phone number",
                        max_length=20,
                    ),
                ),
                (
                    "cell_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cell phone number",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
