# Generated by Django 6.0 on 2026-02-27 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_add_parent_entity_fields"),
        ("tenants", "0010_add_tenant_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.RunSQL(
            sql="""
            -- Enable Row-Level Security for contacts.Contact
            ALTER TABLE contacts_contact ENABLE ROW LEVEL SECURITY;
            
            -- Drop existing policy if it exists (idempotent)
            DROP POLICY IF EXISTS contact_tenant_isolation ON contacts_contact;
            
            -- Create RLS policy for tenant isolation
            CREATE POLICY contact_tenant_isolation ON contacts_contact
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            
            -- Create policy for INSERT operations
            CREATE POLICY contact_tenant_insert ON contacts_contact
            FOR INSERT
            WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            -- Disable Row-Level Security on rollback
            DROP POLICY IF EXISTS contact_tenant_insert ON contacts_contact;
            DROP POLICY IF EXISTS contact_tenant_isolation ON contacts_contact;
            ALTER TABLE contacts_contact DISABLE ROW LEVEL SECURITY;
            """
        ),
    ]
