# Generated by Django 6.0 on 2026-03-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_refactor_contact_to_tenantaware"),
    ]

    operations = []
