# Generated by Django 6.0 on 2026-03-18 03:16
# RLS for Contact model was already applied in migration 0004_refactor_contact_to_tenantaware.
# That migration enabled ENABLE ROW LEVEL SECURITY and created both isolation and insert policies
# using the modern app.current_tenant pattern. No additional operations needed here.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_refactor_contact_to_tenantaware"),
    ]

    operations = []
