# Generated by Django 6.0 on 2026-03-23 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_add_rls_policies_batch"),
        ("customers", "0010_add_rls_policies_batch"),
        ("locations", "0009_fix_locations_rls_policies_safe_current_setting"),
        ("plants", "0011_fix_plants_rls_policies_safe_current_setting"),
        ("suppliers", "0015_shorten_supplieravailableitem_index"),
        ("tenants", "0011_bootstrap_rls_session_vars"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Location this contact belongs to (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="Plant this contact belongs to (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="plants.plant",
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["tenant", "supplier"], name="contacts_co_tenant__5db512_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["tenant", "customer"], name="contacts_co_tenant__949c0f_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["tenant", "plant"], name="contacts_co_tenant__64fb68_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["tenant", "location"], name="contacts_co_tenant__99c730_idx"),
        ),
    ]
