# Generated by Django 6.0 on 2026-03-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0006_contact_location_contact_plant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone_type",
            field=models.CharField(
                blank=True,
                choices=[("mobile", "Mobile"), ("office", "Office")],
                default="office",
                help_text="Contact phone type (mobile or office)",
                max_length=10,
            ),
        ),
    ]
