# Generated by Django 6.0 on 2026-03-31 01:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0007_contact_phone_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sales", "Sales"),
                    ("qa", "Quality Assurance"),
                    ("booking", "Booking"),
                    ("accounting", "Accounting"),
                ],
                default="",
                help_text="Department this contact belongs to (Sales, QA, Booking, Accounting)",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="items_responsible",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Items this contact is responsible for (Sales only)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="mobile_phone",
            field=models.CharField(
                blank=True, default="", help_text="Mobile phone number (optional)", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="office_phone",
            field=models.CharField(
                blank=True, default="", help_text="Office phone number (optional)", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="office_phone_ext",
            field=models.CharField(
                blank=True, default="", help_text="Office phone extension (optional)", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="protein_types_responsible",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text="Protein types this contact is responsible for (Sales only)",
                null=True,
            ),
        ),
    ]
