# Generated by Django 6.0 on 2026-03-31 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0008_contact_department_contact_items_responsible_and_more"),
        ("core", "0003_remove_userfavorite_unique_user_favorite_and_more"),
        ("products", "0009_alter_masterproduct_protein"),
        ("tenants", "0013_alter_activitylog_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMasterProductResponsibility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_product_responsibility_links",
                        to="contacts.contact",
                    ),
                ),
                (
                    "master_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_responsibility_links",
                        to="products.masterproduct",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contact",
            name="products_responsible",
            field=models.ManyToManyField(
                blank=True,
                help_text="Master products this contact is responsible for (department-dependent)",
                related_name="contacts_responsible",
                through="contacts.ContactMasterProductResponsibility",
                to="products.masterproduct",
            ),
        ),
        migrations.CreateModel(
            name="ContactPreferredMasterProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_master_product_links",
                        to="contacts.contact",
                    ),
                ),
                (
                    "master_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_by_contact_links",
                        to="products.masterproduct",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contact",
            name="preferred_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Preferred master products (used for aggregated customer preferences)",
                related_name="preferred_by_contacts",
                through="contacts.ContactPreferredMasterProduct",
                to="products.masterproduct",
            ),
        ),
        migrations.CreateModel(
            name="ContactPreferredProtein",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_protein_links",
                        to="contacts.contact",
                    ),
                ),
                (
                    "protein",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_by_contact_links",
                        to="core.protein",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contact",
            name="preferred_protein_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Preferred proteins (used for aggregated customer preferences)",
                related_name="preferred_by_contacts",
                through="contacts.ContactPreferredProtein",
                to="core.protein",
            ),
        ),
        migrations.CreateModel(
            name="ContactProteinResponsibility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protein_responsibility_links",
                        to="contacts.contact",
                    ),
                ),
                (
                    "protein",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_responsibility_links",
                        to="core.protein",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contact",
            name="proteins_responsible",
            field=models.ManyToManyField(
                blank=True,
                help_text="Proteins this contact is responsible for (department-dependent)",
                related_name="contacts_responsible",
                through="contacts.ContactProteinResponsibility",
                to="core.protein",
            ),
        ),
        migrations.AddIndex(
            model_name="contactmasterproductresponsibility",
            index=models.Index(fields=["tenant", "contact"], name="contacts_co_tenant__2175b2_idx"),
        ),
        migrations.AddIndex(
            model_name="contactmasterproductresponsibility",
            index=models.Index(fields=["tenant", "master_product"], name="contacts_co_tenant__5e16f4_idx"),
        ),
        migrations.AddConstraint(
            model_name="contactmasterproductresponsibility",
            constraint=models.UniqueConstraint(
                fields=("tenant", "contact", "master_product"),
                name="unique_contact_master_product_responsibility_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="contactpreferredmasterproduct",
            index=models.Index(fields=["tenant", "contact"], name="contacts_co_tenant__c1608c_idx"),
        ),
        migrations.AddIndex(
            model_name="contactpreferredmasterproduct",
            index=models.Index(fields=["tenant", "master_product"], name="contacts_co_tenant__d8a487_idx"),
        ),
        migrations.AddConstraint(
            model_name="contactpreferredmasterproduct",
            constraint=models.UniqueConstraint(
                fields=("tenant", "contact", "master_product"),
                name="unique_contact_preferred_master_product_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="contactpreferredprotein",
            index=models.Index(fields=["tenant", "contact"], name="contacts_co_tenant__103891_idx"),
        ),
        migrations.AddIndex(
            model_name="contactpreferredprotein",
            index=models.Index(fields=["tenant", "protein"], name="contacts_co_tenant__b017a7_idx"),
        ),
        migrations.AddConstraint(
            model_name="contactpreferredprotein",
            constraint=models.UniqueConstraint(
                fields=("tenant", "contact", "protein"), name="unique_contact_preferred_protein_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="contactproteinresponsibility",
            index=models.Index(fields=["tenant", "contact"], name="contacts_co_tenant__3f1f30_idx"),
        ),
        migrations.AddIndex(
            model_name="contactproteinresponsibility",
            index=models.Index(fields=["tenant", "protein"], name="contacts_co_tenant__74209c_idx"),
        ),
        migrations.AddConstraint(
            model_name="contactproteinresponsibility",
            constraint=models.UniqueConstraint(
                fields=("tenant", "contact", "protein"), name="unique_contact_protein_responsibility_per_tenant"
            ),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE contacts_contactmasterproductresponsibility ENABLE ROW LEVEL SECURITY;
            ALTER TABLE contacts_contactmasterproductresponsibility FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS contactmasterproductresponsibility_tenant_isolation ON contacts_contactmasterproductresponsibility;
            CREATE POLICY contactmasterproductresponsibility_tenant_isolation ON contacts_contactmasterproductresponsibility
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);

            ALTER TABLE contacts_contactpreferredmasterproduct ENABLE ROW LEVEL SECURITY;
            ALTER TABLE contacts_contactpreferredmasterproduct FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS contactpreferredmasterproduct_tenant_isolation ON contacts_contactpreferredmasterproduct;
            CREATE POLICY contactpreferredmasterproduct_tenant_isolation ON contacts_contactpreferredmasterproduct
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);

            ALTER TABLE contacts_contactpreferredprotein ENABLE ROW LEVEL SECURITY;
            ALTER TABLE contacts_contactpreferredprotein FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS contactpreferredprotein_tenant_isolation ON contacts_contactpreferredprotein;
            CREATE POLICY contactpreferredprotein_tenant_isolation ON contacts_contactpreferredprotein
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);

            ALTER TABLE contacts_contactproteinresponsibility ENABLE ROW LEVEL SECURITY;
            ALTER TABLE contacts_contactproteinresponsibility FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS contactproteinresponsibility_tenant_isolation ON contacts_contactproteinresponsibility;
            CREATE POLICY contactproteinresponsibility_tenant_isolation ON contacts_contactproteinresponsibility
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS contactmasterproductresponsibility_tenant_isolation ON contacts_contactmasterproductresponsibility;
            ALTER TABLE contacts_contactmasterproductresponsibility NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE contacts_contactmasterproductresponsibility DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS contactpreferredmasterproduct_tenant_isolation ON contacts_contactpreferredmasterproduct;
            ALTER TABLE contacts_contactpreferredmasterproduct NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE contacts_contactpreferredmasterproduct DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS contactpreferredprotein_tenant_isolation ON contacts_contactpreferredprotein;
            ALTER TABLE contacts_contactpreferredprotein NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE contacts_contactpreferredprotein DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS contactproteinresponsibility_tenant_isolation ON contacts_contactproteinresponsibility;
            ALTER TABLE contacts_contactproteinresponsibility NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE contacts_contactproteinresponsibility DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
