# Generated by Django 6.0 on 2026-04-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0010_contact_shipping_and_additional_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sales", "Sales"),
                    ("qa", "Quality Assurance"),
                    ("shipping", "Shipping / Loadout"),
                    ("certification", "Certification"),
                    ("accounting", "Accounting"),
                    ("booking", "Booking (Deprecated)"),
                ],
                default="",
                help_text="Department this contact belongs to (Sales, QA, Shipping / Loadout, Certification, Accounting)",
                max_length=32,
                null=True,
            ),
        ),
    ]
