# Generated by Django 6.0 on 2026-01-28 18:00

import django.contrib.postgres.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carriers", "0004_carrier_departments_array_and_more"),
        ("customers", "0007_customer_custom_data_alter_customer_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FulfillmentProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_fulfilled",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Quantity being fulfilled in this shipment",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Price per unit for this fulfillment",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Line total for this fulfillment",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Line item notes"
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fulfillment Product",
                "verbose_name_plural": "Fulfillment Products",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Fulfillment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "fulfillment_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated fulfillment number (FUL-YYYY-NNNNN)",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the fulfillment",
                        max_length=20,
                    ),
                ),
                (
                    "ship_date",
                    models.DateField(
                        blank=True, help_text="When the shipment was sent", null=True
                    ),
                ),
                (
                    "expected_delivery",
                    models.DateField(
                        blank=True, help_text="Expected delivery date", null=True
                    ),
                ),
                (
                    "actual_delivery",
                    models.DateField(
                        blank=True, help_text="Actual delivery date", null=True
                    ),
                ),
                (
                    "tracking_numbers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Tracking numbers for this shipment",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Fulfillment notes"
                    ),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shipment carrier",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fulfillments",
                        to="carriers.carrier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this fulfillment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_fulfillments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer receiving the order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fulfillments",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fulfillment",
                "verbose_name_plural": "Fulfillments",
                "ordering": ["-created_on"],
            },
        ),
    ]
