# Generated by Django 6.0 on 2026-01-28 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fulfillments", "0001_initial"),
        ("inquiries", "0001_initial"),
        ("suppliers", "0009_supplier_custom_data_alter_supplier_tenant"),
        ("tenants", "0006_metadata_lockdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillment",
            name="inquiry",
            field=models.ForeignKey(
                help_text="Source inquiry being fulfilled",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fulfillments",
                to="inquiries.inquiry",
            ),
        ),
        migrations.AddField(
            model_name="fulfillment",
            name="shipped_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who marked as shipped",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipped_fulfillments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fulfillment",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Supplier fulfilling the order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fulfillments",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="fulfillment",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="fulfillmentproduct",
            name="fulfillment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="fulfillments.fulfillment",
            ),
        ),
        migrations.AddField(
            model_name="fulfillmentproduct",
            name="inquiry_product",
            field=models.ForeignKey(
                help_text="Link to the inquiry product being fulfilled",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fulfillment_lines",
                to="inquiries.inquiryproduct",
            ),
        ),
        migrations.AddIndex(
            model_name="fulfillment",
            index=models.Index(
                fields=["tenant", "fulfillment_number"],
                name="fulfillment_tenant__78790d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fulfillment",
            index=models.Index(fields=["tenant", "status"], name="fulfillment_tenant__12673c_idx"),
        ),
        migrations.AddIndex(
            model_name="fulfillment",
            index=models.Index(fields=["inquiry"], name="fulfillment_inquiry_1a7c13_idx"),
        ),
    ]
