# Generated by Django 6.0 on 2026-03-18 03:16
# Add RLS policies for Fulfillment model

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("fulfillments", "0002_initial"),
    ]

    operations = [
        RunSQL(
            sql="""
            -- Enable RLS on fulfillments_fulfillment
            ALTER TABLE fulfillments_fulfillment ENABLE ROW LEVEL SECURITY;

            -- Drop existing policies (idempotent)
            DROP POLICY IF EXISTS fulfillment_tenant_isolation ON fulfillments_fulfillment;
            DROP POLICY IF EXISTS fulfillment_tenant_insert ON fulfillments_fulfillment;

            -- Create tenant isolation policy for SELECT/UPDATE/DELETE
            CREATE POLICY fulfillment_tenant_isolation ON fulfillments_fulfillment
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- Create tenant isolation policy for INSERT
            CREATE POLICY fulfillment_tenant_insert ON fulfillments_fulfillment
                FOR INSERT
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS fulfillment_tenant_insert ON fulfillments_fulfillment;
            DROP POLICY IF EXISTS fulfillment_tenant_isolation ON fulfillments_fulfillment;
            ALTER TABLE fulfillments_fulfillment DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
