# Generated by Django 6.0 on 2026-03-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fulfillments", "0003_add_rls_policies_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillment",
            name="shipping_type",
            field=models.CharField(
                choices=[
                    ("tenant", "Tenant"),
                    ("customer_pickup", "Customer Pick-Up"),
                    ("supplier_delivering", "Supplier Delivering"),
                ],
                db_index=True,
                default="tenant",
                help_text="Shipping type (cascaded from inquiry)",
                max_length=32,
            ),
        ),
    ]
