# Generated by Django 6.0 on 2026-03-30 20:18

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("fulfillments", "0004_fulfillment_shipping_type"),
        ("tenants", "0013_alter_activitylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillmentproduct",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AddField(
            model_name="fulfillmentproduct",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fulfillment_products",
                to="tenants.tenant",
            ),
        ),
        RunSQL(
            sql="""
            UPDATE fulfillments_fulfillmentproduct fp
            SET tenant_id = f.tenant_id
            FROM fulfillments_fulfillment f
            WHERE fp.fulfillment_id = f.id
              AND fp.tenant_id IS NULL;
            """,
            reverse_sql=RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="fulfillmentproduct",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fulfillment_products",
                to="tenants.tenant",
            ),
        ),
        RunSQL(
            sql="""
            -- Enable RLS on fulfillments_fulfillmentproduct
            ALTER TABLE fulfillments_fulfillmentproduct ENABLE ROW LEVEL SECURITY;

            -- Drop existing policies (idempotent)
            DROP POLICY IF EXISTS fulfillmentproduct_tenant_isolation ON fulfillments_fulfillmentproduct;
            DROP POLICY IF EXISTS fulfillmentproduct_tenant_insert ON fulfillments_fulfillmentproduct;

            -- Create tenant isolation policy for SELECT/UPDATE/DELETE
            CREATE POLICY fulfillmentproduct_tenant_isolation ON fulfillments_fulfillmentproduct
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- Create tenant isolation policy for INSERT
            CREATE POLICY fulfillmentproduct_tenant_insert ON fulfillments_fulfillmentproduct
                FOR INSERT
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS fulfillmentproduct_tenant_insert ON fulfillments_fulfillmentproduct;
            DROP POLICY IF EXISTS fulfillmentproduct_tenant_isolation ON fulfillments_fulfillmentproduct;
            ALTER TABLE fulfillments_fulfillmentproduct DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
