# Generated by Django 6.0 on 2026-04-28 19:39

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fulfillments", "0006_fulfillment_deleted_at_fulfillment_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillment",
            name="document_milestones",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Document milestone flags such as proforma_requested, proforma_received, bol_requested, bol_received, coa_received, and coa_sent.",
            ),
        ),
        migrations.AddField(
            model_name="fulfillment",
            name="freight_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Freight or carrier cost attributed to this load",
                max_digits=10,
            ),
        ),
    ]
