import type { Edge, Node } from '@xyflow/react';

import type { FlowTemplate } from '@/components/FlowEditor/templates/flowTemplates';

const CONTAINER_ID = 'mc-inquiry-formprocess';

// NOTE: This template is intentionally explicit (stable IDs, deterministic layout)
// so it can act as the canonical default blueprint.
export const MEATSCENTRAL_INQUIRY_FLOW_TEMPLATE: FlowTemplate = {
  id: 'meatscentral-inquiry-flow-template',
  name: 'Meatscentral-Inquiry-Flow-Template',
  description:
    'Main template blueprint for Inquiry → Sales Order → Customer PO → Supplier PO with bidding + confirmations.',
  category: 'orders',
  difficulty: 'advanced',
  estimatedSetupTime: '15 minutes',
  thumbnail: '🥩',
  tags: ['inquiry', 'sales', 'purchase-order', 'bids', 'meatscentral', 'vanguard'],
  popularity: 9999,
  priority: 1,
  variables: [],
  optionalExtensions: [],
  nodes: [
    // Trigger (top-level)
    {
      id: 'node-trigger-inquiry-created',
      type: 'triggerEvent',
      position: { x: 120, y: 80 },
      data: {
        label: 'New inquiry created',
        config: {
          trigger: 'new inquiry created',
          mode: 'auto',
          entity: 'Inquiry',
          event: 'created',
        },
      },
    },

    // Root container (top-level). This is the canonical "Form Process" blueprint.
    {
      id: CONTAINER_ID,
      type: 'formProcess',
      position: { x: 120, y: 180 },
      style: {
        width: 1700,
        height: 820,
        borderColor: 'rgb(var(--color-primary))',
      },
      data: {
        label: 'Inquiry Flow (Main)',
        // Semantic type used by config schemas (skip steps, navigation, etc.)
        nodeType: 'formMultiStepContainer',
        containerName: 'Inquiry Flow (Main)',
        containerDescription: 'Canonical inquiry-to-order blueprint for new workforms',
        isExpanded: true,
        isGroup: true,
        // Template-specific metadata
        trigger: 'new inquiry created',
      },
    },

    // === 4 sequential Form Nodes (inside container) ===
    {
      id: 'node-form-1-inquiry',
      type: 'form',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 50, y: 80 },
      data: {
        label: '1. Inquiry',
        stepTitle: 'Inquiry',
        stepDescription: 'Customer • Product • Quantity • Spec • Targets',
        sections: ['Customer', 'Product', 'Pricing', 'Spec Sheet'],
        fields: [
          {
            id: 'customer_company',
            type: 'text',
            label: 'Customer / Company',
            required: true,
            placeholder: 'e.g., Acme Meats Ltd',
            defaultValue: '',
            helpText: 'Cascades to all downstream steps',
            validationRules: [],
          },
          {
            id: 'product',
            type: 'text',
            label: 'Product',
            required: true,
            placeholder: 'e.g., Ribeye, Trim, Chuck',
            defaultValue: '',
            validationRules: [],
          },
          {
            id: 'quantity',
            type: 'number',
            label: 'Quantity',
            required: true,
            placeholder: 'e.g., 20000',
            defaultValue: 0,
            helpText: 'Units depend on your process (lbs/kg/cases)',
            validationRules: [],
          },
          {
            id: 'spec_sheet',
            type: 'file',
            label: 'Spec Sheet Upload',
            required: false,
            defaultValue: null,
            validationRules: [],
          },
          {
            id: 'availability_confirmed',
            type: 'checkbox',
            label: 'Availability Confirmed',
            required: false,
            defaultValue: false,
            validationRules: [],
          },
          {
            id: 'target_price',
            type: 'number',
            label: 'Target Price',
            required: false,
            placeholder: 'e.g., 4.25',
            defaultValue: null,
            validationRules: [],
          },
          {
            id: 'due_date',
            type: 'date',
            label: 'Due Date',
            required: false,
            defaultValue: null,
            validationRules: [],
          },
        ],
      },
    },
    {
      id: 'node-form-2-sales-order',
      type: 'form',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 400, y: 80 },
      data: {
        label: '2. Sales Order (to customer)',
        stepTitle: 'Sales Order (to customer)',
        stepDescription: 'Auto-filled from Inquiry',
        fields: [
          {
            id: 'customer_company',
            type: 'text',
            label: 'Customer / Company',
            required: true,
            defaultValue: '{{node-form-1-inquiry.customer_company}}',
            helpText: 'Inherited from Step 1',
            validationRules: [],
          },
          {
            id: 'product',
            type: 'text',
            label: 'Product',
            required: true,
            defaultValue: '{{node-form-1-inquiry.product}}',
            validationRules: [],
          },
          {
            id: 'quantity',
            type: 'number',
            label: 'Quantity',
            required: true,
            defaultValue: '{{node-form-1-inquiry.quantity}}',
            validationRules: [],
          },
          {
            id: 'unit_price',
            type: 'number',
            label: 'Unit Price',
            required: false,
            defaultValue: '{{node-form-1-inquiry.target_price}}',
            helpText: 'Typically starts from Target Price and is finalized later',
            validationRules: [],
          },
          {
            id: 'delivery_terms',
            type: 'select',
            label: 'Delivery Terms',
            required: false,
            defaultValue: 'Delivered',
            options: {
              source: 'manual',
              manualOptions: ['FOB', 'Delivered', 'EXW'],
            },
            validationRules: [],
          },
          {
            id: 'order_notes',
            type: 'textarea',
            label: 'Notes',
            required: false,
            defaultValue: '',
            validationRules: [],
          },
        ],
      },
    },
    {
      id: 'node-form-3-customer-po',
      type: 'form',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 750, y: 80 },
      data: {
        label: '3. Purchase Order (from customer)',
        stepTitle: 'Purchase Order (from customer)',
        stepDescription: 'Attach PO + cascade PO number forward',
        fields: [
          {
            id: 'customer_company',
            type: 'text',
            label: 'Customer / Company',
            required: true,
            defaultValue: '{{node-form-1-inquiry.customer_company}}',
            validationRules: [],
          },
          {
            id: 'po_number',
            type: 'text',
            label: 'PO Number',
            required: true,
            placeholder: 'e.g., PO-10492',
            defaultValue: '',
            helpText: 'Cascades to supplier PO + proforma/BOL/invoice steps',
            validationRules: [],
          },
          {
            id: 'po_file',
            type: 'file',
            label: 'Customer PO (Upload)',
            required: false,
            defaultValue: null,
            validationRules: [],
          },
          {
            id: 'requested_ship_date',
            type: 'date',
            label: 'Requested Ship Date',
            required: false,
            defaultValue: '{{node-form-1-inquiry.due_date}}',
            validationRules: [],
          },
        ],
      },
    },
    {
      id: 'node-form-4-supplier-po',
      type: 'form',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 1100, y: 80 },
      data: {
        label: '4. Purchase Order (to supplier)',
        stepTitle: 'Purchase Order (to supplier)',
        stepDescription: 'Supplier routing + FOB/Delivered toggle + pricing',
        fields: [
          {
            id: 'customer_company',
            type: 'text',
            label: 'Customer / Company',
            required: true,
            defaultValue: '{{node-form-1-inquiry.customer_company}}',
            validationRules: [],
          },
          {
            id: 'po_number',
            type: 'text',
            label: 'Customer PO Number',
            required: true,
            defaultValue: '{{node-form-3-customer-po.po_number}}',
            validationRules: [],
          },
          {
            id: 'supplier_company',
            type: 'text',
            label: 'Supplier',
            required: true,
            placeholder: 'e.g., Supplier Co.',
            defaultValue: '',
            validationRules: [],
          },
          {
            id: 'shipping_terms',
            type: 'radio',
            label: 'Shipping Terms',
            required: true,
            defaultValue: 'FOB',
            options: {
              source: 'manual',
              manualOptions: ['FOB', 'Delivered'],
            },
            validationRules: [],
          },
          {
            id: 'fob_price',
            type: 'number',
            label: 'FOB Price',
            required: false,
            defaultValue: null,
            validationRules: [],
          },
          {
            id: 'delivered_price',
            type: 'number',
            label: 'Delivered Price',
            required: false,
            defaultValue: null,
            validationRules: [],
          },
        ],
      },
    },

    // 4a / 4b branch (inside container)
    {
      id: 'node-branch-4a-4b',
      type: 'conditionIf',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 1100, y: 430 },
      data: {
        label: '4a/4b Shipping Branch',
        config: {
          condition: 'shipping_terms == "FOB"',
        },
      },
    },
    {
      id: 'node-4a-fob',
      type: 'actionScript',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 920, y: 580 },
      data: {
        label: '4a. FOB branch',
        config: { notes: 'FOB branch logic placeholder' },
      },
    },
    {
      id: 'node-4b-delivered',
      type: 'actionScript',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 1280, y: 580 },
      data: {
        label: '4b. Delivered branch',
        config: { notes: 'Delivered branch logic placeholder' },
      },
    },

    // === Inside container (additive): loops, emails, waits, bids ===
    {
      id: 'node-loop-until-due-date',
      type: 'loopWhile',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 50, y: 430 },
      data: {
        label: 'Do Until: Current Date ≥ Inquiry Due Date',
        config: {
          condition: 'current_date < inquiry_due_date',
          notes: 'Loops until due date is reached (Do Until equivalent).',
        },
      },
    },
    {
      id: 'node-loop-for-each-supplier',
      type: 'loopForEach',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 400, y: 430 },
      data: {
        label: 'For Each supplier',
        config: {
          array: 'suppliers',
          itemName: 'supplier',
        },
      },
    },
    {
      id: 'node-email-request-spec',
      type: 'actionEmail',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 400, y: 580 },
      data: {
        label: 'Email Supplier: Request Spec/Avail/Price/Plant',
        config: {
          subject: 'Requesting Spec Sheet + Availability Timeline + Price + Plant Location',
          body: 'Requesting Spec Sheet + Availability Timeline + Price + Plant Location + Confirm 90 days or newer.',
        },
      },
    },
    {
      id: 'node-wait-supplier-response',
      type: 'pendingResponse',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 400, y: 710 },
      data: {
        label: 'Wait for Supplier Response',
        config: { timeoutHours: 72 },
      },
    },
    {
      id: 'node-add-to-inquiry-bids',
      type: 'actionCreateRecord',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 750, y: 580 },
      data: {
        label: 'Add to Inquiry Bids',
        config: {
          entity: 'InquiryBid',
        },
      },
    },
    {
      id: 'node-bid-selection',
      type: 'actionScript',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 750, y: 710 },
      data: {
        label: 'Select TOP 1 Bid (Bid Desc)',
        config: {
          expression: 'TOP 1 WHERE bid = actual_price - desired_price ORDER BY bid DESC',
        },
      },
    },

    // Generate Doc + email customer + wait confirm
    {
      id: 'node-generate-sales-order-doc',
      type: 'documentGenerate',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 1100, y: 710 },
      data: {
        label: 'Generate Doc: Sales Order (+ attach customer PO)',
        config: {
          outputName: 'Sales Order',
        },
      },
    },
    {
      id: 'node-email-customer-sales-order',
      type: 'actionEmail',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 1280, y: 710 },
      data: {
        label: 'Send Email to Customer (Sales Order)',
        config: {
          subject: 'Sales Order + Customer PO',
        },
      },
    },
    {
      id: 'node-wait-customer-confirmation',
      type: 'pendingResponse',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 1460, y: 710 },
      data: {
        label: 'Wait for confirmation',
        config: { timeoutHours: 72 },
      },
    },

    // Steps 5–11 (11 real Form Steps) — production-ready fields + cascading
    {
      id: 'node-step-5-order-confirmation',
      type: 'form',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 50, y: 1480 },
      data: {
        label: '5. Order Confirmation (from supplier)',
        stepTitle: 'Order Confirmation (from supplier)',
        stepDescription: 'Confirm pricing + dates from supplier',
        fields: [
          {
            id: 'confirmation_date',
            type: 'date',
            label: 'Confirmation Date',
            required: true,
            defaultValue: null,
            validationRules: [],
          },
          {
            id: 'confirmed_quantity',
            type: 'number',
            label: 'Confirmed Quantity',
            required: true,
            defaultValue: '{{node-form-1-inquiry.quantity}}',
            validationRules: [],
          },
          {
            id: 'confirmed_unit_price',
            type: 'number',
            label: 'Confirmed Unit Price',
            required: false,
            defaultValue: '{{node-form-2-sales-order.unit_price}}',
            helpText: 'Inherits the current working unit price from Sales Order',
            validationRules: [],
          },
          {
            id: 'supplier_reference',
            type: 'text',
            label: 'Supplier Reference',
            required: false,
            defaultValue: '',
            validationRules: [],
          },
        ],
      },
    },
    {
      id: 'node-step-6-request-proforma-bol',
      type: 'form',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 50, y: 1830 },
      data: {
        label: '6. Request Proforma / Draft BOL',
        stepTitle: 'Request Proforma / Draft BOL',
        stepDescription: 'Auto-populated from prior steps',
        fields: [
          {
            id: 'po_number',
            type: 'text',
            label: 'PO Number',
            required: true,
            defaultValue: '{{node-form-3-customer-po.po_number}}',
            validationRules: [],
          },
          {
            id: 'proforma_requested',
            type: 'checkbox',
            label: 'Request Proforma',
            required: false,
            defaultValue: true,
            validationRules: [],
          },
          {
            id: 'draft_bol_requested',
            type: 'checkbox',
            label: 'Request Draft BOL',
            required: false,
            defaultValue: true,
            validationRules: [],
          },
          {
            id: 'request_notes',
            type: 'textarea',
            label: 'Request Notes',
            required: false,
            defaultValue: '',
            validationRules: [],
          },
        ],
      },
    },
    {
      id: 'node-step-7-send-payment',
      type: 'form',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 50, y: 2180 },
      data: {
        label: '7. Send Payment (to supplier)',
        stepTitle: 'Send Payment (to supplier)',
        stepDescription: 'Scheduled date is typically 3 business days prior',
        fields: [
          {
            id: 'supplier_company',
            type: 'text',
            label: 'Supplier',
            required: true,
            defaultValue: '{{node-form-4-supplier-po.supplier_company}}',
            validationRules: [],
          },
          {
            id: 'payment_amount',
            type: 'number',
            label: 'Payment Amount',
            required: true,
            defaultValue: '{{node-step-5-order-confirmation.confirmed_unit_price}}',
            helpText: 'Typically derived from confirmed pricing (adjust as needed)',
            validationRules: [],
          },
          {
            id: 'scheduled_payment_date',
            type: 'date',
            label: 'Scheduled Payment Date',
            required: false,
            defaultValue: null,
            helpText: 'Recommended: 3 business days prior to ship date',
            validationRules: [],
          },
          {
            id: 'payment_method',
            type: 'select',
            label: 'Payment Method',
            required: false,
            defaultValue: 'Wire',
            options: {
              source: 'manual',
              manualOptions: ['Wire', 'ACH', 'Check', 'Card'],
            },
            validationRules: [],
          },
        ],
      },
    },
    {
      id: 'node-step-8-receive-bol',
      type: 'form',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 50, y: 2530 },
      data: {
        label: '8. Receive BOL',
        stepTitle: 'Receive BOL',
        stepDescription: 'Upload BOL + key shipping details',
        fields: [
          {
            id: 'bol_file',
            type: 'file',
            label: 'BOL File (Upload)',
            required: true,
            defaultValue: null,
            validationRules: [],
          },
          {
            id: 'bol_received_date',
            type: 'date',
            label: 'Received Date',
            required: true,
            defaultValue: null,
            validationRules: [],
          },
          {
            id: 'bol_number',
            type: 'text',
            label: 'BOL Number',
            required: false,
            defaultValue: '',
            validationRules: [],
          },
        ],
      },
    },
    {
      id: 'node-step-9-verify-bol',
      type: 'form',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 50, y: 2880 },
      data: {
        label: '9. Verify BOL vs Proforma',
        stepTitle: 'Verify BOL vs Proforma',
        stepDescription: 'Discrepancy flag triggers File Claim',
        fields: [
          {
            id: 'discrepancy_flag',
            type: 'checkbox',
            label: 'Discrepancy Detected',
            required: false,
            defaultValue: false,
            validationRules: [],
          },
          {
            id: 'discrepancy_details',
            type: 'textarea',
            label: 'Discrepancy Details',
            required: false,
            defaultValue: '',
            validationRules: [],
          },
          {
            id: 'verified_quantity',
            type: 'number',
            label: 'Verified Quantity',
            required: false,
            defaultValue: '{{node-form-1-inquiry.quantity}}',
            validationRules: [],
          },
          {
            id: 'verified_unit_price',
            type: 'number',
            label: 'Verified Unit Price',
            required: false,
            defaultValue: '{{node-step-5-order-confirmation.confirmed_unit_price}}',
            validationRules: [],
          },
        ],
      },
    },
    {
      id: 'node-condition-9-discrepancy',
      type: 'conditionIf',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      // Keep non-form routing nodes off the primary vertical step column
      position: { x: 420, y: 3055 },
      data: {
        label: 'Route: Discrepancy?',
        config: { condition: 'discrepancy_flag == true' },
      },
    },
    {
      id: 'node-step-9b-file-claim',
      type: 'actionCreateRecord',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 420, y: 3230 },
      data: {
        label: 'If discrepancy: File Claim',
        config: { entity: 'Claim' },
      },
    },
    {
      id: 'node-step-10-send-invoice',
      type: 'form',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 50, y: 3580 },
      data: {
        label: '10. Send Invoice (to customer)',
        stepTitle: 'Send Invoice (to customer)',
        stepDescription: 'Auto-calculated from verified BOL',
        fields: [
          {
            id: 'invoice_number',
            type: 'text',
            label: 'Invoice Number',
            required: true,
            defaultValue: '',
            validationRules: [],
          },
          {
            id: 'invoice_date',
            type: 'date',
            label: 'Invoice Date',
            required: true,
            defaultValue: null,
            validationRules: [],
          },
          {
            id: 'invoice_amount',
            type: 'number',
            label: 'Invoice Amount',
            required: false,
            defaultValue: '{{node-step-9-verify-bol.verified_unit_price}}',
            helpText: 'Use verified pricing/quantity; adjust for discrepancies',
            validationRules: [],
          },
          {
            id: 'invoice_file',
            type: 'file',
            label: 'Invoice File (Upload)',
            required: false,
            defaultValue: null,
            validationRules: [],
          },
        ],
      },
    },
    {
      id: 'node-step-11-confirm-payment',
      type: 'form',
      parentId: CONTAINER_ID,
      extent: 'parent',
      expandParent: true,
      position: { x: 50, y: 3930 },
      data: {
        label: '11. Confirm Received Payment',
        stepTitle: 'Confirm Received Payment',
        stepDescription: 'Track status + credit terms',
        fields: [
          {
            id: 'payment_received',
            type: 'checkbox',
            label: 'Payment Received',
            required: true,
            defaultValue: false,
            validationRules: [],
          },
          {
            id: 'payment_received_date',
            type: 'date',
            label: 'Received Date',
            required: false,
            defaultValue: null,
            validationRules: [],
          },
          {
            id: 'payment_status',
            type: 'select',
            label: 'Payment Status',
            required: false,
            defaultValue: 'Pending',
            options: {
              source: 'manual',
              manualOptions: ['Pending', 'Partial', 'Paid'],
            },
            validationRules: [],
          },
          {
            id: 'credit_terms_days',
            type: 'number',
            label: 'Credit Terms (Days)',
            required: false,
            defaultValue: null,
            validationRules: [],
          },
        ],
      },
    },
  ] satisfies Node[],
  edges: [
    { id: 'e-trigger-to-container', source: 'node-trigger-inquiry-created', target: CONTAINER_ID },

    // 4 sequential forms
    { id: 'e-1-2', source: 'node-form-1-inquiry', target: 'node-form-2-sales-order' },
    { id: 'e-2-3', source: 'node-form-2-sales-order', target: 'node-form-3-customer-po' },
    { id: 'e-3-4', source: 'node-form-3-customer-po', target: 'node-form-4-supplier-po' },

    // After form 4 → order confirmation
    { id: 'e-4-5', source: 'node-form-4-supplier-po', target: 'node-step-5-order-confirmation' },

    // Steps 5–11 chain
    { id: 'e-5-6', source: 'node-step-5-order-confirmation', target: 'node-step-6-request-proforma-bol' },
    { id: 'e-6-7', source: 'node-step-6-request-proforma-bol', target: 'node-step-7-send-payment' },
    { id: 'e-7-8', source: 'node-step-7-send-payment', target: 'node-step-8-receive-bol' },
    { id: 'e-8-9', source: 'node-step-8-receive-bol', target: 'node-step-9-verify-bol' },

    // Step 9 routes: discrepancy → claim; else → invoice
    { id: 'e-9-route', source: 'node-step-9-verify-bol', target: 'node-condition-9-discrepancy' },
    { id: 'e-route-claim', source: 'node-condition-9-discrepancy', target: 'node-step-9b-file-claim', label: 'Discrepancy' },
    { id: 'e-route-invoice', source: 'node-condition-9-discrepancy', target: 'node-step-10-send-invoice', label: 'OK' },
    { id: 'e-10-11', source: 'node-step-10-send-invoice', target: 'node-step-11-confirm-payment' },

    // Shipping branch off Form 4
    { id: 'e-4-branch', source: 'node-form-4-supplier-po', target: 'node-branch-4a-4b' },
    { id: 'e-branch-fob', source: 'node-branch-4a-4b', target: 'node-4a-fob', label: 'FOB' },
    { id: 'e-branch-delivered', source: 'node-branch-4a-4b', target: 'node-4b-delivered', label: 'Delivered' },

    // Loops + bids path
    { id: 'e-1-loop-until', source: 'node-form-1-inquiry', target: 'node-loop-until-due-date' },
    { id: 'e-loop-until-foreach', source: 'node-loop-until-due-date', target: 'node-loop-for-each-supplier' },
    { id: 'e-foreach-email', source: 'node-loop-for-each-supplier', target: 'node-email-request-spec' },
    { id: 'e-email-wait', source: 'node-email-request-spec', target: 'node-wait-supplier-response' },
    { id: 'e-wait-add-bid', source: 'node-wait-supplier-response', target: 'node-add-to-inquiry-bids' },
    { id: 'e-add-bid-select', source: 'node-add-to-inquiry-bids', target: 'node-bid-selection' },

    // Doc + email + wait
    { id: 'e-bid-doc', source: 'node-bid-selection', target: 'node-generate-sales-order-doc' },
    { id: 'e-doc-email', source: 'node-generate-sales-order-doc', target: 'node-email-customer-sales-order' },
    { id: 'e-email-wait-confirm', source: 'node-email-customer-sales-order', target: 'node-wait-customer-confirmation' },
  ] satisfies Edge[],
};
