# Generated by Django 6.0 on 2025-12-06 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BugReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bug", "Bug"),
                            ("feature_request", "Feature Request"),
                            ("question", "Question"),
                            ("feedback", "Feedback"),
                        ],
                        default="bug",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("wont_fix", "Won't Fix"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "reporter_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("browser", models.CharField(blank=True, default="", max_length=100)),
                ("os", models.CharField(blank=True, default="", max_length=100)),
                (
                    "screen_resolution",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("url", models.URLField(blank=True, default="")),
                ("steps_to_reproduce", models.TextField(blank=True, default="")),
                ("expected_behavior", models.TextField(blank=True, default="")),
                ("actual_behavior", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bug_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bug Report",
                "verbose_name_plural": "Bug Reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
