# Generated by Django 6.0 on 2026-03-18 03:16
# Add RLS policy for BugReport model

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ("bug_reports", "0004_bugreport_created_on_bugreport_custom_data_and_more"),
    ]

    operations = [
        RunSQL(
            sql="""
            -- Enable RLS on bug_reports_bugreport
            ALTER TABLE bug_reports_bugreport ENABLE ROW LEVEL SECURITY;
            
            -- Create tenant isolation policy
            CREATE POLICY bug_reports_bugreport_tenant_isolation ON bug_reports_bugreport
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS bug_reports_bugreport_tenant_isolation ON bug_reports_bugreport;
            ALTER TABLE bug_reports_bugreport DISABLE ROW LEVEL SECURITY;
            """
        ),
    ]
