# Generated by Django 6.0 on 2026-03-22
# Normalize RLS policy to safe current_setting('app.current_tenant', true)

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("bug_reports", "0005_add_rls_policies_batch"),
    ]

    operations = [
        RunSQL(
            sql="""
            ALTER TABLE bug_reports_bugreport ENABLE ROW LEVEL SECURITY;
            ALTER TABLE bug_reports_bugreport FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS bug_reports_bugreport_tenant_isolation ON bug_reports_bugreport;
            CREATE POLICY bug_reports_bugreport_tenant_isolation ON bug_reports_bugreport
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS bug_reports_bugreport_tenant_isolation ON bug_reports_bugreport;
            CREATE POLICY bug_reports_bugreport_tenant_isolation ON bug_reports_bugreport
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
        ),
    ]
