# Generated by Django 6.0 on 2026-02-26 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(
                        choices=[("outlook", "Microsoft Outlook"), ("gmail", "Google Gmail")],
                        help_text="Email service provider",
                        max_length=20,
                    ),
                ),
                ("email_address", models.EmailField(help_text="Connected email address", max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Token Expired"),
                            ("revoked", "Access Revoked"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("access_token", models.CharField(max_length=1024)),
                ("refresh_token", models.CharField(blank=True, max_length=1024)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("provider_user_id", models.CharField(blank=True, max_length=255)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "webhook_id",
                    models.CharField(blank=True, help_text="Provider webhook/subscription ID", max_length=255),
                ),
                ("webhook_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this email connection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_accounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "workflow_node_id",
                    models.CharField(help_text="ID of the Workforms node this action belongs to", max_length=255),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("send_email", "Send Email"),
                            ("reply", "Reply to Email"),
                            ("forward", "Forward Email"),
                        ],
                        max_length=50,
                    ),
                ),
                ("template_subject", models.CharField(blank=True, max_length=255)),
                ("template_body", models.TextField(blank=True)),
                ("use_html", models.BooleanField(default=True)),
                ("recipient_to", models.TextField(help_text="Comma-separated or template variables")),
                ("recipient_cc", models.TextField(blank=True)),
                ("recipient_bcc", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("execution_count", models.IntegerField(default=0)),
                ("last_executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="email_integration.emailaccount",
                    ),
                ),
            ],
            options={
                "db_table": "email_actions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("trigger", "Trigger Activated"),
                            ("action", "Action Executed"),
                            ("webhook", "Webhook Received"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("workflow_node_id", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("from_address", models.EmailField(blank=True, max_length=254)),
                ("to_address", models.TextField(blank=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                (
                    "email_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="email_integration.emailaccount",
                    ),
                ),
            ],
            options={
                "db_table": "email_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailTrigger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "workflow_node_id",
                    models.CharField(help_text="ID of the Workforms node this trigger activates", max_length=255),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("new_email", "New Email Received"),
                            ("new_thread", "New Email Thread"),
                            ("reply_received", "Reply Received"),
                            ("attachment_received", "Email with Attachment"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "filter_from",
                    models.CharField(blank=True, help_text="Filter by sender email/domain", max_length=255),
                ),
                (
                    "filter_subject",
                    models.CharField(blank=True, help_text="Filter by subject keywords", max_length=255),
                ),
                ("filter_has_attachment", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.IntegerField(default=0)),
                (
                    "email_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="email_integration.emailaccount",
                    ),
                ),
            ],
            options={
                "db_table": "email_triggers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="emailaccount",
            index=models.Index(fields=["user", "status"], name="email_accou_user_id_76b4c4_idx"),
        ),
        migrations.AddIndex(
            model_name="emailaccount",
            index=models.Index(fields=["provider", "email_address"], name="email_accou_provide_941253_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="emailaccount",
            unique_together={("user", "provider", "email_address")},
        ),
        migrations.AddIndex(
            model_name="emailaction",
            index=models.Index(fields=["email_account"], name="email_actio_email_a_03d117_idx"),
        ),
        migrations.AddIndex(
            model_name="emailaction",
            index=models.Index(fields=["workflow_node_id"], name="email_actio_workflo_cca2ed_idx"),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(fields=["email_account", "-created_at"], name="email_logs_email_a_bb956c_idx"),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(fields=["workflow_node_id", "-created_at"], name="email_logs_workflo_50f93d_idx"),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(fields=["success"], name="email_logs_success_cb26a4_idx"),
        ),
        migrations.AddIndex(
            model_name="emailtrigger",
            index=models.Index(fields=["email_account", "is_active"], name="email_trigg_email_a_425a43_idx"),
        ),
        migrations.AddIndex(
            model_name="emailtrigger",
            index=models.Index(fields=["workflow_node_id"], name="email_trigg_workflo_ae7cd5_idx"),
        ),
    ]
