# Generated by Django 6.0 on 2026-04-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaccount",
            name="webhook_client_state_hash",
            field=models.CharField(
                blank=True, help_text="SHA256 hash of Microsoft Graph webhook clientState", max_length=64
            ),
        ),
    ]
