# Generated by Django 6.0 on 2026-04-21 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_integration", "0002_emailaccount_webhook_client_state_hash"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaccount",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this email connection",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_integration_accounts",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="emailaction",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_integration_actions",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_integration_logs",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="emailtrigger",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_integration_triggers",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="emailaccount",
            index=models.Index(fields=["tenant", "status"], name="email_accou_tenant__b593ca_idx"),
        ),
        migrations.AddIndex(
            model_name="emailaccount",
            index=models.Index(fields=["tenant", "provider", "email_address"], name="email_accou_tenant__1a9c3d_idx"),
        ),
        migrations.AddIndex(
            model_name="emailaction",
            index=models.Index(fields=["tenant"], name="email_actio_tenant__c3efb8_idx"),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(fields=["tenant", "-created_at"], name="email_logs_tenant__80e2f2_idx"),
        ),
        migrations.AddIndex(
            model_name="emailtrigger",
            index=models.Index(fields=["tenant", "is_active"], name="email_trigg_tenant__7b9907_idx"),
        ),
        migrations.AddConstraint(
            model_name="emailaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", False)),
                fields=("tenant", "provider", "email_address"),
                name="uniq_emailaccount_tenant_provider_email",
            ),
        ),
    ]
