# Generated by Django 6.0 on 2026-05-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_integration", "0005_fix_email_rls_uuid_cast_safety"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaccount",
            name="access_token",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="refresh_token",
            field=models.TextField(blank=True),
        ),
    ]
