# Generated by Django 6.0 on 2026-02-14 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0010_add_tenant_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalAuthProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("microsoft", "Microsoft Outlook"),
                            ("google", "Gmail"),
                            ("aws_ses", "AWS SES"),
                            ("sendgrid", "SendGrid"),
                        ],
                        help_text="Email provider type",
                        max_length=20,
                    ),
                ),
                ("access_token", models.TextField(help_text="Encrypted OAuth access token")),
                ("refresh_token", models.TextField(blank=True, help_text="Encrypted OAuth refresh token", null=True)),
                ("token_expiry", models.DateTimeField(help_text="When the access token expires")),
                ("is_active", models.BooleanField(default=True, help_text="Whether this provider is currently active")),
                (
                    "connected_email",
                    models.EmailField(
                        blank=True, help_text="Email address of the connected account", max_length=254, null=True
                    ),
                ),
                (
                    "connected_name",
                    models.CharField(
                        blank=True, help_text="Display name of the connected account", max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="auth_providers", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "provider_type"], name="integration_tenant__cfb42a_idx"),
                    models.Index(fields=["tenant", "is_active"], name="integration_tenant__3e92cc_idx"),
                ],
                "unique_together": {("tenant", "provider_type")},
            },
        ),
    ]
