# Generated by Django 6.0 on 2026-03-18 01:25

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.special import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
        ("tenants", "0010_add_tenant_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "message_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique message ID from provider (prevents duplicates)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(blank=True, help_text="Thread/conversation ID", max_length=255, null=True),
                ),
                ("subject", models.CharField(max_length=500)),
                ("sender_email", models.EmailField(max_length=254)),
                ("sender_name", models.CharField(blank=True, max_length=255)),
                ("received_at", models.DateTimeField(help_text="When email was sent/received")),
                ("body_text", models.TextField(blank=True, help_text="Plain text body")),
                ("body_html", models.TextField(blank=True, help_text="HTML body")),
                ("has_attachments", models.BooleanField(default=False)),
                ("attachment_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("logged", "Logged"),
                            ("ai_parsing", "AI Parsing"),
                            ("order_created", "Order Created"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="logged",
                        max_length=20,
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(blank=True, help_text="Error message if processing failed", null=True),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True, help_text="AI-extracted order data (products, quantities, etc.)", null=True
                    ),
                ),
                (
                    "related_order_id",
                    models.IntegerField(blank=True, help_text="ID of order created from this email", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, help_text="When AI processing completed", null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="Auth provider this email was fetched from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="integrations.externalauthprovider",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="email_logs", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="integration_tenant__03a3a8_idx"),
                    models.Index(fields=["tenant", "received_at"], name="integration_tenant__ee8d50_idx"),
                    models.Index(fields=["provider", "created_at"], name="integration_provide_445aaf_idx"),
                ],
            },
        ),
        RunSQL(
            sql="""
            ALTER TABLE integrations_emaillog ENABLE ROW LEVEL SECURITY;
            ALTER TABLE integrations_emaillog FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS emaillog_tenant_isolation ON integrations_emaillog;
            CREATE POLICY emaillog_tenant_isolation ON integrations_emaillog
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS emaillog_tenant_isolation ON integrations_emaillog;
            ALTER TABLE integrations_emaillog NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE integrations_emaillog DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
