# Generated by Django 6.0 on 2026-03-22
# Normalize RLS policy to safe current_setting('app.current_tenant', true)

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_emaillog"),
    ]

    operations = [
        RunSQL(
            sql="""
            ALTER TABLE integrations_emaillog ENABLE ROW LEVEL SECURITY;
            ALTER TABLE integrations_emaillog FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS integrations_emaillog_tenant_isolation ON integrations_emaillog;
            CREATE POLICY integrations_emaillog_tenant_isolation ON integrations_emaillog
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS integrations_emaillog_tenant_isolation ON integrations_emaillog;
            CREATE POLICY integrations_emaillog_tenant_isolation ON integrations_emaillog
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
        ),
    ]
