# Generated by Django 6.0 on 2026-05-04 01:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_enable_rls_externalauthprovider"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("logged", "Logged"),
                    ("ai_parsing", "AI Parsing"),
                    ("draft_created", "Draft Created"),
                    ("order_created", "Order Created"),
                    ("failed", "Failed"),
                    ("ignored", "Ignored"),
                ],
                db_index=True,
                default="logged",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EmailReviewDraft",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "draft_type",
                    models.CharField(
                        choices=[
                            ("purchase_order", "Purchase Order"),
                            ("bill_of_lading", "Bill of Lading"),
                            ("new_customer", "New Customer"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("summary", models.CharField(blank=True, default="", max_length=500)),
                ("extracted_payload", models.JSONField(blank=True, default=dict)),
                ("classification_confidence", models.FloatField(default=0.0)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email_log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_draft",
                        to="integrations.emaillog",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_review_drafts",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "status", "created_at"], name="integration_tenant__a821f0_idx"),
                    models.Index(fields=["tenant", "draft_type", "created_at"], name="integration_tenant__e4b25f_idx"),
                ],
                },
            ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE integrations_emailreviewdraft ENABLE ROW LEVEL SECURITY;
            ALTER TABLE integrations_emailreviewdraft FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS integrations_emailreviewdraft_tenant_isolation ON integrations_emailreviewdraft;
            DROP POLICY IF EXISTS integrations_emailreviewdraft_tenant_insert ON integrations_emailreviewdraft;

            CREATE POLICY integrations_emailreviewdraft_tenant_isolation ON integrations_emailreviewdraft
              USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

            CREATE POLICY integrations_emailreviewdraft_tenant_insert ON integrations_emailreviewdraft
              FOR INSERT WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS integrations_emailreviewdraft_tenant_insert ON integrations_emailreviewdraft;
            DROP POLICY IF EXISTS integrations_emailreviewdraft_tenant_isolation ON integrations_emailreviewdraft;
            ALTER TABLE integrations_emailreviewdraft DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
