# Generated by Django 6.0 on 2026-05-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0005_alter_emaillog_status_emailreviewdraft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("logged", "Logged"),
                    ("ai_parsing", "AI Parsing"),
                    ("draft_created", "Draft Created"),
                    ("order_created", "Order Created"),
                    ("action_required", "Action Required"),
                    ("failed", "Failed"),
                    ("ignored", "Ignored"),
                ],
                db_index=True,
                default="logged",
                max_length=20,
            ),
        ),
    ]
