# Generated by Django 6.0 on 2026-05-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0007_emaillog_attachment_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailreviewdraft",
            name="draft_type",
            field=models.CharField(
                choices=[
                    ("purchase_order", "Purchase Order"),
                    ("bill_of_lading", "Bill of Lading"),
                    ("new_customer", "New Customer"),
                    ("invoice", "Invoice"),
                    ("pricing_sheet", "Pricing Sheet"),
                ],
                max_length=32,
            ),
        ),
    ]
