# Generated by Django 6.0 on 2026-05-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_alter_emailreviewdraft_draft_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailreviewdraft",
            name="draft_type",
            field=models.CharField(
                choices=[
                    ("purchase_order", "Purchase Order"),
                    ("bill_of_lading", "Bill of Lading"),
                    ("new_customer", "New Customer"),
                    ("invoice", "Invoice"),
                    ("pricing_sheet", "Pricing Sheet"),
                    ("contact", "Contact Update"),
                    ("company", "Company Update"),
                    ("payment", "Payment Notice"),
                    ("supplier_note", "Supplier Note"),
                ],
                max_length=32,
            ),
        ),
    ]
