# Generated by Django 6.0 on 2026-05-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0009_add_missing_draft_type_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="failure_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stable failure code for operator-safe ingest/sync status semantics",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="status_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Compact status metadata for structured retryability and failure-state reporting",
            ),
        ),
    ]
