# Generated by Django 6.0 on 2025-12-06 20:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Tenant organization name", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly identifier", max_length=100, unique=True),
                ),
                (
                    "schema_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Database schema name (for future django-tenants compatibility)",
                        max_length=63,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="Custom domain for the tenant (optional)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(help_text="Primary contact email", max_length=254),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_trial", models.BooleanField(default=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "settings",
                    models.JSONField(default=dict, help_text="Tenant-specific configuration settings"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Tenant logo image for branding",
                        null=True,
                        upload_to="tenant_logos/",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this tenant",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenants_tenant",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TenantDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        help_text="Domain name (e.g., 'tenant.example.com' or 'tenant.localhost')",
                        max_length=253,
                        unique=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the primary domain for the tenant",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant associated with this domain",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenants_tenantdomain",
                "ordering": ["domain"],
            },
        ),
        migrations.CreateModel(
            name="TenantInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Unique invitation token sent to invitee",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the person being invited",
                        max_length=254,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Administrator"),
                            ("manager", "Manager"),
                            ("user", "User"),
                            ("readonly", "Read Only"),
                        ],
                        default="user",
                        help_text="Role the user will have upon acceptance",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this invitation expires"),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.TextField(blank=True, help_text="Optional message from inviter"),
                ),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User created from this invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="User who sent this invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant extending the invitation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenants_invitation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Administrator"),
                            ("manager", "Manager"),
                            ("user", "User"),
                            ("readonly", "Read Only"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenants_tenant_user",
            },
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["slug"], name="tenants_ten_slug_63daca_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["is_active"], name="tenants_ten_is_acti_8f654a_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["created_at"], name="tenants_ten_created_99c6ff_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantdomain",
            index=models.Index(fields=["domain"], name="td_domain_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantdomain",
            index=models.Index(fields=["tenant", "is_primary"], name="td_tenant_primary_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantinvitation",
            index=models.Index(fields=["token"], name="tenants_inv_token_9e2edb_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantinvitation",
            index=models.Index(fields=["email", "status"], name="tenants_inv_email_74dee3_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantinvitation",
            index=models.Index(fields=["tenant", "status"], name="tenants_inv_tenant__acc54c_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantinvitation",
            index=models.Index(fields=["expires_at"], name="tenants_inv_expires_181628_idx"),
        ),
        migrations.AddConstraint(
            model_name="tenantinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("tenant", "email"),
                name="unique_pending_invitation_per_tenant_email",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantuser",
            index=models.Index(fields=["tenant", "is_active"], name="tenants_ten_tenant__78b8df_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantuser",
            index=models.Index(fields=["user", "is_active"], name="tenants_ten_user_id_d07440_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tenantuser",
            unique_together={("tenant", "user")},
        ),
    ]
