# Generated by Django - do not edit manually
from django.db import migrations


class Migration(migrations.Migration):
    """
    Enable PostgreSQL Row-Level Security (RLS) for tenant isolation.
    
    This migration enforces tenant_id isolation at the database level using
    PostgreSQL's Row-Level Security feature. This provides defense-in-depth
    security by ensuring that even if application-level filtering fails,
    the database will prevent cross-tenant data access.
    
    IMPORTANT: This migration uses shared-schema multi-tenancy approach.
    All tenants share the same PostgreSQL schema (public) with RLS policies
    enforcing data isolation via tenant_id foreign keys.
    """

    dependencies = [
        ('tenants', '0001_initial'),
        # Wait for all tenant_apps tables to be created before applying RLS
        ('suppliers', '0002_supplier_tenant'),
        ('customers', '0002_customer_tenant_and_more'),
        ('products', '0002_product_tenant'),
        ('purchase_orders', '0002_carrierpurchaseorder_tenant_coldstorageentry_tenant_and_more'),
        ('sales_orders', '0002_salesorder_tenant'),
        ('invoices', '0002_invoice_tenant'),
        ('carriers', '0002_carrier_tenant_and_more'),
        ('contacts', '0002_contact_tenant_and_more'),
        ('plants', '0002_plant_tenant_plant_plants_plan_tenant__9efb37_idx_and_more'),
        # NOTE: locations is excluded - it has its own RLS migration (locations/0002_enable_rls_locations.py)
        # and would create circular dependency since locations/0001 depends on tenants/0006
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Enable RLS on tenant-aware tables with FORCE for superusers
            -- Note: Using NULLIF to convert empty string to NULL before UUID cast
            
            -- Suppliers
            ALTER TABLE suppliers_supplier ENABLE ROW LEVEL SECURITY;
            ALTER TABLE suppliers_supplier FORCE ROW LEVEL SECURITY;
            CREATE POLICY supplier_tenant_isolation ON suppliers_supplier
                FOR ALL
                USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);
            
            -- Customers
            ALTER TABLE customers_customer ENABLE ROW LEVEL SECURITY;
            ALTER TABLE customers_customer FORCE ROW LEVEL SECURITY;
            CREATE POLICY customer_tenant_isolation ON customers_customer
                FOR ALL
                USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);
            
            -- Purchase Orders
            ALTER TABLE purchase_orders_purchaseorder ENABLE ROW LEVEL SECURITY;
            ALTER TABLE purchase_orders_purchaseorder FORCE ROW LEVEL SECURITY;
            CREATE POLICY purchase_order_tenant_isolation ON purchase_orders_purchaseorder
                FOR ALL
                USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);
            
            -- Sales Orders
            ALTER TABLE sales_orders_salesorder ENABLE ROW LEVEL SECURITY;
            ALTER TABLE sales_orders_salesorder FORCE ROW LEVEL SECURITY;
            CREATE POLICY sales_order_tenant_isolation ON sales_orders_salesorder
                FOR ALL
                USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);
            
            -- Products
            ALTER TABLE products_product ENABLE ROW LEVEL SECURITY;
            ALTER TABLE products_product FORCE ROW LEVEL SECURITY;
            CREATE POLICY product_tenant_isolation ON products_product
                FOR ALL
                USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);
            
            -- Contacts
            ALTER TABLE contacts_contact ENABLE ROW LEVEL SECURITY;
            ALTER TABLE contacts_contact FORCE ROW LEVEL SECURITY;
            CREATE POLICY contact_tenant_isolation ON contacts_contact
                FOR ALL
                USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);
            
            -- Invoices
            ALTER TABLE invoices_invoice ENABLE ROW LEVEL SECURITY;
            ALTER TABLE invoices_invoice FORCE ROW LEVEL SECURITY;
            CREATE POLICY invoice_tenant_isolation ON invoices_invoice
                FOR ALL
                USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);
            
            -- Carriers
            ALTER TABLE carriers_carrier ENABLE ROW LEVEL SECURITY;
            ALTER TABLE carriers_carrier FORCE ROW LEVEL SECURITY;
            CREATE POLICY carrier_tenant_isolation ON carriers_carrier
                FOR ALL
                USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);
            
            -- Plants
            ALTER TABLE plants_plant ENABLE ROW LEVEL SECURITY;
            ALTER TABLE plants_plant FORCE ROW LEVEL SECURITY;
            CREATE POLICY plant_tenant_isolation ON plants_plant
                FOR ALL
                USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);
            """,
            reverse_sql="""
            -- Disable RLS on all tables
            DROP POLICY IF EXISTS supplier_tenant_isolation ON suppliers_supplier;
            ALTER TABLE suppliers_supplier NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE suppliers_supplier DISABLE ROW LEVEL SECURITY;
            
            DROP POLICY IF EXISTS customer_tenant_isolation ON customers_customer;
            ALTER TABLE customers_customer NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE customers_customer DISABLE ROW LEVEL SECURITY;
            
            DROP POLICY IF EXISTS purchase_order_tenant_isolation ON purchase_orders_purchaseorder;
            ALTER TABLE purchase_orders_purchaseorder NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE purchase_orders_purchaseorder DISABLE ROW LEVEL SECURITY;
            
            DROP POLICY IF EXISTS sales_order_tenant_isolation ON sales_orders_salesorder;
            ALTER TABLE sales_orders_salesorder NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE sales_orders_salesorder DISABLE ROW LEVEL SECURITY;
            
            DROP POLICY IF EXISTS product_tenant_isolation ON products_product;
            ALTER TABLE products_product NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE products_product DISABLE ROW LEVEL SECURITY;
            
            DROP POLICY IF EXISTS contact_tenant_isolation ON contacts_contact;
            ALTER TABLE contacts_contact NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE contacts_contact DISABLE ROW LEVEL SECURITY;
            
            DROP POLICY IF EXISTS invoice_tenant_isolation ON invoices_invoice;
            ALTER TABLE invoices_invoice NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE invoices_invoice DISABLE ROW LEVEL SECURITY;
            
            DROP POLICY IF EXISTS carrier_tenant_isolation ON carriers_carrier;
            ALTER TABLE carriers_carrier NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE carriers_carrier DISABLE ROW LEVEL SECURITY;
            
            DROP POLICY IF EXISTS plant_tenant_isolation ON plants_plant;
            ALTER TABLE plants_plant NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE plants_plant DISABLE ROW LEVEL SECURITY;
            """
        ),
    ]
