# Generated by Django 6.0 on 2026-01-02 01:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_enable_rls_policies"),
        ("tenants", "0002_invitation_reusability"),
    ]

    operations = []
