# Generated by Django 5.1.4 on 2026-01-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_add_golden_ticket_features"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tenantinvitation",
            name="unique_pending_invitation_per_tenant_email",
        ),
        migrations.AlterField(
            model_name="tenant",
            name="settings",
            field=models.JSONField(blank=True, default=dict, help_text="Tenant-specific settings"),
        ),
        migrations.AlterField(
            model_name="tenantinvitation",
            name="is_reusable",
            field=models.BooleanField(
                default=False,
                help_text="If True, this invitation can be used by multiple users until max usage is reached or it expires",
            ),
        ),
        migrations.AlterField(
            model_name="tenantinvitation",
            name="usage_count",
            field=models.IntegerField(default=0, help_text="Number of times this invitation has been used"),
        ),
        migrations.AddConstraint(
            model_name="tenantinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("tenant", "email"),
                name="unique_pending_invitation_per_tenant_email",
            ),
        ),
    ]
