# Generated by Django 6.0 on 2026-01-04 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0005_baseline_metadata_cleanup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tenantinvitation",
            name="unique_pending_invitation_per_tenant_email",
        ),
        migrations.AlterField(
            model_name="tenant",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Tenant-specific configuration settings",
            ),
        ),
        migrations.AlterField(
            model_name="tenantinvitation",
            name="is_reusable",
            field=models.BooleanField(
                default=False,
                help_text="If true, this token can be used by multiple people",
            ),
        ),
        migrations.AlterField(
            model_name="tenantinvitation",
            name="usage_count",
            field=models.PositiveIntegerField(default=0, help_text="Current number of times used"),
        ),
        migrations.AddConstraint(
            model_name="tenantinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending"), ("email__isnull", False)),
                fields=("tenant", "email"),
                name="unique_pending_invitation_per_tenant_email",
            ),
        ),
    ]
