# Generated by Django 6.0 on 2026-02-09 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0006_metadata_lockdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user.invite", "User Invited"),
                            ("user.role_change", "User Role Changed"),
                            ("user.deactivate", "User Deactivated"),
                            ("user.activate", "User Activated"),
                            ("profile.update", "Profile Updated"),
                            ("config.update", "Configuration Updated"),
                            ("theme.update", "Theme Updated"),
                            ("optionlist.create", "Option List Created"),
                            ("optionlist.update", "Option List Updated"),
                            ("optionlist.delete", "Option List Deleted"),
                        ],
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        help_text='Type of entity affected (e.g., "TenantUser", "Tenant")',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(blank=True, help_text="ID of the affected entity", max_length=255, null=True),
                ),
                ("description", models.TextField(help_text="Human-readable description of the action")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata (old values, new values, etc.)"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, help_text="IP address of the user", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this activity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenants_activity_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "-created_at"], name="tenants_act_tenant__b94f36_idx"),
                    models.Index(fields=["user", "-created_at"], name="tenants_act_user_id_928255_idx"),
                    models.Index(fields=["action", "-created_at"], name="tenants_act_action_7f8222_idx"),
                    models.Index(fields=["entity_type", "entity_id"], name="tenants_act_entity__4f622e_idx"),
                ],
            },
        ),
    ]
