# Generated by Django 6.0 on 2026-02-09 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0007_activitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this activity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_activity_logs",
                to="tenants.tenant",
            ),
        ),
    ]
