# Generated by Django 6.0 on 2026-02-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0008_alter_activitylog_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="address",
            field=models.TextField(blank=True, default="", help_text="Physical address"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="description",
            field=models.TextField(blank=True, default="", help_text="Tenant organization description"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="website",
            field=models.URLField(blank=True, default="", help_text="Company website"),
        ),
    ]
