# Generated by Django 6.0 on 2026-02-09 03:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_tenant_address_tenant_description_tenant_website"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantConfiguration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("security", "Security"),
                            ("notifications", "Notifications"),
                            ("integrations", "Integrations"),
                            ("appearance", "Appearance"),
                            ("advanced", "Advanced"),
                        ],
                        default="general",
                        help_text="Configuration category for organization",
                        max_length=50,
                    ),
                ),
                ("key", models.CharField(help_text="Configuration key (e.g., 'session_timeout')", max_length=100)),
                ("display_name", models.CharField(help_text="Human-readable name for display in UI", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description of what this configuration controls"),
                ),
                ("value", models.TextField(help_text="Configuration value (stored as text, interpreted by data_type)")),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        help_text="Data type for value interpretation and validation",
                        max_length=20,
                    ),
                ),
                ("default_value", models.TextField(blank=True, help_text="Default value for reset functionality")),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System-defined config (cannot be deleted, only modified)"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, help_text="Required configuration (must have a value)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_configurations",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this configuration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_configurations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenants_configuration",
                "ordering": ["category", "key"],
                "indexes": [
                    models.Index(fields=["tenant", "category"], name="tenants_con_tenant__fa38c0_idx"),
                    models.Index(fields=["tenant", "key"], name="tenants_con_tenant__64f598_idx"),
                ],
                "unique_together": {("tenant", "key")},
            },
        ),
    ]
