# Generated by Django 6.0 on 2026-03-22
# Bootstrap session variables used by legacy RLS policies during migrations.
#
# Some historical RLS policies reference current_setting('app.current_tenant') without the
# safe (missing_ok=true) flag. During migrations (and FK validation queries), this can
# raise "unrecognized configuration parameter" unless the setting exists in the session.
#
# We set both app.current_tenant and app.current_tenant_id to a harmless dummy UUID for
# the migration connection. Corrective migrations later normalize policies to the safe
# current_setting(..., true) form.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0010_add_tenant_configuration"),
    ]

    run_before = [
        ("integrations", "0002_emaillog"),
        ("locations", "0002_enable_rls_locations"),
        ("carriers", "0006_add_rls_policies_batch"),
        ("cockpit", "0006_add_rls_policies_batch"),
        ("ai_assistant", "0005_add_rls_policies_batch"),
        ("bug_reports", "0005_add_rls_policies_batch"),
        ("plants", "0008_plantassociatedproduct_plant_associated_products_and_more"),
        ("workflows", "0022_add_tenant_to_step_models"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            SELECT set_config('app.current_tenant', '00000000-0000-0000-0000-000000000000', false);
            SELECT set_config('app.current_tenant_id', '00000000-0000-0000-0000-000000000000', false);
            """,
            reverse_sql="""
            SELECT set_config('app.current_tenant', '', false);
            SELECT set_config('app.current_tenant_id', '', false);
            """,
        ),
    ]
