# Generated by Django 6.0 on 2026-03-22
# Bootstrap session variables used by legacy RLS policies during migrations.
#
# Some historical RLS policies reference current_setting('app.current_tenant') without the
# safe (missing_ok=true) flag. During migrations (and FK validation queries), this can
# raise "unrecognized configuration parameter" unless the setting exists in the session.
#
# We set both app.current_tenant and app.current_tenant_id to a harmless dummy UUID for
# the migration connection. Corrective migrations later normalize policies to the safe
# current_setting(..., true) form.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0010_add_tenant_configuration"),
    ]

    # NOTE:
    # We intentionally do NOT use `run_before` here.
    #
    # Some environments already have historical RLS migrations applied (e.g. locations.0002).
    # Adding `run_before` edges can create an implicit dependency and trigger
    # `InconsistentMigrationHistory` on deploy.
    #
    # If a future migration truly requires these GUCs at migration-time, it should either:
    #   1) use safe current_setting(..., true), or
    #   2) set_config() within that migration.

    operations = [
        migrations.RunSQL(
            sql="""
            SELECT set_config('app.current_tenant', '00000000-0000-0000-0000-000000000000', false);
            SELECT set_config('app.current_tenant_id', '00000000-0000-0000-0000-000000000000', false);
            """,
            reverse_sql="""
            SELECT set_config('app.current_tenant', '', false);
            SELECT set_config('app.current_tenant_id', '', false);
            """,
        ),
    ]
