# Generated by Django 6.0 on 2026-03-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0011_bootstrap_rls_session_vars"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="contact_phone_type",
            field=models.CharField(
                blank=True,
                choices=[("mobile", "Mobile"), ("office", "Office")],
                default="office",
                help_text="Primary contact phone type (mobile or office)",
                max_length=10,
            ),
        ),
    ]
