# Generated by Django 6.0 on 2026-03-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0012_tenant_contact_phone_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("user.invite", "User Invited"),
                    ("user.role_change", "User Role Changed"),
                    ("user.deactivate", "User Deactivated"),
                    ("user.activate", "User Activated"),
                    ("user.remove", "User Removed"),
                    ("profile.update", "Profile Updated"),
                    ("config.update", "Configuration Updated"),
                    ("theme.update", "Theme Updated"),
                    ("optionlist.create", "Option List Created"),
                    ("optionlist.update", "Option List Updated"),
                    ("optionlist.delete", "Option List Deleted"),
                ],
                help_text="Type of action performed",
                max_length=50,
            ),
        ),
    ]
