# Generated by Django 6.0 on 2026-03-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0012_locationassociatedmasterproduct_and_more"),
        ("plants", "0015_alter_plant_plant_type"),
        ("tenants", "0013_alter_activitylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantuser",
            name="restricted_locations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional location-level access restriction for this membership",
                related_name="restricted_to_memberships",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="tenantuser",
            name="restricted_plants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional plant-level access restriction for this membership",
                related_name="restricted_to_memberships",
                to="plants.plant",
            ),
        ),
    ]
