# Generated by Django 6.0 on 2026-03-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0014_tenantuser_restricted_locations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("plant_manager", "Plant Manager"),
                    ("sales_rep", "Sales Rep"),
                    ("auditor", "Auditor"),
                    ("user", "User"),
                    ("readonly", "Read Only"),
                ],
                default="user",
                help_text="Role the user will have upon acceptance",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenantuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("plant_manager", "Plant Manager"),
                    ("sales_rep", "Sales Rep"),
                    ("auditor", "Auditor"),
                    ("user", "User"),
                    ("readonly", "Read Only"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
