# Generated by Django 6.0 on 2026-03-31 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantAPIKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("key_prefix", models.CharField(db_index=True, max_length=20)),
                ("key_hash", models.CharField(max_length=64)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_api_keys_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant", "revoked_at"], name="tenant_inte_tenant__7a29e4_idx"),
                    models.Index(fields=["tenant", "key_prefix"], name="tenant_inte_tenant__8a9190_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "key_prefix"), name="unique_tenant_api_key_prefix")
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantWebhook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("target_url", models.URLField(max_length=500)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("purchase_order.created", "Purchase Order Created"),
                            ("workform.completed", "Workform Completed"),
                        ],
                        max_length=64,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("signing_secret", models.CharField(blank=True, default="", max_length=128)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_webhooks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant", "event_type", "is_active"], name="tenant_inte_tenant__cdbbfe_idx")
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies
                    WHERE tablename = 'tenant_integrations_tenantapikey'
                    AND policyname = 'tenantapikey_tenant_isolation'
                ) THEN
                    ALTER TABLE tenant_integrations_tenantapikey ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE tenant_integrations_tenantapikey FORCE ROW LEVEL SECURITY;
                    CREATE POLICY tenantapikey_tenant_isolation ON tenant_integrations_tenantapikey
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tenantapikey_tenant_isolation ON tenant_integrations_tenantapikey;
            ALTER TABLE tenant_integrations_tenantapikey DISABLE ROW LEVEL SECURITY;
            """,
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies
                    WHERE tablename = 'tenant_integrations_tenantwebhook'
                    AND policyname = 'tenantwebhook_tenant_isolation'
                ) THEN
                    ALTER TABLE tenant_integrations_tenantwebhook ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE tenant_integrations_tenantwebhook FORCE ROW LEVEL SECURITY;
                    CREATE POLICY tenantwebhook_tenant_isolation ON tenant_integrations_tenantwebhook
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tenantwebhook_tenant_isolation ON tenant_integrations_tenantwebhook;
            ALTER TABLE tenant_integrations_tenantwebhook DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
