# Generated by Django 6.0 on 2026-05-06 10:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_integrations", "0001_initial"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("provider_code", models.CharField(max_length=64)),
                ("provider_account_reference", models.CharField(max_length=120)),
                (
                    "auth_mode",
                    models.CharField(
                        choices=[
                            ("tenant_api_key", "Tenant API Key"),
                            ("provider_hmac_signature", "Provider HMAC Signature"),
                        ],
                        default="tenant_api_key",
                        max_length=32,
                    ),
                ),
                ("signing_secret", models.CharField(blank=True, default="", max_length=128)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlement_sources",
                        to="tenant_integrations.tenantapikey",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlement_sources_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SettlementEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("provider_code", models.CharField(max_length=64)),
                ("provider_account_reference", models.CharField(max_length=120)),
                ("external_event_id", models.CharField(blank=True, default="", max_length=120)),
                ("event_type", models.CharField(max_length=64)),
                ("direction", models.CharField(max_length=32)),
                ("occurred_at", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("raw_payload", models.TextField()),
                ("raw_payload_sha256", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("validated", "Validated"),
                            ("duplicate", "Duplicate"),
                            ("ready_to_post", "Ready to Post"),
                            ("posted", "Posted"),
                            ("ignored", "Ignored"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=32,
                    ),
                ),
                ("normalized_payload", models.JSONField(blank=True, default=dict)),
                ("delivery_count", models.PositiveIntegerField(default=1)),
                ("received_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("last_received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_task_id", models.CharField(blank=True, default="", max_length=64)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="tenant_integrations.settlementsource",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="settlementsource",
            index=models.Index(fields=["tenant", "provider_code", "is_active"], name="tenant_inte_tenant__017b0d_idx"),
        ),
        migrations.AddIndex(
            model_name="settlementsource",
            index=models.Index(fields=["tenant", "public_id"], name="tenant_inte_tenant__4f2f30_idx"),
        ),
        migrations.AddConstraint(
            model_name="settlementsource",
            constraint=models.UniqueConstraint(
                fields=("tenant", "provider_code", "provider_account_reference"),
                name="unique_tenant_settlement_source_provider_account",
            ),
        ),
        migrations.AddIndex(
            model_name="settlementevent",
            index=models.Index(fields=["tenant", "state", "received_at"], name="tenant_inte_tenant__d2c6bc_idx"),
        ),
        migrations.AddIndex(
            model_name="settlementevent",
            index=models.Index(fields=["tenant", "source", "occurred_at"], name="tenant_inte_tenant__80b2fd_idx"),
        ),
        migrations.AddIndex(
            model_name="settlementevent",
            index=models.Index(
                fields=["tenant", "provider_code", "external_event_id"], name="tenant_inte_tenant__c4cf9b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementevent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "idempotency_key"), name="unique_tenant_settlement_event_idempotency"
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_event_id", ""), _negated=True),
                fields=("tenant", "provider_code", "external_event_id"),
                name="unique_tenant_settlement_provider_event",
            ),
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies
                    WHERE tablename = 'tenant_integrations_settlementsource'
                    AND policyname = 'settlementsource_tenant_isolation'
                ) THEN
                    ALTER TABLE tenant_integrations_settlementsource ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE tenant_integrations_settlementsource FORCE ROW LEVEL SECURITY;
                    CREATE POLICY settlementsource_tenant_isolation ON tenant_integrations_settlementsource
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS settlementsource_tenant_isolation ON tenant_integrations_settlementsource;
            ALTER TABLE tenant_integrations_settlementsource DISABLE ROW LEVEL SECURITY;
            """,
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies
                    WHERE tablename = 'tenant_integrations_settlementevent'
                    AND policyname = 'settlementevent_tenant_isolation'
                ) THEN
                    ALTER TABLE tenant_integrations_settlementevent ENABLE ROW LEVEL SECURITY;
                    ALTER TABLE tenant_integrations_settlementevent FORCE ROW LEVEL SECURITY;
                    CREATE POLICY settlementevent_tenant_isolation ON tenant_integrations_settlementevent
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS settlementevent_tenant_isolation ON tenant_integrations_settlementevent;
            ALTER TABLE tenant_integrations_settlementevent DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
