# Generated by Django 6.0 on 2026-05-06 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0016_operational_readiness"),
        ("purchase_orders", "0019_operational_readiness"),
        ("sales_orders", "0017_operational_readiness"),
        ("tenant_integrations", "0002_settlementsource_settlementevent_and_more"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlementevent",
            name="matched_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_settlement_events",
                to="invoices.invoice",
            ),
        ),
        migrations.AddField(
            model_name="settlementevent",
            name="matched_purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_settlement_events",
                to="purchase_orders.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="settlementevent",
            name="matched_sales_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_settlement_events",
                to="sales_orders.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="settlementevent",
            name="payment_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_settlement_event",
                to="invoices.paymenttransaction",
            ),
        ),
        migrations.AddField(
            model_name="settlementevent",
            name="reconciliation_reason_code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddIndex(
            model_name="settlementevent",
            index=models.Index(
                fields=["tenant", "reconciliation_reason_code", "received_at"], name="tenant_inte_tenant__0a6a36_idx"
            ),
        ),
    ]
