# Generated by Django 6.0 on 2025-12-10 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0002_supplier_tenant"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="supplier",
            new_name="suppliers_s_tenant__566edc_idx",
            old_name="suppliers_s_tenant__idx",
        ),
    ]
