# Generated by Django 6.0 on 2026-01-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "suppliers",
            "0003_rename_suppliers_s_tenant__idx_suppliers_s_tenant__566edc_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="shipping_offered",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Yes - Domestic", "Yes - Domestic"),
                    ("Yes - International", "Yes - International"),
                    ("Yes - Exported", "Yes - Exported"),
                    ("Yes - Domestic & Exported", "Yes - Domestic & Exported"),
                    ("No", "No"),
                ],
                default="",
                help_text="Shipping services offered (e.g., Yes - Domestic)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="type_of_certificate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3rd Party", "3rd Party"),
                    ("BRC", "BRC"),
                    ("FSSAI", "FSSAI"),
                    ("SQF", "SQF"),
                    ("IFS", "IFS"),
                    ("ISO", "ISO"),
                    ("HACCP", "HACCP"),
                    ("Halal", "Halal"),
                    ("Kosher", "Kosher"),
                    ("Organic", "Organic"),
                ],
                default="",
                help_text="Certificate type (e.g., 3rd Party, BRC)",
                max_length=100,
            ),
        ),
    ]
