# Generated by Django 6.0 on 2026-01-07 23:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0004_alter_supplier_shipping_offered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="departments_array",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Sales", "Sales"),
                        ("Doc's BOL", "Doc's BOL"),
                        ("Doc's COA", "Doc's COA"),
                        ("Accounting", "Accounting"),
                        ("Shipping", "Shipping"),
                        ("Receiving", "Receiving"),
                        ("Operations", "Operations"),
                        ("Quality", "Quality"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="Departments (multi-select: Sales, Doc's BOL, Doc's COA, etc.) - NEW",
            ),
        ),
    ]
