# Generated by Django 6.0 on 2026-01-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_add_products_m2m"),
        ("suppliers", "0006_alter_supplier_plant"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products available from this supplier",
                related_name="suppliers",
                to="products.product",
            ),
        ),
    ]
