# Generated by Django 6.0 on 2026-01-10 11:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0007_add_products_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="preferred_protein_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Beef", "Beef"),
                        ("Chicken", "Chicken"),
                        ("Pork", "Pork"),
                        ("Lamb", "Lamb"),
                        ("Turkey", "Turkey"),
                        ("Fish", "Fish"),
                        ("Horse", "Horse"),
                        ("Other", "Other"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="Preferred protein types (multi-select: Beef, Chicken, Pork, etc.)",
            ),
        ),
    ]
