# Generated by Django 6.0 on 2026-02-02 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_update_order_plant_references"),
        ("suppliers", "0010_alter_supplier_products_to_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated plant/location establishment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_assignments",
                to="locations.location",
            ),
        ),
    ]
