# Generated by Django 6.0 on 2026-03-18
# Upgrade RLS policy for Supplier model to modern standard (app.current_tenant)

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0011_alter_supplier_plant"),
    ]

    operations = [
        RunSQL(
            sql="""
            -- Enable RLS on suppliers_supplier (idempotent)
            ALTER TABLE suppliers_supplier ENABLE ROW LEVEL SECURITY;

            -- Drop any existing policies:
            -- 'supplier_tenant_isolation' is the standard name from tenants/0002_enable_rls_policies.py
            -- 'suppliers_supplier_tenant_isolation' is a legacy naming variant used in some environments
            -- Both are removed to ensure a clean, consistently-named policy is in place.
            DROP POLICY IF EXISTS supplier_tenant_isolation ON suppliers_supplier;
            DROP POLICY IF EXISTS suppliers_supplier_tenant_isolation ON suppliers_supplier;
            DROP POLICY IF EXISTS supplier_tenant_insert ON suppliers_supplier;

            -- Create tenant isolation policy for SELECT/UPDATE/DELETE
            CREATE POLICY supplier_tenant_isolation ON suppliers_supplier
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- Create tenant isolation policy for INSERT
            CREATE POLICY supplier_tenant_insert ON suppliers_supplier
                FOR INSERT
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS supplier_tenant_insert ON suppliers_supplier;
            DROP POLICY IF EXISTS supplier_tenant_isolation ON suppliers_supplier;
            ALTER TABLE suppliers_supplier DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
