# Generated by Django 6.0 on 2026-03-20 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0010_alter_plant_associated_products_and_more"),
        ("products", "0008_masterproduct_delete_product_and_more"),
        ("suppliers", "0012_add_rls_policies_batch"),
        ("tenants", "0010_add_tenant_configuration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="products",
        ),
        migrations.CreateModel(
            name="SupplierPlant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="supplier_links", to="plants.plant"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="plant_links", to="suppliers.supplier"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="supplier",
            name="plants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Plants associated with this supplier (used for active item filtering).",
                related_name="suppliers",
                through="suppliers.SupplierPlant",
                to="plants.plant",
            ),
        ),
        migrations.CreateModel(
            name="SupplierAvailableItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                ("product_code", models.CharField(blank=True, default="", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "master_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_variants",
                        to="products.masterproduct",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_items",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["supplier", "master_product__display_name"],
                "indexes": [
                    models.Index(fields=["tenant", "supplier"], name="suppliers_s_tenant__2e3c56_idx"),
                    models.Index(fields=["tenant", "master_product"], name="suppliers_s_tenant__09f0b8_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "supplier", "master_product"),
                        name="unique_supplier_master_product_per_tenant",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="supplierplant",
            index=models.Index(fields=["tenant", "supplier"], name="suppliers_s_tenant__d2adfa_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierplant",
            index=models.Index(fields=["tenant", "plant"], name="suppliers_s_tenant__134507_idx"),
        ),
        migrations.AddConstraint(
            model_name="supplierplant",
            constraint=models.UniqueConstraint(
                fields=("tenant", "supplier", "plant"), name="unique_supplier_plant_per_tenant"
            ),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE suppliers_supplierplant ENABLE ROW LEVEL SECURITY;
            ALTER TABLE suppliers_supplierplant FORCE ROW LEVEL SECURITY;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies
                    WHERE tablename = 'suppliers_supplierplant'
                    AND policyname = 'supplierplant_tenant_isolation'
                ) THEN
                    CREATE POLICY supplierplant_tenant_isolation ON suppliers_supplierplant
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;
            END $$;

            ALTER TABLE suppliers_supplieravailableitem ENABLE ROW LEVEL SECURITY;
            ALTER TABLE suppliers_supplieravailableitem FORCE ROW LEVEL SECURITY;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies
                    WHERE tablename = 'suppliers_supplieravailableitem'
                    AND policyname = 'supplieravailableitem_tenant_isolation'
                ) THEN
                    CREATE POLICY supplieravailableitem_tenant_isolation ON suppliers_supplieravailableitem
                        USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS supplierplant_tenant_isolation ON suppliers_supplierplant;
            ALTER TABLE suppliers_supplierplant NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE suppliers_supplierplant DISABLE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS supplieravailableitem_tenant_isolation ON suppliers_supplieravailableitem;
            ALTER TABLE suppliers_supplieravailableitem NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE suppliers_supplieravailableitem DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
