# Generated by Django 6.0 on 2026-03-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0014_supplieravailableitem_use_system_product"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="supplieravailableitem",
            new_name="sup_av_tenant_prod_idx",
            old_name="suppliers_s_tenant__product_idx",
        ),
    ]
