# Generated by Django 6.0 on 2026-03-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0015_shorten_supplieravailableitem_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="phone_type",
            field=models.CharField(
                blank=True,
                choices=[("mobile", "Mobile"), ("office", "Office")],
                default="office",
                help_text="Primary contact phone type (mobile or office)",
                max_length=10,
            ),
        ),
    ]
