# Generated by Django 6.0 on 2026-03-29 19:39

from django.db import migrations, models


def backfill_supplier_phone_slots(apps, schema_editor):
    Supplier = apps.get_model('suppliers', 'Supplier')

    for s in Supplier.objects.all().iterator():
        legacy_phone = (s.phone or '').strip()
        if not legacy_phone:
            continue

        # Only backfill when the new slots are empty.
        if (s.phone_mobile or '').strip() or (s.phone_office or '').strip():
            continue

        if (s.phone_type or '').strip() == 'mobile':
            s.phone_mobile = legacy_phone
        else:
            s.phone_office = legacy_phone

        s.save(update_fields=['phone_mobile', 'phone_office'])


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0016_supplier_phone_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="phone_mobile",
            field=models.CharField(blank=True, default="", help_text="Mobile phone number", max_length=20),
        ),
        migrations.AddField(
            model_name="supplier",
            name="phone_office",
            field=models.CharField(blank=True, default="", help_text="Office phone number", max_length=20),
        ),
        migrations.AddField(
            model_name="supplier",
            name="phone_office_extension",
            field=models.CharField(blank=True, default="", help_text="Office phone extension", max_length=10),
        ),
        migrations.RunPython(backfill_supplier_phone_slots, migrations.RunPython.noop),
    ]
