# Generated by Django 6.0 on 2026-03-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0018_alter_supplier_preferred_protein_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="account_line_of_credit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("$0 - $50,000", "$0 - $50,000"),
                    ("$50,000 - $100,000", "$50,000 - $100,000"),
                    ("$100,000 - $250,000", "$100,000 - $250,000"),
                    ("$250,000 - $500,000", "$250,000 - $500,000"),
                    ("$500,000 - $1,000,000", "$500,000 - $1,000,000"),
                    ("$1,000,000+", "$1,000,000+"),
                ],
                default="",
                help_text="Line of credit amount range",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="accounting_line_of_credit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Line of credit amount (deprecated, use account_line_of_credit)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="accounting_payment_terms",
            field=models.CharField(
                blank=True,
                choices=[("Wire", "Wire"), ("ACH", "ACH"), ("Check", "Check"), ("Credit Card", "Credit Card")],
                default="",
                help_text="Payment terms (e.g., Wire, ACH, Check)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="accounting_terms",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Accounting terms (deprecated, use accounting_payment_terms)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="country_origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USA", "USA"),
                    ("CAN", "Canada"),
                    ("MEX", "Mexico"),
                    ("BRA", "Brazil"),
                    ("AUS", "Australia"),
                    ("NZL", "New Zealand"),
                ],
                default="",
                help_text="Country of origin (e.g., USA, CAN)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="credit_limits",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Wire 1 day prior", "Wire 1 day prior"),
                    ("Net 7", "Net 7"),
                    ("Net 15", "Net 15"),
                    ("Net 30", "Net 30"),
                    ("Net 45", "Net 45"),
                    ("Net 60", "Net 60"),
                ],
                default="",
                help_text="Credit limits/terms (e.g., Net 30, Wire 1 day prior)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="departments",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Departments (comma-separated: Sales, BOL, COA, etc.)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="edible_inedible",
            field=models.CharField(
                blank=True,
                choices=[("Edible", "Edible"), ("Inedible", "Inedible"), ("Edible & Inedible", "Edible & Inedible")],
                default="",
                help_text="Type of products supplied",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="fresh_or_frozen",
            field=models.CharField(
                blank=True,
                choices=[("Fresh", "Fresh"), ("Frozen", "Frozen")],
                default="",
                help_text="Product state (Fresh or Frozen)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="how_to_book_pickup",
            field=models.CharField(
                blank=True, default="", help_text="How to book pickup (e.g., Website, Call)", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="net_or_catch",
            field=models.CharField(
                blank=True,
                choices=[("Net", "Net"), ("Catch", "Catch")],
                default="",
                help_text="Weight type (Net or Catch)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[("Domestic", "Domestic"), ("Imported", "Imported")],
                default="",
                help_text="Product origin (e.g., Domestic, Imported)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="package_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Boxed wax lined", "Boxed wax lined"),
                    ("Boxed CO2", "Boxed CO2"),
                    ("Combo bins", "Combo bins"),
                    ("Totes", "Totes"),
                    ("Bags", "Bags"),
                    ("Bulk", "Bulk"),
                    ("Poly-Multiple", "Poly-Multiple"),
                    ("Nude", "Nude"),
                ],
                default="",
                help_text="Package type (e.g., Boxed wax lined, Combo bins)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone_mobile",
            field=models.CharField(blank=True, default="", help_text="Mobile phone number", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone_office",
            field=models.CharField(blank=True, default="", help_text="Office phone number", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone_office_extension",
            field=models.CharField(
                blank=True, default="", help_text="Office phone extension", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="shipping_offered",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Yes - Domestic", "Yes - Domestic"),
                    ("Yes - International", "Yes - International"),
                    ("Yes - Exported", "Yes - Exported"),
                    ("Yes - Domestic & Exported", "Yes - Domestic & Exported"),
                    ("No", "No"),
                ],
                default="",
                help_text="Shipping services offered (e.g., Yes - Domestic)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="street_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Street address (alternative to address field)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="type_of_certificate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3rd Party", "3rd Party"),
                    ("BRC", "BRC"),
                    ("FSSAI", "FSSAI"),
                    ("SQF", "SQF"),
                    ("IFS", "IFS"),
                    ("ISO", "ISO"),
                    ("HACCP", "HACCP"),
                    ("Halal", "Halal"),
                    ("Kosher", "Kosher"),
                    ("Organic", "Organic"),
                ],
                default="",
                help_text="Certificate type (e.g., 3rd Party, BRC)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="type_of_plant",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Vertical", "Vertical"),
                    ("Processor", "Processor"),
                    ("Distributor", "Distributor"),
                    ("Renderer", "Renderer"),
                ],
                default="",
                help_text="Type of plant (e.g., Vertical, Processor)",
                max_length=100,
                null=True,
            ),
        ),
    ]
