# Generated by Django 6.0 on 2026-04-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0019_alter_supplier_account_line_of_credit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
