# Generated by Django 6.0 on 2026-01-25 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSchema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the schema", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (auto-generated)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the schema's purpose",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        help_text="Current status of the schema",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Current version number"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this schema is active and usable",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a core system schema (cannot be deleted)",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="database",
                        help_text="Icon identifier for UI display",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="blue",
                        help_text="Color theme for UI display",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, help_text="When the schema was submitted", null=True
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, help_text="When the schema was published", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this schema",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schemas_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who published this schema (superuser only)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schemas_published",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who submitted this schema for review",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schemas_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Schema",
                "verbose_name_plural": "Data Schemas",
                "ordering": ["name"],
                "permissions": [
                    ("submit_dataschema", "Can submit schema for review"),
                    ("publish_dataschema", "Can publish schema (superuser only)"),
                    ("view_versions", "Can view schema version history"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FieldOptionList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the option list", max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the option list",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        default=list,
                        help_text="List of options [{value: 'v1', label: 'Label 1'}, ...]",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="Whether this is a core system list"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this list",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Option List",
                "verbose_name_plural": "Field Option Lists",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataSchemaField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Machine-readable field identifier (snake_case)",
                        max_length=100,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable field label", max_length=255
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Text Area"),
                            ("integer", "Number (Integer)"),
                            ("decimal", "Number (Decimal)"),
                            ("dropdown", "Dropdown (Single Select)"),
                            ("multiselect", "Multi-select"),
                            ("currency", "Currency"),
                            ("phone", "Phone Number"),
                            ("email", "Email"),
                            ("date", "Date"),
                            ("datetime", "Date & Time"),
                            ("boolean", "Yes/No (Boolean)"),
                            ("url", "URL"),
                        ],
                        default="text",
                        help_text="Type of field",
                        max_length=20,
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this field is visible in forms and lists",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, help_text="Whether this field is required"
                    ),
                ),
                (
                    "is_searchable",
                    models.BooleanField(
                        default=True, help_text="Whether this field is searchable"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order of the field"
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Options for dropdown/multiselect fields (list of {value, label})",
                    ),
                ),
                (
                    "default_value",
                    models.JSONField(
                        blank=True, help_text="Default value for the field", null=True
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Help text shown below the field",
                        max_length=500,
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Placeholder text shown in empty fields",
                        max_length=255,
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Validation rules (min, max, pattern, etc.)",
                    ),
                ),
                (
                    "decimal_places",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Decimal places for decimal/currency fields",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schema",
                    models.ForeignKey(
                        help_text="Schema this field belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="schema_builder.dataschema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schema Field",
                "verbose_name_plural": "Schema Fields",
                "ordering": ["schema", "order", "label"],
                "unique_together": {("schema", "key")},
            },
        ),
        migrations.CreateModel(
            name="DataSchemaVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        help_text="Version number at time of snapshot"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action that created this version (created, updated, submitted, published, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "snapshot_data",
                    models.JSONField(
                        help_text="Complete snapshot of schema and fields at this version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional notes about this version",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        help_text="Schema this version belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="schema_builder.dataschema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schema Version",
                "verbose_name_plural": "Schema Versions",
                "ordering": ["-created_at"],
                "unique_together": {("schema", "version_number", "action")},
            },
        ),
    ]
