# Generated by Django 6.0 on 2026-01-25 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schema_builder", "0001_initial"),
        ("tenants", "0006_metadata_lockdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Custom field data stored as JSON, validated against schema",
                    ),
                ),
                (
                    "search_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Concatenated searchable field values for full-text search",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dynamic_entities_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        help_text="Schema that defines this entity's structure",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entities",
                        to="schema_builder.dataschema",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this entity belongs to (null for system entities)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_entities",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dynamic_entities_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dynamic Entity",
                "verbose_name_plural": "Dynamic Entities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["schema", "tenant"],
                        name="schema_buil_schema__da4978_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="schema_buil_created_88bc56_idx"
                    ),
                ],
            },
        ),
    ]
