# Generated by Django 6.0 on 2026-01-30 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schema_builder", "0002_dynamicentity"),
        ("tenants", "0006_metadata_lockdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantFieldChoiceOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Entity type (e.g., 'customer', 'product')",
                        max_length=100,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        db_index=True,
                        help_text="Field name (e.g., 'protein_type', 'edible_inedible')",
                        max_length=100,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("replace", "Replace All"),
                            ("append", "Append to Defaults"),
                            ("prepend", "Prepend to Defaults"),
                            ("filter", "Filter Defaults"),
                        ],
                        default="replace",
                        help_text="How to apply this override",
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        default=list,
                        help_text="List of options [{value: 'v1', label: 'Label 1'}, ...]",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this override is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this override",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_choice_overrides_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "option_list",
                    models.ForeignKey(
                        blank=True,
                        help_text="Use options from a reusable list instead of inline options",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_overrides",
                        to="schema_builder.fieldoptionlist",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this override belongs to (null for root/system level)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_choice_overrides",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Choice Override",
                "verbose_name_plural": "Field Choice Overrides",
                "ordering": ["entity_type", "field_name", "tenant"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "field_name"],
                        name="schema_buil_entity__869bac_idx",
                    ),
                    models.Index(
                        fields=["tenant", "is_active"],
                        name="schema_buil_tenant__5609a9_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "entity_type", "field_name"),
                        name="unique_tenant_entity_field_override",
                    )
                ],
            },
        ),
    ]
