# Generated by Django 6.0 on 2026-01-30 23:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schema_builder", "0003_add_tenant_field_choice_override"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoiceOverrideAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(blank=True, null=True)),
                (
                    "tenant_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("entity_type", models.CharField(max_length=100)),
                ("field_name", models.CharField(max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("activate", "Activated"),
                            ("deactivate", "Deactivated"),
                        ],
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "previous_state",
                    models.JSONField(
                        default=dict,
                        help_text="State before the change (empty for creates)",
                    ),
                ),
                (
                    "new_state",
                    models.JSONField(
                        default=dict,
                        help_text="State after the change (empty for deletes)",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=list,
                        help_text="List of specific field changes: [{field, old, new}]",
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "override",
                    models.ForeignKey(
                        blank=True,
                        help_text="The override that was modified",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="schema_builder.tenantfieldchoiceoverride",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="choice_override_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Choice Override Audit Log",
                "verbose_name_plural": "Choice Override Audit Logs",
                "ordering": ["-performed_at"],
                "indexes": [
                    models.Index(
                        fields=["override"], name="schema_buil_overrid_f29d84_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "field_name"],
                        name="schema_buil_entity__02896f_idx",
                    ),
                    models.Index(
                        fields=["performed_at"], name="schema_buil_perform_71fce0_idx"
                    ),
                    models.Index(
                        fields=["action"], name="schema_buil_action_78b2b1_idx"
                    ),
                ],
            },
        ),
    ]
