# Generated by Django 6.0 on 2026-01-07 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0004_alter_customer_type_of_certificate"),
        ("suppliers", "0004_alter_supplier_shipping_offered_and_more"),
        ("tenants", "0006_metadata_lockdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Location name or identifier", max_length=255),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", help_text="Full street address"),
                ),
                (
                    "city",
                    models.CharField(blank=True, default="", help_text="City", max_length=100),
                ),
                (
                    "state_zip",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="State and ZIP code",
                        max_length=50,
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact person name",
                        max_length=255,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact phone number",
                        max_length=20,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Contact email address",
                        max_length=254,
                    ),
                ),
                (
                    "how_make_appointment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Email", "Email"),
                            ("Phone", "Phone"),
                            ("Website", "Website"),
                            ("Fax", "Fax"),
                            ("First Come First Serve", "First Come First Serve"),
                        ],
                        default="",
                        help_text="How to make an appointment",
                        max_length=50,
                    ),
                ),
                (
                    "plant_est_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Plant establishment number",
                        max_length=50,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated customer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locations",
                        to="customers.customer",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated supplier",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locations",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this location belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["tenant", "name"], name="locations_l_tenant__86980e_idx"),
                    models.Index(
                        fields=["tenant", "supplier"],
                        name="locations_l_tenant__994396_idx",
                    ),
                    models.Index(
                        fields=["tenant", "customer"],
                        name="locations_l_tenant__5c0c75_idx",
                    ),
                ],
            },
        ),
    ]
