# Generated by Django 6.0 on 2026-01-07 23:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        # Enable Row Level Security on locations_location table
        migrations.RunSQL(
            sql="ALTER TABLE locations_location ENABLE ROW LEVEL SECURITY;",
            reverse_sql="ALTER TABLE locations_location DISABLE ROW LEVEL SECURITY;",
        ),
        # Create tenant isolation policy
        migrations.RunSQL(
            sql="""
                CREATE POLICY tenant_isolation_policy ON locations_location
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
            reverse_sql="DROP POLICY IF EXISTS tenant_isolation_policy ON locations_location;",
        ),
    ]
