# Generated by Django 6.0 on 2026-01-10 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_customer_industry_array_and_more"),
        ("locations", "0002_enable_rls_locations"),
        ("suppliers", "0006_alter_supplier_plant"),
        ("tenants", "0006_metadata_lockdown"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="location",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="location",
            name="how_make_appointment",
        ),
        migrations.RemoveField(
            model_name="location",
            name="plant_est_number",
        ),
        migrations.RemoveField(
            model_name="location",
            name="state_zip",
        ),
        migrations.AddField(
            model_name="location",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Location code or identifier",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.CharField(blank=True, default="USA", help_text="Country", max_length=100),
        ),
        migrations.AddField(
            model_name="location",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Location email address",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Whether this location is active"),
        ),
        migrations.AddField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Type of location (warehouse, store, distribution_center, office)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="phone",
            field=models.CharField(blank=True, default="", help_text="Location phone number", max_length=20),
        ),
        migrations.AddField(
            model_name="location",
            name="state",
            field=models.CharField(blank=True, default="", help_text="State or province", max_length=50),
        ),
        migrations.AddField(
            model_name="location",
            name="zip_code",
            field=models.CharField(blank=True, default="", help_text="ZIP or postal code", max_length=20),
        ),
        migrations.AlterField(
            model_name="location",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated customer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_locations",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated supplier",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_locations",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["tenant", "location_type"],
                name="locations_l_tenant__4592dc_idx",
            ),
        ),
    ]
