# Generated by Django 6.0 on 2026-02-02 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_customer_custom_data_alter_customer_tenant"),
        ("locations", "0003_remove_location_contact_email_and_more"),
        ("suppliers", "0009_supplier_custom_data_alter_supplier_tenant"),
        ("tenants", "0006_metadata_lockdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="capacity",
            field=models.PositiveIntegerField(blank=True, help_text="Capacity in units (for plants)", null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_locations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="legacy_plant_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, help_text="Original Plant ID before migration (for reference)", null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="manager",
            field=models.CharField(blank=True, default="", help_text="Plant manager name", max_length=100),
        ),
        migrations.AddField(
            model_name="location",
            name="plant_est_num",
            field=models.CharField(
                blank=True, default="", help_text="Plant establishment number (USDA/FDA)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Location code or identifier (unique for plants)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("warehouse", "Warehouse"),
                    ("store", "Store"),
                    ("distribution_center", "Distribution Center"),
                    ("office", "Office"),
                    ("plant_processing", "Processing Plant"),
                    ("plant_distribution", "Plant Distribution Center"),
                    ("plant_warehouse", "Plant Warehouse"),
                    ("plant_retail", "Retail Location"),
                    ("plant_other", "Other Plant"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Type of location",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["tenant", "code"], name="locations_l_tenant__906ccb_idx"),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code__gt", "")), fields=("tenant", "code"), name="unique_location_code_per_tenant"
            ),
        ),
    ]
