# Generated by Django 6.0 on 2026-02-27 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_update_order_plant_references"),
        ("tenants", "0010_add_tenant_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="custom_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extensible schema data for dynamic fields defined in Blueprints."
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
        # Enable Row-Level Security (RLS) for tenant isolation
        migrations.RunSQL(
            sql="""
            -- Enable RLS on locations_location
            ALTER TABLE locations_location ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS location_tenant_isolation ON locations_location;
            CREATE POLICY location_tenant_isolation ON locations_location
            USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

            DROP POLICY IF EXISTS location_tenant_insert ON locations_location;
            CREATE POLICY location_tenant_insert ON locations_location
            FOR INSERT WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            -- Disable RLS policies for locations_location
            DROP POLICY IF EXISTS location_tenant_isolation ON locations_location;
            DROP POLICY IF EXISTS location_tenant_insert ON locations_location;
            ALTER TABLE locations_location DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
