# Generated by Django 6.0 on 2026-03-15 18:21

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.special import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0007_refactor_to_tenantaware"),
        ("system", "0010_product_is_system_tenantproductpreference_is_custom"),
        ("tenants", "0010_add_tenant_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationAssociatedProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associated_product_links",
                        to="locations.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_affinity_links",
                        to="system.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Known Product",
                "verbose_name_plural": "Location Known Products",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="associated_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products commonly purchased/handled at this location",
                related_name="purchased_by_locations",
                through="locations.LocationAssociatedProduct",
                to="system.product",
                verbose_name="Known Products Purchased",
            ),
        ),
        migrations.AddIndex(
            model_name="locationassociatedproduct",
            index=models.Index(fields=["tenant", "location"], name="locations_l_tenant__92cee0_idx"),
        ),
        migrations.AddIndex(
            model_name="locationassociatedproduct",
            index=models.Index(fields=["tenant", "product"], name="locations_l_tenant__bf8192_idx"),
        ),
        migrations.AddConstraint(
            model_name="locationassociatedproduct",
            constraint=models.UniqueConstraint(
                fields=("tenant", "location", "product"), name="unique_location_product_affinity_per_tenant"
            ),
        ),
        RunSQL(
            sql="""
            ALTER TABLE locations_locationassociatedproduct ENABLE ROW LEVEL SECURITY;
            ALTER TABLE locations_locationassociatedproduct FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS locationassociatedproduct_tenant_isolation ON locations_locationassociatedproduct;
            CREATE POLICY locationassociatedproduct_tenant_isolation ON locations_locationassociatedproduct
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS locationassociatedproduct_tenant_isolation ON locations_locationassociatedproduct;
            ALTER TABLE locations_locationassociatedproduct NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE locations_locationassociatedproduct DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
