# Generated by Django 6.0 on 2026-03-22
# Normalize RLS policies to safe current_setting('app.current_tenant', true)

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0008_locationassociatedproduct_and_more"),
    ]

    operations = [
        RunSQL(
            sql="""
            -- locations_location (legacy policy name)
            ALTER TABLE locations_location ENABLE ROW LEVEL SECURITY;
            ALTER TABLE locations_location FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS tenant_isolation_policy ON locations_location;
            CREATE POLICY tenant_isolation_policy ON locations_location
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);

            -- locations_locationassociatedproduct
            ALTER TABLE locations_locationassociatedproduct ENABLE ROW LEVEL SECURITY;
            ALTER TABLE locations_locationassociatedproduct FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS locationassociatedproduct_tenant_isolation ON locations_locationassociatedproduct;
            CREATE POLICY locationassociatedproduct_tenant_isolation ON locations_locationassociatedproduct
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS tenant_isolation_policy ON locations_location;
            CREATE POLICY tenant_isolation_policy ON locations_location
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant')::uuid);

            DROP POLICY IF EXISTS locationassociatedproduct_tenant_isolation ON locations_locationassociatedproduct;
            CREATE POLICY locationassociatedproduct_tenant_isolation ON locations_locationassociatedproduct
                FOR ALL
                USING (tenant_id = current_setting('app.current_tenant')::uuid);
            """,
        ),
    ]
