# Generated by Django 6.0 on 2026-03-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0010_location_phone_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("warehouse", "Warehouse"),
                    ("store", "Store"),
                    ("distribution_center", "Distribution Center"),
                    ("office", "Office"),
                    ("plant_processing", "Processing Plant"),
                    ("plant_distribution", "Plant Distribution Center"),
                    ("plant_warehouse", "Plant Warehouse"),
                    ("plant_retail", "Retail Location"),
                    ("plant_vertical", "Vertical (Kill to Capture)"),
                    ("plant_other", "Other Plant"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Type of location",
                max_length=50,
            ),
        ),
    ]
