# Generated by Django 6.0 on 2026-03-31 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0011_alter_location_location_type"),
        ("products", "0009_alter_masterproduct_protein"),
        ("tenants", "0013_alter_activitylog_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationAssociatedMasterProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible schema data for dynamic fields defined in Blueprints.",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associated_master_product_links",
                        to="locations.location",
                    ),
                ),
                (
                    "master_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_affinity_links",
                        to="products.masterproduct",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Known Master Product",
                "verbose_name_plural": "Location Known Master Products",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="associated_master_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Master products commonly purchased/handled at this location",
                related_name="known_by_locations",
                through="locations.LocationAssociatedMasterProduct",
                to="products.masterproduct",
                verbose_name="Known Master Products",
            ),
        ),
        migrations.AddIndex(
            model_name="locationassociatedmasterproduct",
            index=models.Index(fields=["tenant", "location"], name="locations_l_tenant__880929_idx"),
        ),
        migrations.AddIndex(
            model_name="locationassociatedmasterproduct",
            index=models.Index(fields=["tenant", "master_product"], name="locations_l_tenant__7e2e19_idx"),
        ),
        migrations.AddConstraint(
            model_name="locationassociatedmasterproduct",
            constraint=models.UniqueConstraint(
                fields=("tenant", "location", "master_product"),
                name="unique_location_master_product_affinity_per_tenant",
            ),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE locations_locationassociatedmasterproduct ENABLE ROW LEVEL SECURITY;
            ALTER TABLE locations_locationassociatedmasterproduct FORCE ROW LEVEL SECURITY;

            DROP POLICY IF EXISTS locationassociatedmasterproduct_tenant_isolation ON locations_locationassociatedmasterproduct;
            CREATE POLICY locationassociatedmasterproduct_tenant_isolation ON locations_locationassociatedmasterproduct
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS locationassociatedmasterproduct_tenant_isolation ON locations_locationassociatedmasterproduct;
            ALTER TABLE locations_locationassociatedmasterproduct NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE locations_locationassociatedmasterproduct DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
