# Generated by Django 6.0 on 2026-04-28 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0016_customer_deleted_at_customer_is_deleted"),
        ("locations", "0012_locationassociatedmasterproduct_and_more"),
        ("products", "0009_alter_masterproduct_protein"),
        ("suppliers", "0020_supplier_deleted_at_supplier_is_deleted"),
        ("system", "0015_enable_rls_tenant_forms_workforms"),
        ("tenants", "0015_alter_tenantinvitation_role_alter_tenantuser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="location",
            name="unique_location_code_per_tenant",
        ),
        migrations.AddField(
            model_name="location",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code__gt", ""), ("is_deleted", False)),
                fields=("tenant", "code"),
                name="unique_location_code_per_tenant",
            ),
        ),
    ]
